import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_3_FACTS: BankFact[] = [
  {
    id: "3-1-f01",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "طالب يفتح صفحة الحضور على هاتفه ويرى أسماء الشعبة وأزرار التأكيد.",
    sceneEn: "A student opens the attendance page on a phone and sees class names and confirm buttons.",
    claimAr: "ابنِ ما يراه في المتصفح بـ HTML وCSS وجافاسكربت في الواجهة الأمامية.",
    claimEn: "Build what the student sees with HTML, CSS, and JavaScript in the frontend.",
    whyAr: "الواجهة الأمامية هي طبقة العرض في المتصفح: هيكل ومظهر وسلوك ظاهر.",
    whyEn: "The frontend is the browser presentation layer: structure, look, and visible behaviour.",
    termAr: "الواجهة الأمامية",
    termEn: "Frontend",
    wrongAr: [
      "اخفِ القائمة كلها داخل قاعدة البيانات من غير صفحة",
      "ارسم الأسماء بمحرك قاعدة البيانات فقط",
      "ضع الأزرار داخل إعداد الموجّه المدرسي",
    ],
    wrongEn: [
      "Hide the whole list inside the database with no page",
      "Draw the names only with the database engine",
      "Put the buttons inside the school router config",
    ],
  },
  {
    id: "3-1-f02",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "المعلم يضغط «حفظ الحضور» بعد الحصة الثانية.",
    sceneEn: "The teacher taps Save attendance after second period.",
    claimAr: "دع الخادم يتحقق ممن يجوز له الحفظ ثم يكتب السجل.",
    claimEn: "Let the backend check who may save, then write the record.",
    whyAr: "الخلفية تملك المنطق والصلاحيات؛ المتصفح يرسل الطلب فقط.",
    whyEn: "The backend owns logic and permissions; the browser only sends the request.",
    termAr: "الخادم / الخلفية",
    termEn: "Backend",
    wrongAr: [
      "ثق في الهاتف ليكتب الدرجات على فلاشة مشتركة",
      "احفظ الكشف لقطة شاشة وعدّها سجلًا رسميًا",
      "اسمح لأي زائر بتعديل ملفات الخادم من ملف CSS",
    ],
    wrongEn: [
      "Trust the phone to write marks onto a shared USB stick",
      "Save a screenshot and treat it as the official record",
      "Let any visitor edit server files from a CSS file",
    ],
  },
  {
    id: "3-1-f03",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "بعد اختبار منتصف الترم يجب أن تبقى الدرجات ظاهرة في الترم التالي.",
    sceneEn: "After the midterm, the marks must still be there next term.",
    claimAr: "اخزن الدرجات في قاعدة البيانات على طبقة البيانات.",
    claimEn: "Store the marks in the database on the data layer.",
    whyAr: "قاعدة البيانات حفظ دائم منظم يبقى بعد إغلاق المتصفح.",
    whyEn: "A database is persistent structured storage that outlives the closed browser.",
    termAr: "قاعدة البيانات",
    termEn: "Database",
    wrongAr: [
      "اترك الدرجات في التبويب المفتوح فقط",
      "اطبع الورقة ثم ألقِها وعدّ ذلك نسخًا احتياطيًا",
      "شفّر الدرجة لونًا في ملف CSS",
    ],
    wrongEn: [
      "Leave the marks only in the open tab",
      "Print the paper and throw it away as a backup",
      "Encode the mark as a colour in a CSS file",
    ],
  },
  {
    id: "3-1-f04",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "جهاز المعمل يعرض نموذج حجز الحصة، والجهاز يتحدث مع خادم المدرسة.",
    sceneEn: "A lab PC shows the period-booking form and talks to the school server.",
    claimAr: "المتصفح يطلب؛ الخادم يرد ويقرر.",
    claimEn: "The browser asks; the server replies and decides.",
    whyAr: "نموذج العميل والخادم يعني أن العميل يطلب والخادم يجيب.",
    whyEn: "Client–server means the client requests and the server answers.",
    termAr: "العميل-الخادم",
    termEn: "Client–server",
    wrongAr: [
      "دع الجهاز يكتب الحجوزات في هواتف الطلاب الآخرين",
      "اجعل قاعدة البيانات تخاطب الطالب من غير خادم",
      "اترك CSS يختار من يحصل على المعمل",
    ],
    wrongEn: [
      "Let the PC write bookings into other students' phones",
      "Let the database talk to the student with no server",
      "Let CSS choose who gets the lab",
    ],
  },
  {
    id: "3-1-f05",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "صفحة التسجيل تعرض المقاعد المتبقية في شعبة الحاسوب.",
    sceneEn: "The registration page shows seats left in the computer section.",
    claimAr: "اجعل طبقة العرض تُظهر المقاعد، ولا تقرر المقعد الأخير وحدها.",
    claimEn: "Let the presentation layer show the seats; do not let it award the last seat alone.",
    whyAr: "طبقة العرض تعرض؛ سلطة العدد الحقيقي ليست في الصفحة الجميلة.",
    whyEn: "Presentation displays; the true remaining count is not decided by a pretty page.",
    termAr: "طبقة العرض",
    termEn: "Presentation layer",
    wrongAr: [
      "دع الصفحة الجميلة تطرح المقعد الأخير وحدها",
      "اخزن المقاعد في لون الزر فقط",
      "احذف الخادم لأن الصفحة تبدو ممتلئة",
    ],
    wrongEn: [
      "Let the pretty page subtract the last seat by itself",
      "Store seats only in the button colour",
      "Delete the server because the page looks full",
    ],
  },
  {
    id: "3-1-f06",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "طالبان يضغطان «تسجيل» في الثانية نفسها على آخر مقعد.",
    sceneEn: "Two students tap Enroll in the same second for the last seat.",
    claimAr: "نفّذ قاعدة القبول على طبقة التطبيق في الخادم.",
    claimEn: "Run the enrollment rule on the server application layer.",
    whyAr: "طبقة التطبيق تقرر من يفوز بالمقعد الأخير وفق صلاحية ومنطق.",
    whyEn: "The application layer decides who wins the last seat with logic and rights.",
    termAr: "طبقة التطبيق",
    termEn: "Application layer",
    wrongAr: [
      "أعطِ المقعد لأسرع هاتف من غير فحص خادم",
      "حرّك رسمة CSS لتعيين المقعد",
      "اطبع القاعدة على ملصق وعدّها كافية",
    ],
    wrongEn: [
      "Give the seat to the faster phone with no server check",
      "Move a CSS animation to assign the seat",
      "Print the rule on a poster and call that enough",
    ],
  },
  {
    id: "3-1-f07",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "بعد إجازة الصيف يجب أن يفتح كشف غياب العام الماضي.",
    sceneEn: "After summer break, last year's absence sheet must still open.",
    claimAr: "أبقِ الغياب على طبقة البيانات حتى يعيش بعد إغلاق المتصفح.",
    claimEn: "Keep absences on the data layer so they survive a closed browser.",
    whyAr: "طبقة البيانات تخزين دائم، ليست شاشة مؤقتة.",
    whyEn: "The data layer is persistent storage, not a temporary screen.",
    termAr: "طبقة البيانات",
    termEn: "Data layer",
    wrongAr: [
      "اعتمد ألبوم لقطات الطالب",
      "اخفِ الغياب في تعليق HTML",
      "اترك السجلات في ذاكرة جهاز المعمل فقط",
    ],
    wrongEn: [
      "Rely on a student's screenshot album",
      "Hide absences in an HTML comment",
      "Keep the records only in the lab PC's memory",
    ],
  },
  {
    id: "3-1-f08",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "متدرب يلصق مفتاح رسائل سري داخل جافاسكربت صفحة الحضور.",
    sceneEn: "An intern pastes a secret SMS API key into the attendance-page JavaScript.",
    claimAr: "انقل المفتاح إلى الخادم، ولا تشحنه أبدًا في كود الواجهة.",
    claimEn: "Move the key to the server; never ship it in frontend code.",
    whyAr: "أي زائر يفتح أدوات المتصفح يقرأ ملفات الواجهة.",
    whyEn: "Anyone who opens browser tools can read frontend files.",
    termAr: "سر الواجهة",
    termEn: "Frontend secret",
    wrongAr: [
      "اترك المفتاح في الجافاسكربت لأن الطلاب أمناء",
      "ضعه في تعليق HTML حتى يختفي",
      "سمِّ صف CSS باسم المفتاح",
    ],
    wrongEn: [
      "Leave the key in JavaScript because students are honest",
      "Put it in an HTML comment so it disappears",
      "Name a CSS class after the key",
    ],
  },
  {
    id: "3-1-f09",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "نموذج التسجيل يحمل كلمة مرور المشرف في حقل مخفي.",
    sceneEn: "The registration form carries the admin password in a hidden field.",
    claimAr: "احذف كلمة المرور من الصفحة وأبقها على الخادم فقط.",
    claimEn: "Remove the password from the page and keep it only on the server.",
    whyAr: "الحقل المخفي ما زال مكشوفًا في مصدر الصفحة.",
    whyEn: "A hidden field is still public in the page source.",
    termAr: "كلمة المرور",
    termEn: "Password",
    wrongAr: [
      "ثق في type=hidden كخزنة",
      "اخزن كلمة المرور في التخزين المحلي للسرعة",
      "اطبعها في تذييل الصفحة بخط صغير",
    ],
    wrongEn: [
      "Trust type=hidden as a vault",
      "Store the password in localStorage for speed",
      "Print it in a tiny page footer",
    ],
  },
  {
    id: "3-1-f10",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "فريق يصمم شاشة الدرجات، وفريق آخر يكتب خدمة حفظ العلامات.",
    sceneEn: "One team designs the grades screen; another writes the marks service.",
    claimAr: "افصل الواجهة عن الخادم حتى يعمل الفريقان على حدود واضحة.",
    claimEn: "Split frontend from backend so the two teams work on clear edges.",
    whyAr: "الفصل يسهّل الصيانة: يتغيّر الشكل أو المنطق من غير أن يُغلق الفريق الآخر.",
    whyEn: "A split eases maintenance: look or logic can change without blocking the other team.",
    termAr: "فصل الطبقات",
    termEn: "Layer split",
    wrongAr: [
      "اخلط أوامر القاعدة داخل كل نقرة في المتصفح",
      "أجبر شخصًا واحدًا على تعديل كل الملفات معًا",
      "ضع قاعدة البيانات داخل ملف تنسيق",
    ],
    wrongEn: [
      "Mix database commands into every browser click",
      "Force one person to edit every file at once",
      "Put the database inside a stylesheet",
    ],
  },
  {
    id: "3-1-f11",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "طالب يغيّر درجة ظاهرة بأدوات المطوّر في المتصفح.",
    sceneEn: "A student changes a displayed mark with the browser developer tools.",
    claimAr: "تجاهل الرقم المعدَّل على الشاشة؛ الخادم يقرر الدرجة الحقيقية ويحفظها.",
    claimEn: "Ignore the edited screen; the server decides the real mark and stores it.",
    whyAr: "المتصفح يعرض ويطلب؛ الرقم على الشاشة يمكن تزويره، والخادم هو المرجع.",
    whyEn: "The browser displays and asks; a screen number can be faked, and the server is the source of truth.",
    termAr: "العميل-الخادم",
    termEn: "Client–server",
    wrongAr: [
      "اقبل رقم الأدوات المطوّرة درجة رسمية",
      "اجعل CSS يقفل الدرجة إلى الأبد",
      "احذف القاعدة لأن الشاشة تبدو صحيحة",
    ],
    wrongEn: [
      "Accept the inspector number as official",
      "Let CSS lock the mark forever",
      "Delete the database because the screen looks right",
    ],
  },
  {
    id: "3-1-f12",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "كشف الغياب يحتاج أسماء وتواريخ وزر إرسال.",
    sceneEn: "The absence sheet needs names, dates, and a submit control.",
    claimAr: "ابنِ الجدول والزر بـ HTML حتى يكون للصفحة معنى وهيكل.",
    claimEn: "Build the table and button in HTML so the page has meaning and structure.",
    whyAr: "HTML في الواجهة هو هيكل ما يراه المستخدم ومعناه.",
    whyEn: "Frontend HTML is the structure and meaning of what the user sees.",
    termAr: "هيكل الصفحة",
    termEn: "HTML",
    wrongAr: [
      "ارسم الأسماء بظلال CSS فقط",
      "اترك الجدول في سجل الخادم من غير صفحة",
      "شفّر الأسماء داخل شهادة الشبكة",
    ],
    wrongEn: [
      "Draw the names with CSS shadows only",
      "Leave the table in a server log with no page",
      "Encode the names inside a network certificate",
    ],
  },
  {
    id: "3-1-f13",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "الحاضر يجب أن يظهر أخضر والغائب أحمر على كشف الحضور.",
    sceneEn: "Present should look green and absent red on the attendance sheet.",
    claimAr: "استخدم CSS للون والتخطيط، لا لتقرير من حضر.",
    claimEn: "Use CSS for colour and layout, not to decide who attended.",
    whyAr: "CSS يغيّر المظهر؛ حقيقة الحضور قرار طبقة التطبيق والبيانات.",
    whyEn: "CSS changes look; attendance truth belongs to the application and data layers.",
    termAr: "تنسيق الصفحة",
    termEn: "CSS",
    wrongAr: [
      "عدّ اللون الأخضر دليل حضور رسمي",
      "ضع قاعدة الحضور داخل متغيّر لون",
      "اخفِ الغياب بجعل النص أبيض",
    ],
    wrongEn: [
      "Treat a green style as official attendance",
      "Put the attendance rule inside a colour variable",
      "Hide absences by making the text white",
    ],
  },
  {
    id: "3-1-f14",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "نموذج حضور فارغ يجب أن ينبّه قبل الإرسال.",
    sceneEn: "An empty attendance form should warn before it is sent.",
    claimAr: "استخدم جافاسكربت للتنبيه، ودع الخادم يرفض الحفظ الفارغ أيضًا.",
    claimEn: "Use JavaScript to warn, and still let the server reject an empty save.",
    whyAr: "سلوك الواجهة يساعد، لكنه ليس السلطة الأخيرة على البيانات.",
    whyEn: "Frontend behaviour helps, but it is not the last authority on the data.",
    termAr: "جافاسكربت",
    termEn: "JavaScript",
    wrongAr: [
      "تجاوز الخادم لأن السكربت بدا صالحًا",
      "ضع قاعدة البيانات كلها داخل وسم سكربت",
      "عطّل الحماية لأن الجافاسكربت تعمل",
    ],
    wrongEn: [
      "Skip the server because the script looked valid",
      "Put the whole database inside a script tag",
      "Turn off protection because JavaScript is running",
    ],
  },
  {
    id: "3-1-f15",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "مجلد الموقع العام للمدرسة فيه مفاتيح دفع ظاهرة.",
    sceneEn: "The school's public site folder contains visible payment API keys.",
    claimAr: "انزع المفاتيح من مستودع الواجهة وأبقها في إعداد الخادم.",
    claimEn: "Strip the keys from the frontend repo and keep them in server config.",
    whyAr: "الواجهة العامة مقروءة لكل من ينسخ الملفات.",
    whyEn: "A public frontend is readable by anyone who copies the files.",
    termAr: "مفتاح واجهة البرمجة",
    termEn: "API key",
    wrongAr: [
      "ارفع المفاتيح «للتجربة الصفية فقط»",
      "اخفِ المفاتيح في أسماء الصور",
      "أرسل المفاتيح داخل ملف تنسيق بالبريد",
    ],
    wrongEn: [
      "Commit the keys “just for the class demo”",
      "Hide the keys in image filenames",
      "Email the keys inside a stylesheet",
    ],
  },
  {
    id: "3-1-f16",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "زائر يظن أن فتح صفحة الدرجات يعني أنه فتح قاعدة البيانات نفسها.",
    sceneEn: "A visitor thinks opening the grades page means they opened the database itself.",
    claimAr: "اعرض نظرة في المتصفح، وأبقِ القاعدة خلف الخادم.",
    claimEn: "Show a view in the browser; keep the database behind the server.",
    whyAr: "قاعدة البيانات ليست ما يراه المستخدم؛ هي تخزين دائم خلف الطبقات.",
    whyEn: "The database is not what the user sees; it is persistent storage behind the layers.",
    termAr: "قاعدة البيانات",
    termEn: "Database",
    wrongAr: [
      "اعرض الجداول الخام في المتصفح",
      "اسمح للطلاب باستعلام أي جدول من CSS",
      "انسخ القاعدة كلها إلى التخزين المحلي",
    ],
    wrongEn: [
      "Expose the raw tables in the browser",
      "Let students query any table from CSS",
      "Copy the whole database into localStorage",
    ],
  },
  {
    id: "3-1-f17",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "أجهزة المعمل تفقد شبكة المدرسة ونموذج الحجز ما زال مفتوحًا.",
    sceneEn: "Lab PCs lose the school network while the booking form is still open.",
    claimAr: "أخبر المستخدم أن العميل لا يحفظ حجزًا موثوقًا حتى يرد الخادم.",
    claimEn: "Tell the user the client cannot store a trusted booking until the server replies.",
    whyAr: "من غير الخادم لا يكتمل حفظ يعتمد عليه في نموذج العميل والخادم.",
    whyEn: "Without the server, a trusted write cannot finish in a client–server model.",
    termAr: "العميل-الخادم",
    termEn: "Client–server",
    wrongAr: [
      "احفظ الحجوزات في المتصفح وعدّها رسمية",
      "سمِّ وضعًا بلا شبكة في CSS قاعدة بيانات",
      "اكتب الحجوزات على فلاشة طالب آخر",
    ],
    wrongEn: [
      "Save bookings only in the browser and call them official",
      "Call an offline CSS mode a database",
      "Write bookings onto another student's USB stick",
    ],
  },
  {
    id: "3-1-f18",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "تطبيق الهاتف وموقع المدرسة يحتاجان نفس سجلات الغياب.",
    sceneEn: "The phone app and the school website both need the same absence records.",
    claimAr: "شارك خادمًا واحدًا وقاعدة واحدة؛ اجعل كل واجهة تعرض فقط.",
    claimEn: "Share one backend and one database; let each frontend only present.",
    whyAr: "طبقة تطبيق وبيانات واحدة تبقي العميلين على الحقيقة نفسها.",
    whyEn: "One application and data layer keeps both clients on the same truth.",
    termAr: "الخادم / الخلفية",
    termEn: "Backend",
    wrongAr: [
      "أعطِ كل تطبيق جدولًا خاصًا متعارضًا",
      "اخزن الغياب في ثيم الهاتف فقط",
      "دع CSS يزامن التطبيقين",
    ],
    wrongEn: [
      "Give each app a private conflicting table",
      "Store absences only in the phone theme",
      "Let CSS sync the two apps",
    ],
  },
  {
    id: "3-1-f19",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "بطاقة لوحة التحكم تقول «12 غيابات» بينما المخزون المحفوظ 15.",
    sceneEn: "A dashboard card says 12 absences while the stored count is 15.",
    claimAr: "عامل البطاقة طبقة عرض وحدّثها من طبقة البيانات.",
    claimEn: "Treat the card as presentation and refresh it from the data layer.",
    whyAr: "الشاشة القديمة ليست الحقيقة المخزّنة.",
    whyEn: "A stale screen is not the stored truth.",
    termAr: "طبقة العرض",
    termEn: "Presentation layer",
    wrongAr: [
      "غيّر المخزون ليطابق البطاقة الجميلة",
      "احذف القاعدة لتبسيط الرقم",
      "ثق في صورة متحركة للعدد",
    ],
    wrongEn: [
      "Change the stored count to match the pretty card",
      "Delete the database to simplify the number",
      "Trust an animated picture of the count",
    ],
  },
  {
    id: "3-1-f20",
    lessonId: "3-1",
    chapterId: "3",
    sceneAr: "ولي الأمر يطلب كشف درجات PDF من بوابة المدرسة.",
    sceneEn: "A parent asks for a transcript PDF from the school portal.",
    claimAr: "المتصفح يطلب؛ الخادم يفحص الحق ويقرأ البيانات ويحفظ أثر الطلب.",
    claimEn: "The browser asks; the server checks the right, reads the data, and stores an audit.",
    whyAr: "الخادم يقرر ويحفظ؛ المتصفح يعرض الطلب والنتيجة فقط.",
    whyEn: "The server decides and stores; the browser only displays the request and the result.",
    termAr: "طبقة التطبيق",
    termEn: "Application layer",
    wrongAr: [
      "دع هاتف ولي الأمر يخترع الكشف",
      "تجاوز فحص الصلاحية لأن ملف PDF يبدو رسميًا",
      "احفظ الأثر خلفية على سطح المكتب فقط",
    ],
    wrongEn: [
      "Let the parent's phone invent the transcript",
      "Skip the permission check because the PDF looks official",
      "Store the audit only as a desktop wallpaper",
    ],
  },
  {
    id: "3-2-f01",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "طالب يفتح درجاته على شبكة مقهى، والشريط يظهر http بلا قفل.",
    sceneEn: "A student opens grades on cafe Wi-Fi; the bar shows http with no padlock.",
    claimAr: "ارفض كتابة كلمة المرور حتى تصبح الصفحة HTTPS.",
    claimEn: "Refuse to type the password until the page uses HTTPS.",
    whyAr: "HTTP يرسل الطلب واضحًا؛ HTTPS يغلفه بقناة TLS مشفّرة.",
    whyEn: "HTTP sends the request in the clear; HTTPS wraps it in an encrypted TLS channel.",
    termAr: "بروتوكول ويب آمن",
    termEn: "HTTPS",
    wrongAr: [
      "اكتب كلمة المرور لأن المقهى مزدحم",
      "ثق بزر أخضر بدل القناة المشفّرة",
      "أزل القفل حتى تُفتح الصفحة أسرع",
    ],
    wrongEn: [
      "Type the password because the cafe is busy",
      "Trust a green button instead of the encrypted channel",
      "Drop the padlock so the page loads faster",
    ],
  },
  {
    id: "3-2-f02",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "المعلم يريد فقط قراءة كشف حضور اليوم من غير تعديل.",
    sceneEn: "The teacher only wants to read today's attendance list without changing it.",
    claimAr: "أرسل طلب GET للقراءة من غير تغيير القائمة.",
    claimEn: "Send a GET request that reads and does not change the list.",
    whyAr: "GET هي الطريقة الشائعة للقراءة الآمنة لمورد.",
    whyEn: "GET is the common method for a safe read of a resource.",
    termAr: "طلب قراءة",
    termEn: "GET",
    wrongAr: [
      "احذف القائمة حتى تراها",
      "أنشئ شعبة فارغة بـ POST في كل مشاهدة",
      "استبدل العام كله بـ PUT لتحديث الشاشة",
    ],
    wrongEn: [
      "DELETE the list in order to see it",
      "POST a new empty class on every view",
      "PUT the whole year to refresh the screen",
    ],
  },
  {
    id: "3-2-f03",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "طالب ينشئ حجز معمل جديد يوم الأربعاء.",
    sceneEn: "A student creates a new Wednesday lab booking.",
    claimAr: "أرسل POST لإنشاء مورد الحجز.",
    claimEn: "Send POST to create the booking resource.",
    whyAr: "POST هي الطريقة المعتادة لإنشاء سجل جديد.",
    whyEn: "POST is the usual method for creating a new record.",
    termAr: "طلب إرسال",
    termEn: "POST",
    wrongAr: [
      "استخدم GET يحجز في الخفاء",
      "احذف الموعد أولًا حتى يوجد",
      "اخفِ الحجز في كوكي من غير خادم",
    ],
    wrongEn: [
      "Use a GET that silently books the slot",
      "DELETE the slot first so it exists",
      "Hide the booking in a cookie with no server",
    ],
  },
  {
    id: "3-2-f04",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "شؤون الطلاب تستبدل ملف تسجيل الطالب كله بعد نقل الصف.",
    sceneEn: "The registrar replaces a student's entire registration profile after a class move.",
    claimAr: "استخدم PUT عندما يُستبدل المورد كاملًا.",
    claimEn: "Use PUT when the whole resource is replaced.",
    whyAr: "PUT يحدّث بإرسال بديل كامل للمورد.",
    whyEn: "PUT updates by sending a full replacement of the resource.",
    termAr: "طلب استبدال",
    termEn: "PUT",
    wrongAr: [
      "اقرأ الملف القديم بـ GET وعدّ ذلك تحديثًا",
      "احذف الطالب لتغيير حقل واحد",
      "ضع الملف الجديد في عنوان CSS فقط",
    ],
    wrongEn: [
      "GET the old profile and call that an update",
      "DELETE the student to change one field",
      "Put the new profile only in a CSS title",
    ],
  },
  {
    id: "3-2-f05",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "تغيّر رقم هاتف ولي الأمر فقط في بطاقة التسجيل.",
    sceneEn: "Only the parent phone number changed on the registration card.",
    claimAr: "استخدم PATCH لتحديث ذلك الحقل وحده.",
    claimEn: "Use PATCH to update that one field.",
    whyAr: "PATCH تحديث جزئي، لا إعادة كتابة للملف كله.",
    whyEn: "PATCH is a partial update, not a full rewrite.",
    termAr: "طلب تعديل جزئي",
    termEn: "PATCH",
    wrongAr: [
      "احذف الطالب وأعد إنشاءه من أجل رقم",
      "افتح صفحة فارغة بـ GET لتغيير الرقم",
      "ضع الرقم في عنوان الصفحة وتوقف",
    ],
    wrongEn: [
      "DELETE the student and recreate them for one digit",
      "GET a blank page to change the number",
      "Put the number in the page title and stop",
    ],
  },
  {
    id: "3-2-f06",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "النادي يلغي ساعة معمل محجوزة بعد اعتذار المدرب.",
    sceneEn: "The club cancels a booked lab hour after the coach cancels.",
    claimAr: "أرسل DELETE لإزالة ذلك الحجز إن سمح الخادم.",
    claimEn: "Send DELETE to remove that booking if the server allows it.",
    whyAr: "DELETE هي الطريقة التي تطلب حذف مورد.",
    whyEn: "DELETE is the method that asks to remove a resource.",
    termAr: "طلب حذف",
    termEn: "DELETE",
    wrongAr: [
      "كرّر GET حتى يختفي الموعد",
      "أرسل POST لنفس الساعة مرتين للإلغاء",
      "غيّر لون الزر وافترض أن الموعد اختفى",
    ],
    wrongEn: [
      "Repeat GET until the slot vanishes",
      "POST the same hour twice to cancel",
      "Change the button colour and assume the booking is gone",
    ],
  },
  {
    id: "3-2-f07",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "التطبيق يطلب حضور الصف 9-ز لكن رمز الصف خطأ.",
    sceneEn: "The app requests attendance for class 9-Z, but that class code is wrong.",
    claimAr: "اقرأ 404 على أنه «هذا المورد غير موجود».",
    claimEn: "Read 404 as this resource is not here.",
    whyAr: "رمز 404 يعني أن الخادم لم يجد المورد على ذلك العنوان.",
    whyEn: "Status 404 means the server did not find the resource at that address.",
    termAr: "رمز 404",
    termEn: "Status 404",
    wrongAr: [
      "اقرأ 404 نجاحًا كاملًا",
      "اقرأ 404 انهيار قرص الخادم",
      "تجاهل الرمز واخترع شعبة",
    ],
    wrongEn: [
      "Read 404 as full success",
      "Read 404 as a crashed server disk",
      "Ignore the code and invent a class",
    ],
  },
  {
    id: "3-2-f08",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "حفظ التسجيل يرجع 500 عند الثامنة ودقيقة.",
    sceneEn: "A registration save returns 500 at 8:01.",
    claimAr: "اقرأ 500 خطأ خادم، لا صفحة ناقصة.",
    claimEn: "Read 500 as a server error, not as a missing page.",
    whyAr: "رمز 500 يخبر أن الخادم فشل أثناء معالجة الطلب.",
    whyEn: "Status 500 reports that the server failed while handling the request.",
    termAr: "رمز 500",
    termEn: "Status 500",
    wrongAr: [
      "احتفل بـ 500 مقعدًا محفوظًا",
      "عامل 500 ككوكي خاص",
      "افترض أن 500 خطأ إملائي في الرابط فقط",
    ],
    wrongEn: [
      "Celebrate 500 as a saved seat",
      "Treat 500 like a private cookie",
      "Assume 500 is only a typo in the URL",
    ],
  },
  {
    id: "3-2-f09",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "جلب الدرجات يرجع 200 وقائمة JSON.",
    sceneEn: "A grades fetch returns 200 and a JSON list.",
    claimAr: "اقرأ 200 نجاحًا ثم فسّر جسم الرد.",
    claimEn: "Read 200 as success and then parse the body.",
    whyAr: "رمز 200 هو حالة النجاح الشائعة للطلب.",
    whyEn: "Status 200 is the common success status for the request.",
    termAr: "رمز 200",
    termEn: "Status 200",
    wrongAr: [
      "عامل 200 بمعنى غير موجود",
      "عامل 200 انهيار خادم",
      "تجاهل الجسم لأن الرقم يبدو محظوظًا",
    ],
    wrongEn: [
      "Treat 200 as not found",
      "Treat 200 as a server crash",
      "Ignore the body because the code looks lucky",
    ],
  },
  {
    id: "3-2-f10",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "بعد تسجيل الدخول ينتقل المعلم من الحضور إلى الدرجات من غير إعادة كتابة السر.",
    sceneEn: "After login, the teacher moves from attendance to grades without typing the secret again.",
    claimAr: "أبقِ الدخول في جلسة وكوكي يثق به الخادم.",
    claimEn: "Keep the login in a session cookie that the server trusts.",
    whyAr: "الكوكيز والجلسات تحفظ حالة الدخول عبر الطلبات.",
    whyEn: "Cookies and sessions keep login state alive across requests.",
    termAr: "جلسة",
    termEn: "Session",
    wrongAr: [
      "ضع كلمة المرور في عنوان الصفحة",
      "اطلب السر في كل نقرة بلا جلسة",
      "اكتفِ بشارة مطبوعة بدل الجلسة",
    ],
    wrongEn: [
      "Put the password in the page title",
      "Ask for the secret on every click with no session",
      "Rely on a printed badge instead of a session",
    ],
  },
  {
    id: "3-2-f11",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "تطبيق الهاتف يرسل الحقل mark بينما الخادم ينتظر score.",
    sceneEn: "The phone app sends the field mark while the server expects score.",
    claimAr: "اكتب عقد واجهة برمجة واضحًا يتفق على أسماء الحقول.",
    claimEn: "Write a clear API contract that agrees on field names.",
    whyAr: "من غير اتفاق على الطلب والرد لا يفهم البرنامجان بعضهما.",
    whyEn: "Without an agreed request and response, the two programs do not understand each other.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: [
      "أمل أن يخمن الخادم الأسماء العربية",
      "أصلح الخلاف بلون أجمل",
      "احذف JSON لأن الأسماء اختلفت",
    ],
    wrongEn: [
      "Hope the server guesses Arabic field names",
      "Fix the mismatch with a prettier colour",
      "Delete JSON because the names differ",
    ],
  },
  {
    id: "3-2-f12",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "درجات طالب تعيش على المسار /students/1204/grades.",
    sceneEn: "A student's marks live at the path /students/1204/grades.",
    claimAr: "عامل هذا العنوان مورد REST تتصرّف عليه الطرق.",
    claimEn: "Treat that URL as a REST resource that the methods act on.",
    whyAr: "REST ينظّم البيانات موارد لها عناوين.",
    whyEn: "REST organizes data as resources with addresses.",
    termAr: "موارد بعنوان",
    termEn: "REST",
    wrongAr: [
      "اخفِ الدرجات في اسم إجراء عشوائي بلا مورد",
      "اخزن REST داخل شبكة CSS",
      "استخدم الرابط كلمة مرور",
    ],
    wrongEn: [
      "Hide the marks in a random action name with no resource",
      "Store REST inside a CSS grid",
      "Use the URL as a password",
    ],
  },
  {
    id: "3-2-f13",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "رد التسجيل هو {\"ok\":true,\"seat\":18}.",
    sceneEn: "The registration reply is {\"ok\":true,\"seat\":18}.",
    claimAr: "أرسل واقرأ JSON بوصفه شكل الجسم المتفق عليه.",
    claimEn: "Send and read JSON as the agreed payload shape.",
    whyAr: "JSON جسم شائع لواجهات REST.",
    whyEn: "JSON is the common body for REST APIs.",
    termAr: "نص بيانات منظم",
    termEn: "JSON",
    wrongAr: [
      "أرسل لقطة شاشة بدل الجسم",
      "شفّر المقعد ملف خط",
      "ضع الرد في اسم كوكي فقط",
    ],
    wrongEn: [
      "Send a screenshot instead of a payload",
      "Encode the seat as a font file",
      "Put the reply only in a cookie name",
    ],
  },
  {
    id: "3-2-f14",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "صفحة الدخول بلا قفل وتظهر تحذير شهادة.",
    sceneEn: "The login page has no padlock and shows a certificate warning.",
    claimAr: "توقف؛ قناة TLS لا تحمي طلب HTTP.",
    claimEn: "Stop; the TLS channel is not protecting the HTTP request.",
    whyAr: "HTTPS هو HTTP فوق قناة TLS مشفّرة بشهادة الموقع.",
    whyEn: "HTTPS is HTTP over a TLS-encrypted channel with the site certificate.",
    termAr: "قناة مشفرة",
    termEn: "TLS",
    wrongAr: [
      "تجاوز التحذير لأن الشعار يبدو رسميًا",
      "ثق بملصق المدرسة بدل TLS",
      "انقل كلمة المرور إلى HTML لتجاوز التشفير",
    ],
    wrongEn: [
      "Click through because the logo looks official",
      "Trust a school poster instead of TLS",
      "Move the password into HTML to skip encryption",
    ],
  },
  {
    id: "3-2-f15",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "تبويب الحضور بقي مفتوحًا ليلة كاملة على جهاز المعمل ثم طلب الدخول من جديد.",
    sceneEn: "The attendance tab stayed open overnight on a lab PC and then asked for login again.",
    claimAr: "دع الجلسة تنتهي واطلب دخولًا جديدًا.",
    claimEn: "Let the session end and require a fresh login.",
    whyAr: "الجلسة يجب أن تنتهي حتى لا يبقى جهاز المعمل المشترك مفتوحًا.",
    whyEn: "A session should expire so a shared lab PC is not left open.",
    termAr: "كوكي",
    termEn: "Cookie",
    wrongAr: [
      "اجعل الكوكي أبديًا على كل أجهزة المعمل",
      "اكتب كلمة المرور على ورقة تحت لوحة المفاتيح",
      "عطّل HTTPS بعد أول دخول",
    ],
    wrongEn: [
      "Keep an immortal cookie on every lab PC",
      "Write the password on a note under the keyboard",
      "Disable HTTPS after the first login",
    ],
  },
  {
    id: "3-2-f16",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "مطوّر يحفظ الحضور عبر GET /attend?save=1.",
    sceneEn: "A developer marks presence with GET /attend?save=1.",
    claimAr: "لا تستخدم GET لتغيير الحضور؛ استخدم POST.",
    claimEn: "Do not use GET to change attendance; use POST.",
    whyAr: "GET للقراءة؛ الإنشاء يحتاج طريقة تعني إنشاء سجل.",
    whyEn: "GET is for reading; a create needs a method that means a new record.",
    termAr: "طلب قراءة",
    termEn: "GET",
    wrongAr: [
      "استمر في الحفظ بـ GET لأنه أقصر",
      "احذف الطالب كي يظهر حاضرًا",
      "اخفِ الحفظ في تحويل لون عند المرور",
    ],
    wrongEn: [
      "Keep saving with GET because it is shorter",
      "DELETE the student to mark them present",
      "Hide the save in a hover colour change",
    ],
  },
  {
    id: "3-2-f17",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "كوكي الجلسة يُرسل على HTTP واضح من مكتبة المدرسة.",
    sceneEn: "The session cookie is sent on clear HTTP from the school library.",
    claimAr: "افرض HTTPS حتى لا يُسرق الكوكي على الخط.",
    claimEn: "Require HTTPS so the cookie is not stolen on the wire.",
    whyAr: "قناة HTTP الواضحة يمكن أن تسرّب الكوكيز.",
    whyEn: "A clear HTTP channel can leak cookies.",
    termAr: "بروتوكول ويب آمن",
    termEn: "HTTPS",
    wrongAr: [
      "ألصق ملصقات أكثر على موجّه المكتبة",
      "ضع الكوكي في عنوان الصفحة",
      "استخدم 404 لتشفير الكوكي",
    ],
    wrongEn: [
      "Put more stickers on the library router",
      "Put the cookie in the page heading",
      "Use 404 to encrypt the cookie",
    ],
  },
  {
    id: "3-2-f18",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "الواجهة ترسل 16/09/2026 والخادم ينتظر 2026-09-16 في التسجيل.",
    sceneEn: "The frontend sends 16/09/2026 while the server expects 2026-09-16 on registration.",
    claimAr: "اتفق على شكل التاريخ في عقد الواجهة قبل الإطلاق.",
    claimEn: "Agree the date format in the API contract before launch.",
    whyAr: "العقد لغة مشتركة للطلب والرد.",
    whyEn: "The contract is the shared language of request and response.",
    termAr: "عقد الواجهة",
    termEn: "API contract",
    wrongAr: [
      "دع كل شعبة تخترع كتابة تاريخ",
      "أصلح التواريخ برمز 500 عشوائي",
      "اخزن التواريخ ألوان أزرار فقط",
    ],
    wrongEn: [
      "Let each class invent a date spelling",
      "Fix dates with a random 500",
      "Store dates only as button colours",
    ],
  },
  {
    id: "3-2-f19",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "أي شخص يخمن رابط الحجز يقدر يرسل DELETE.",
    sceneEn: "Anyone who guesses a booking URL can send DELETE.",
    claimAr: "يجب أن يقرر الخادم الصلاحية قبل الحذف.",
    claimEn: "The server must still decide the right before deleting.",
    whyAr: "الطريقة وحدها لا تكفي؛ طبقة التطبيق تفحص من يجوز له الفعل.",
    whyEn: "A method is not enough; the application layer checks who may act.",
    termAr: "طلب حذف",
    termEn: "DELETE",
    wrongAr: [
      "ثق بأي DELETE قادم من الشبكة",
      "اخفِ الزر وعدّ ذلك حماية",
      "اخزن الحقوق في المتصفح فقط",
    ],
    wrongEn: [
      "Trust any DELETE from the network",
      "Hide the button and call that security",
      "Store rights only in the browser",
    ],
  },
  {
    id: "3-2-f20",
    lessonId: "3-2",
    chapterId: "3",
    sceneAr: "قائمة المعمل تفشل: هاتف يرجع 404 وآخر يرجع 500.",
    sceneEn: "The lab list fails: one phone gets 404, another gets 500.",
    claimAr: "استخدم رمز الحالة لتفريق مورد ناقص عن عطل خادم.",
    claimEn: "Use the status code to tell a missing resource from a server fault.",
    whyAr: "رموز الحالة تخبر النتيجة حتى يردّ التطبيقان بشكل صحيح.",
    whyEn: "Status codes report the result so the two apps can react correctly.",
    termAr: "رمز الحالة",
    termEn: "Status code",
    wrongAr: [
      "تجاهل الرموز وحدّث إلى ما لا نهاية",
      "عامل كل فشل مشكلة ألوان",
      "افترض أن للهاتفين السبب نفسه",
    ],
    wrongEn: [
      "Ignore the codes and refresh forever",
      "Treat every failure as a colour problem",
      "Assume both phones have the same cause",
    ],
  },
  {
    id: "3-3-f01",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "زر «حاضر» في صفحة الحضور مربع div أخضر عليه سكربت نقرة.",
    sceneEn: "The Present control on attendance is a green div with a click script.",
    claimAr: "استخدم زرًا حقيقيًا حتى تعمل لوحة المفاتيح والمعنى.",
    claimEn: "Use a real button so the keyboard and the meaning work.",
    whyAr: "الـ div ليس عنصر تحكم؛ الزر عنصر له معنى.",
    whyEn: "A div is not a control; a button is an element with meaning.",
    termAr: "عنصر دلالي",
    termEn: "Semantic element",
    wrongAr: [
      "أبقِ الـ div وكبّر الظل",
      "ارسم صورة زر",
      "اخفِ الفعل في صورة خلفية",
    ],
    wrongEn: [
      "Keep the div and enlarge the shadow",
      "Draw a picture of a button",
      "Hide the action in a background image",
    ],
  },
  {
    id: "3-3-f02",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "صفحة الدرجات جدار من مربعات div بخط عريض كبير.",
    sceneEn: "The grades page is a wall of divs with large bold text.",
    claimAr: "استخدم عناوين HTML حقيقية حتى يكون للهيكل معنى.",
    claimEn: "Use real HTML headings so the structure has meaning.",
    whyAr: "HTML يعطي المعنى؛ التكبير البصري وحده لا يصنع عنوانًا.",
    whyEn: "HTML gives meaning; visual size alone does not make a heading.",
    termAr: "هيكل الصفحة",
    termEn: "HTML",
    wrongAr: [
      "زيّف العناوين بحجم CSS فقط",
      "ضع العنوان في كوكي",
      "تجاوز الهيكل لأن الألوان قوية",
    ],
    wrongEn: [
      "Fake headings with CSS size only",
      "Put the title in a cookie",
      "Skip structure because the colours are strong",
    ],
  },
  {
    id: "3-3-f03",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "المتأخر نقطة حمراء والحاضر نقطة خضراء من غير كلمة.",
    sceneEn: "Late is only a red dot and present is only a green dot, with no word.",
    claimAr: "أضف كلمة أو تسمية، لا تعتمد على اللون وحده.",
    claimEn: "Add a word or a label; do not rely on colour alone.",
    whyAr: "الحالة باللون فقط تفشل مع كثير من المستخدمين ومع قارئ الشاشة.",
    whyEn: "A colour-only status fails many users and a screen reader.",
    termAr: "إتاحة الوصول",
    termEn: "Accessibility",
    wrongAr: [
      "أضف درجات أكثر من الأحمر",
      "احذف الكلمة ليبدو التصميم حديثًا",
      "استبدل الاسم بحركة بصرية",
    ],
    wrongEn: [
      "Add more shades of red",
      "Drop the word so the design looks modern",
      "Replace the name with a motion effect",
    ],
  },
  {
    id: "3-3-f04",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "حقول حجز المعمل بلا تسمية ظاهرة، فقط نص رمادي يختفي.",
    sceneEn: "Lab booking fields have no visible label, only grey placeholder text that vanishes.",
    claimAr: "اربط تسمية ظاهرة بكل حقل إدخال.",
    claimEn: "Bind a visible label to every input.",
    whyAr: "النص المؤقت يختفي، وقارئ الشاشة يحتاج اسمًا ثابتًا.",
    whyEn: "A placeholder vanishes, and a screen reader needs a lasting name.",
    termAr: "قارئ الشاشة",
    termEn: "Screen reader",
    wrongAr: [
      "اعتمد النص الرمادي إلى الأبد",
      "لوّن الإطار وتوقف",
      "ضع التلميح في تلميح يظهر عند المرور فقط",
    ],
    wrongEn: [
      "Rely on the grey placeholder forever",
      "Colour the border and stop",
      "Put the hint in a hover-only tooltip",
    ],
  },
  {
    id: "3-3-f05",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "زر «التالي» في التسجيل يعمل بالفأرة فقط.",
    sceneEn: "The Next control on registration works only with a mouse click.",
    claimAr: "اجعل كل خطوة تصل بلوحة المفاتيح.",
    claimEn: "Make every step reachable with the keyboard.",
    whyAr: "إتاحة الوصول تشمل لوحة المفاتيح، لا الفأرة وحدها.",
    whyEn: "Accessibility includes keyboard use, not the mouse alone.",
    termAr: "لوحة المفاتيح",
    termEn: "Keyboard",
    wrongAr: [
      "افرض الفأرة لإثبات أن الطالب حاضر",
      "احذف إطار التركيز ليبدو أنظف",
      "احبس التركيز داخل مربع مخفي",
    ],
    wrongEn: [
      "Require a mouse to prove the student is present",
      "Remove focus outlines for a cleaner look",
      "Trap focus inside a hidden box",
    ],
  },
  {
    id: "3-3-f06",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "جدول الحضور شبكة عريضة تفيض عن شاشة الهاتف.",
    sceneEn: "The attendance table is a wide desktop grid that overflows on a phone.",
    claimAr: "صمّم تخطيط الهاتف أولًا ثم وسّع للشاشة الكبيرة.",
    claimEn: "Design the phone layout first, then expand to the wide screen.",
    whyAr: "التصميم المتجاوب يخدم الشاشة الضيقة قبل الشاشة العريضة أحيانًا.",
    whyEn: "Responsive design often serves the narrow screen before the wide one.",
    termAr: "الهاتف أولًا",
    termEn: "Mobile first",
    wrongAr: [
      "صمّم فقط لشاشة سينما المعمل",
      "اجعل القرص بالإصبعين الخطة الوحيدة",
      "صغّر الحروف حتى تنضغط",
    ],
    wrongEn: [
      "Design only for the lab cinema screen",
      "Treat pinch-zoom as the only plan",
      "Shrink the type until it fits",
    ],
  },
  {
    id: "3-3-f07",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "CSS يجعل «إرسال التسجيل» يبدو معطّلًا بينما التحكم ما زال يرسل.",
    sceneEn: "CSS makes Submit registration look disabled, but the control still sends.",
    claimAr: "عطّل التحكم الحقيقي، لا تغيّر مظهره فقط.",
    claimEn: "Disable the real control; do not only restyle it.",
    whyAr: "المظهر عمل CSS؛ الحالة الحقيقية تحتاج تعطيل عنصر حقيقي.",
    whyEn: "Look is CSS; real state needs a genuinely disabled control.",
    termAr: "تنسيق الصفحة",
    termEn: "CSS",
    wrongAr: [
      "اللون الرمادي حماية كافية",
      "اخفِ الزر بالشفافية واتركه نشطًا",
      "اكتب معطّل في تعليق الصفحة فقط",
    ],
    wrongEn: [
      "A grey colour is enough protection",
      "Hide the button with opacity and leave it active",
      "Write disabled only in a page comment",
    ],
  },
  {
    id: "3-3-f08",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "قائمة الدرجات تظهر فقط بعد سكربت يحقن نصوصًا بلا روابط.",
    sceneEn: "The grades menu appears only after a script injects spans with no links.",
    claimAr: "ضع روابط أو أزرارًا حقيقية في HTML ثم حسّنها بجافاسكربت.",
    claimEn: "Put real links or buttons in HTML, then enhance them with JavaScript.",
    whyAr: "HTML يجب أن يحمل الهيكل حتى قبل تشغيل السلوك.",
    whyEn: "HTML should carry the structure even before behaviour runs.",
    termAr: "هيكل الصفحة",
    termEn: "HTML",
    wrongAr: [
      "أغلق الموقع إن توقفت الجافاسكربت بلا هيكل",
      "استبدل الروابط برسوم على لوحة",
      "اخزن التنقل في القاعدة فقط",
    ],
    wrongEn: [
      "Block the site if JavaScript is off and leave no structure",
      "Replace all links with canvas drawings",
      "Store navigation only in the database",
    ],
  },
  {
    id: "3-3-f09",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "«حفظ الحضور» صورة PNG عليها كلمة إرسال.",
    sceneEn: "Save attendance is a PNG picture of the word Submit.",
    claimAr: "استخدم زرًا حقيقيًا بنص، لا صورة زر.",
    claimEn: "Use a real button with text, not a picture of a button.",
    whyAr: "صورة التحكم تخفي المعنى عن لوحة المفاتيح وقارئ الشاشة.",
    whyEn: "A picture of a control hides meaning from keyboards and screen readers.",
    termAr: "زر حقيقي",
    termEn: "Real button",
    wrongAr: [
      "أضف نصًا بديلًا يقول صورة جميلة",
      "كبّر ملف PNG",
      "ضع فعل الحفظ على شعار المدرسة",
    ],
    wrongEn: [
      "Add alt text that says nice picture",
      "Make the PNG larger",
      "Put the save action on the school logo",
    ],
  },
  {
    id: "3-3-f10",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "الفريق جرّب الحضور بلوحة تتبع فقط أمام المدير.",
    sceneEn: "The team demoed attendance with a trackpad only in front of the principal.",
    claimAr: "اختبر المسار كله بلوحة المفاتيح من غير فأرة.",
    claimEn: "Test the whole flow with the keyboard and no mouse.",
    whyAr: "صفحة تحتاج مؤشرًا تفشل في اختبار الإتاحة البسيط.",
    whyEn: "A page that needs a pointer fails a simple accessibility test.",
    termAr: "لوحة المفاتيح",
    termEn: "Keyboard",
    wrongAr: [
      "اختبر أجمل سمة سطح مكتب فقط",
      "اخفِ التركيز حتى يبدو حديثًا",
      "تجاوز جهاز المعمل اللوحي",
    ],
    wrongEn: [
      "Test only the prettiest desktop theme",
      "Hide focus so testers feel modern",
      "Skip the lab tablet",
    ],
  },
  {
    id: "3-3-f11",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "قارئ الشاشة يقول «5 12 9» على جدول الدرجات بلا أسماء أعمدة.",
    sceneEn: "A screen reader says 5 12 9 on the marks grid with no column names.",
    claimAr: "استخدم رؤوس جدول حتى يكون لكل درجة معنى.",
    claimEn: "Use table headers so each mark has meaning.",
    whyAr: "شبكة بلا رؤوس أرقام بلا أسماء.",
    whyEn: "A grid without headers is numbers without names.",
    termAr: "قارئ الشاشة",
    termEn: "Screen reader",
    wrongAr: [
      "أضف لونًا أعلى صوتًا",
      "حوّل الجدول إلى مربعات متداخلة",
      "اقرأ الأرقام أسرع",
    ],
    wrongEn: [
      "Add a louder colour",
      "Turn the table into nested boxes",
      "Read the numbers faster",
    ],
  },
  {
    id: "3-3-f12",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "نص شروط التسجيل صغير جدًا على الهاتف.",
    sceneEn: "Registration terms are tiny on a phone.",
    claimAr: "كبّر الحروف لشاشة الهاتف أولًا حتى تُقرأ.",
    claimEn: "Size the type for a phone first so it can be read.",
    whyAr: "CSS المتجاوب يجب أن يخدم الشاشة المحمولة باليد.",
    whyEn: "Responsive CSS must serve a hand-held screen.",
    termAr: "تصميم متجاوب",
    termEn: "Responsive design",
    wrongAr: [
      "اطلب من الطلاب شراء شاشة",
      "ضع النص في صندوق يظهر عند المرور فقط",
      "التقط صورة لصفحة سطح المكتب",
    ],
    wrongEn: [
      "Tell students to buy a monitor",
      "Put the text in a hover-only box",
      "Screenshot the desktop page",
    ],
  },
  {
    id: "3-3-f13",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "أدوات المعمل تظهر فقط حين تمر الفأرة على الجانب.",
    sceneEn: "Lab tools appear only when a mouse hovers the side.",
    claimAr: "افتح الأدوات نفسها بتركيز لوحة المفاتيح، لا بالمرور وحده.",
    claimEn: "Open the same tools with keyboard focus, not hover alone.",
    whyAr: "القائمة بالمرور فقط تغلق الباب على لوحة المفاتيح وكثير من الهواتف.",
    whyEn: "A hover-only menu locks out keyboards and many phones.",
    termAr: "إتاحة الوصول",
    termEn: "Accessibility",
    wrongAr: [
      "أطل تأخير المرور",
      "افرض درس فأرة أولًا",
      "اخفِ الأدوات خلف زر أيمن",
    ],
    wrongEn: [
      "Add a longer hover delay",
      "Require a mouse lesson first",
      "Hide the tools behind a right-click",
    ],
  },
  {
    id: "3-3-f14",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "دخول البوابة يستخدم «الرقم القومي» نصًا مؤقتًا هو التلميح الوحيد.",
    sceneEn: "Portal login uses national id as the only placeholder hint.",
    claimAr: "أبقِ تسمية دائمة خارج الحقل.",
    claimEn: "Keep a lasting label outside the field.",
    whyAr: "النص المؤقت ليس اسمًا ثابتًا للمعنى.",
    whyEn: "A placeholder is not a durable name for meaning.",
    termAr: "هيكل الصفحة",
    termEn: "HTML",
    wrongAr: [
      "حرّك النص المؤقت وتوقف",
      "ضع التلميح في خلفية الصفحة",
      "استخدم خطًا ملونًا وحده",
    ],
    wrongEn: [
      "Animate the placeholder and stop",
      "Put the hint in the page background",
      "Use a colour-only underline",
    ],
  },
  {
    id: "3-3-f15",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "نموذج التسجيل كله مربعات متداخلة تمثّل قوائم وأزرارًا.",
    sceneEn: "The whole registration form is nested boxes acting like lists and buttons.",
    claimAr: "استخدم عناصر النموذج والتسمية والإدخال والزر والقائمة الحقيقية.",
    claimEn: "Use real form, label, input, button, and list elements.",
    whyAr: "العناصر الحقيقية تحمل معنى؛ كومة المربعات لا تفعل.",
    whyEn: "Real elements carry meaning; a pile of boxes does not.",
    termAr: "عنصر دلالي",
    termEn: "Semantic element",
    wrongAr: [
      "أضف أغلفة أكثر للوضوح",
      "زيّن المربعات حتى تبدو رسمية",
      "استبدل النموذج بصورة واحدة ضخمة",
    ],
    wrongEn: [
      "Add more wrappers for clarity",
      "Style the boxes until they look official",
      "Replace the form with one giant image",
    ],
  },
  {
    id: "3-3-f16",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "عناوين صفحة المعمل تظهر فقط بعد تشغيل سكربت.",
    sceneEn: "Lab page headings appear only after a script runs.",
    claimAr: "ضع هيكل العناوين في HTML أولًا.",
    claimEn: "Put the heading structure in the HTML first.",
    whyAr: "المعنى يجب ألا ينتظر السلوك بعد التحميل.",
    whyEn: "Meaning should not wait for behaviour after load.",
    termAr: "هيكل الصفحة",
    termEn: "HTML",
    wrongAr: [
      "أخّر كل النص حتى تنتهي دائرة الانتظار",
      "اخزن العناوين في التخزين المحلي",
      "ارسم العناوين بمحتوى CSS فقط",
    ],
    wrongEn: [
      "Delay all text until a spinner ends",
      "Store headings in localStorage",
      "Paint headings with CSS content only",
    ],
  },
  {
    id: "3-3-f17",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "شارة المتأخر أصفر باهت على أبيض في كشف الحضور.",
    sceneEn: "The late badge is pale yellow on white on the attendance sheet.",
    claimAr: "ارفع التباين حتى تُقرأ الكلمة.",
    claimEn: "Raise the contrast so the word can be read.",
    whyAr: "المظهر يشمل لونًا مقروءًا، لا زينة فقط.",
    whyEn: "Look includes readable colour, not decoration alone.",
    termAr: "تنسيق الصفحة",
    termEn: "CSS",
    wrongAr: [
      "أضف حركة خفيفة بدل التباين",
      "صغّر الشارة",
      "دع الطلاب يخمنون الحالة",
    ],
    wrongEn: [
      "Add a faint animation instead of contrast",
      "Shrink the badge",
      "Let students guess the status",
    ],
  },
  {
    id: "3-3-f18",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "نقاط الحضور على الهاتف عرضها ثماني بكسلات.",
    sceneEn: "Attendance dots on the phone are eight pixels wide.",
    claimAr: "اجعل أهداف اللمس كبيرة في تخطيط الهاتف أولًا.",
    claimEn: "Give large tap targets on a phone-first layout.",
    whyAr: "الإصبع ليس مؤشرًا دقيقًا كالبكسل.",
    whyEn: "A finger is not a pixel-precise pointer.",
    termAr: "الهاتف أولًا",
    termEn: "Mobile first",
    wrongAr: [
      "أبقِ النقاط صغيرة للأناقة",
      "افرض قلمًا رقميًا",
      "انقل النقاط إلى قائمة تظهر عند المرور",
    ],
    wrongEn: [
      "Keep tiny dots to look elegant",
      "Require a stylus",
      "Move the dots into a hover menu",
    ],
  },
  {
    id: "3-3-f19",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "شبكة أجهزة المعمل تفيض عن جهاز لوحي ضيق.",
    sceneEn: "The CSS grid of lab PCs overflows on a narrow tablet.",
    claimAr: "أعد تدفق التخطيط بـ CSS متجاوب.",
    claimEn: "Reflow the layout with responsive CSS.",
    whyAr: "CSS مسؤول عن تخطيط يناسب عرض الشاشة.",
    whyEn: "CSS is responsible for a layout that fits the screen width.",
    termAr: "تصميم متجاوب",
    termEn: "Responsive design",
    wrongAr: [
      "افرض تمريرًا جانبيًا بوصفه التصميم",
      "اقطع الأسماء",
      "افتح موقع سطح المكتب داخل إطار صغير",
    ],
    wrongEn: [
      "Force sideways scroll as the design",
      "Crop the names",
      "Open the desktop site in a tiny frame",
    ],
  },
  {
    id: "3-3-f20",
    lessonId: "3-3",
    chapterId: "3",
    sceneAr: "«تنزيل الدرجات» نص span عليه نقرة جافاسكربت.",
    sceneEn: "Download grades is a span with a JavaScript click.",
    claimAr: "استخدم رابطًا أو زرًا حقيقيًا يمكن تركيزه.",
    claimEn: "Use a real link or button that can receive focus.",
    whyAr: "الـ span ليس رابطًا؛ الآلة المساعدة تحتاج عنصر تحكم حقيقي.",
    whyEn: "A span is not a link; an assistive machine needs a real control.",
    termAr: "جافاسكربت",
    termEn: "JavaScript",
    wrongAr: [
      "أبقِ الـ span وأضف ظلًا",
      "ضع الملف في تنبيه فقط",
      "عطّل لوحة المفاتيح في تلك الصفحة",
    ],
    wrongEn: [
      "Keep the span and add a shadow",
      "Put the file in an alert only",
      "Disable the keyboard on that page",
    ],
  },
];

export const CHAPTER_3_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "3-1-a01",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "حلّل مسار ضغط «حفظ الحضور»: ماذا تفعل طبقة العرض، وماذا تقرر طبقة التطبيق، وأين تُحفظ النتيجة؟",
    promptEn: "Analyse the Save attendance tap: what does the presentation layer do, what does the application layer decide, and where is the result stored?",
    guideAr: "المتصفح يعرض ويجمع الطلب. الخادم يفحص الصلاحية. قاعدة البيانات تحفظ السجل. لا تخلط السلطة بالشكل.",
    guideEn: "The browser displays and collects the request. The server checks the right. The database stores the record. Do not mix authority with look.",
  },
  {
    id: "3-1-a02",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "قارن مسؤولية الواجهة الأمامية بمسؤولية الخادم حين يعرض طالب درجة ثم يحاول تغيير الرقم في المتصفح.",
    promptEn: "Compare frontend and backend jobs when a student sees a mark and then tries to change the number in the browser.",
    guideAr: "الواجهة تعرض. الخادم يقرر الرقم الحقيقي ويحفظه. الرقم المعدَّل على الشاشة ليس سجلًا.",
    guideEn: "The frontend displays. The backend decides the real mark and stores it. An edited screen is not the record.",
  },
  {
    id: "3-1-a03",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "انتقد وضع مفتاح واجهة برمجة أو كلمة مرور داخل جافاسكربت صفحة التسجيل.",
    promptEn: "Critique putting an API key or a password inside the registration page JavaScript.",
    guideAr: "المتصفح مكشوف. أي زائر يقرأ المصدر. الأسرار تعيش على الخادم بعيدًا عن الواجهة.",
    guideEn: "The browser is public. Any visitor can read the source. Secrets live on the server, away from the frontend.",
  },
  {
    id: "3-1-a04",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "اشرح لماذا نقول: المتصفح يطلب، والخادم يقرر ويحفظ، في حجز حصة المعمل.",
    promptEn: "Explain why we say the browser asks and the server decides and stores, in a lab-period booking.",
    guideAr: "العميل يرسل الرغبة. الخادم يطبق القاعدة ويكتب في طبقة البيانات. الصفحة وحدها لا تملك المقعد.",
    guideEn: "The client sends the wish. The server applies the rule and writes the data layer. The page alone does not own the seat.",
  },
  {
    id: "3-1-a05",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "قارن طبقات العرض والتطبيق والبيانات عندما يتسابق طالبان على آخر مقعد تسجيل.",
    promptEn: "Compare the presentation, application, and data layers when two students race for the last registration seat.",
    guideAr: "العرض يظهر العدد. التطبيق يحسم التسابق. البيانات تبقي المقعد بعد إغلاق التبويب.",
    guideEn: "Presentation shows the count. Application settles the race. Data keeps the seat after the tab closes.",
  },
  {
    id: "3-1-a06",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "حلّل لماذا لا تكفي بطاقة لوحة التحكم «12 غيابات» إن كان المخزون 15.",
    promptEn: "Analyse why a dashboard card that says 12 absences is not enough if the stored count is 15.",
    guideAr: "البطاقة طبقة عرض قديمة. الحقيقة في طبقة البيانات. حدّث العرض من الخادم لا العكس.",
    guideEn: "The card is a stale presentation layer. Truth lives in the data layer. Refresh the view from the server, not the other way around.",
  },
  {
    id: "3-1-a07",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "انتقد حفظ درجات منتصف الترم في التبويب أو في لقطة شاشة بدل قاعدة البيانات.",
    promptEn: "Critique keeping midterm marks in an open tab or a screenshot instead of a database.",
    guideAr: "التبويب ذاكرة مؤقتة. اللقطة ليست سجلًا منظمًا. طبقة البيانات تبقي الدرجات للترم التالي.",
    guideEn: "A tab is temporary memory. A screenshot is not structured storage. The data layer keeps marks for next term.",
  },
  {
    id: "3-1-a08",
    lessonId: "3-1",
    chapterId: "3",
    promptAr: "اشرح لماذا يسهّل فصل الواجهة عن الخادم عمل فريقي شاشة الدرجات وخدمة العلامات معًا.",
    promptEn: "Explain why splitting frontend from backend helps the grades-screen team and the marks-service team work together.",
    guideAr: "حد واضح: فريق يرى HTML وCSS وجافاسكربت، وفريق يملك المنطق والقاعدة. يتغيّر الشكل من غير كسر الحفظ.",
    guideEn: "A clear edge: one team owns HTML, CSS, and JavaScript; the other owns logic and the database. Look can change without breaking the save.",
  },
  {
    id: "3-2-a01",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "قارن HTTP وHTTPS حين يفتح طالب درجاته على شبكة مقهى ويهمّ بكتابة كلمة المرور.",
    promptEn: "Compare HTTP and HTTPS when a student opens grades on cafe Wi-Fi and is about to type a password.",
    guideAr: "HTTP قناة واضحة. HTTPS هو HTTP فوق TLS. ارفض السر إن غاب القفل أو ظهرت شهادة تحذير.",
    guideEn: "HTTP is a clear channel. HTTPS is HTTP over TLS. Refuse the secret if the padlock is missing or a certificate warning appears.",
  },
  {
    id: "3-2-a02",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "حلّل أي طريقة تختار لقراءة كشف حضور، وإنشاء حجز معمل، وتحديث رقم ولي الأمر، وإلغاء الساعة.",
    promptEn: "Analyse which method you choose to read an attendance list, create a lab booking, update a parent phone, and cancel the hour.",
    guideAr: "GET للقراءة. POST للإنشاء. PATCH للحقل الواحد. DELETE للحذف بعد إذن الخادم.",
    guideEn: "GET to read. POST to create. PATCH for one field. DELETE to remove after the server allows it.",
  },
  {
    id: "3-2-a03",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "اشرح لماذا يفرّق رمز 404 عن رمز 500 عندما تفشل قائمة المعمل على هاتفين.",
    promptEn: "Explain why status 404 is not status 500 when the lab list fails on two phones.",
    guideAr: "404 مورد غير موجود على العنوان. 500 الخادم فشل في المعالجة. 200 نجاح. الرمز جزء من العقد.",
    guideEn: "404 is a missing resource at that address. 500 is a server failure. 200 is success. The code is part of the contract.",
  },
  {
    id: "3-2-a04",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "انتقد تطبيق هاتف يرسل mark بينما خادم الدرجات ينتظر score، من غير عقد مكتوب.",
    promptEn: "Critique a phone app that sends mark while the grades server expects score, with no written contract.",
    guideAr: "واجهة البرمجة اتفاق. REST وJSON يحتاجان أسماء وأشكالًا مشتركة. التخمين يكسر التفاهم.",
    guideEn: "An API is a contract. REST and JSON need shared names and shapes. Guessing breaks understanding.",
  },
  {
    id: "3-2-a05",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "قارن PUT وPATCH عندما تنقل شؤون الطلاب صف طالب ثم عندما يتغيّر رقم الهاتف وحده.",
    promptEn: "Compare PUT and PATCH when the registrar moves a student's class, then when only the phone number changes.",
    guideAr: "PUT بديل كامل للمورد. PATCH جزء منه. لا تحذف الطالب لتغيير رقم.",
    guideEn: "PUT replaces the whole resource. PATCH changes a part. Do not delete the student to change a digit.",
  },
  {
    id: "3-2-a06",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "حلّل دور الكوكي والجلسة بعد دخول المعلم من الحضور إلى الدرجات على جهاز المعمل.",
    promptEn: "Analyse the job of the cookie and the session after a teacher logs in and moves from attendance to grades on a lab PC.",
    guideAr: "الجلسة تحمل حالة الدخول عبر الطلبات. يجب أن تنتهي على الجهاز المشترك. الكوكي على HTTP الواضح خطر.",
    guideEn: "The session carries login state across requests. It should expire on a shared machine. A cookie on clear HTTP is a risk.",
  },
  {
    id: "3-2-a07",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "اشرح لماذا نحتاج عقدًا واضحًا إن أرسلت الواجهة 16/09/2026 بينما الخادم ينتظر 2026-09-16.",
    promptEn: "Explain why a clear contract is needed if the frontend sends 16/09/2026 while the server expects 2026-09-16.",
    guideAr: "الطلب والرد لغة واحدة. بلا اتفاق على الشكل لا يفهم التطبيقان بعضهما ولو كان JSON صحيح الشكل ظاهريًا.",
    guideEn: "Request and response share one language. Without an agreed shape the two apps do not understand each other, even if the JSON looks neat.",
  },
  {
    id: "3-2-a08",
    lessonId: "3-2",
    chapterId: "3",
    promptAr: "انتقد حفظ الحضور عبر GET يخفي التعديل في عنوان، وإخفاء زر الحذف بوصفه حماية.",
    promptEn: "Critique saving attendance with a GET that hides a write in the URL, and hiding a delete button as security.",
    guideAr: "GET للقراءة لا للإنشاء. DELETE يحتاج قرار خادم لا زرًا مخفيًا. الطريقة بلا عقد وصلاحية لا تكفي.",
    guideEn: "GET reads; it does not create. DELETE needs a server decision, not a hidden button. A method without a contract and a right is not enough.",
  },
  {
    id: "3-3-a01",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "انتقد صفحة درجات مبنية كلها من مربعات div بخط عريض من غير عناوين أو جداول حقيقية.",
    promptEn: "Critique a grades page built only from bold divs with no real headings or tables.",
    guideAr: "HTML معنى وهيكل: عنوان، جدول، قائمة. الشكل وحده لا يكفي للإنسان ولا لقارئ الشاشة.",
    guideEn: "HTML is meaning and structure: heading, table, list. Look alone is not enough for a human or a screen reader.",
  },
  {
    id: "3-3-a02",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "قارن أدوار HTML وCSS وجافاسكربت في صفحة حضور: الهيكل، المظهر، السلوك بعد التحميل.",
    promptEn: "Compare the jobs of HTML, CSS, and JavaScript on an attendance page: structure, look, and behaviour after load.",
    guideAr: "HTML المعنى. CSS اللون والشبكة والتجاوب. جافاسكربت التفاعل. لا تضع قرار الحضور في اللون أو في سكربت يغني عن الخادم.",
    guideEn: "HTML is meaning. CSS is colour, layout, and responsiveness. JavaScript is interaction. Do not put attendance truth in a colour or in a script that replaces the server.",
  },
  {
    id: "3-3-a03",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "اشرح لماذا يجب اختبار تسجيل الشعبة من غير فأرة قبل العرض على المدير.",
    promptEn: "Explain why registration for a section must be tested without a mouse before the principal demo.",
    guideAr: "إتاحة الوصول تشمل لوحة المفاتيح. إن احتاج المسار مؤشرًا فقد فشل الاختبار البسيط.",
    guideEn: "Accessibility includes the keyboard. If the path needs a pointer, the simple test has failed.",
  },
  {
    id: "3-3-a04",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "حلّل ما يسمعه قارئ الشاشة في جدول درجات بلا رؤوس، وفي حجز معمل يعتمد على نص مؤقت فقط.",
    promptEn: "Analyse what a screen reader hears on a marks table with no headers, and on a lab booking that uses only placeholder text.",
    guideAr: "بلا رأس تُقرأ أرقام يتيمة. بلا تسمية يختفي الاسم. اربط label واستخدم th.",
    guideEn: "With no header the reader hears orphan numbers. With no label the name vanishes. Bind a label and use table headers.",
  },
  {
    id: "3-3-a05",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "قارن تصميم الهاتف أولًا بتصميم سطح المكتب فقط حين يفيض جدول الحضور عن الشاشة الضيقة.",
    promptEn: "Compare phone-first design with desktop-only design when the attendance table overflows a narrow screen.",
    guideAr: "ابدأ باللمس الكبير والنص المقروء ثم وسّع. القرص بالإصبعين ليس بديلًا عن تخطيط متجاوب.",
    guideEn: "Start with large taps and readable type, then expand. Pinch-zoom is not a substitute for a responsive layout.",
  },
  {
    id: "3-3-a06",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "انتقد كشف حضور يميّز المتأخر بنقطة حمراء والحاضر بنقطة خضراء من غير كلمة.",
    promptEn: "Critique an attendance sheet that marks late with a red dot and present with a green dot and no word.",
    guideAr: "اللون وحده يفشل إتاحة الوصول. أضف نصًا. ارفع التباين. لا تجعل الحالة زينة.",
    guideEn: "Colour alone fails accessibility. Add text. Raise contrast. Do not treat status as decoration.",
  },
  {
    id: "3-3-a07",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "اشرح لماذا لا يكفي div أو صورة PNG مكان زر حفظ الحضور.",
    promptEn: "Explain why a div or a PNG picture is not enough in place of a Save attendance button.",
    guideAr: "العنصر الحقيقي يحمل المعنى ويمكن تركيزه. الصورة أو المربع يخفيان الفعل عن لوحة المفاتيح وقارئ الشاشة.",
    guideEn: "A real element carries meaning and can receive focus. A picture or a box hides the action from the keyboard and the screen reader.",
  },
  {
    id: "3-3-a08",
    lessonId: "3-3",
    chapterId: "3",
    promptAr: "حلّل قائمة أدوات معمل تظهر عند مرور الفأرة فقط، وقائمة درجات تُحقن بعد السكربت فقط.",
    promptEn: "Analyse a lab-tools menu that appears only on hover, and a grades menu injected only after a script.",
    guideAr: "المرور وحده يغلق الهاتف ولوحة المفاتيح. الهيكل يجب أن يوجد في HTML قبل السلوك. اختبر من غير فأرة.",
    guideEn: "Hover alone locks out phones and keyboards. Structure should exist in HTML before behaviour. Test without a mouse.",
  },
];
