import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_6_FACTS: BankFact[] = [
  {
    id: "6-1-f01",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "اختبار قصير: درجة واحدة 98 وباقي الصف بين 11 و14.",
    sceneEn: "A short quiz: one mark is 98 and the rest sit between 11 and 14.",
    claimAr: "انظر الوسيط أيضًا لأن المتوسط ارتفع بسبب القيمة الشاذة.",
    claimEn: "Look at the median too; the mean jumped because of the outlier.",
    whyAr: "المتوسط ينجذب للشاذ؛ الوسيط يصف مركز الصف أوضح.",
    whyEn: "The mean is pulled by the outlier; the median shows the class centre more clearly.",
    termAr: "إحصاء وصفي",
    termEn: "Descriptive stats",
    wrongAr: ["أعْلِن المتوسط وحده كحقيقة الصف", "احذف الإحصاء كله", "اعتبر 98 متوسط الصف"],
    wrongEn: ["Announce the mean alone as the class truth", "Delete all statistics", "Treat 98 as the class average"],
  },
  {
    id: "6-1-f02",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "مجلس الطلاب يعلن متوسط ثمن العصير في المدرسة كلها من 8 مشترين في فسحة واحدة.",
    sceneEn: "The student council announces the whole school's juice price from eight buyers in one break.",
    claimAr: "عمّم بحذر واذكر أن العينة صغيرة وقد لا تمثل كل المشترين.",
    claimEn: "Generalise cautiously and say the sample is small and may not represent all buyers.",
    whyAr: "الاستدلال تعميم من العينة إلى المجتمع مع مقدار عدم يقين.",
    whyEn: "Inference is a cautious leap from sample to population, with uncertainty.",
    termAr: "استدلال",
    termEn: "Inference",
    wrongAr: ["انسخ الرقم كحقيقة مدرسية قاطعة", "اعتبر الثمانية هم المجتمع كله", "ارفض أي رقم لأن العينة ليست ألفًا"],
    wrongEn: ["Copy the number as a final school fact", "Treat the eight as the whole population", "Reject any number unless the sample is a thousand"],
  },
  {
    id: "6-1-f03",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "مدرب الصباح يقول إن الجري قبل الحصة سيقلل غياب الظهيرة، من غير دفتر حضور.",
    sceneEn: "The morning coach says a pre-class run will cut afternoon absences, with no attendance book.",
    claimAr: "اكتب فرضية واختبرها بأرقام الحضور لا بالشعور.",
    claimEn: "Write a hypothesis and test it with attendance numbers, not with feeling.",
    whyAr: "الفرضية ادعاء نختبره بالبيانات لا بالإحساس.",
    whyEn: "A hypothesis is a claim we test with data, not with a hunch.",
    termAr: "فرضية",
    termEn: "Hypothesis",
    wrongAr: ["أعلن النتيجة لأن المدرب واثق", "أثبت الادعاء بتصفيق الصف", "اكتفِ بإحساس المدرب"],
    wrongEn: ["Announce the result because the coach is sure", "Prove the claim with class applause", "Stop at the coach's feeling"],
  },
  {
    id: "6-1-f04",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "نادي الطقس يملك 5 قراءات مطر على السطح ويطبع «معدل السنة 12 مم قطعًا».",
    sceneEn: "The weather club has five roof rain readings and prints “yearly rainfall is exactly 12 mm”.",
    claimAr: "اعرض فترة ثقة واسعة ولا تصرخ برقم قاطع.",
    claimEn: "Show a wide confidence interval and do not shout a single final number.",
    whyAr: "العينة الصغيرة توسّع فترة الثقة وتمنع الجزم.",
    whyEn: "A small sample widens the interval and blocks a blunt claim.",
    termAr: "فترة ثقة",
    termEn: "Confidence interval",
    wrongAr: ["احذف ذكر عدم اليقين", "ضيّق الفترة يدويًا لتبدو علمية", "أعلن الرقم من غير عينة"],
    wrongEn: ["Drop any mention of uncertainty", "Narrow the interval by hand so it looks scientific", "Announce the number with no sample"],
  },
  {
    id: "6-1-f05",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "أسبوع الكانتين: يوم المهرجان باع 900 ساندويتش وباقي الأيام بين 40 و55.",
    sceneEn: "Canteen week: festival day sold 900 sandwiches and the other days sat between 40 and 55.",
    claimAr: "لخّص الأسبوع بالمتوسط والوسيط معًا حتى لا يخدع يوم المهرجان.",
    claimEn: "Summarise the week with both mean and median so festival day does not fool you.",
    whyAr: "الإحصاء الوصفي يكشف أثر الشاذ حين يلخّص العينة بأكثر من رقم.",
    whyEn: "Descriptive stats reveal an outlier’s pull when the sample is summarised with more than one number.",
    termAr: "إحصاء وصفي",
    termEn: "Descriptive stats",
    wrongAr: ["اكتفِ بالمتوسط لأنه أسهل", "اذكر أكبر رقم فقط", "تجاهل يوم المهرجان من غير إشارة"],
    wrongEn: ["Use the mean alone because it is easier", "Report only the largest number", "Ignore festival day with no note"],
  },
  {
    id: "6-1-f06",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "استطلاع في مجموعة المتفوقين (12 طالبًا) يُعمَّم على رأي المدرسة كلها في طول الواجب.",
    sceneEn: "A poll in the honor-roll chat (12 students) is generalised as the whole school’s view of homework length.",
    claimAr: "لا تعمم على المدرسة؛ العينة لا تشبه مجتمع الطلاب.",
    claimEn: "Do not generalise to the school; the sample does not look like the student population.",
    whyAr: "الاستدلال الصادق يحتاج عينة تمثل من نتكلم عنهم.",
    whyEn: "Honest inference needs a sample that resembles the people we speak about.",
    termAr: "استدلال",
    termEn: "Inference",
    wrongAr: ["عمّم فورًا لأن الرقم أنيق", "زد الأسئلة داخل المجموعة نفسها فقط", "اعتبر صمت الباقين موافقة"],
    wrongEn: ["Generalise at once because the number looks neat", "Only add more questions inside the same chat", "Treat everyone else’s silence as agreement"],
  },
  {
    id: "6-1-f07",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "أمينة المكتبة تشعر أن الجالسين قرب النافذة يقرأون صفحات أكثر.",
    sceneEn: "The librarian feels that students by the window read more pages.",
    claimAr: "حوّل الشعور إلى فرضية وقِس الاستعارات أو الصفحات قبل أي إعلان.",
    claimEn: "Turn the feeling into a hypothesis and measure loans or pages before any announcement.",
    whyAr: "الفرضية تنتظر اختبارًا رقميًا لا انطباعًا في الردهة.",
    whyEn: "A hypothesis waits for a numerical test, not a hallway impression.",
    termAr: "فرضية",
    termEn: "Hypothesis",
    wrongAr: ["أعلن القاعدة في الإذاعة الصباحية", "اعتمد على حديث طالبين", "اعتبر النافذة سببًا مؤكدًا"],
    wrongEn: ["Announce the rule in the morning broadcast", "Rely on a chat with two students", "Treat the window as a proven cause"],
  },
  {
    id: "6-1-f08",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "ستة مشاريع في معرض العلوم قيست أزمانها ثم نُشرت فترة ضيقة كأنها من 200 مشروع.",
    sceneEn: "Six science-fair projects were timed, then a tight interval was published as if n were 200.",
    claimAr: "اترك الفترة واسعة وصرّح بحجم العينة.",
    claimEn: "Leave the interval wide and state the sample size.",
    whyAr: "صغر العينة يمنع فترة ضيقة صادقة.",
    whyEn: "A tiny sample cannot honestly support a narrow interval.",
    termAr: "فترة ثقة",
    termEn: "Confidence interval",
    wrongAr: ["قلّد فترة دراسة كبيرة", "أخفِ عدد المشاريع", "أعلن يقينًا تامًا"],
    wrongEn: ["Copy the interval from a large study", "Hide the project count", "Announce total certainty"],
  },
  {
    id: "6-1-f09",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "أزمنة جري الحصة: طالب مصاب أنهى في 18 دقيقة والباقون بين 7 و8.",
    sceneEn: "PE lap times: an injured student finished in 18 minutes and the rest sat between 7 and 8.",
    claimAr: "انشر الوسيط مع المتوسط حتى لا يسحب المصاب مركز الصف.",
    claimEn: "Publish the median with the mean so the injured time does not drag the class centre.",
    whyAr: "الشاذ يحرّك المتوسط أكثر مما يحرّك الوسيط.",
    whyEn: "An outlier moves the mean more than it moves the median.",
    termAr: "إحصاء وصفي",
    termEn: "Descriptive stats",
    wrongAr: ["المتوسط وحده يكفي دائمًا", "احذف زمن المصاب سرًا", "أعلن أن الصف كله بطيء"],
    wrongEn: ["The mean alone is always enough", "Quietly delete the injured time", "Announce that the whole class is slow"],
  },
  {
    id: "6-1-f10",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "غياب يوم الاثنين فقط يُستخدم لاستنتاج نسبة الغياب في الترم كله.",
    sceneEn: "Monday absences alone are used to infer the absence rate for the whole term.",
    claimAr: "لا تستدل على الترم من يوم واحد؛ وسّع العينة أو حدّد الادعاء.",
    claimEn: "Do not infer the term from one day; widen the sample or narrow the claim.",
    whyAr: "الاستدلال يتجاوز العينة فقط إن شابهت المجتمع في الزمن والفئة.",
    whyEn: "Inference may leave the sample only if that sample matches the population in time and group.",
    termAr: "استدلال",
    termEn: "Inference",
    wrongAr: ["عمّم على الترم بلا تحفظ", "اعتبر الاثنين متوسط كل الأيام", "ارفض أي إحصاء عن الغياب"],
    wrongEn: ["Generalise to the term with no caution", "Treat Monday as the mean of every day", "Reject any statistic about absence"],
  },
  {
    id: "6-1-f11",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "بعد عاصفة ترابية واحدة انخفض الحضور، فيريد المعلم إعلان أن العواصف تسبب الغياب دائمًا.",
    sceneEn: "After one dust storm, attendance fell, and the teacher wants to announce that storms always cause absence.",
    claimAr: "صغ فرضية واختبرها في عواصف لاحقة مع أيام مقارنة.",
    claimEn: "State a hypothesis and test it on later storms with comparison days.",
    whyAr: "حدث واحد لا يختبر ادعاءً عن قاعدة عامة.",
    whyEn: "A single event does not test a claim about a general rule.",
    termAr: "فرضية",
    termEn: "Hypothesis",
    wrongAr: ["أعلن السببية في نفس اليوم", "اكتفِ بشعور المعلم بعد العاصفة", "احذف يوم العاصفة من السجل"],
    wrongEn: ["Announce cause on the same day", "Stop at the teacher’s feeling after the storm", "Delete the storm day from the log"],
  },
  {
    id: "6-1-f12",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "شعبة من 40 طالبًا وشعبة من 5 يُعلن متوسط مصروف الكانتين فيهما كأن الفترتين متساويتان في الدقة.",
    sceneEn: "A class of 40 and a class of 5 report mean canteen spend as if both intervals were equally sharp.",
    claimAr: "اعتبر فترة الخمسة أوسع ولا تساوِ الدقتين.",
    claimEn: "Treat the n=5 interval as wider and do not equate the two precisions.",
    whyAr: "العينة الأصغر تعطي عادة فترة ثقة أوسع.",
    whyEn: "The smaller sample usually gives a wider confidence interval.",
    termAr: "فترة ثقة",
    termEn: "Confidence interval",
    wrongAr: ["ضيّق فترة الخمسة يدويًا", "أعلن الرقمين بنفس اليقين", "احذف شعبة الخمسة لأنها مزعجة"],
    wrongEn: ["Narrow the n=5 interval by hand", "Announce both numbers with the same certainty", "Drop the class of five because it is awkward"],
  },
  {
    id: "6-1-f13",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "قراءات المطر هذا الشهر اختُصرت بمتوسط أنيق من غير وسيط ولا مدى.",
    sceneEn: "This month’s rain readings were reduced to a neat mean with no median and no spread.",
    claimAr: "أضف الوسيط ومدى الانتشار لا المتوسط وحده.",
    claimEn: "Add the median and the spread; do not leave the mean alone.",
    whyAr: "الملخص الوصفي الكامل يظهر المركز والانتشار معًا.",
    whyEn: "A full descriptive summary shows both centre and spread.",
    termAr: "إحصاء وصفي",
    termEn: "Descriptive stats",
    wrongAr: ["المتوسط يكفي لأي طقس", "ارسم دائرة من غير أرقام", "اخفِ الأيام الجافة"],
    wrongEn: ["The mean is enough for any weather", "Draw a pie with no numbers", "Hide the dry days"],
  },
  {
    id: "6-1-f14",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "طالب محوّل حصل 20 من 20 في تدريب كان متوسط الصف فيه 9، فيُعلن أن مستوى المدرسة صار امتيازًا.",
    sceneEn: "A transfer student scored 20/20 on a practice the class averaged 9, so the school is declared “excellent”.",
    claimAr: "لا تعمم من فرد واحد إلى مجتمع المدرسة.",
    claimEn: "Do not generalise from one person to the school population.",
    whyAr: "الاستدلال يحتاج عينة لا حالة واحدة لامعة.",
    whyEn: "Inference needs a sample, not one shiny case.",
    termAr: "استدلال",
    termEn: "Inference",
    wrongAr: ["أعلن امتياز المدرسة فورًا", "احذف درجته لأنها تربك المتوسط", "استبدل متوسط الصف بدرجته من غير شرح"],
    wrongEn: ["Announce school excellence at once", "Delete the mark because it spoils the mean", "Replace the class mean with that mark and give no note"],
  },
  {
    id: "6-1-f15",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "مبيعات الآيس كريم في الكانتين وأعذار حصة الرياضة ترتفع معًا في حرّ مايو.",
    sceneEn: "Canteen ice-cream sales and PE excuses both rise in the May heat.",
    claimAr: "سجّل ارتباطًا ولا تقبل فرضية أن الآيس كريم يسبب الأعذار؛ الحر عامل ثالث.",
    claimEn: "Record a correlation; do not accept the hypothesis that ice cream causes excuses — heat is a third factor.",
    whyAr: "التزامن يحرّك رقمين معًا ولا يختبر سببًا.",
    whyEn: "Moving together is not a test of cause.",
    termAr: "فرضية",
    termEn: "Hypothesis",
    wrongAr: ["أعلن أن الآيس كريم يمرض الطلاب", "احذف مبيعات مايو", "اعتبر الارتباط برهانًا كافيًا"],
    wrongEn: ["Announce that ice cream makes students ill", "Delete May sales", "Treat the correlation as enough proof"],
  },
  {
    id: "6-1-f16",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "سبع درجات في مسابقة الخطابة تُعرض رقمًا واحدًا من غير مدى عدم يقين.",
    sceneEn: "Seven debate scores are shown as one number with no range of uncertainty.",
    claimAr: "ارفق التقدير بفترة ثقة واذكر صغر العينة.",
    claimEn: "Attach a confidence interval to the estimate and state that the sample is small.",
    whyAr: "الفترة تقول إلى أي حد يجوز التعميم، لا «احفظ الرقم».",
    whyEn: "The interval asks how far we may generalise — it does not say “memorise the number”.",
    termAr: "فترة ثقة",
    termEn: "Confidence interval",
    wrongAr: ["اطبع الرقم وحده بخط عريض", "اخترع فترة ضيقة لتبدو واثقًا", "ارفض ذكر n"],
    wrongEn: ["Print the lone number in bold", "Invent a narrow interval to look confident", "Refuse to mention n"],
  },
  {
    id: "6-1-f17",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "أسبوع إنفلونزا رفع الغياب كثيرًا، والتقرير يذكر متوسط الشهر كأنه أسبوع عادي.",
    sceneEn: "A flu week spiked absences, and the monthly report quotes the mean as if it were an ordinary week.",
    claimAr: "اذكر الوسيط وعلّم الأسبوع الشاذ في الملخص.",
    claimEn: "State the median and flag the unusual week in the summary.",
    whyAr: "الملخص الوصفي يخون القارئ إن أخفى أسبوعًا شاذًا.",
    whyEn: "A descriptive summary betrays the reader if it hides an unusual week.",
    termAr: "إحصاء وصفي",
    termEn: "Descriptive stats",
    wrongAr: ["اترك المتوسط وحده ليبدو هادئًا", "احذف أسبوع الإنفلونزا من غير ذكر", "أعلن أن الشهر بلا غياب"],
    wrongEn: ["Leave the mean alone so the month looks calm", "Drop the flu week with no note", "Announce a month with no absences"],
  },
  {
    id: "6-1-f18",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "دقائق تسجيل الدخول إلى تطبيق المراجعة ترتبط بدرجات الإنجليزية في الصف.",
    sceneEn: "Minutes logged in the revision app correlate with English marks in the class.",
    claimAr: "صف الارتباط واطلب دليلًا آخر قبل قول إن التطبيق يرفع الدرجة.",
    claimEn: "Describe the link and ask for more evidence before saying the app raises the mark.",
    whyAr: "من يستخدم التطبيق قد يكون أصلًا أكثر التزامًا؛ الارتباط ليس سببية.",
    whyEn: "App users may already be more committed; correlation is not causation.",
    termAr: "استدلال",
    termEn: "Inference",
    wrongAr: ["أعلن أن الدقائق تسبب الدرجة قطعًا", "احذف من لم يحمّل التطبيق", "اعتبر العينة بلا فائدة"],
    wrongEn: ["Announce that minutes certainly cause the mark", "Drop anyone who did not install the app", "Treat the sample as useless"],
  },
  {
    id: "6-1-f19",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "في أسبوع واحد تأخرت الحافلات وانخفضت درجات الرياضيات، فيُقال إن التأخير سبب الرسوب.",
    sceneEn: "In one week buses ran late and maths marks fell, so lateness is called the cause of failure.",
    claimAr: "ارفض فرضية السببية من أسبوع واحد من غير مقارنة.",
    claimEn: "Reject the causal hypothesis based on one week with no comparison.",
    whyAr: "تزامن أسبوع لا يختبر ادعاء السبب.",
    whyEn: "One week of coincidence does not test a cause claim.",
    termAr: "فرضية",
    termEn: "Hypothesis",
    wrongAr: ["أعلن السببية في اجتماع أولياء الأمور", "أثبت الفرضية لأن القصتين حدثتا معًا", "ألغِ اختبار الرياضيات"],
    wrongEn: ["Announce cause at the parents’ meeting", "Prove the hypothesis because the two stories happened together", "Cancel the maths test"],
  },
  {
    id: "6-1-f20",
    lessonId: "6-1",
    chapterId: "6",
    sceneAr: "صف واحد في 1ب سُئل عن رضا الكانتين ثم طُبع رقم واحد بلا مدى كأنه رأي المدرسة.",
    sceneEn: "One row in class 1B was asked about canteen satisfaction, then one number was printed as the school’s view.",
    claimAr: "اعرض فترة واسعة أو حدّد أن الرقم يخص الصف لا المدرسة.",
    claimEn: "Show a wide interval or state that the number belongs to that class, not the school.",
    whyAr: "عينة صف واحد تجزم أقل مما يوحي رقم وحيد.",
    whyEn: "A one-class sample supports less certainty than a lone printed number suggests.",
    termAr: "فترة ثقة",
    termEn: "Confidence interval",
    wrongAr: ["اطبع الرقم على الملصق العام", "اعتبر الصف مجتمع المدرسة", "اختر فترة صفر العرض لتبدو دقيقة"],
    wrongEn: ["Print the number on the public poster", "Treat the class as the school population", "Choose a zero-width interval so it looks precise"],
  },
  {
    id: "6-2-f01",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "ساعات المذاكرة ودرجة الاختبار القصير ترسمان اتجاهًا صاعدًا تقريبيًا.",
    sceneEn: "Study hours and the short-quiz mark show an approximate upward trend.",
    claimAr: "جرّب خط انحدار لوصف الاتجاه ولا تعلنه سببًا.",
    claimEn: "Try a regression line to describe the trend; do not announce it as a cause.",
    whyAr: "الانحدار الخطي يصف علاقة تقريبية بين متغيرين كميين.",
    whyEn: "Linear regression roughly describes a link between two quantitative variables.",
    termAr: "انحدار خطي",
    termEn: "Linear regression",
    wrongAr: ["ارفض أي خط لأن الوصف ممنوع", "أعلن أن الساعات تسبب الدرجة", "استبدل النقاط بدائرة"],
    wrongEn: ["Reject any line because description is forbidden", "Announce that hours cause the mark", "Replace the points with a pie"],
  },
  {
    id: "6-2-f02",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "أنواع وجبات الكانتين مقابل حرارة الظهيرة تظهر سحابة نقاط بلا شكل.",
    sceneEn: "Canteen snack types versus afternoon heat appear as a shapeless cloud of points.",
    claimAr: "ارفض الخط المستقيم؛ البواقي ستكون كبيرة بلا اتجاه.",
    claimEn: "Reject a straight line; residuals would be large and trendless.",
    whyAr: "إن كبرت البواقي فالخط ضعيف ولا يمسك السحابة.",
    whyEn: "Large residuals mean the line is weak and does not hold the cloud.",
    termAr: "بواقي",
    termEn: "Residuals",
    wrongAr: ["افرض خطًا لأن التقرير يطلب رسمًا", "تجاهل تشتت النقاط", "اعتبر السحابة ملاءمة ممتازة"],
    wrongEn: ["Force a line because the report wants a drawing", "Ignore how scattered the points are", "Call the cloud an excellent fit"],
  },
  {
    id: "6-2-f03",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "بيانات المذاكرة بين ساعة واحدة و8 ساعات، والتقرير يتنبأ بدرجة من يذاكر 40 ساعة.",
    sceneEn: "Study data run from 1 to 8 hours, and the report predicts the mark of someone who studies 40 hours.",
    claimAr: "ارفض التنبؤ؛ هذا استكمال خارج مدى البيانات.",
    claimEn: "Refuse the prediction; that is extrapolation beyond the data range.",
    whyAr: "الاستكمال يمد الخط حيث لا نقاط تسنده.",
    whyEn: "Extrapolation stretches the line where no points support it.",
    termAr: "الاستكمال الخارجي",
    termEn: "Extrapolation",
    wrongAr: ["أعلن الدرجة المتوقعة بثقة", "عدّ الاستكمال آمنًا دائمًا", "اخفِ أن الأربعين خارج المدى"],
    wrongEn: ["Announce the predicted mark with confidence", "Treat extrapolation as always safe", "Hide that 40 hours sits outside the range"],
  },
  {
    id: "6-2-f04",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "حرارة الظهيرة تُستخدم لتوقع عدد أكواب العصير في الكانتين.",
    sceneEn: "Afternoon temperature is used to predict how many juice cups the canteen sells.",
    claimAr: "اعتبر الحرارة متغيرًا تفسيريًا منطقيًا ثم افحص البواقي.",
    claimEn: "Treat temperature as a sensible explanatory variable, then check the residuals.",
    whyAr: "المتغير التفسيري يُختار لأنه قد يشرح أو يتوقع الآخر بعقل.",
    whyEn: "An explanatory variable is chosen because it may reasonably explain or predict the other.",
    termAr: "متغير تفسيري",
    termEn: "Explanatory variable",
    wrongAr: ["اختر متغيرًا عشوائيًا من الجدول", "أعلن السببية من غير فحص", "استبدل الحرارة بلون الكوب"],
    wrongEn: ["Pick a random column from the table", "Announce cause with no check", "Replace temperature with cup colour"],
  },
  {
    id: "6-2-f05",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "زيارات المكتبة الأسبوعية ودرجة القراءة ترسمان ميلًا تقريبيًا.",
    sceneEn: "Weekly library visits and the reading mark show an approximate slope.",
    claimAr: "استخدم الانحدار إن وُجد اتجاه، مع التذكير أنه وصف لا برهان.",
    claimEn: "Use regression if a trend exists, and remind readers it is a description, not proof.",
    whyAr: "الخط أداة وصف حين تتوقع اتجاهًا، لا حين تريد سببًا جاهزًا.",
    whyEn: "The line is a description when you expect a trend, not a ready-made cause.",
    termAr: "انحدار خطي",
    termEn: "Linear regression",
    wrongAr: ["ارفض الخط رغم وضوح الميل", "أعلن أن الزيارة تسبب الدرجة", "ارسم سحابة من غير سؤال"],
    wrongEn: ["Reject the line even though the slope is clear", "Announce that visits cause the mark", "Draw a cloud and ask no question"],
  },
  {
    id: "6-2-f06",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "طالب بلا ساعة مذاكرة حصل 100، وباقي نقاط الصف قريبة من الخط.",
    sceneEn: "A student with zero study hours scored 100, while the other class points hug the line.",
    claimAr: "علّم الباقي الضخم وافحص إن كان الخط ما زال مفيدًا.",
    claimEn: "Flag the huge residual and check whether the line is still useful.",
    whyAr: "الباقي الكبير يكشف نقطة لا يفسرها الخط.",
    whyEn: "A large residual marks a point the line does not explain.",
    termAr: "بواقي",
    termEn: "Residuals",
    wrongAr: ["تجاهل الـ100 لأنها قصة لطيفة", "احذف النقطة سرًا ليبدو الخط مثاليًا", "اعتبر الباقي دليل سببية"],
    wrongEn: ["Ignore the 100 because it is a nice story", "Quietly drop the point so the line looks perfect", "Treat the residual as proof of cause"],
  },
  {
    id: "6-2-f07",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "مبيعات الكانتين من سبتمبر إلى مايو تُمدّ خطًا لتوقع يوليو والإجازة.",
    sceneEn: "Canteen sales from September to May are stretched into a line to forecast July and the holiday.",
    claimAr: "لا تتنبأ خارج شهور الدراسة؛ السياق مختلف.",
    claimEn: "Do not predict outside term months; the setting has changed.",
    whyAr: "الاستكمال خطر حين يتغير الإيقاع لا الرقم فقط.",
    whyEn: "Extrapolation is risky when the rhythm changes, not only the number.",
    termAr: "الاستكمال الخارجي",
    termEn: "Extrapolation",
    wrongAr: ["اطبع توقع يوليو بخط عريض", "عامل الإجازة كشهر دراسي", "أخفِ أن يوليو خارج المدى"],
    wrongEn: ["Print the July forecast in bold", "Treat the holiday as a school month", "Hide that July sits outside the range"],
  },
  {
    id: "6-2-f08",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "مقاس الحذاء يظهر اقترانًا ضعيفًا مع درجة الرياضيات في الصف.",
    sceneEn: "Shoe size shows a weak link with the maths mark in the class.",
    claimAr: "ارفض مقاس الحذاء متغيرًا تفسيريًا؛ العلاقة صدفة أو عمر.",
    claimEn: "Reject shoe size as an explanatory variable; the link is chance or age.",
    whyAr: "المتغير التفسيري يجب أن يكون منطقيًا لا مجرد رقم متزامن.",
    whyEn: "An explanatory variable must make sense, not merely move at the same time.",
    termAr: "متغير تفسيري",
    termEn: "Explanatory variable",
    wrongAr: ["أعلن أن الحذاء يشرح الرياضيات", "ابنِ سياسة دعم على المقاس", "اخفِ ضعف الاقتران"],
    wrongEn: ["Announce that shoes explain maths", "Build a support policy on shoe size", "Hide how weak the link is"],
  },
  {
    id: "6-2-f09",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "زمن الحصة ودرجة سلوك الصف نقاط متناثرة بلا ميل تراه العين.",
    sceneEn: "Lesson length and the class behaviour score are scattered points with no slope the eye can see.",
    claimAr: "لا تفرض خطًا إن كانت النقاط سحابة بلا اتجاه.",
    claimEn: "Do not force a line when the points are a cloud with no trend.",
    whyAr: "الانحدار يناسب اتجاهًا تقريبيًا لا ضجيجًا عشوائيًا.",
    whyEn: "Regression fits an approximate trend, not random noise.",
    termAr: "انحدار خطي",
    termEn: "Linear regression",
    wrongAr: ["ارسم خطًا لأن البرنامج يقدر", "أعلن ملاءمة ممتازة", "استبدل السحابة بعنوان سببي"],
    wrongEn: ["Draw a line because the software can", "Announce an excellent fit", "Replace the cloud with a causal title"],
  },
  {
    id: "6-2-f10",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "كل نقاط الغياب في الأيام الممطرة أعلى من خط المطر المتوقع، وعلى جانب واحد.",
    sceneEn: "Every rainy-day absence point sits above the fitted rain line, all on one side.",
    claimAr: "الخط منحاز؛ راجع النموذج لأن البواقي ليست عشوائية حول الصفر.",
    claimEn: "The line is biased; revisit the model because residuals are not random around zero.",
    whyAr: "نمط البواقي على جانب واحد يكشف وصفًا ضعيفًا.",
    whyEn: "Residuals piled on one side reveal a weak description.",
    termAr: "بواقي",
    termEn: "Residuals",
    wrongAr: ["أعد الخط كما هو في المجلة", "تجاهل أن النقاط كلها فوق الخط", "اعتبر الانحياز دليل دقة"],
    wrongEn: ["Keep the line as printed in the magazine", "Ignore that every point sits above the line", "Treat the bias as a sign of accuracy"],
  },
  {
    id: "6-2-f11",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "حضور خمسة أيام دراسية يُستخدم لتوقع حضور إجازة عشرين يومًا.",
    sceneEn: "Attendance from five school days is used to forecast attendance across a twenty-day holiday.",
    claimAr: "ارفض الاستكمال؛ الإجازة خارج مدى أيام الدراسة.",
    claimEn: "Refuse the extrapolation; the holiday lies outside the school-day range.",
    whyAr: "خارج المدى يتغير المعنى لا الميل فقط.",
    whyEn: "Outside the range the meaning changes, not only the slope.",
    termAr: "الاستكمال الخارجي",
    termEn: "Extrapolation",
    wrongAr: ["مدّ الخط إلى يوم 20 بثقة", "عامل الإجازة كأسبوع اختبارات", "اخفِ أن البيانات خمسة أيام فقط"],
    wrongEn: ["Stretch the line to day 20 with confidence", "Treat the holiday as an exam week", "Hide that the data are only five days"],
  },
  {
    id: "6-2-f12",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "سعر ساندويتش الكانتين يُوضع لتوقع العدد المباع في الفسحة.",
    sceneEn: "The canteen sandwich price is placed as the predictor of how many sell at break.",
    claimAr: "السعر متغير تفسيري معقول إن بقيت باقي العوامل قريبة.",
    claimEn: "Price is a reasonable explanatory variable if the other conditions stay similar.",
    whyAr: "نفسّر الكمية بالسعر حين تكون القصة اقتصادية لا صدفة.",
    whyEn: "We explain quantity with price when the story is economic, not accidental.",
    termAr: "متغير تفسيري",
    termEn: "Explanatory variable",
    wrongAr: ["اعتبر لون الغلاف هو المفسر", "أعلن أن الخط يثبت سياسة السعر", "ارفض أي متغير حتى لو كان منطقيًا"],
    wrongEn: ["Treat wrapper colour as the explainer", "Announce that the line proves the price policy", "Reject every variable even when it makes sense"],
  },
  {
    id: "6-2-f13",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "ثلاث نقاط امتحان فقط تُمدّ خطًا لتوقع درجات السنة القادمة كلها.",
    sceneEn: "Only three exam points are stretched into a line to forecast the whole next year.",
    claimAr: "خط من ثلاث نقاط وصف هش؛ لا تعتمد عليه وحده.",
    claimEn: "A line from three points is a fragile description; do not rely on it alone.",
    whyAr: "الانحدار يحتاج اتجاهًا تسنده بيانات كافية لا ثلاث نقاط.",
    whyEn: "Regression needs a trend backed by enough data, not three dots.",
    termAr: "انحدار خطي",
    termEn: "Linear regression",
    wrongAr: ["أعلن خطة السنة من الثلاث نقاط", "اخفِ عدد النقاط", "سمِّ الهشاشة يقينًا"],
    wrongEn: ["Announce next year’s plan from the three points", "Hide the point count", "Call the fragility certainty"],
  },
  {
    id: "6-2-f14",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "عدد لفات الجري الأسبوعية قريب جدًا من الخط المرسوم لأسابيع الترم.",
    sceneEn: "Weekly PE lap counts sit very close to the line drawn across the term.",
    claimAr: "البواقي الصغيرة تعني وصفًا أفضل، لا برهان أن الأسبوع يسبب اللياقة.",
    claimEn: "Small residuals mean a better description, not proof that the week causes fitness.",
    whyAr: "صغر الباقي جودة ملاءمة لا سببية.",
    whyEn: "A small residual is a quality of fit, not a cause.",
    termAr: "بواقي",
    termEn: "Residuals",
    wrongAr: ["أعلن السببية لأن النقاط لزجة على الخط", "تجاهل الملاءمة الجيدة", "احذف الخط رغم صغر البواقي"],
    wrongEn: ["Announce cause because the points hug the line", "Ignore the good fit", "Delete the line even though residuals are small"],
  },
  {
    id: "6-2-f15",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "الخط بُني على أعمار 10 إلى 15 سنة ويُستخدم لتوقع درجة معلم في الأربعين.",
    sceneEn: "The line was built on ages 10 to 15 and is used to predict a mark for a teacher in their forties.",
    claimAr: "لا تمد الخط خارج فئة الأعمار التي رصدتها.",
    claimEn: "Do not stretch the line outside the age band you observed.",
    whyAr: "الاستكمال خارج الفئة يخترع علاقة لم تُرصد.",
    whyEn: "Extrapolation outside the group invents a relationship nobody measured.",
    termAr: "الاستكمال الخارجي",
    termEn: "Extrapolation",
    wrongAr: ["أعلن درجة المعلم من خط المراهقين", "عدّ العمر رقمًا بلا سياق", "اخفِ مدى البيانات"],
    wrongEn: ["Announce the teacher’s mark from the teen line", "Treat age as a number with no context", "Hide the data range"],
  },
  {
    id: "6-2-f16",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "عدد أعضاء نادي الشطرنج هذا الأسبوع يُستخدم لتوقع حرارة الغد على سطح المدرسة.",
    sceneEn: "This week’s chess-club headcount is used to forecast tomorrow’s temperature on the school roof.",
    claimAr: "ارفضه متغيرًا تفسيريًا؛ لا آلية معقولة تربط العضوية بالطقس.",
    claimEn: "Reject it as an explanatory variable; no sensible mechanism links membership to weather.",
    whyAr: "التفسير يحتاج قصة ممكنة لا اقترانًا أعمى.",
    whyEn: "Explanation needs a possible story, not a blind pairing.",
    termAr: "متغير تفسيري",
    termEn: "Explanatory variable",
    wrongAr: ["ابنِ نشرة الطقس على النادي", "أعلن أن الشطرنج يبرّد السطح", "اختر العمود لأنه متاح في الجدول"],
    wrongEn: ["Build the weather bulletin on the club", "Announce that chess cools the roof", "Pick the column only because it is in the sheet"],
  },
  {
    id: "6-2-f17",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "دقائق التأخير عن الحصة الأولى ودرجة الاختبار تميل نزولًا معًا.",
    sceneEn: "Minutes late to first period and the test mark slope downward together.",
    claimAr: "صف الخط واسأل عن متغير ثالث قبل قول إن التأخير يخفض الدرجة.",
    claimEn: "Describe the line and ask about a third variable before saying lateness lowers the mark.",
    whyAr: "الخط يصف الاقتران ولا يثبت أن س تسبب ص.",
    whyEn: "The line describes the pairing; it does not prove that X causes Y.",
    termAr: "انحدار خطي",
    termEn: "Linear regression",
    wrongAr: ["أعلن أن التأخير سبب الرسوب", "ارفض وصف الاتجاه أصلًا", "استبدل الخط بصورة الحافلة"],
    wrongEn: ["Announce that lateness causes failure", "Refuse to describe the trend at all", "Replace the line with a photo of the bus"],
  },
  {
    id: "6-2-f18",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "ساعات العمل بعد المدرسة مقابل الدرجات تترك بواقي ضخمة متفرقة حول الخط.",
    sceneEn: "After-school job hours versus marks leave huge, scattered residuals around the line.",
    claimAr: "اعتبر الخط ضعيفًا وابحث عن وصف آخر.",
    claimEn: "Treat the line as weak and look for another description.",
    whyAr: "البواقي الكبيرة المتفرقة تعني أن الخط لا يمسك الواقع.",
    whyEn: "Large scattered residuals mean the line does not hold reality.",
    termAr: "بواقي",
    termEn: "Residuals",
    wrongAr: ["أعلن ملاءمة قوية", "استخدم الخط لتقرير الرسوب", "تجاهل حجم البواقي"],
    wrongEn: ["Announce a strong fit", "Use the line in a fail report", "Ignore how large the residuals are"],
  },
  {
    id: "6-2-f19",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "بيانات مبيعات الفسحة من 10:00 إلى 10:20 تُستخدم لتوقع مبيعات الثالثة فجرًا في حفلة المدرسة.",
    sceneEn: "Break sales from 10:00 to 10:20 are used to forecast 3 a.m. sales at the school party.",
    claimAr: "ارفض التوقع؛ الساعة خارج مدى الرصد.",
    claimEn: "Refuse the forecast; that hour sits outside the observed range.",
    whyAr: "الاستكمال يمد عادة الفسحة إلى ليل مختلف تمامًا.",
    whyEn: "Extrapolation stretches a break-time habit into a totally different night.",
    termAr: "الاستكمال الخارجي",
    termEn: "Extrapolation",
    wrongAr: ["اطبع طلبية الفجر من خط الفسحة", "عدّ الساعة رقمًا قابلاً للمدّ دائمًا", "اخفِ زمن جمع البيانات"],
    wrongEn: ["Print the dawn order from the break line", "Treat the hour as a number you can always stretch", "Hide when the data were collected"],
  },
  {
    id: "6-2-f20",
    lessonId: "6-2",
    chapterId: "6",
    sceneAr: "المدرب يستخدم دقائق التمرين الأسبوعي لتوقع زمن سباق الملعب.",
    sceneEn: "The coach uses weekly practice minutes to predict the track-race time.",
    claimAr: "اقبل التمرين متغيرًا تفسيريًا منطقيًا ثم افحص البواقي.",
    claimEn: "Accept practice as a sensible explanatory variable, then inspect the residuals.",
    whyAr: "المتغير التفسيري الجيد معقول أولًا ثم يُختبر بالملاءمة.",
    whyEn: "A good explanatory variable is plausible first, then tested by fit.",
    termAr: "متغير تفسيري",
    termEn: "Explanatory variable",
    wrongAr: ["استبدل التمرين بلون الحذاء", "أعلن أن الخط يغني عن قياس الزمن", "ارفض الفحص لأن المدرب واثق"],
    wrongEn: ["Replace practice with shoe colour", "Announce that the line replaces timing the race", "Skip the check because the coach is sure"],
  },
  {
    id: "6-3-f01",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "المطلوب مقارنة عدد الغياب هذا الأسبوع في ثلاث شعب.",
    sceneEn: "The task is to compare this week’s absences across three classes.",
    claimAr: "اختر أعمدة؛ السؤال مقارنة فئات لا أجزاء من كل.",
    claimEn: "Choose bars; the question compares categories, not parts of one whole.",
    whyAr: "رسم الأعمدة يخدم مقارنة أعداد مستقلة جنبًا إلى جنب.",
    whyEn: "A bar chart serves a side-by-side comparison of separate counts.",
    termAr: "رسم أعمدة",
    termEn: "Bar chart",
    wrongAr: ["ارسم دائرة بعشرين شريحة", "ضع صورة المدرس", "اكتب نصًا من غير أرقام"],
    wrongEn: ["Draw a twenty-slice pie", "Put the teacher’s photo", "Write text with no numbers"],
  },
  {
    id: "6-3-f02",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "درجة متوسط الفصل كل أسبوع عبر الترم.",
    sceneEn: "The class mean mark each week across the term.",
    claimAr: "استخدم خطًا زمنيًا لتتبع التغير.",
    claimEn: "Use a line chart to track the change.",
    whyAr: "الخط يكشف الاتجاه عبر الوقت أوضح من شرائح كثيرة.",
    whyEn: "A line reveals the trend over time more clearly than many slices.",
    termAr: "خط زمني",
    termEn: "Line chart",
    wrongAr: ["دائرة لكل أسبوع", "خريطة العالم", "أيقونات عشوائية"],
    wrongEn: ["A pie for every week", "A world map", "Random icons"],
  },
  {
    id: "6-3-f03",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "ميزانية رحلة الصف: نقل، طعام، تذاكر، واحتياطي من مبلغ واحد.",
    sceneEn: "The class-trip budget: transport, food, tickets, and a reserve from one total.",
    claimAr: "دائرة بأربع شرائح مناسبة لأنها أجزاء من كل واحد.",
    claimEn: "A four-slice pie fits because the parts belong to one whole.",
    whyAr: "الدائرة تُظهر أجزاء الكل إن قلّت الشرائح.",
    whyEn: "A pie shows parts of a whole when there are few slices.",
    termAr: "دائرة",
    termEn: "Pie",
    wrongAr: ["خط من غير محور زمن", "دائرة بعشرين بندًا", "صورة الحافلة بدل النسب"],
    wrongEn: ["A line with no time axis", "A twenty-item pie", "A bus photo instead of shares"],
  },
  {
    id: "6-3-f04",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "ملصق الكانتين يكتب «المبيعات ارتفعت 30%» من غير ذكر من جمع الرقم.",
    sceneEn: "A canteen poster says “sales rose 30%” with no note of who collected the figure.",
    claimAr: "ارفض الملصق حتى يُذكر المصدر تحت الرسم.",
    claimEn: "Reject the poster until the source is cited under the chart.",
    whyAr: "المصدر يقول من أين جاءت الأرقام ويتيح المراجعة.",
    whyEn: "The source says where the numbers came from and lets others check.",
    termAr: "المصدر",
    termEn: "Source",
    wrongAr: ["انشر الملصق لأنه لافت", "امسح أي إشارة للدفتر", "استبدل المصدر بشعار جميل"],
    wrongEn: ["Publish the poster because it is catchy", "Wipe any pointer to the logbook", "Replace the source with a pretty logo"],
  },
  {
    id: "6-3-f05",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "نجاح ثلاث مواد في امتحان واحد يُعرض بدائرة ثلاثية الأبعاد لامعة.",
    sceneEn: "Pass rates for three subjects in one exam are shown as a shiny 3D pie.",
    claimAr: "استبدلها بأعمدة واضحة للمقارنة.",
    claimEn: "Replace it with clear bars for the comparison.",
    whyAr: "الأعمدة أصدق لمقارنة فئات قليلة من زينة تضخّم الشرائح.",
    whyEn: "Bars compare a few categories more honestly than decorative slices.",
    termAr: "رسم أعمدة",
    termEn: "Bar chart",
    wrongAr: ["أبقِ البعد الثالث لأنه أجمل", "اخفِ النسب", "قصّ المحور إن وُجد"],
    wrongEn: ["Keep the third dimension because it looks nicer", "Hide the rates", "Crop any axis you add"],
  },
  {
    id: "6-3-f06",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "مبيعات العصير الأسبوعية رُسمت أعمدة بلا ترتيب الأسابيع من الأول إلى الأخير.",
    sceneEn: "Weekly juice sales were drawn as bars with the weeks in no first-to-last order.",
    claimAr: "رتّب الأسابيع على خط زمني إن كان السؤال عن التغير.",
    claimEn: "Order the weeks on a line if the question is about change.",
    whyAr: "الخط يخدم سؤال «كيف تغيرت المبيعات عبر الزمن؟».",
    whyEn: "A line serves the question “how did sales change through time?”",
    termAr: "خط زمني",
    termEn: "Line chart",
    wrongAr: ["اترك الأسابيع مشوشة", "حوّلها إلى دائرة بعشرة أسابيع", "احذف محور الزمن"],
    wrongEn: ["Leave the weeks jumbled", "Turn them into a ten-week pie", "Delete the time axis"],
  },
  {
    id: "6-3-f07",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "عضوية عشرين ناديًا مدرسيًا تُحشر في دائرة واحدة.",
    sceneEn: "Membership of twenty school clubs is crammed into one pie.",
    claimAr: "ارفض الدائرة؛ الشرائح الكثيرة لا تُقرأ.",
    claimEn: "Reject the pie; too many slices cannot be read.",
    whyAr: "الدائرة تضعف إذا كثرت الشرائح عن حدّ العين.",
    whyEn: "A pie weakens once the slices pass what the eye can hold.",
    termAr: "دائرة",
    termEn: "Pie",
    wrongAr: ["أضف شرائح أكثر للزينة", "أعلن أن العشرين أفضل عدد", "اخفِ أسماء الأندية"],
    wrongEn: ["Add more slices for decoration", "Announce that twenty is the ideal count", "Hide the club names"],
  },
  {
    id: "6-3-f08",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "رسم أعمدة لمطر الشهر على سطح الملعب بلا ذكر محطة القياس أو تاريخ الرصد.",
    sceneEn: "A bar chart of this month’s rain on the pitch roof names neither the gauge nor the date of the readings.",
    claimAr: "اكتب المصدر وتاريخ الرصد تحت الرسم.",
    claimEn: "Write the source and the observation date under the chart.",
    whyAr: "من غير مصدر لا تُراجع أرقام الطقس.",
    whyEn: "Without a source the weather numbers cannot be checked.",
    termAr: "المصدر",
    termEn: "Source",
    wrongAr: ["اترك الرسم بلا حاشية", "استبدل المصدر بأيقونة غيمة", "أعلن الأرقام كأنها سرّ الصف"],
    wrongEn: ["Leave the chart with no footnote", "Replace the source with a cloud icon", "Announce the numbers as a class secret"],
  },
  {
    id: "6-3-f09",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "نسبة النجاح 71% و73% في شعبتين، والمحور الرأسي يبدأ من 70 ليبدو القفز هائلًا.",
    sceneEn: "Pass rates are 71% and 73% in two classes, and the y-axis starts at 70 so the jump looks huge.",
    claimAr: "ابدأ المحور من صفر أو صرّح بالقطع حتى لا يتضخم فرق تافه.",
    claimEn: "Start the axis at zero or declare the crop so a tiny gap is not inflated.",
    whyAr: "قطع المحور الرأسي يضلّل عين القارئ.",
    whyEn: "Cropping the y-axis misleads the reader’s eye.",
    termAr: "رسم أعمدة",
    termEn: "Bar chart",
    wrongAr: ["أبقِ القطع لأنه درامي", "امسح النسب واكتفِ بالشكل", "عدّ التضخيم واجبًا في كل رسم"],
    wrongEn: ["Keep the crop because it is dramatic", "Wipe the rates and keep the shape", "Treat the inflation as required on every chart"],
  },
  {
    id: "6-3-f10",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "عدد الغياب الأسبوعي عبر أربعة عشر أسبوعًا في الترم.",
    sceneEn: "Weekly absences across fourteen weeks of the term.",
    claimAr: "خط زمني بعنوان يقول الادعاء ومحاور موسومة.",
    claimEn: "A line over time whose title states the claim and whose axes are labelled.",
    whyAr: "تتبع الزمن يناسبه الخط لا دائرة بعشر شرائح.",
    whyEn: "Tracking time suits a line, not a ten-slice pie.",
    termAr: "خط زمني",
    termEn: "Line chart",
    wrongAr: ["دائرة لكل أسبوع", "نص شعري بلا محور", "صورة المدير"],
    wrongEn: ["A pie for each week", "A poem with no axis", "The principal’s photo"],
  },
  {
    id: "6-3-f11",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "حضور ثلاث مدارس في المسابقة يُرسم دائرة واحدة كأنها أجزاء مبلغ مشترك.",
    sceneEn: "Attendance from three schools at the contest is drawn as one pie, as if they were shares of one pot.",
    claimAr: "ارفض الدائرة؛ الأعداد مستقلة. استخدم أعمدة.",
    claimEn: "Reject the pie; the counts are separate. Use bars.",
    whyAr: "الدائرة لأجزاء من مجموع واحد لا لمدارس لا تُجمع حصصها.",
    whyEn: "A pie is for parts of one total, not for schools whose shares are not a single pot.",
    termAr: "دائرة",
    termEn: "Pie",
    wrongAr: ["أبقِ الدائرة لأنها ملوّنة", "ادمج المدارس في شريحة واحدة غامضة", "احذف الأرقام"],
    wrongEn: ["Keep the pie because it is colourful", "Merge the schools into one vague slice", "Delete the numbers"],
  },
  {
    id: "6-3-f12",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "طالب ينسخ أرقام محضر مجلس الطلاب ويمسح اسم المصدر ليبدو بحث الكانتين أصليًا.",
    sceneEn: "A student copies figures from the council minutes and erases the source so the canteen report looks original.",
    claimAr: "أعد ذكر المصدر؛ إخفاؤه غش في التواصل.",
    claimEn: "Put the source back; hiding it is dishonest communication.",
    whyAr: "ذكر المصدر واجب تحت الرسم ولو نُقلت الأرقام.",
    whyEn: "Citing the source under the chart is required even when the numbers are reused.",
    termAr: "المصدر",
    termEn: "Source",
    wrongAr: ["امسح الاسم ليبدو العمل شخصيًا", "استبدل الحاشية بعبارة «بحثي»", "عدّ الإخفاء مهارة عرض"],
    wrongEn: ["Erase the name so the work looks personal", "Replace the footnote with “my research”", "Call the hiding a presentation skill"],
  },
  {
    id: "6-3-f13",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "سعر وجبة الكانتين 9.0 ثم 9.2 جنيه، والجراف يقطع المحور عند 8.9.",
    sceneEn: "The canteen meal is 9.0 then 9.2 pounds, and the graph crops the axis at 8.9.",
    claimAr: "أظهر المقياس الكامل أو اذكر أن الفرق قرشان حتى لا يُضخَّم.",
    claimEn: "Show the full scale or state that the gap is two piastres so it is not inflated.",
    whyAr: "الفرق التافه يبدو أزمة إذا قُطع المحور الرأسي.",
    whyEn: "A trivial gap looks like a crisis if the y-axis is cropped.",
    termAr: "رسم أعمدة",
    termEn: "Bar chart",
    wrongAr: ["أبقِ القطع ليصوت الطلاب ضد السعر", "اخفِ وحدة الجنيه", "سمِّ القرشين قفزة تاريخية من غير رقم"],
    wrongEn: ["Keep the crop so students vote against the price", "Hide the pound unit", "Call the two piastres a historic jump with no number"],
  },
  {
    id: "6-3-f14",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "خط غياب بلا أسماء أسابيع على المحور الأفقي.",
    sceneEn: "An absence line with no week names on the horizontal axis.",
    claimAr: "سمّ المحاور؛ الخط من غير أسابيع لا يُقرأ.",
    claimEn: "Label the axes; a line with no weeks cannot be read.",
    whyAr: "التسمية جزء من الرسم الذي يخدم السؤال.",
    whyEn: "Labelling is part of a chart that serves the question.",
    termAr: "خط زمني",
    termEn: "Line chart",
    wrongAr: ["اترك المحور فارغًا للجمال", "استبدل الأسابيع بأيقونات", "احذف العنوان أيضًا"],
    wrongEn: ["Leave the axis blank for beauty", "Replace the weeks with icons", "Delete the title as well"],
  },
  {
    id: "6-3-f15",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "توزيع ألوان شعار اليوم الرياضي: أحمر وأخضر وأبيض من قماش واحد.",
    sceneEn: "The sports-day logo colours: red, green, and white cut from one piece of cloth.",
    claimAr: "دائرة بثلاث شرائح تخدم سؤال «كم من الكل؟».",
    claimEn: "A three-slice pie serves the question “how much of the whole?”",
    whyAr: "الأجزاء القليلة من كل واحد تناسب الدائرة.",
    whyEn: "A few parts of one whole suit a pie.",
    termAr: "دائرة",
    termEn: "Pie",
    wrongAr: ["خط زمني للألوان", "دائرة بخمس عشرة درجة لون", "أعمدة من غير ذكر أنها أجزاء كل"],
    wrongEn: ["A line chart of the colours", "A pie with fifteen shades", "Bars with no note that they are parts of a whole"],
  },
  {
    id: "6-3-f16",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "رسم مصروف حفلة الصف أُخذ من محضر مجلس الطلاب المؤرخ.",
    sceneEn: "The class-party spend chart was taken from a dated student-council minute.",
    claimAr: "اكتب تحت الرسم: محضر مجلس الطلاب والتاريخ.",
    claimEn: "Write under the chart: student-council minutes and the date.",
    whyAr: "المصدر المؤرخ يتيح لقارئ آخر أن يعود للأرقام.",
    whyEn: "A dated source lets another reader return to the figures.",
    termAr: "المصدر",
    termEn: "Source",
    wrongAr: ["اترك الحاشية فارغة", "اكتب «مصدر سري»", "انسب الرقم لنفسك"],
    wrongEn: ["Leave the footnote empty", "Write “secret source”", "Claim the number as your own"],
  },
  {
    id: "6-3-f17",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "نسب نجاح ثلاث مواد عبر أربعة امتحانات في الترم.",
    sceneEn: "Pass rates of three subjects across four exams in the term.",
    claimAr: "استخدم أعمدة مجمّعة أو خطوطًا متعددة، ولا تقطع المحور ولا تخفِ المصدر.",
    claimEn: "Use grouped bars or several lines, and neither crop the axis nor hide the source.",
    whyAr: "المقارنة عبر فئات وزمن تحتاج رسمًا يخدم السؤال لا زينة.",
    whyEn: "Comparing categories across time needs a chart that serves the question, not decoration.",
    termAr: "رسم أعمدة",
    termEn: "Bar chart",
    wrongAr: ["دائرة بعشرين شريحة لكل امتحان", "اقطع المحور عند 90 لتضخم فرقًا صغيرًا", "اخفِ مصدر النسب"],
    wrongEn: ["A twenty-slice pie for every exam", "Crop the axis at 90 to inflate a small gap", "Hide the source of the rates"],
  },
  {
    id: "6-3-f18",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "تقرير طقس المدرسة يضع صورة المعلم بدل خط حرارة الأسابيع.",
    sceneEn: "The school weather report places the teacher’s photo instead of a weekly temperature line.",
    claimAr: "استبدل الصورة بخط زمني للأرقام.",
    claimEn: "Replace the photo with a line chart of the numbers.",
    whyAr: "الصورة لا تُظهر التغير عبر الوقت.",
    whyEn: "A photo does not show change over time.",
    termAr: "خط زمني",
    termEn: "Line chart",
    wrongAr: ["أبقِ الصورة لأنها ودودة", "ارسم دائرة لدرجات الحرارة العشرين", "احذف الأرقام واكتفِ بالابتسامة"],
    wrongEn: ["Keep the photo because it is friendly", "Draw a pie of twenty temperature readings", "Drop the numbers and keep the smile"],
  },
  {
    id: "6-3-f19",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "دائرة ميزانية النشاط عنوانها «شكل 1» من غير ادعاء وبلا نسب مقروءة.",
    sceneEn: "The activity-budget pie is titled “Figure 1”, with no claim and no readable shares.",
    claimAr: "اجعل العنوان يقول الادعاء، واكتب النسب والمصدر.",
    claimEn: "Make the title state the claim, and write the shares and the source.",
    whyAr: "عنوان الرسم يقول الادعاء حتى يخدم سؤال القارئ.",
    whyEn: "The title states the claim so the chart serves the reader’s question.",
    termAr: "دائرة",
    termEn: "Pie",
    wrongAr: ["أبقِ «شكل 1» لأنه رسمي", "اخفِ النسب داخل الشرائح الداكنة", "امسح أي جملة ادعاء"],
    wrongEn: ["Keep “Figure 1” because it looks official", "Hide the shares inside dark slices", "Wipe any sentence that states a claim"],
  },
  {
    id: "6-3-f20",
    lessonId: "6-3",
    chapterId: "6",
    sceneAr: "ملخص الكانتين جاهز: أعمدة جميلة بلا مصدر وبلا عنوان يقول ماذا ارتفع.",
    sceneEn: "The canteen summary is ready: pretty bars with no source and no title saying what rose.",
    claimAr: "أضف عنوانًا يقول الادعاء واذكر المصدر تحت الرسم.",
    claimEn: "Add a title that states the claim and cite the source under the chart.",
    whyAr: "الرسم الصادق يحترم عين القارئ بالعنوان والمصدر معًا.",
    whyEn: "An honest chart respects the reader’s eye with both a title and a source.",
    termAr: "المصدر",
    termEn: "Source",
    wrongAr: ["انشر الأعمدة لأنها لامعة", "اكتب «رسم توضيحي» من غير رقم", "استبدل المصدر بشعار الكانتين فقط"],
    wrongEn: ["Publish the bars because they shine", "Write “illustration” with no number", "Replace the source with the canteen logo only"],
  },
];

export const CHAPTER_6_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "6-1-a01",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "حلّل اختبارًا قصيرًا فيه درجة 98 وباقي الصف بين 11 و14: لماذا يخدع المتوسط القارئ، وماذا يضيف الوسيط؟",
    promptEn: "Analyse a short quiz with one 98 and the rest between 11 and 14: why does the mean mislead, and what does the median add?",
    guideAr: "المتوسط ينجذب للشاذ؛ الوسيط يبقى قرب 12–13 ويصف مركز الصف. اذكر أن الملخص الوصفي يحتاج أكثر من رقم.",
    guideEn: "The mean is pulled by the outlier; the median stays near 12–13 and shows the class centre. Note that a descriptive summary needs more than one number.",
  },
  {
    id: "6-1-a02",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "قارن تلخيص 30 درجة حضور في شعبة واحدة بتعميم الرقم على المدرسة كلها.",
    promptEn: "Compare summarising 30 attendance marks in one class with generalising that number to the whole school.",
    guideAr: "الأول إحصاء وصفي للعينة؛ الثاني استدلال يحتاج تمثيلًا وعدم يقين. اسأل: من غاب عن العينة؟",
    guideEn: "The first is descriptive of the sample; the second is inference and needs representativeness and uncertainty. Ask: who is missing from the sample?",
  },
  {
    id: "6-1-a03",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "انتقد قول المدرسة: «من يستخدم تطبيق المراجعة أكثر درجته أعلى، إذن التطبيق يرفع الدرجة».",
    promptEn: "Critique the school’s claim: “Heavier revision-app users get higher marks, so the app raises marks.”",
    guideAr: "ارتباط لا سببية. متغير ثالث: الالتزام السابق. اطلب مجموعة مقارنة أو زمنًا قبل/بعد لا قفزًا للسبب.",
    guideEn: "Correlation is not causation. A third variable is prior commitment. Ask for a comparison group or a before/after, not a leap to cause.",
  },
  {
    id: "6-1-a04",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "اشرح لماذا تعطي 6 قراءات مطر على السطح فترة ثقة أوسع من 60 قراءة، وماذا يعني ذلك للإعلان عن «معدل السنة».",
    promptEn: "Explain why six roof rain readings give a wider confidence interval than 60, and what that means for announcing a “yearly rate”.",
    guideAr: "صغر العينة يزيد عدم اليقين فيتسع المدى. لا تصرخ برقم قاطع؛ صرّح بـ n وبعرض الفترة.",
    guideEn: "A smaller sample raises uncertainty, so the range widens. Do not shout a final number; state n and the width of the interval.",
  },
  {
    id: "6-1-a05",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "حلّل فرضية أمينة المكتبة أن الجلوس قرب النافذة يزيد القراءة، إن بُنيت على شعور في الردهة فقط.",
    promptEn: "Analyse the librarian’s hypothesis that sitting by the window increases reading, if it rests only on a hallway feeling.",
    guideAr: "الفرضية ادعاء يُختبر بعدد الصفحات أو الاستعارات، مع مقارنة بمقاعد أخرى، لا بإحساس.",
    guideEn: "A hypothesis is a claim tested with page or loan counts, compared with other seats — not with a hunch.",
  },
  {
    id: "6-1-a06",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "قارن فترة ثقة لمتوسط مصروف الكانتين من شعبة n=40 بفترة من شعبة n=5.",
    promptEn: "Compare a confidence interval for mean canteen spend from a class of n=40 with one from a class of n=5.",
    guideAr: "فترة الخمسة أوسع عادة. لا تساوِ الدقتين ولا تضيّق الصغيرة يدويًا.",
    guideEn: "The n=5 interval is usually wider. Do not equate the two precisions or narrow the small one by hand.",
  },
  {
    id: "6-1-a07",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "انتقد تعميم مبيعات عصير يوم ممطر واحد على مبيعات السنة كلها.",
    promptEn: "Critique generalising juice sales from one rainy day to the whole year’s sales.",
    guideAr: "يوم واحد عينة لا تشبه السنة: الطقس والمناسبات تختلف. حدّد الادعاء أو وسّع الأيام قبل الاستدلال.",
    guideEn: "One day is a sample that does not resemble the year: weather and events change. Narrow the claim or add more days before inferring.",
  },
  {
    id: "6-1-a08",
    lessonId: "6-1",
    chapterId: "6",
    promptAr: "اشرح لماذا ننظر إلى الوسيط أيضًا حين يرفع أسبوع إنفلونزا متوسط الغياب الشهري.",
    promptEn: "Explain why we also look at the median when a flu week lifts the monthly mean of absences.",
    guideAr: "الشاذ يسحب المتوسط؛ الوسيط يبقى أقرب لأسابيع عادية. علّم الأسبوع في الملخص ولا تخفه.",
    guideEn: "The unusual week pulls the mean; the median stays closer to ordinary weeks. Flag the week in the summary; do not hide it.",
  },
  {
    id: "6-2-a01",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "حلّل قرار رسم خط مستقيم على سحابة أنواع وجبات الكانتين مقابل الحرارة.",
    promptEn: "Analyse the decision to draw a straight line through a cloud of canteen snack types versus temperature.",
    guideAr: "إن لم تتوقع اتجاهًا فالبواقي كبيرة والخط ضعيف. ارفض الخط إن كانت النقاط ضجيجًا.",
    guideEn: "If you do not expect a trend, residuals will be large and the line is weak. Reject the line if the points are noise.",
  },
  {
    id: "6-2-a02",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "قارن توقع درجة عند 5 ساعات مذاكرة (داخل مدى 1–8) بتوقع درجة عند 40 ساعة.",
    promptEn: "Compare predicting a mark at 5 study hours (inside a 1–8 range) with predicting a mark at 40 hours.",
    guideAr: "الأول داخل المدى وصف حذر؛ الثاني استكمال خطر يمد الخط حيث لا بيانات.",
    guideEn: "The first stays inside the range as a cautious description; the second is risky extrapolation beyond any points.",
  },
  {
    id: "6-2-a03",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "انتقد جملة: «خط التأخير والدرجة يثبت أن التأخير يسبب الرسوب».",
    promptEn: "Critique the sentence: “The lateness–mark line proves that lateness causes failure.”",
    guideAr: "الخط وصف للاقتران. اسأل عن متغير ثالث (نوم، حافلة، التزام) ولا تخلط الوصف بالسبب.",
    guideEn: "The line describes a pairing. Ask about a third variable (sleep, bus, commitment) and do not mix description with cause.",
  },
  {
    id: "6-2-a04",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "اشرح لماذا تعني البواقي الكبيرة المتفرقة حول خط ساعات العمل بعد المدرسة أن الخط ضعيف.",
    promptEn: "Explain why large scattered residuals around an after-school-hours line mean the line is weak.",
    guideAr: "الباقي = الواقع − الخط. إن كبر وتفرق فالخط لا يمسك النقاط. الصغر جودة ملاءمة لا سببية.",
    guideEn: "Residual = reality minus the line. If residuals are large and scattered, the line does not hold the points. Small residuals are fit quality, not cause.",
  },
  {
    id: "6-2-a05",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "حلّل استخدام مقاس الحذاء متغيرًا تفسيريًا لدرجة الرياضيات.",
    promptEn: "Analyse using shoe size as the explanatory variable for the maths mark.",
    guideAr: "لا آلية معقولة؛ العمر قد يحرّك الاثنين. ارفض المتغير ولو ظهر اقتران ضعيف.",
    guideEn: "No sensible mechanism; age may move both. Reject the variable even if a weak pairing appears.",
  },
  {
    id: "6-2-a06",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "قارن الحرارة لتوقع مبيعات العصير بعدد أعضاء نادي الشطرنج لتوقع حرارة السطح.",
    promptEn: "Compare temperature as a predictor of juice sales with chess-club headcount as a predictor of roof temperature.",
    guideAr: "الأول متغير تفسيري منطقي يُفحص بالبواقي؛ الثاني اقتران أعمى بلا قصة. المنطق أولًا ثم الملاءمة.",
    guideEn: "The first is a plausible explanatory variable, then checked by residuals; the second is a blind pairing with no story. Sense first, then fit.",
  },
  {
    id: "6-2-a07",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "انتقد مدّ مبيعات الفسحة (10:00–10:20) لتوقع مبيعات الثالثة فجرًا في حفلة المدرسة.",
    promptEn: "Critique stretching break sales (10:00–10:20) to forecast 3 a.m. sales at the school party.",
    guideAr: "السياق والساعة خارج المدى. الاستكمال يخترع عادة ليل لم تُرصد. ارفض التوقع أو اجمع بيانات الحفلة.",
    guideEn: "The setting and the hour sit outside the range. Extrapolation invents a night-time habit nobody measured. Refuse the forecast or collect party data.",
  },
  {
    id: "6-2-a08",
    lessonId: "6-2",
    chapterId: "6",
    promptAr: "اشرح لماذا يبقى خط زيارات المكتبة والدرجة وصفًا حتى لو صغرت البواقي.",
    promptEn: "Explain why a library-visits-and-mark line stays a description even when residuals are small.",
    guideAr: "الملاءمة الجيدة لا تثبت أن الزيارة تسبب الدرجة. الخط أداة وصف؛ السبب يحتاج تصميمًا آخر.",
    guideEn: "A good fit does not prove that visits cause the mark. The line is a description; cause needs another design.",
  },
  {
    id: "6-3-a01",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "حلّل رسم نسب نجاح 71% و73% إذا بدأ المحور الرأسي من 70.",
    promptEn: "Analyse a chart of 71% and 73% pass rates if the y-axis starts at 70.",
    guideAr: "القطع يضخّم فرق نقطتين. ابدأ من صفر أو صرّح بالقطع واكتب النسب صراحة.",
    guideEn: "The crop inflates a two-point gap. Start at zero or declare the crop, and write the rates plainly.",
  },
  {
    id: "6-3-a02",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "قارن أعمدة ودائرة وخطًا زمنيًا لعرض غياب أسبوعي عبر الترم: أيها يخدم السؤال؟",
    promptEn: "Compare bars, a pie, and a line for weekly absences across the term: which serves the question?",
    guideAr: "السؤال تتبع عبر الزمن → خط. الأعمدة ممكنة إن رُتبت الأسابيع. الدائرة بعشرات الشرائح ضعيفة.",
    guideEn: "The question tracks time → a line. Bars can work if weeks are ordered. A pie with dozens of slices is weak.",
  },
  {
    id: "6-3-a03",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "انتقد دائرة واحدة لعضوية عشرين ناديًا مدرسيًا.",
    promptEn: "Critique a single pie for membership of twenty school clubs.",
    guideAr: "الشرائح الكثيرة لا تُقرأ. انتقل إلى أعمدة مرتبة أو اجمع الأندية الصغيرة. الدائرة لأجزاء قليلة من كل.",
    guideEn: "Too many slices cannot be read. Move to sorted bars or group tiny clubs. A pie is for a few parts of a whole.",
  },
  {
    id: "6-3-a04",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "اشرح لماذا نختار الرسم الذي يخدم السؤال لا الذي يبدو أجمل في تقرير الكانتين.",
    promptEn: "Explain why we pick the chart that serves the question, not the prettiest one, in a canteen report.",
    guideAr: "الجمال بلا محور أو بمصدر مخفي يضلّل. حدّد السؤال أولًا: مقارنة فئات، زمن، أم أجزاء كل؟",
    guideEn: "Pretty charts with no axis or a hidden source mislead. Name the question first: categories, time, or parts of a whole?",
  },
  {
    id: "6-3-a05",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "حلّل رسم مطر الملعب إذا غاب المصدر وغابت تسميات المحاور.",
    promptEn: "Analyse a pitch-rain chart if the source is missing and the axes are unlabelled.",
    guideAr: "لا مراجعة من غير مصدر وتاريخ. من غير أسماء محاور لا يُعرف إن كان المطر يومًا أم شهرًا. أصلح الاثنين.",
    guideEn: "No check is possible without a source and a date. Unlabelled axes hide whether the rain is a day or a month. Fix both.",
  },
  {
    id: "6-3-a06",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "قارن عنوانًا يقول «ارتفع النجاح بعد حصص الدعم» بعنوان «شكل 2» على الرسم نفسه.",
    promptEn: "Compare a title that says “pass rates rose after support lessons” with the title “Figure 2” on the same chart.",
    guideAr: "الأول يصرّح بالادعاء وعلى القارئ أن يفحصه. الثاني رقم شكل لا يخدم السؤال. العنوان جزء من التواصل.",
    guideEn: "The first states a claim the reader can test. The second is a figure number that does not serve the question. The title is part of the communication.",
  },
  {
    id: "6-3-a07",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "انتقد دائرة ثلاثية الأبعاد لمقارنة غياب ثلاث شعب.",
    promptEn: "Critique a 3D pie used to compare absences in three classes.",
    guideAr: "البعد الثالث يضخّم شريحة ويصغّر أخرى. الشعب فئات مستقلة تناسبها أعمدة من صفر، مع مصدر.",
    guideEn: "The third dimension inflates one slice and shrinks another. Separate classes suit bars from zero, with a source.",
  },
  {
    id: "6-3-a08",
    lessonId: "6-3",
    chapterId: "6",
    promptAr: "اشرح لماذا لا نقطع المحور الرأسي عند 8.9 حين يرتفع سعر الوجبة من 9.0 إلى 9.2.",
    promptEn: "Explain why we do not crop the y-axis at 8.9 when the meal price rises from 9.0 to 9.2.",
    guideAr: "القرشان فرق تافه؛ القطع يصنعه أزمة بصرية. ابدأ من صفر أو اكتب الفرق صراحة واذكر المصدر.",
    guideEn: "Two piastres are a tiny gap; the crop turns it into a visual crisis. Start at zero or state the gap plainly and cite the source.",
  },
];
