import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_4_FACTS: BankFact[] = [
  {
    id: "4-1-f01",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "صفحة المدرسة تفتح ببانر ترحيب حجمه ثمانية ميغابايت بينما الطلاب على شبكة الجيل الثالث.",
    sceneEn: "The school homepage opens with an eight-megabyte welcome banner while students are on 3G.",
    claimAr: "اختصر البانر لوسيط أخف يحمل التحية نفسها.",
    claimEn: "Shrink the banner to a lighter medium that still carries the greeting.",
    whyAr: "الوسيط يخدم المعنى؛ الملف الثقيل يحجب الصفحة قبل أن تُقرأ التحية.",
    whyEn: "The medium serves the meaning; a heavy file blocks the page before the greeting is read.",
    termAr: "وسائط متعددة",
    termEn: "Multimedia",
    wrongAr: ["اترك البانر كما صُوّر ليبدو أفخم", "احذف كل النص وابقِ الصورة وحدها", "حوّل التحية إلى بودكاست صامت"],
    wrongEn: ["Leave the banner as shot so it looks premium", "Delete all text and keep only the image", "Turn the greeting into a silent podcast"],
  },
  {
    id: "4-1-f02",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "نتائج امتحان منتصف الترم نُشرت كمقطع صوتي طوله اثنتا عشرة دقيقة بلا أرقام مكتوبة.",
    sceneEn: "Midterm exam results were published as a twelve-minute audio clip with no written numbers.",
    claimAr: "اعرض الدرجات في جدول أو رسم؛ الصوت وحده يخفي المقارنة.",
    claimEn: "Show the scores in a table or chart; audio alone hides the comparison.",
    whyAr: "الأرقام تُقارن بالعين؛ الوسيط الصوتي لا يناسب قائمة درجات.",
    whyEn: "Numbers are compared by eye; audio is the wrong medium for a score list.",
    termAr: "وسائط متعددة",
    termEn: "Multimedia",
    wrongAr: ["أطل المقطع ليبدو أهم", "ارسم الدرجات كخلفية متحركة بلا محاور", "أرسل النتائج همسًا في الإذاعة المدرسية فقط"],
    wrongEn: ["Make the clip longer so it feels important", "Paint the scores as a moving background with no axes", "Announce results only as a whisper on school radio"],
  },
  {
    id: "4-1-f03",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "نادي المسرح رفع فيديو للرقصة وأسقط موعد العرض ومكان القاعة من الصفحة.",
    sceneEn: "The drama club posted a dance video and dropped the show time and hall from the page.",
    claimAr: "اكتب الموعد والمكان نصًا، وأبقِ مقطعًا قصيرًا للحركة فقط.",
    claimEn: "Write the time and place as text, and keep a short clip only for the motion.",
    whyAr: "الفيديو يناسب الحركة؛ الحقائق الثابتة تُقرأ أسرع في سطر.",
    whyEn: "Video fits motion; fixed facts are read faster in a line of text.",
    termAr: "وسائط متعددة",
    termEn: "Multimedia",
    wrongAr: ["اعتمد الرقصة بديلًا عن الموعد", "ارفع العرض كاملًا بدقة السينما", "اخفِ المكان ليأتي الجمهور مصادفة"],
    wrongEn: ["Let the dance replace the show time", "Upload the whole play at cinema resolution", "Hide the hall so the audience finds it by chance"],
  },
  {
    id: "4-1-f04",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "مواعيد أتوبيس المدرسة ظهرت كحلقة رسوم متحركة تدور ولا تتوقف عند الساعة التالية.",
    sceneEn: "School bus times appeared as a looping animation that never settles on the next hour.",
    claimAr: "انشر الجدول نصًا أو في جدول بسيط يُقرأ في ثانية.",
    claimEn: "Publish the timetable as text or a simple table that can be read in a second.",
    whyAr: "الجدول بيانات؛ الرسوم التي تدور تخفي الأتوبيس التالي.",
    whyEn: "A schedule is data; a spinning cartoon hides the next bus.",
    termAr: "وسائط متعددة",
    termEn: "Multimedia",
    wrongAr: ["زد سرعة الدوران ليبدو أحدث", "حوّل المواعيد إلى أغنية من غير كلمات", "ضع الجدول داخل فيديو بلا أزرار توقف"],
    wrongEn: ["Spin it faster so it looks newer", "Turn the times into a song with no lyrics", "Put the timetable inside a video with no pause button"],
  },
  {
    id: "4-1-f05",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "قاعدة معمل الكيمياء ظهرت كأيقونة لهب بلا جملة مكتوبة بجانب المغسلة.",
    sceneEn: "The chemistry-lab rule appeared as a flame icon with no written sentence beside the sink.",
    claimAr: "اربط أيقونة واضحة بقاعدة قصيرة مكتوبة.",
    claimEn: "Pair a clear icon with a short written rule.",
    whyAr: "الأيقونة تسرّع النظرة؛ القاعدة يجب أن تبقى مقروءة.",
    whyEn: "An icon speeds a glance; the rule must stay readable.",
    termAr: "وسائط متعددة",
    termEn: "Multimedia",
    wrongAr: ["اترك اللهب وحده فهو أجمل", "سجّل القاعدة بودكاستًا يُشغَّل عند الاشتعال", "ارسم اللهب كخلفية صفحة كاملة"],
    wrongEn: ["Leave the flame alone because it looks nicer", "Record the rule as a podcast that plays when something ignites", "Paint the flame as a full-page background"],
  },
  {
    id: "4-1-f06",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "معرض يوم الرياضة رفع أربعين صورة خام من الكاميرا على شبكة الفناء الضعيفة.",
    sceneEn: "The sports-day gallery uploaded forty camera-raw photos onto the weak yard network.",
    claimAr: "اضغط صور المعرض قبل النشر.",
    claimEn: "Compress the gallery photos before publishing.",
    whyAr: "الملفات الخام تثقل الشبكة المدرسية وتؤخر فتح الصفحة.",
    whyEn: "Raw files weigh down the school network and delay the page.",
    termAr: "ضغط الملفات",
    termEn: "Compression",
    wrongAr: ["ارفع الأصول كما خرجت من الكاميرا", "احذف المعرض لأن الضغط ممنوع", "بدّل الصور بمقطع صوتي لصفير الحكم"],
    wrongEn: ["Upload the originals exactly as they left the camera", "Delete the gallery because compression is forbidden", "Replace the photos with audio of the referee's whistle"],
  },
  {
    id: "4-1-f07",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "ملصق تحذير الأحماض حُفظ كصورة PNG حجمها عشرون ميغابايت أعلى صفحة المعمل.",
    sceneEn: "An acid-warning poster was saved as a twenty-megabyte PNG at the top of the lab page.",
    claimAr: "صدّر صورة مضغوطة بحجم العرض على الشاشة.",
    claimEn: "Export a compressed image at the size the screen actually shows.",
    whyAr: "الضغط يصغّر الملف ويُبقي التحذير مقروءًا.",
    whyEn: "Compression shrinks the file while the warning stays readable.",
    termAr: "ضغط الملفات",
    termEn: "Compression",
    wrongAr: ["أبقِ الـ PNG الأصلي ليبدو أوضح من الحقيقة", "ارفع الملصق كملف فيديو صامت", "اخفِ التحذير حتى لا يثقل الموقع"],
    wrongEn: ["Keep the original PNG so it looks sharper than reality", "Upload the poster as a silent video file", "Hide the warning so the site stays light"],
  },
  {
    id: "4-1-f08",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "صفحة الكورال وضعت تسجيل الحفل بصيغة WAV غير مضغوطة يستغرق تنزيلها دقائق.",
    sceneEn: "The choir page posted the concert as an uncompressed WAV that takes minutes to download.",
    claimAr: "قدّم الصوت بصيغة مضغوطة تناسب الويب.",
    claimEn: "Offer the audio in a compressed format that fits the web.",
    whyAr: "ضغط الصوت يقلل الانتظار دون أن يلغي الأداء.",
    whyEn: "Audio compression cuts the wait without deleting the performance.",
    termAr: "ضغط الملفات",
    termEn: "Compression",
    wrongAr: ["أصرّ على WAV لأن الضغط يحذف المعنى دائمًا", "استبدل الحفل بصورة للكرسي الفارغ", "ارفع ثلاث نسخ WAV بأحجام أكبر"],
    wrongEn: ["Insist on WAV because compression always deletes meaning", "Replace the concert with a photo of an empty chair", "Upload three larger WAV copies"],
  },
  {
    id: "4-1-f09",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "مشرف الموقع منع أي ضغط وقال إن الجودة المدرسية تعني الملف الأكبر دائمًا.",
    sceneEn: "The site supervisor banned all compression and said school quality always means the largest file.",
    claimAr: "اضغط ما دام المعنى باقيًا، وتجنب سحق النص حتى يصير ضبابًا.",
    claimEn: "Compress while the meaning survives, and avoid crushing text into fog.",
    whyAr: "الضغط أداة موازنة لا حظر ولا تكسير أعمى للجودة.",
    whyEn: "Compression is a balancing tool, not a ban and not a blind wrecking of quality.",
    termAr: "ضغط الملفات",
    termEn: "Compression",
    wrongAr: ["ارفع كل ملف بأكبر حجم متاح", "امنع الصور كلها حتى لا نضغط شيئًا", "ضغط الشعار حتى تختفي حروف اسم المدرسة"],
    wrongEn: ["Upload every file at the largest size available", "Ban all images so nothing needs compressing", "Crush the logo until the school name vanishes"],
  },
  {
    id: "4-1-f10",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "بعد البث المباشر للتخرج بقيت صور الكاميرا الأصلية على صفحة الأخبار لأيام.",
    sceneEn: "After the graduation livestream, the camera-original stills sat on the news page for days.",
    claimAr: "أبقِ صورة واضحة بحجم الويب لا أرشيف الاستوديو.",
    claimEn: "Keep a sharp still at web size, not the studio archive.",
    whyAr: "الصفحة تحتاج وجهًا واضحًا لا ملف آلة التصوير كاملًا.",
    whyEn: "The page needs a clear face, not the camera's full archive file.",
    termAr: "ضغط الملفات",
    termEn: "Compression",
    wrongAr: ["اترك الأصول لأن الحفل لن يتكرر", "احذف الصور وضع صوت التصفيق فقط", "ضاعف العرض حتى تنزلق الصفحة جانبًا"],
    wrongEn: ["Leave the originals because the ceremony will not repeat", "Delete the photos and keep only applause audio", "Double the width so the page slides sideways"],
  },
  {
    id: "4-1-f11",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "صور معرض العلوم نُشرت بلا وصف، وزميل يستخدم قارئ شاشة سمع كلمة صورة فقط.",
    sceneEn: "Science-fair photos went up with no description, and a classmate using a screen reader heard only the word image.",
    claimAr: "اكتب نصًا بديلًا يذكر المشروع واسم الطالب.",
    claimEn: "Write alt text that names the project and the student.",
    whyAr: "النص البديل واجب لمن لا يرى الصورة لا زينة اختيارية.",
    whyEn: "Alt text is a duty for someone who cannot see the photo, not optional decoration.",
    termAr: "النص البديل",
    termEn: "Alt text",
    wrongAr: ["اترك الحقل فارغًا فالصورة تشرح نفسها", "اكتب كلمة ديكور في كل الصور", "عوّض الغياب بتكبير الملف"],
    wrongEn: ["Leave the field empty because the photo explains itself", "Write the word decor on every image", "Make up for the gap by enlarging the file"],
  },
  {
    id: "4-1-f12",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "صورة معلمة الرياضيات على صفحة الهيئة حُفظ نصها البديل باسم الملف IMG_4401.",
    sceneEn: "The maths teacher's photo on the staff page used the filename IMG_4401 as its alt text.",
    claimAr: "استبدل اسم الملف بوصف حقيقي للشخص والسياق.",
    claimEn: "Replace the filename with a real description of the person and the context.",
    whyAr: "اسم الملف ليس وصفًا يفهمه قارئ الشاشة.",
    whyEn: "A filename is not a description a screen reader can understand.",
    termAr: "النص البديل",
    termEn: "Alt text",
    wrongAr: ["أبقِ رقم الكاميرا فهو أدق", "انسخ اسم الملف في العنوان أيضًا", "احذف الصورة حتى لا تحتاج وصفًا"],
    wrongEn: ["Keep the camera number because it is more precise", "Copy the filename into the heading as well", "Delete the photo so no description is needed"],
  },
  {
    id: "4-1-f13",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "شريط زينة بين فقرات نشرة الأسبوع كُتب له نص بديل قصيدة طويلة لا علاقة لها بالمحتوى.",
    sceneEn: "A decorative strip between weekly-bulletin paragraphs got a long poem as alt text with no link to the content.",
    claimAr: "اترك الزينة الصرفة بلا وصف مزعج، وصف ما يحمل معنى فقط.",
    claimEn: "Leave pure decoration without noisy description, and describe only images that carry meaning.",
    whyAr: "النص البديل ينقل المعنى لا يضيف ضجيجًا على القارئ.",
    whyEn: "Alt text should carry meaning, not add noise for the reader.",
    termAr: "النص البديل",
    termEn: "Alt text",
    wrongAr: ["أطل الوصف حتى لو كانت الزينة بلا رسالة", "كرر القصيدة في كل فاصل", "حوّل الزينة إلى فيديو ليُسمع الصوت"],
    wrongEn: ["Lengthen the description even if the strip has no message", "Repeat the poem on every divider", "Turn the decoration into a video so sound is heard"],
  },
  {
    id: "4-1-f14",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "صفحة المفقودات عرضت حقائب بلا تسمية، والأوصاف بقيت في دفتر الحارس فقط.",
    sceneEn: "The lost-and-found page showed unlabeled bags, and the descriptions stayed in the guard's notebook.",
    claimAr: "أضف نصًا بديلًا يذكر اللون والنوع ومكان العثور.",
    claimEn: "Add alt text that states the colour, the item, and where it was found.",
    whyAr: "من غير وصف لن يعرف زميل يستخدم قارئًا ماذا ضاع.",
    whyEn: "Without a description, a classmate using a reader never learns what was lost.",
    termAr: "النص البديل",
    termEn: "Alt text",
    wrongAr: ["اكتفِ بالصورة الملونة فهي كافية", "اكتب كلمة حقيبة على المئة صورة", "انشر دفتر الحارس كمسح ضوئي ثقيل بلا نص"],
    wrongEn: ["Rely on the colour photo because it is enough", "Write the word bag on all one hundred photos", "Publish a heavy scan of the guard's notebook with no text"],
  },
  {
    id: "4-1-f15",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "المدير قال في الاجتماع إن النص البديل تجميل نضيفه إن بقي وقت قبل الحفل.",
    sceneEn: "The principal said in a meeting that alt text is polish we add if time remains before the concert.",
    claimAr: "عامل النص البديل واجب نشر لا لمسة أخيرة.",
    claimEn: "Treat alt text as a publishing duty, not a last flourish.",
    whyAr: "الإتاحة جزء من إطلاق الصفحة لا معروف يُؤجَّل.",
    whyEn: "Access is part of launching the page, not a favour you postpone.",
    termAr: "النص البديل",
    termEn: "Alt text",
    wrongAr: ["أجّله إلى ما بعد الحفل دائمًا", "عوّضه بضغط أقوى للملف", "اكتفِ بعنوان الموقع بدل وصف الصورة"],
    wrongEn: ["Always postpone it until after the concert", "Replace it with heavier file compression", "Use only the site title instead of describing the image"],
  },
  {
    id: "4-1-f16",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "قائمة كانتين اليوم ظهرت كمسح ضبابي لصورة ورقة مكتوبة بخط اليد.",
    sceneEn: "Today's canteen menu appeared as a blurry scan of a handwritten sheet.",
    claimAr: "أعد القائمة نصًا أو صورة حادة خفيفة تُقرأ على الهاتف.",
    claimEn: "Retype the menu as text or a sharp light image that reads on a phone.",
    whyAr: "الموازنة بين الوضوح والحجم تعني أسماء أكل مقروءة تُحمَّل بسرعة.",
    whyEn: "Quality versus size means readable food names that still load quickly.",
    termAr: "الدقة مقابل الحجم",
    termEn: "Quality vs size",
    wrongAr: ["ارفع المسح بأعلى دقة متاحة ولو غابت الأسماء", "بدّل القائمة بمقطع فيديو للمطبخ", "صغّر الصورة حتى تختفي الأسعار"],
    wrongEn: ["Upload the scan at the highest resolution even if names vanish", "Replace the menu with a kitchen video", "Shrink the image until the prices disappear"],
  },
  {
    id: "4-1-f17",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "خريطة الفناء نُشرت بعرض أربعة آلاف بكسل بينما شاشة هاتف الطالب لا تعرض إلا جزءًا صغيرًا.",
    sceneEn: "The yard map was published four thousand pixels wide, while a student's phone shows only a sliver.",
    claimAr: "قدّم خريطة بحجم شاشة الهاتف.",
    claimEn: "Serve a map sized for the phone screen.",
    whyAr: "بكسلات تزيد على الشاشة تهدر الوقت ولا تضيف معنى.",
    whyEn: "Pixels beyond the screen waste time and add no meaning.",
    termAr: "الدقة مقابل الحجم",
    termEn: "Quality vs size",
    wrongAr: ["أبقِ العرض الكامل ليبدو أدق على الورق", "قصّ المعالم حتى تبقى بوابة واحدة", "حوّل الخريطة إلى صوت خطوات فقط"],
    wrongEn: ["Keep the full width so it looks sharper on paper", "Crop the landmarks until one gate remains", "Turn the map into footstep audio only"],
  },
  {
    id: "4-1-f18",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "تعليمات تجريب الإخلاء دارت كصورة متحركة ثقيلة لا تكتمل على شبكة الطوارئ.",
    sceneEn: "Evacuation-drill steps looped as a heavy animated image that never finished on the emergency network.",
    claimAr: "استخدم ملصقًا خفيفًا ثابتًا مع خطوات مكتوبة قصيرة.",
    claimEn: "Use a light static poster plus short written steps.",
    whyAr: "في الطوارئ السرعة والوضوح أهم من حلقة ثقيلة.",
    whyEn: "In an emergency, speed and clarity beat a heavy loop.",
    termAr: "الدقة مقابل الحجم",
    termEn: "Quality vs size",
    wrongAr: ["أطل الحركة حتى يبدو الإنذار أفخم", "احذف الخطوات المكتوبة واعتمد الوميض", "ارفع الملصق بدقة الطباعة الجدارية"],
    wrongEn: ["Lengthen the motion so the alarm looks grander", "Delete the written steps and rely on the flicker", "Upload the poster at wall-print resolution"],
  },
  {
    id: "4-1-f19",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "رسم تغيّر درجات الصف عبر الشهور كان لقطة شاشة لجدول حسابات بخطوط الشبكة ظاهرة.",
    sceneEn: "A chart of class scores over months was a screenshot of a spreadsheet with gridlines showing.",
    claimAr: "أعد الرسم بدقة الويب أو ضع جدولًا حقيقيًا للأرقام.",
    claimEn: "Rebuild the chart at web resolution or use a real table for the numbers.",
    whyAr: "لقطة الجدول ثقيلة وضعيفة؛ الوسيط يجب أن يُظهر التغيّر لا شبكة الخلايا.",
    whyEn: "A sheet screenshot is heavy and weak; the medium should show the change, not the cell grid.",
    termAr: "الدقة مقابل الحجم",
    termEn: "Quality vs size",
    wrongAr: ["كبّر اللقطة حتى تُقرأ أرقام الصفوف البعيدة", "بدّل الرسم بأيقونة نجمة واحدة", "غطِّ الصفحة بخلفية متحركة للدرجات"],
    wrongEn: ["Enlarge the screenshot until distant row numbers are readable", "Replace the chart with a single star icon", "Cover the page with a moving scores background"],
  },
  {
    id: "4-1-f20",
    lessonId: "4-1",
    chapterId: "4",
    sceneAr: "دليل الطالب الجديد فيديو صامت بدقة سينمائية طوله ثماني دقائق عن باب الإدارة.",
    sceneEn: "The new-student guide is an eight-minute silent cinema-resolution video of the office door.",
    claimAr: "قدّم مقطعًا قصيرًا مضغوطًا أو صفحة خطوات مكتوبة.",
    claimEn: "Offer a short compressed clip or a page of written steps.",
    whyAr: "الفيلم الصامت الضخم يؤخر مهمة اليوم الأول من غير أن يزيد الفهم.",
    whyEn: "A huge silent film delays the first-day task without adding understanding.",
    termAr: "الدقة مقابل الحجم",
    termEn: "Quality vs size",
    wrongAr: ["أبقِ الدقة السينمائية ليبدو الدليل فاخرًا", "احذف الخطوات واعتمد الباب المتحرك فقط", "ارفع النسخة نفسها ثلاث مرات بأحجام أكبر"],
    wrongEn: ["Keep cinema resolution so the guide looks luxurious", "Delete the steps and rely on the moving door alone", "Upload the same cut three times at larger sizes"],
  },
  {
    id: "4-2-f01",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "تسجيل الحضور الصباحي يمر بست قوائم قبل أن يظهر زر حاضر.",
    sceneEn: "Morning attendance travels through six menus before a Present button appears.",
    claimAr: "اجعل مهمة الحضور أقرب مسار وأقل خطوات.",
    claimEn: "Make attendance the shortest path with the fewest steps.",
    whyAr: "تجربة المستخدم تُقاس بوصول الطالب لهدفه بسهولة لا بعدد القوائم.",
    whyEn: "UX is measured by how easily the student reaches the goal, not by how many menus exist.",
    termAr: "تجربة المستخدم UX",
    termEn: "UX",
    wrongAr: ["أضف قائمة سابعة لتبدو الرحلة أغنى", "اخفِ الزر حتى يكتشفه المجتهد", "اهتم بلون الشعار واترك المسار كما هو"],
    wrongEn: ["Add a seventh menu so the journey feels richer", "Hide the button so only a keen student finds it", "Worry about the logo colour and leave the path as it is"],
  },
  {
    id: "4-2-f02",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "ولي الأمر يريد إيصال عذر غياب فيجد نفسه في نادي الشطرنج ثم في أخبار الحفل.",
    sceneEn: "A parent wants to send an absence note and lands in the chess club, then in concert news.",
    claimAr: "ارسم رحلة واضحة من الهدف إلى النموذج من غير طرق جانبية.",
    claimEn: "Draw a clear journey from the goal to the form with no side roads.",
    whyAr: "الرحلة الناجحة توصل المهمة لا المعرض.",
    whyEn: "A successful journey delivers the task, not the gallery.",
    termAr: "تجربة المستخدم UX",
    termEn: "UX",
    wrongAr: ["أبقِ التحويلات لتزيد وقت التصفح", "ابدأ الحفل قبل نموذج العذر", "وجّه الزائر بصورة النادي فقط"],
    wrongEn: ["Keep the detours so browsing time rises", "Start the concert before the excuse form", "Orient the visitor with only the club photo"],
  },
  {
    id: "4-2-f03",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "بعد تسجيل الدخول يُطلب من الطالبة إعادة إدخال الاسم في كل صفحة نادٍ.",
    sceneEn: "After login the student is asked to retype her name on every club page.",
    claimAr: "احمل الهوية عبر الرحلة ولا تكرر السؤال بلا سبب.",
    claimEn: "Carry identity through the journey and do not repeat the question without a reason.",
    whyAr: "تكرار البيانات يقطع سهولة الرحلة ويوحي أن النظام لا يتذكر المستخدم.",
    whyEn: "Repeating data breaks journey ease and suggests the system does not remember the user.",
    termAr: "تجربة المستخدم UX",
    termEn: "UX",
    wrongAr: ["كرر الاسم ليبدو أكثر رسمية", "اطلب رقم الجلوس في كل نقرة", "امسح الجلسة بعد كل نادٍ عمدًا"],
    wrongEn: ["Repeat the name so it feels more official", "Ask for the seat number on every click", "Clear the session after every club on purpose"],
  },
  {
    id: "4-2-f04",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "زميل صامت يراقب شاشة رسوم الرحلات ولا يجد زر السداد حتى يغلق الصفحة.",
    sceneEn: "A silent classmate watches the trip-fees screen and never finds the pay button before closing the page.",
    claimAr: "اختبر مع زميل صامت وسجّل أين يتوه ثم قرّب الزر.",
    claimEn: "Test with a silent classmate, note where they get lost, then bring the button closer.",
    whyAr: "اختبار الزميل الصامت يكشف ضياع الرحلة قبل أن يخسر المدرسة السداد.",
    whyEn: "The silent-classmate test reveals a lost journey before the school loses the payment.",
    termAr: "تجربة المستخدم UX",
    termEn: "UX",
    wrongAr: ["غيّر الألوان كل دقيقة أثناء المشاهدة", "اخفِ الزر الرئيسي ليزيد التركيز", "أزل العناوين حتى يعتمد على الحدس"],
    wrongEn: ["Change colours every minute during the watch", "Hide the main button to increase focus", "Remove headings so they rely on instinct"],
  },
  {
    id: "4-2-f05",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "مصمم الصفحة فخور بتدرج البنفسجي بينما المعلمة لا تجد رابط جدول الحصص.",
    sceneEn: "The page designer is proud of a purple gradient while the teacher cannot find the timetable link.",
    claimAr: "قدّم وضوح المهمة على إعجاب لقطة الشاشة.",
    claimEn: "Put task clarity ahead of screenshot admiration.",
    whyAr: "الموقع الناجح يُفهم في ثانية لا الذي يُعجب في صورة فقط.",
    whyEn: "A successful site is understood in a second, not only admired in a picture.",
    termAr: "تجربة المستخدم UX",
    termEn: "UX",
    wrongAr: ["أطل التدرج حتى لو اختفى الجدول", "قِس النجاح بعدد الإعجابات على اللون", "انقل الجدول إلى تذييل بلا رابط"],
    wrongEn: ["Lengthen the gradient even if the timetable vanishes", "Score success by likes on the colour", "Move the timetable to a footer with no link"],
  },
  {
    id: "4-2-f06",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "زر إلغاء الحجز في ملعب المدرسة نفس لون زر تأكيد الحجز ونفس شكله.",
    sceneEn: "Cancel booking on the school pitch uses the same colour and shape as Confirm booking.",
    claimAr: "ميّز عنصر التحكم الرئيسي عن الإلغاء بلون وتسمية واضحين.",
    claimEn: "Set the primary control apart from cancel with a clear colour and label.",
    whyAr: "واجهة المستخدم هي ما يلمسه الطالب؛ التشابه يصنع ضغطًا خاطئًا.",
    whyEn: "UI is what the student touches; look-alike controls cause a wrong press.",
    termAr: "واجهة المستخدم UI",
    termEn: "UI",
    wrongAr: ["وحّد اللون ليبدو التصميم أنيقًا", "احذف التسميات واعتمد الشكل فقط", "بدّل مكان الزرين عشوائيًا كل يوم"],
    wrongEn: ["Unify the colour so the design looks elegant", "Delete the labels and rely on shape alone", "Swap the two buttons at random every day"],
  },
  {
    id: "4-2-f07",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "أزرار حضور الحصة على الهاتف أصغر من أن تُلمس بإصبع في الفسحة.",
    sceneEn: "Period-attendance buttons on the phone are too small to tap with a finger during break.",
    claimAr: "كبّر أهداف اللمس حتى تصح الضغطة الأولى.",
    claimEn: "Enlarge tap targets so the first press is correct.",
    whyAr: "عناصر الواجهة تُصمَّم لليد لا للصورة المصغّرة على الشاشة الكبيرة.",
    whyEn: "Interface controls are designed for a hand, not for a thumbnail on a wide screen.",
    termAr: "واجهة المستخدم UI",
    termEn: "UI",
    wrongAr: ["صغّر الأزرار لتسع الصفحة إعلاناتًا", "اطلب قلمًا دقيقًا من كل طالب", "انقل الأزرار خارج الشاشة للجمال"],
    wrongEn: ["Shrink the buttons so the page fits more ads", "Ask every student for a fine stylus", "Move the buttons off-screen for beauty"],
  },
  {
    id: "4-2-f08",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "أيقونة الحفظ في سجل الدرجات نجمة مرة وقرص مرة وسحابة مرة في الصفحات الثلاث.",
    sceneEn: "The save icon in the marks book is a star on one page, a disk on the next, and a cloud on the third.",
    claimAr: "وحّد أيقونة الفعل نفسه في كل الصفحات.",
    claimEn: "Use the same icon for the same action on every page.",
    whyAr: "اتساق عناصر الواجهة يمنع إعادة تعلّم الزر في كل شاشة.",
    whyEn: "Consistent UI controls stop the user from relearning the button on every screen.",
    termAr: "واجهة المستخدم UI",
    termEn: "UI",
    wrongAr: ["نوّع الأيقونات حتى لا يملّ المشاهد", "اخفِ الحفظ داخل قائمة من عشر طبقات", "بدّل المعنى كل أسبوع ليبقى مفاجئًا"],
    wrongEn: ["Vary the icons so the viewer does not get bored", "Hide save inside a ten-layer menu", "Change the meaning every week so it stays surprising"],
  },
  {
    id: "4-2-f09",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "صندوق البحث عن كتاب المكتبة مدفون في ذيل الصفحة تحت شعار الرعاة.",
    sceneEn: "The library book search box is buried in the footer under the sponsors' logos.",
    claimAr: "ضع حقل البحث حيث تبدأ العين مهمة الاستعارة.",
    claimEn: "Put the search field where the eye starts the borrowing task.",
    whyAr: "عنصر الواجهة الأساسي يعيش قرب المهمة لا تحت الإعلان.",
    whyEn: "The primary UI control lives next to the task, not under an advert.",
    termAr: "واجهة المستخدم UI",
    termEn: "UI",
    wrongAr: ["أبقِ البحث في الذيل ليبقى الشعار بطلاً", "استبدل الحقل بلغز أيكنات", "احذف البحث واطلب رقم الرف شفهيًا"],
    wrongEn: ["Keep search in the footer so the logo stays the hero", "Replace the field with an icon riddle", "Delete search and ask for the shelf number out loud"],
  },
  {
    id: "4-2-f10",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "صفحة النوادي تستخدم مرة أرسل ومرة تم ومرة حسنا لذات زر الإرسال.",
    sceneEn: "The clubs page uses Send, Done, and OK on different screens for the same submit action.",
    claimAr: "سمِّ زر الإرسال تسمية واحدة ثابتة.",
    claimEn: "Give the submit button one stable label.",
    whyAr: "اختلاف تسمية التحكم نفسه يربك اليد قبل أن يربك العين.",
    whyEn: "Changing the label of the same control confuses the hand before it confuses the eye.",
    termAr: "واجهة المستخدم UI",
    termEn: "UI",
    wrongAr: ["غيّر الكلمة كل صفحة لكسر الملل", "احذف النص واترك الزر بلا كلمة", "اكتب جملة طويلة داخل الزر"],
    wrongEn: ["Change the word on every page to break boredom", "Delete the text and leave the button wordless", "Write a long sentence inside the button"],
  },
  {
    id: "4-2-f11",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "إعلان الكافتيريا أكبر من زر سجّل حضورك في رأس الصفحة الرئيسية.",
    sceneEn: "The cafeteria advert is larger than the Mark your attendance button in the homepage header.",
    claimAr: "اجعل الهدف الأول أكبر أوضح شيء تراه العين.",
    claimEn: "Make the first goal the largest, clearest thing the eye sees.",
    whyAr: "التسلسل البصري يقول أين تبدأ وأين تضغط قبل أن تقرأ الإعلان.",
    whyEn: "Visual hierarchy says where to start and where to click before you read an advert.",
    termAr: "التسلسل البصري",
    termEn: "Visual hierarchy",
    wrongAr: ["كبّر الإعلان حتى يختفي الحضور", "ساوِ كل العناصر حتى لا يبرز شيء", "اخفِ الزر تحت صورة الطعام"],
    wrongEn: ["Enlarge the advert until attendance disappears", "Equalise every element so nothing stands out", "Hide the button under the food photo"],
  },
  {
    id: "4-2-f12",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "حالة متأخر وحاضر في كشف الفصل تُفرَّق باللون الأحمر والأخضر فقط من غير كلمة.",
    sceneEn: "Late and Present in the class roll are split only by red and green, with no words.",
    claimAr: "أضف تسمية مكتوبة إلى اللون حتى يُفهم المعنى بلا تخمين.",
    claimEn: "Add a written label to the colour so the meaning is not a guess.",
    whyAr: "التسلسل البصري يعتمد على الحجم والموضع والكلمة لا على اللون وحده.",
    whyEn: "Visual hierarchy uses size, place, and words, not colour alone.",
    termAr: "التسلسل البصري",
    termEn: "Visual hierarchy",
    wrongAr: ["اكتفِ باللون فهو أسرع للمصمم", "أزل العناوين وزد التشبع", "بدّل الأحمر والأخضر يوميًا"],
    wrongEn: ["Rely on colour alone because it is faster for the designer", "Remove headings and raise the saturation", "Swap red and green every day"],
  },
  {
    id: "4-2-f13",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "صورة الملعب البطل تدفع نموذج حجز الحصة إلى أسفل الشاشة على الهاتف.",
    sceneEn: "A hero photo of the pitch pushes the period-booking form below the fold on a phone.",
    claimAr: "قدّم النموذج فوق الزينة حتى تبدأ العين بالمهمة.",
    claimEn: "Put the form above the decoration so the eye starts with the task.",
    whyAr: "ما يظهر أولًا يحدد أين تضغط؛ الصورة الواسعة تؤجّل الفعل.",
    whyEn: "What appears first decides where you click; a wide photo delays the action.",
    termAr: "التسلسل البصري",
    termEn: "Visual hierarchy",
    wrongAr: ["أطل الصورة حتى يصل النموذج في النشرة التالية", "كرر الملعب ثلاث مرات فوق الزر", "اخفِ العنوان لأن الصورة تغني"],
    wrongEn: ["Lengthen the photo so the form arrives in the next newsletter", "Repeat the pitch three times above the button", "Hide the heading because the photo is enough"],
  },
  {
    id: "4-2-f14",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "قائمة الموقع تقفز من اليمين إلى الأعلى إلى أيقونة مخفية بعد تسجيل الدخول.",
    sceneEn: "The site menu jumps from the right, to the top, to a hidden icon after login.",
    claimAr: "ثبّت مكان القائمة وشكلها في كل الصفحات.",
    claimEn: "Keep the menu in the same place and shape on every page.",
    whyAr: "الاتساق في موضع القائمة أهم من مفاجأة تخطيط جديد بعد الدخول.",
    whyEn: "A consistent menu place beats a surprise layout after login.",
    termAr: "التسلسل البصري",
    termEn: "Visual hierarchy",
    wrongAr: ["غيّر المكان كل شاشة لكسر الملل", "اخفِ القائمة بعد الدخول لتبدو أنظف", "وزّع الروابط داخل الصور فقط"],
    wrongEn: ["Move it on every screen to break boredom", "Hide the menu after login so the page looks cleaner", "Scatter the links only inside photos"],
  },
  {
    id: "4-2-f15",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "صفحة دليل المختبر بلا مسار تنقل، والطالب لا يعرف هل هو في السلامة أم في الحجوزات.",
    sceneEn: "The lab-guide page has no breadcrumb, and the student cannot tell whether they are in safety or bookings.",
    claimAr: "أظهر مسار الصفحة حتى تعرف العين أين هي وإلى أين تعود.",
    claimEn: "Show the page path so the eye knows where it is and how to go back.",
    whyAr: "التسلسل البصري يشمل موضعك في الموقع لا حجم الزر فقط.",
    whyEn: "Visual hierarchy includes your place in the site, not only button size.",
    termAr: "التسلسل البصري",
    termEn: "Visual hierarchy",
    wrongAr: ["احذف المسار ليبدو التصميم حديثًا", "اعتمد لون الخلفية ليدل على القسم", "أظهر المسار في تذييل بلون باهت"],
    wrongEn: ["Delete the path so the design looks modern", "Let background colour hint at the section", "Show the path in a faint footer"],
  },
  {
    id: "4-2-f16",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "تحميل جدول الحصص يحتاج تسع نقرات عبر النشرات القديمة.",
    sceneEn: "Downloading the timetable takes nine clicks through old newsletters.",
    claimAr: "اختصر التحميل إلى أقل نقرات توصل الملف.",
    claimEn: "Cut the download to the fewest clicks that deliver the file.",
    whyAr: "عدد النقرات يقيس كم خطوة تلزم حتى تتم المهمة.",
    whyEn: "Click count measures how many steps the user needs to finish the task.",
    termAr: "عدد النقرات",
    termEn: "Click count",
    wrongAr: ["أضف نشرة عاشرة قبل الملف", "اطلب تأكيدًا بعد كل نقرة", "فرّق الجدول على صفحات يوم بيوم"],
    wrongEn: ["Add a tenth newsletter before the file", "Ask for confirmation after every click", "Split the timetable across a page per day"],
  },
  {
    id: "4-2-f17",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "أيقونة البيت في تطبيق الصف تفتح صفحة نادي التصوير لا الصفحة الرئيسية.",
    sceneEn: "The home icon in the class app opens the photography-club page, not the home page.",
    claimAr: "اجعل أيقونة البيت تعيد إلى بداية الرحلة في خطوة واحدة.",
    claimEn: "Make the home icon return to the start of the journey in one step.",
    whyAr: "نقرة البيت وُجدت لتقصّر الطريق لا لتفتح ناديًا بالمصادفة.",
    whyEn: "The home click exists to shorten the path, not to open a club by surprise.",
    termAr: "عدد النقرات",
    termEn: "Click count",
    wrongAr: ["أبقِ المفاجأة فهي تُعلّم الاستكشاف", "اطلب ثلاث نقرات للعودة إلى البيت", "أزل الأيقونة لأن القائمة تكفي"],
    wrongEn: ["Keep the surprise because it teaches exploration", "Require three clicks to return home", "Remove the icon because the menu is enough"],
  },
  {
    id: "4-2-f18",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "تعليمات تسليم المشروع مخفية داخل تلميح يظهر فقط إن ثبّت المؤشر عشر ثوان.",
    sceneEn: "Project-handover instructions hide in a tooltip that appears only if the pointer rests for ten seconds.",
    claimAr: "أظهر خطوات التسليم في الصفحة من غير انتظار تلميح.",
    claimEn: "Show the handover steps on the page without waiting for a tooltip.",
    whyAr: "كل ثانية بحث هي نقرة ضائعة على الطريق إلى التسليم.",
    whyEn: "Every second of hunting is a wasted click on the road to handover.",
    termAr: "عدد النقرات",
    termEn: "Click count",
    wrongAr: ["أطل زمن التلميح ليبدو أذكى", "وزّع كل خطوة في نافذة منبثقة جديدة", "اخفِ الزر حتى يكتمل التلميح"],
    wrongEn: ["Lengthen the tooltip delay so it feels smarter", "Put each step in a new pop-up", "Hide the button until the tooltip finishes"],
  },
  {
    id: "4-2-f19",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "نافذة استطلاع الرأي تغطي زر تأكيد الحضور ولا تُغلق إلا بعد خمس خيارات.",
    sceneEn: "An opinion-poll modal covers the confirm-attendance button and closes only after five choices.",
    claimAr: "لا تحجب المهمة بنافذة؛ اجعل الاستطلاع بعد إتمام الحضور أو جانبًا.",
    claimEn: "Do not block the task with a modal; run the poll after attendance or to the side.",
    whyAr: "كل طبقة فوق الزر تزيد النقرات قبل الهدف الحقيقي.",
    whyEn: "Each layer over the button adds clicks before the real goal.",
    termAr: "عدد النقرات",
    termEn: "Click count",
    wrongAr: ["أطل الاستطلاع قبل أي حضور", "كرر النافذة إن أُغلقت سهوًا", "اربط الإغلاق بمشاهدة فيديو"],
    wrongEn: ["Lengthen the poll before any attendance", "Repeat the modal if it is closed by accident", "Tie closing it to watching a video"],
  },
  {
    id: "4-2-f20",
    lessonId: "4-2",
    chapterId: "4",
    sceneAr: "الطالب يحتاج لوحة مفاتيح للوصول إلى زر الحضور لأن المربع لا يستقبل التركيز.",
    sceneEn: "A student needs a keyboard to reach attendance, but the control never receives focus.",
    claimAr: "اجعل عنصر التحكم قابلًا للوصول بلوحة المفاتيح في أقل خطوات.",
    claimEn: "Make the control reachable by keyboard in the fewest steps.",
    whyAr: "الرحلة القصيرة تشمل من لا يستخدم فأرة لا عدد النقرات للفأرة وحدها.",
    whyEn: "A short journey includes someone with no mouse, not only mouse-click counts.",
    termAr: "عدد النقرات",
    termEn: "Click count",
    wrongAr: ["صمّم للفأرة فقط فهي الأسرع للمصمم", "اطلب عشر ضغطات تاب قبل الزر", "اخفِ التركيز لأنه يشوّه الشكل"],
    wrongEn: ["Design for the mouse only because it is faster for the designer", "Require ten Tab presses before the button", "Hide focus because it spoils the look"],
  },
  {
    id: "4-3-f01",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "لجنة الموقع اختارت الصفحة الرئيسية الأجمل بالتصويت الداخلي من غير أن يجرّب أحد تسجيل حضور.",
    sceneEn: "The site committee picked the prettier homepage by an internal vote without anyone trying to mark attendance.",
    claimAr: "قيّم هل تُنجز المهمة بسرعة وبلا أخطاء لا أي صورة أحلى.",
    claimEn: "Score whether the task finishes quickly with few errors, not which picture is prettier.",
    whyAr: "قابلية الاستخدام تُقاس بإتمام الهدف لا بذوق اللجنة.",
    whyEn: "Usability is measured by finishing the goal, not by the committee's taste.",
    termAr: "قابلية الاستخدام",
    termEn: "Usability",
    wrongAr: ["اعتمد تصويت الألوان وحده", "أجل التجربة حتى بعد الحفل", "احذف زر الحضور ليصفو التصميم"],
    wrongEn: ["Trust a colour vote alone", "Postpone the trial until after the concert", "Delete the attendance button so the design looks calmer"],
  },
  {
    id: "4-3-f02",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "نموذج دفع رسوم الرحلة يُرسل الطالب إلى صفحة خطأ مرتين قبل أن يُقبل التاريخ.",
    sceneEn: "The trip-fee form sends the student to an error page twice before it accepts the date.",
    claimAr: "احسب عدد الأخطاء وزمن الإصلاح وعدّ ذلك درجة الاستخدام.",
    claimEn: "Count the errors and the repair time and treat that as the usability score.",
    whyAr: "الأخطاء المتكررة دليل أن المهمة غير قابلة للاستخدام حتى لو بدا النموذج أنيقًا.",
    whyEn: "Repeated errors show the task is not usable even if the form looks neat.",
    termAr: "قابلية الاستخدام",
    termEn: "Usability",
    wrongAr: ["تجاهل الأخطاء إن بقي الشعار جميلًا", "زِد الحقول حتى يقلّ الضغط على التاريخ", "أخفِ رسالة الخطأ لأنها محرجة"],
    wrongEn: ["Ignore the errors if the logo stays beautiful", "Add more fields so the date is pressed less often", "Hide the error message because it is embarrassing"],
  },
  {
    id: "4-3-f03",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "تقييم بوابة المكتبة اكتفى بسؤال هل يعجبك الشكل؟ ولم يسأل هل استعرت كتابًا؟",
    sceneEn: "The library-portal review only asked do you like the look and never asked did you borrow a book.",
    claimAr: "أدخل إتمام الاستعارة ضمن درجة قابلية الاستخدام.",
    claimEn: "Put completing a borrow inside the usability score.",
    whyAr: "الاستخدام يعني إنجاز المهمة لا الإعجاب العابر بالشكل.",
    whyEn: "Usability means finishing the task, not a passing like of the look.",
    termAr: "قابلية الاستخدام",
    termEn: "Usability",
    wrongAr: ["اكتفِ بالإعجاب فهو أصدق شعورًا", "قِس عدد الخطوط الغريبة بدل الإعارة", "أجل سؤال المهمة إلى العام القادم"],
    wrongEn: ["Stop at likes because they feel more honest", "Measure fancy fonts instead of loans", "Postpone the task question until next year"],
  },
  {
    id: "4-3-f04",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "طالب يستخدم لوحة المفاتيح فقط عجز عن إنهاء حجز المختبر في الاختبار التجريبي.",
    sceneEn: "A student using only a keyboard failed to finish a lab booking in the practice test.",
    claimAr: "اجعل إتاحة الوصول بندًا في درجة التقييم لا ملحقًا بعد الدرجة.",
    claimEn: "Make accessibility a line in the score, not an appendix after the grade.",
    whyAr: "إن لم تُنجز المهمة بلا فأرة فالموقع غير قابل للاستخدام لفئة من الزملاء.",
    whyEn: "If the task cannot finish without a mouse, the site is not usable for a group of classmates.",
    termAr: "قابلية الاستخدام",
    termEn: "Usability",
    wrongAr: ["احسب الدرجة لمن يستخدم الفأرة فقط", "أضف الإتاحة في حاشية التقرير", "ارفع الدرجة لأن الألوان زاهية"],
    wrongEn: ["Score only people who use a mouse", "Add accessibility as a footnote in the report", "Raise the score because the colours are bright"],
  },
  {
    id: "4-3-f05",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "فريق التصميم احتفل بإطلاق صفحة الخريطة ثم اكتشف أن نصف الصف يفتح باب المبنى الخطأ.",
    sceneEn: "The design team celebrated the map-page launch, then found half the class opening the wrong building door.",
    claimAr: "أعد قياس وضوح الهدف بعد الإطلاق وعدّ الضياع فشل استخدام.",
    claimEn: "Measure goal clarity again after launch and count getting lost as a usability failure.",
    whyAr: "قابلية الاستخدام تُختبر في السلوك الحقيقي لا في حفل الإطلاق.",
    whyEn: "Usability is tested in real behaviour, not at the launch party.",
    termAr: "قابلية الاستخدام",
    termEn: "Usability",
    wrongAr: ["تجاهل الضياع فالاحتفال تم", "زد حجم الشعار فوق الخريطة", "امنع الأسئلة لأن الصفحة جديدة"],
    wrongEn: ["Ignore the lost students because the party already happened", "Enlarge the logo above the map", "Ban questions because the page is new"],
  },
  {
    id: "4-3-f06",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "نسختان من زر الحضور: سجّل الآن مقابل أنا هنا، والفريق يريد اختيار الأحلى بالذوق.",
    sceneEn: "Two attendance-button labels exist: Mark now versus I am here, and the team wants to pick the prettier one by taste.",
    claimAr: "قارن النسختين واختبر أيهما يرفع إتمام الحضور.",
    claimEn: "Compare the two versions and test which one raises completed attendance.",
    whyAr: "اختبار أ/ب يقيس أي نص يعمل لا أي نص يعجب المصمم.",
    whyEn: "An A/B test measures which wording works, not which wording the designer likes.",
    termAr: "اختبار أ/ب",
    termEn: "A/B test",
    wrongAr: ["اختر الأحلى من غير قياس", "انشر النسختين معًا في الصفحة نفسها", "احذف الموقع أسبوعًا حتى يحسم النقاش"],
    wrongEn: ["Pick the prettier one with no measurement", "Publish both labels on the same page at once", "Take the site down for a week until the argument ends"],
  },
  {
    id: "4-3-f07",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "اختبار قائمتين لبوابة أولياء الأمور أُجري على صديقين في الفسحة ثم أُعلن فوز البنفسجي.",
    sceneEn: "A test of two parent-portal menus ran on two friends at break, then purple was declared the winner.",
    claimAr: "اجمع عينة كافية وقِس الإتمام قبل إعلان فائز.",
    claimEn: "Collect an adequate sample and measure completion before naming a winner.",
    whyAr: "اختبار أ/ب بلا عدد كافٍ يعيد الذوق متخفيًا في رقم صغير.",
    whyEn: "An A/B test with too few people is taste wearing a tiny number.",
    termAr: "اختبار أ/ب",
    termEn: "A/B test",
    wrongAr: ["اعتمد الصديقين فهما أصدق رأيًا", "غيّر اللون كل يوم من غير تسجيل", "أعلن الفوز قبل أن يفتح أحد الصفحة"],
    wrongEn: ["Trust the two friends because their opinion is truer", "Change the colour every day with no log", "Announce the win before anyone opens the page"],
  },
  {
    id: "4-3-f08",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "نسخة أيقونات فقط ونسخة أيقونة مع كلمة لصفحة العيادة المدرسية تنتظران قرار الإطلاق.",
    sceneEn: "An icons-only version and an icon-plus-word version of the school clinic page are waiting for a launch decision.",
    claimAr: "وزّع الزوار بين النسختين وقِس من يصل إلى موعد الممرضة.",
    claimEn: "Split visitors between the versions and measure who reaches a nurse appointment.",
    whyAr: "المقارنة المقاسة تكشف أي واجهة توصل الموعد لا أيقونة أعجب الفريق.",
    whyEn: "A measured comparison shows which interface reaches the appointment, not which icon the team liked.",
    termAr: "اختبار أ/ب",
    termEn: "A/B test",
    wrongAr: ["أطلق الأيقونات لأنها تبدو أحدث", "ادمج النسختين في شاشة واحدة مربكة", "اسأل عن اللون المفضل بدل الموعد"],
    wrongEn: ["Ship icons-only because it looks newer", "Merge both versions into one confusing screen", "Ask about a favourite colour instead of the appointment"],
  },
  {
    id: "4-3-f09",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "خريطة حرارة النقرات تظهر أن أحدًا لا يلمس رابط جدول الامتحان، والفريق يجادل في درجة البنفسجي.",
    sceneEn: "A click heatmap shows nobody touching the exam-timetable link, while the team argues about the shade of purple.",
    claimAr: "استخدم الدليل المرصود لاختبار موضع الرابط لا للجدل اللوني.",
    claimEn: "Use the observed evidence to test the link's place, not to argue about colour.",
    whyAr: "اختبار أ/ب يتبع سلوك النقر لا انطباع اللون في الاجتماع.",
    whyEn: "An A/B test follows click behaviour, not a colour impression in a meeting.",
    termAr: "اختبار أ/ب",
    termEn: "A/B test",
    wrongAr: ["تجاهل الخريطة وناقش البنفسجي", "احذف الرابط لأنه ضعيف النقر", "غيّر كل الألوان دفعة واحدة بلا قياس"],
    wrongEn: ["Ignore the map and debate purple", "Delete the link because clicks are weak", "Change every colour at once with no measure"],
  },
  {
    id: "4-3-f10",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "بعد اختبار نسختين لصفحة الإذاعة بقي الفريق يعتمد أول رسم بياني لم يراجعوا محاوره.",
    sceneEn: "After testing two radio-club pages the team still trusted the first chart whose axes they never checked.",
    claimAr: "اقرأ مقياس الإتمام لا أول رسم يظهر في الشاشة.",
    claimEn: "Read the completion measure, not the first chart that appears on screen.",
    whyAr: "الاختبار يصدق القياس الصحيح لا أول صورة تُعرض.",
    whyEn: "The test believes the right measure, not the first picture on display.",
    termAr: "اختبار أ/ب",
    termEn: "A/B test",
    wrongAr: ["صدّق أول رسم تراه", "اختر النسخة من غير فتح الملف", "أبدل المحاور حتى تفوز النسخة المفضلة سلفًا"],
    wrongEn: ["Believe the first chart you see", "Pick a version without opening the file", "Swap the axes so the already-favourite version wins"],
  },
  {
    id: "4-3-f11",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "تسجيل الحضور استغرق أربع دقائق في النسخة القديمة وأربعين ثانية بعد تقريب الزر.",
    sceneEn: "Marking attendance took four minutes on the old version and forty seconds after the button was moved closer.",
    claimAr: "سجّل زمن المهمة قبل التعديل وبعده وعدّ الفرق دليل نجاح.",
    claimEn: "Record task time before and after the change and treat the difference as proof.",
    whyAr: "زمن المهمة يبيّن هل صار الهدف أقرب لا هل صار أجمل.",
    whyEn: "Task time shows whether the goal got closer, not whether it got prettier.",
    termAr: "زمن المهمة",
    termEn: "Task time",
    wrongAr: ["تجاهل الزمن إن أعجب المدير اللون", "قِس حجم الشعار بدل الثواني", "أطل الخطوات حتى يبدو النظام مهمًا"],
    wrongEn: ["Ignore the time if the principal liked the colour", "Measure logo size instead of seconds", "Lengthen the steps so the system feels important"],
  },
  {
    id: "4-3-f12",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "العثور على خريطة لجنة الامتحان احتاج دقيقتين من التمرير في أخبار الحفل.",
    sceneEn: "Finding the exam-hall map took two minutes of scrolling through concert news.",
    claimAr: "قِس الزمن حتى تظهر الخريطة وعدّ التمرير الطويل فشلًا.",
    claimEn: "Measure the time until the map appears and count long scrolling as a failure.",
    whyAr: "الزمن حتى الهدف معيار أوضح من انطباع أن الصفحة غنية.",
    whyEn: "Time-to-goal is a clearer standard than the impression that the page is rich.",
    termAr: "زمن المهمة",
    termEn: "Task time",
    wrongAr: ["أبقِ الأخبار فوق الخريطة لإطالة التصفح", "احذف قياس الزمن لأنه يضغط المصمم", "اعتمد شعور الغنى بدل الثواني"],
    wrongEn: ["Keep news above the map to lengthen browsing", "Drop the time measure because it pressures the designer", "Trust a feeling of richness instead of seconds"],
  },
  {
    id: "4-3-f13",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "اختبار لوحة المفاتيح وحده جعل حجز الملعب يستغرق ثلاثة أضعاف زمن الفأرة.",
    sceneEn: "A keyboard-only test made pitch booking take three times the mouse time.",
    claimAr: "أدخل زمن لوحة المفاتيح في الدرجة ولا تكتفِ بزمن الفأرة.",
    claimEn: "Put keyboard task time in the score and do not stop at mouse time.",
    whyAr: "إن طال الزمن بلا فأرة فالإتاحة جزء ناقص من القياس.",
    whyEn: "If time balloons without a mouse, accessibility is a missing part of the measure.",
    termAr: "زمن المهمة",
    termEn: "Task time",
    wrongAr: ["أبلغ زمن الفأرة فقط في التقرير", "ارفض لوحة المفاتيح لأنها أبطأ للمصمم", "احذف التركيز لتسريع الشكل"],
    wrongEn: ["Report only mouse time", "Reject the keyboard because it is slower for the designer", "Remove focus to speed the look"],
  },
  {
    id: "4-3-f14",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "منتقي تاريخ الرحلة يخطئ الشهر فيحذف الطالب الخانة ويعيد الكتابة أربع مرات.",
    sceneEn: "The trip date picker misses the month, so the student clears the field and retypes four times.",
    claimAr: "قِس زمن التصحيح وعدد الإعادة وعدّ ذلك كلفة المهمة.",
    claimEn: "Measure correction time and retries and count that as the cost of the task.",
    whyAr: "الزمن يشمل الإصلاح لا اللحظة الأولى التي بدا فيها الحقل جاهزًا.",
    whyEn: "Time includes repair, not only the first moment the field looked ready.",
    termAr: "زمن المهمة",
    termEn: "Task time",
    wrongAr: ["احسب أول نقرة فقط وتجاهل الإعادة", "أطل التقويم بثلاثة أشهر إضافية", "اخفِ خانة التاريخ حتى لا تُقاس"],
    wrongEn: ["Count only the first click and ignore retries", "Lengthen the calendar by three extra months", "Hide the date field so it cannot be measured"],
  },
  {
    id: "4-3-f15",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "نجاح النقرة الأولى على رابط نتائج الفصل كان واحدًا من عشرة في التجربة الصباحية.",
    sceneEn: "First-click success on the class-results link was one in ten in the morning trial.",
    claimAr: "سجّل زمن الوصول بعد النقرة الأولى الصحيحة وعدّ الفشل المبكر إنذارًا.",
    claimEn: "Log time-to-arrival after a correct first click and treat an early miss as a warning.",
    whyAr: "الزمن يطول إن ضاعت النقرة الأولى حتى لو اكتملت المهمة لاحقًا.",
    whyEn: "Time grows if the first click is missed even when the task finishes later.",
    termAr: "زمن المهمة",
    termEn: "Task time",
    wrongAr: ["تجاهل النقرة الأولى ما دامت النتيجة فُتحت يومًا ما", "قِس فقط زمن تحميل الشعار", "أزل الرابط لأن النسبة ضعيفة"],
    wrongEn: ["Ignore the first click as long as results open someday", "Measure only logo load time", "Remove the link because the rate is weak"],
  },
  {
    id: "4-3-f16",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "بعد ليلة اجتماع أولياء الأمور امتدح الجميع الألوان ثم همس ثلاثة بأنهم لم يجدوا درجات أبنائهم.",
    sceneEn: "After parents' evening everyone praised the colours, then three whispered they never found their children's marks.",
    claimAr: "اجمع رضا حقيقي عن وضوح المهمة لا مديح الألوان وحدها.",
    claimEn: "Collect real satisfaction about task clarity, not colour praise alone.",
    whyAr: "الرضا يعني أن التجربة واضحة ومريحة لا أن الشعار نال تصفيقًا.",
    whyEn: "Satisfaction means the experience felt clear and comfortable, not that the logo won applause.",
    termAr: "رضا المستخدم",
    termEn: "Satisfaction",
    wrongAr: ["اكتفِ بتصفيق الألوان في التقرير", "تجاهل الهمس لأنه غير رسمي", "ارفع درجة الرضا تلقائيًا بعد الحفل"],
    wrongEn: ["Put only colour applause in the report", "Ignore the whispers because they are unofficial", "Raise the satisfaction score automatically after the event"],
  },
  {
    id: "4-3-f17",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "استطلاع الرضا أعطي خمس نجوم بينما نصف الطلاب غادروا قبل إرسال استمارة النادي.",
    sceneEn: "The satisfaction survey gave five stars while half the students left before sending the club form.",
    claimAr: "اقرأ الرضا مع معدل الإتمام ولا تصدق النجوم وحدها.",
    claimEn: "Read satisfaction together with completion rate and do not trust stars alone.",
    whyAr: "شعور مريح مع مهمة ناقصة رضا ناقص حتى لو لمع الاستطلاع.",
    whyEn: "A comfortable feeling with an unfinished task is incomplete satisfaction even if the survey sparkles.",
    termAr: "رضا المستخدم",
    termEn: "Satisfaction",
    wrongAr: ["انشر النجوم واخفِ المغادرة", "احذف الاستمارة حتى ترتفع النجوم", "عاقب من غادر بخصم من الدرجة"],
    wrongEn: ["Publish the stars and hide the drop-off", "Delete the form so the stars rise", "Punish leavers by cutting their grade"],
  },
  {
    id: "4-3-f18",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "التقرير النهائي لموقع الحضور خلا من سؤال هل شعرت أن الخطوة واضحة؟ واكتفى بعدّ الزيارات.",
    sceneEn: "The final attendance-site report skipped did the step feel clear and only counted visits.",
    claimAr: "أضف سؤال رضا عن الوضوح إلى جانب عدد الزيارات.",
    claimEn: "Add a satisfaction question about clarity beside the visit count.",
    whyAr: "الزيارة بلا شعور بالوضوح لا تثبت أن التجربة مريحة.",
    whyEn: "A visit with no sense of clarity does not prove the experience was comfortable.",
    termAr: "رضا المستخدم",
    termEn: "Satisfaction",
    wrongAr: ["اكتفِ بعداد الزيارات فهو رقم صلب", "افترض الرضا إن لم يشتكِ أحد جهرًا", "استبدل السؤال بصورة للفريق"],
    wrongEn: ["Stop at the visit counter because it is a hard number", "Assume satisfaction if nobody complained out loud", "Replace the question with a team photo"],
  },
  {
    id: "4-3-f19",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "قائمة تقييم الموقع تجاهلت قارئ الشاشة ثم منحت الصفحة عشر درجات على الأناقة.",
    sceneEn: "The site score sheet skipped the screen reader, then awarded the page ten points for elegance.",
    claimAr: "أدخل اختبار الإتاحة في درجة الرضا والاستخدام معًا.",
    claimEn: "Put an accessibility test inside both the satisfaction and usability scores.",
    whyAr: "من يُستبعد من القراءة لن يرضى مهما لمع التصميم.",
    whyEn: "Someone excluded from reading will not be satisfied no matter how elegant the design looks.",
    termAr: "رضا المستخدم",
    termEn: "Satisfaction",
    wrongAr: ["أبقِ الإتاحة ملحقًا بعد الأناقة", "ارفع الدرجة إن مدح المدير الخط", "اختبر القارئ في السنة التالية"],
    wrongEn: ["Keep accessibility as an appendix after elegance", "Raise the score if the principal praised the font", "Test the reader next year"],
  },
  {
    id: "4-3-f20",
    lessonId: "4-3",
    chapterId: "4",
    sceneAr: "مصمم الصفحة قال إن ذوقه يكفي لأنه يستخدم الموقع كل صباح، ولم يسأل طالبًا واحدًا.",
    sceneEn: "The page designer said his taste is enough because he uses the site every morning, and he asked no student.",
    claimAr: "اجمع ملاحظات حقيقية من مستخدمين غير المصمم.",
    claimEn: "Collect real notes from users who are not the designer.",
    whyAr: "الرضا يُسأل عنه لا يُفترض من عادة من بنى الصفحة.",
    whyEn: "Satisfaction is asked for, not assumed from the habit of the person who built the page.",
    termAr: "رضا المستخدم",
    termEn: "Satisfaction",
    wrongAr: ["صدّق ذوق المصمم لأنه الأقرب للملف", "اسأل الفريق الداخلي فقط", "ألغِ الاستطلاع حتى لا تتعارض الآراء"],
    wrongEn: ["Trust the designer's taste because he is closest to the file", "Ask only the internal team", "Cancel the survey so opinions do not clash"],
  },
  {
    id: "4-4-f01",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "بعد فشل تسجيل يوم الرياضة قرر الفريق إعادة بناء الموقع كاملًا في عطلة نهاية الأسبوع.",
    sceneEn: "After sports-day registration failed, the team decided to rebuild the whole site over the weekend.",
    claimAr: "عد إلى الحلقة: صمّم إصلاحًا صغيرًا، اختبر، تعلّم، ثم حسّن.",
    claimEn: "Return to the loop: design a small fix, test, learn, then improve.",
    whyAr: "التكرار حلقة مغلقة لا هدم كامل بعد أول عثرة.",
    whyEn: "Iteration is a closed loop, not a total demolition after the first stumble.",
    termAr: "التكرار",
    termEn: "Iteration",
    wrongAr: ["اهدم الموقع كله لأن الشعور سيئ", "انشر قائمة أمنيات من ثلاثين فكرة دفعة واحدة", "انتظر الحظ من غير اختبار"],
    wrongEn: ["Demolish the whole site because the feeling is bad", "Ship a thirty-idea wish list in one go", "Wait for luck with no test"],
  },
  {
    id: "4-4-f02",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "في دورة واحدة غيّر الفريق لون الزر وموضعه ونصّه وخط الصفحة معًا.",
    sceneEn: "In one cycle the team changed the button colour, place, wording, and page font together.",
    claimAr: "غيّر شيئًا واحدًا في الدورة حتى يُعرف أي تعديل صنع الفرق.",
    claimEn: "Change one thing in the cycle so you know which edit made the difference.",
    whyAr: "إن تحركت أربعة عناصر معًا ضاع سبب التحسن أو التراجع.",
    whyEn: "If four elements move together, the cause of the gain or the drop is lost.",
    termAr: "التكرار",
    termEn: "Iteration",
    wrongAr: ["غيّر عشرين عنصرًا لتسريع الإحساس بالإنجاز", "لا تغيّر شيئًا وانتظر الأسبوع القادم", "أطل الدورة حتى تُنسى نقطة البداية"],
    wrongEn: ["Change twenty elements so progress feels faster", "Change nothing and wait until next week", "Lengthen the cycle until the starting point is forgotten"],
  },
  {
    id: "4-4-f03",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "بعد تقريب زر النادي انخفض زمن التسجيل عشرين ثانية، فاقترح أحدهم إضافة رسوم متحركة فورًا.",
    sceneEn: "After the club button was moved closer, signup time dropped twenty seconds, then someone proposed adding animation at once.",
    claimAr: "أغلق الدورة على دليل الزر أولًا ولا تخلط التحسين التالي قبل التثبيت.",
    claimEn: "Close the cycle on the button evidence first and do not mix the next improvement before it is locked.",
    whyAr: "كل دورة تتعلم من قياس واحد؛ الخلط يعيد قائمة الأمنيات.",
    whyEn: "Each cycle learns from one measurement; mixing returns the wish list.",
    termAr: "التكرار",
    termEn: "Iteration",
    wrongAr: ["أضف الحركة فورًا قبل تثبيت الدليل", "أرجع الزر البعيد لأن الصفحة صارت أهدأ", "افتح عشر دورات متوازية من غير سجل"],
    wrongEn: ["Add motion at once before the evidence is locked", "Move the button far again because the page feels calmer", "Open ten parallel cycles with no record"],
  },
  {
    id: "4-4-f04",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "الموقع نُشر يوم الأحد ثم لم يفتح أحد تقرير أين يغادر الزائر حتى امتحانات آخر الترم.",
    sceneEn: "The site launched on Sunday, then nobody opened a report of where visitors leave until end-of-term exams.",
    claimAr: "راقب المغادرة بعد النشر وأعد الحلقة قبل أن يبرد الأثر.",
    claimEn: "Watch drop-off after launch and restart the loop before the trail goes cold.",
    whyAr: "الموقع لا يُنشر مرة ويُنسى؛ التكرار يحتاج ملاحظة مستمرة.",
    whyEn: "A site is not published once and forgotten; iteration needs ongoing observation.",
    termAr: "التكرار",
    termEn: "Iteration",
    wrongAr: ["اترك الموقع حتى العام الدراسي التالي", "عدّ الإطلاق نهاية العمل", "أضف صفحات جديدة من غير النظر للمغادرة"],
    wrongEn: ["Leave the site until the next school year", "Treat launch as the end of the work", "Add new pages without looking at drop-off"],
  },
  {
    id: "4-4-f05",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "دورة أولى غيّرت تسمية الزر فقط، ودورة ثانية نقلت موضعه بعد ثبوت التسمية.",
    sceneEn: "The first cycle changed only the button label; the second moved its place after the label was proven.",
    claimAr: "سلسل الدورات: أثبت عنصرًا ثم انتقل إلى التالي.",
    claimEn: "Sequence the cycles: prove one element, then move to the next.",
    whyAr: "التكرار المنضبط يراكم الدليل لا يخلط الأسباب.",
    whyEn: "Disciplined iteration stacks evidence instead of mixing causes.",
    termAr: "التكرار",
    termEn: "Iteration",
    wrongAr: ["ارجع وغيّر التسمية والموضع معًا بأثر رجعي", "قف بعد الدورة الأولى إلى الأبد", "أدخل دورة ألوان بين القياس من غير هدف"],
    wrongEn: ["Go back and change the label and the place together in retrospect", "Stop forever after the first cycle", "Insert a colour cycle between measurements with no goal"],
  },
  {
    id: "4-4-f06",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "قبل برمجة استمارة النادي رسم الفريق مربعات على ورق وطلب من زملاء الضغط بإصبع.",
    sceneEn: "Before coding the club form the team drew boxes on paper and asked classmates to press with a finger.",
    claimAr: "اختبر نموذجًا أوليًا رخيصًا قبل البناء الكامل.",
    claimEn: "Test a cheap prototype before the full build.",
    whyAr: "النموذج الأولي يكشف الضياع وهو ما زال ورقة لا خادمًا غاليًا.",
    whyEn: "A prototype reveals getting lost while it is still paper, not an expensive server.",
    termAr: "النموذج الأولي",
    termEn: "Prototype",
    wrongAr: ["ابدأ بالنسخة النهائية الغالية فورًا", "ارسم الورق واحفظه من غير تجربة إصبع", "اشترِ أغلى برنامج تصميم قبل السؤال"],
    wrongEn: ["Start with the expensive final version at once", "Draw the paper and file it with no finger test", "Buy the dearest design tool before asking anyone"],
  },
  {
    id: "4-4-f07",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "نسخة قابلة للنقر من صفحة الرسوم صُنعت في حصة واحدة وجُرّبت على ثلاثة طلاب قبل قاعدة البيانات.",
    sceneEn: "A clickable fees-page version was made in one lesson and tried on three students before any database existed.",
    claimAr: "استخدم نموذجًا سريعًا للنقر حتى تتعلم المسار قبل الربط بالبيانات.",
    claimEn: "Use a fast clickable prototype to learn the path before wiring data.",
    whyAr: "اختبار المسار أرخص وهو هيكل فارغ من ربط الجداول.",
    whyEn: "Testing the path is cheaper while it is an empty shell than after tables are wired.",
    termAr: "النموذج الأولي",
    termEn: "Prototype",
    wrongAr: ["اربط القاعدة أولًا ثم اسأل عن المسار", "اعتبار النسخة النهائية أرخص لأنها مرة واحدة", "انسخ موقعًا مشهورًا بلا تجربة طلاب"],
    wrongEn: ["Wire the database first, then ask about the path", "Treat the final version as cheaper because it happens once", "Copy a famous site with no student trial"],
  },
  {
    id: "4-4-f08",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "مقطع قصير صوّر إصبع زميل وهو يبحث عن زر المكتبة على نموذج ورقي مُثبَّت على الحائط.",
    sceneEn: "A short clip filmed a classmate's finger hunting the library button on a paper prototype taped to the wall.",
    claimAr: "راجع نموذج الفيديو لترى أين توقف الإصبع قبل كتابة سطر كود.",
    claimEn: "Review the prototype video to see where the finger stopped before writing a line of code.",
    whyAr: "النموذج المرئي أرخص من إصلاح زر بُني في الخادم.",
    whyEn: "A visible prototype is cheaper than repairing a button already built on the server.",
    termAr: "النموذج الأولي",
    termEn: "Prototype",
    wrongAr: ["ابدأ بالكود لأن الفيديو غير رسمي", "ألصق الورق من غير تصوير الضياع", "اطبع النموذج على ورق مصقول فاخر فقط"],
    wrongEn: ["Start with code because video is unofficial", "Tape the paper without filming the lost moment", "Print the prototype only on expensive glossy paper"],
  },
  {
    id: "4-4-f09",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "فريق الحصة أراد شراء رخصة تصميم كاملة قبل أن يجرّب تدفق الاستئذان على السبورة.",
    sceneEn: "The class team wanted to buy a full design licence before trying the permission flow on the blackboard.",
    claimAr: "جرّب التدفق على السبورة كنموذج أولي قبل أي رخصة.",
    claimEn: "Try the flow on the blackboard as a prototype before any licence.",
    whyAr: "الرخيص السريع يكفي لتعلم أين ينكسر الاستئذان.",
    whyEn: "Cheap and fast is enough to learn where permission breaks.",
    termAr: "النموذج الأولي",
    termEn: "Prototype",
    wrongAr: ["اشترِ الرخصة أولًا حتى يبدو العمل جادًا", "تخطَّ التجربة لأن السبورة ليست موقعًا", "صمم الشعار الذهبي قبل المسار"],
    wrongEn: ["Buy the licence first so the work looks serious", "Skip the trial because a blackboard is not a website", "Design the gold logo before the path"],
  },
  {
    id: "4-4-f10",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "نموذج هاتف من ورق مقوى كشف أن زر نعم للعذر يقع تحت إبهام يغلق الصفحة.",
    sceneEn: "A cardboard phone prototype showed the Yes on the excuse sitting under a thumb that closes the page.",
    claimAr: "انقل الزر في النموذج الرخيص قبل أن يُبنى في التطبيق.",
    claimEn: "Move the button on the cheap prototype before it is built in the app.",
    whyAr: "إصلاح الورق أرخص من إصلاح نسخة وصلت إلى متاجر الطلاب.",
    whyEn: "Fixing paper is cheaper than fixing a version that already reached student devices.",
    termAr: "النموذج الأولي",
    termEn: "Prototype",
    wrongAr: ["ابنِ الزر كما هو ثم اعتذر لاحقًا", "أضف زرًا ثانيًا فوق الإبهام من غير تجربة", "ارمِ النموذج لأن الورق لا يُقنع المدير"],
    wrongEn: ["Build the button as it is and apologise later", "Add a second button above the thumb with no trial", "Throw the prototype away because paper will not convince the principal"],
  },
  {
    id: "4-4-f11",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "معظم الزوار يتركون صفحة الرسوم عند خانة كلمة المرور قبل الضغط على ادفع.",
    sceneEn: "Most visitors leave the fees page at the password field before pressing Pay.",
    claimAr: "عالج نقطة الخروج أولًا وراقب هل يكمل السداد بعدها.",
    claimEn: "Fix the drop-off point first and watch whether payment then completes.",
    whyAr: "معدل الخروج يبيّن أين تنكسر المهمة قبل الزر الأخير.",
    whyEn: "Drop-off shows where the task breaks before the last button.",
    termAr: "معدل الخروج",
    termEn: "Drop-off",
    wrongAr: ["أضف رسومًا متحركة فوق الخانة واترك السبب", "انشر صفحة رسوم ثانية من غير قياس", "اللوم على الزائر لأنه استعجل"],
    wrongEn: ["Add animation above the field and leave the cause", "Publish a second fees page with no measurement", "Blame the visitor for rushing"],
  },
  {
    id: "4-4-f12",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "خريطة المغادرة في استمارة الرحلة تُظهر انقطاعًا بعد خطوة اختر الفصل.",
    sceneEn: "The trip-form drop-off map shows a break after the choose-your-class step.",
    claimAr: "بسّط خطوة الفصل وقِس هل ينخفض الخروج هناك.",
    claimEn: "Simplify the class step and measure whether drop-off falls there.",
    whyAr: "مكان المغادرة هو فرضية التحسين التالية لا ذوق الصفحة كلها.",
    whyEn: "The leave point is the next improvement hypothesis, not a taste verdict on the whole page.",
    termAr: "معدل الخروج",
    termEn: "Drop-off",
    wrongAr: ["جمّل رأس الصفحة واترك خطوة الفصل", "احذف اختيار الفصل من غير بديل", "تجاهل الخريطة لأنها ليست ألوانًا"],
    wrongEn: ["Prettify the header and leave the class step", "Delete class choice with no replacement", "Ignore the map because it is not about colours"],
  },
  {
    id: "4-4-f13",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "صفحة نتائج البحث في المكتبة تُغلق بعد أن تغطي قائمة الفلاتر عناوين الكتب.",
    sceneEn: "The library search-results page closes after a filter list covers the titles.",
    claimAr: "ارفع الفلاتر عن العناوين وتابع هل يقل إغلاق الصفحة.",
    claimEn: "Lift the filters off the titles and watch whether page closes fall.",
    whyAr: "الخروج بعد حجب النتيجة إشارة إلى عائق لا إلى زائر كسول.",
    whyEn: "Leaving after the result is covered signals a barrier, not a lazy visitor.",
    termAr: "معدل الخروج",
    termEn: "Drop-off",
    wrongAr: ["أطل قائمة الفلاتر حتى تبدو أقوى", "اللوم على الطلاب لأنهم لا يحبون القراءة", "أضف أغنية خلفية عند الإغلاق"],
    wrongEn: ["Lengthen the filter list so it looks stronger", "Blame students for not liking reading", "Add background music on close"],
  },
  {
    id: "4-4-f14",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "طلب الكانتين يُهجر بعد اختيار الساندويتش لأن خطوة العنوان تطلب الحي والشارع والفصل معًا.",
    sceneEn: "Canteen orders are abandoned after the sandwich choice because the address step asks for district, street, and class together.",
    claimAr: "افصل الحقول وراقب نقطة الترك قبل أن تضيف زينة للسلة.",
    claimEn: "Split the fields and watch the leave point before decorating the basket.",
    whyAr: "معدل الخروج يدل على عائق في الخطوة لا على حاجة لمزيد من الحركة.",
    whyEn: "Drop-off points to a barrier in the step, not a need for more motion.",
    termAr: "معدل الخروج",
    termEn: "Drop-off",
    wrongAr: ["أضف رسومًا للسلة واترك الحقول كما هي", "احذف الساندويتش لأنه يسبب الترك", "أخفِ العداد حتى لا يُرى الخروج"],
    wrongEn: ["Animate the basket and leave the fields as they are", "Delete the sandwich because it causes leaving", "Hide the counter so drop-off cannot be seen"],
  },
  {
    id: "4-4-f15",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "خريطة حرارة صفحة الرسوم تُظهر مغادرة كثيفة، والفريق أضاف ثلاث حركات جديدة فوق النموذج.",
    sceneEn: "A heatmap of the fees page shows heavy leaving, and the team added three new motions over the form.",
    claimAr: "اتبع كثافة المغادرة بدليل، ولا تغطِّ الخروج بزينة.",
    claimEn: "Follow the density of leaving with evidence, and do not cover drop-off with decoration.",
    whyAr: "الحركة فوق النموذج تخفي السبب ولا تخفض معدل الخروج.",
    whyEn: "Motion over the form hides the cause and does not lower drop-off.",
    termAr: "معدل الخروج",
    termEn: "Drop-off",
    wrongAr: ["زد الحركات حتى تبدو الصفحة حيّة", "امحُ الخريطة لأنها محبطة", "انقل اللوم إلى شبكة المدرسة من غير قياس الخطوة"],
    wrongEn: ["Add more motion so the page feels alive", "Erase the map because it is depressing", "Blame the school network without measuring the step"],
  },
  {
    id: "4-4-f16",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "بعد نقل زر حاضر كُتب في المحضر أعجبنا المكان الجديد من غير ذكر تجربة.",
    sceneEn: "After the Present button was moved, the minutes said we liked the new place, with no trial mentioned.",
    claimAr: "وثّق لماذا نُقل الزر وأي دليل شوهد.",
    claimEn: "Record why the button moved and which evidence was seen.",
    whyAr: "دليل القرار سبب مكتوب مبني على ملاحظة لا على جملة أعجبنا.",
    whyEn: "A decision record is a written reason based on a note, not on the sentence we liked it.",
    termAr: "دليل القرار",
    termEn: "Decision record",
    wrongAr: ["اكتفِ بجملة أعجبنا في المحضر", "انقل الزر ثانية لأن المزاج تغيّر", "احذف المحضر حتى يبقى المجال حرًا"],
    wrongEn: ["Stop at we liked it in the minutes", "Move the button again because the mood changed", "Delete the minutes so the field stays free"],
  },
  {
    id: "4-4-f17",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "سبعة من عشرة طلاب في التجربة الصباحية تجاوزوا زر التسليم لأنه بدا كإعلان.",
    sceneEn: "Seven of ten students in the morning trial skipped the submit button because it looked like an advert.",
    claimAr: "اكتب في سجل القرار: سبعة من عشرة تجاوزوا الزر، لذلك غيّرنا شكله.",
    claimEn: "Write in the decision record: seven of ten skipped the button, so we changed its look.",
    whyAr: "الرقم المشاهد أقوى من قائمة أمنيات شكلية.",
    whyEn: "An observed number is stronger than a stylistic wish list.",
    termAr: "دليل القرار",
    termEn: "Decision record",
    wrongAr: ["تجاهل السبعة لأن العينة صغيرة في نظر المصمم", "غيّر الشكل لأن المدير يفضل الأزرق فقط", "أخفِ نتيجة التجربة عن المحضر"],
    wrongEn: ["Ignore the seven because the designer finds the sample small", "Change the look only because the principal prefers blue", "Hide the trial result from the minutes"],
  },
  {
    id: "4-4-f18",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "أحد الأعضاء شعر أن بوابة المدرسة قديمة فطلب هدمها من غير ملاحظة مسجّلة.",
    sceneEn: "One member felt the school portal was old and asked to tear it down with no written observation.",
    claimAr: "ارفض الهدم حتى يُكتب دليل يربط الشعور بمهمة فاشلة.",
    claimEn: "Refuse the teardown until written evidence ties the feeling to a failed task.",
    whyAr: "القرار يُبنى على دليل لا على أمنية تجديد عامة.",
    whyEn: "A decision is built on evidence, not on a general wish to refresh.",
    termAr: "دليل القرار",
    termEn: "Decision record",
    wrongAr: ["اهدم البوابة لأن الشعور كافٍ", "أضف ثلاثين ميزة من قائمة الأمنيات", "أخّر التوثيق حتى بعد الهدم"],
    wrongEn: ["Tear the portal down because the feeling is enough", "Add thirty features from the wish list", "Postpone the write-up until after the teardown"],
  },
  {
    id: "4-4-f19",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "الزمن حتى تحميل جدول الامتحان انخفض عشرين ثانية بعد تقريب الرابط، والمحضر فارغ.",
    sceneEn: "Time to download the exam timetable fell twenty seconds after the link was moved closer, and the minutes are blank.",
    claimAr: "املأ سجل القرار: قرّبنا الرابط لأن الزمن انخفض عشرين ثانية.",
    claimEn: "Fill the decision record: we moved the link closer because time fell twenty seconds.",
    whyAr: "من غير سجل يعود الفريق إلى الذوق في الدورة التالية.",
    whyEn: "Without a record the team returns to taste in the next cycle.",
    termAr: "دليل القرار",
    termEn: "Decision record",
    wrongAr: ["اترك المحضر فارغًا فالنجاح واضح", "أرجع الرابط البعيد لتجربة شعور جديد", "اكتب حسنا فقط من غير رقم"],
    wrongEn: ["Leave the minutes blank because success is obvious", "Move the link far again to try a new feeling", "Write only OK with no number"],
  },
  {
    id: "4-4-f20",
    lessonId: "4-4",
    chapterId: "4",
    sceneAr: "لوحة الأمنيات تضم ثلاثين فكرة لصفحة الحضور بينما دليل واحد يقول إن التسمية غامضة.",
    sceneEn: "The wish board holds thirty ideas for the attendance page, while one piece of evidence says the label is unclear.",
    claimAr: "نفّذ إصلاح التسمية المدعوم بالدليل واترك الأمنيات إلى دورات لاحقة.",
    claimEn: "Ship the evidence-backed label fix and leave the wishes for later cycles.",
    whyAr: "التحسين حلقة دليل لا قائمة أمنيات تُنفَّذ دفعة واحدة.",
    whyEn: "Improvement is an evidence loop, not a wish list shipped in one batch.",
    termAr: "دليل القرار",
    termEn: "Decision record",
    wrongAr: ["نفّذ الثلاثين فكرة في أسبوع الامتحانات", "ارمِ دليل التسمية لأنه فكرة واحدة", "صوّت على الأمنيات من غير تجربة"],
    wrongEn: ["Ship all thirty ideas in exam week", "Throw away the label evidence because it is a single idea", "Vote on the wishes with no trial"],
  },
];

export const CHAPTER_4_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "4-1-a01",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "حلّل اختيار نشر نتائج منتصف الترم كمقطع صوتي طويل بلا جدول: أي وسيط يخدم المقارنة وأي وسيط يخفيها؟",
    promptEn: "Analyse publishing midterm results as a long audio clip with no table: which medium serves comparison, and which hides it?",
    guideAr: "اربط الرسالة بالوسيط: الأرقام للجدول أو الرسم، والصوت للتعليق لا للقيم. اذكر كلفة البحث في المقطع.",
    guideEn: "Tie the message to the medium: numbers belong in a table or chart, audio in commentary not in values. Mention the cost of hunting inside a clip.",
  },
  {
    id: "4-1-a02",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "قارن بانر ترحيب ثمانية ميغابايت على شبكة الجيل الثالث بصورة مضغوطة بالحجم الظاهر على الشاشة.",
    promptEn: "Compare an eight-megabyte welcome banner on 3G with a compressed image at on-screen size.",
    guideAr: "وازن الجودة والحجم وسرعة الفتح. وضّح أن البكسل الزائد لا يزيد المعنى بعد حد الشاشة.",
    guideEn: "Balance quality, size, and open speed. Show that extra pixels add no meaning past the screen limit.",
  },
  {
    id: "4-1-a03",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "انتقد معرض علوم بلا نص بديل يعتمد اسم الملف رقم الكاميرا وصفًا للصورة.",
    promptEn: "Critique a science-fair gallery with no real alt text that uses the camera filename as the image description.",
    guideAr: "بيّن أن النص البديل واجب لمن يستخدم قارئ شاشة، وأن اسم الملف ليس وصفًا. اقترح جملة تصف المشروع والطالب.",
    guideEn: "Show that alt text is a duty for someone using a screen reader, and that a filename is not a description. Propose a sentence that names the project and the student.",
  },
  {
    id: "4-1-a04",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "اشرح لماذا يُعد النص البديل واجب نشر لا تجميلًا يُؤجَّل إلى ما بعد الحفل.",
    promptEn: "Explain why alt text is a publishing duty, not polish postponed until after the concert.",
    guideAr: "اربط الإتاحة بلحظة الإطلاق. فرّق بين زينة صرفة تُترك بلا ضجيج وصورة ذات معنى يجب وصفها.",
    guideEn: "Tie access to the launch moment. Separate pure decoration that should stay quiet from a meaningful image that must be described.",
  },
  {
    id: "4-1-a05",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "حلّل قائمة كانتين نُشرت كمسح ضبابي لورقة بخط اليد من جهة الوضوح والحجم والوسيط الأنسب.",
    promptEn: "Analyse a canteen menu published as a blurry handwritten scan in terms of clarity, size, and the fittest medium.",
    guideAr: "اقترح نصًا أو صورة حادة خفيفة. اذكر أن المسح الثقيل يفشل على الهاتف ويفشل مع قارئ الشاشة.",
    guideEn: "Propose text or a sharp light image. Note that a heavy scan fails on a phone and fails with a screen reader.",
  },
  {
    id: "4-1-a06",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "قارن جدول مواعيد الأتوبيس بنشرة رسوم متحركة تدور ولا تتوقف عند الساعة التالية.",
    promptEn: "Compare a bus timetable table with a looping animation that never settles on the next hour.",
    guideAr: "حدد مهمة الراكب: معرفة الوقت التالي. بيّن أن الحركة زينة إن أخفت البيان.",
    guideEn: "Name the rider's task: know the next time. Show that motion is decoration if it hides the fact.",
  },
  {
    id: "4-1-a07",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "انتقد رفع تسجيل حفل كورال بصيغة غير مضغوطة مع منع المشرف لأي ضغط بدعوى الجودة.",
    promptEn: "Critique posting a choir concert as an uncompressed file while the supervisor bans compression in the name of quality.",
    guideAr: "فرّق بين فقد المعنى وسحق الجودة وبين ضغط يُبقي الأداء ويسرّع التنزيل. اذكر حدًا لا يُسحق بعده النص أو الوجه.",
    guideEn: "Separate meaning loss and crushed quality from compression that keeps the performance and speeds the download. Mention a limit beyond which text or a face must not be crushed.",
  },
  {
    id: "4-1-a08",
    lessonId: "4-1",
    chapterId: "4",
    promptAr: "اشرح لماذا يفشل دليل طالب جديد يُنشر فيديو صامتًا بدقة سينمائية طولها دقائق على باب الإدارة.",
    promptEn: "Explain why a new-student guide fails when it is an eight-minute silent cinema-resolution video of the office door.",
    guideAr: "اربط الوسيط بالمهمة: خطوات اليوم الأول تحتاج نصًا أو مقطعًا قصيرًا مضغوطًا. الزمن والحجم جزء من جودة الدليل.",
    guideEn: "Tie the medium to the task: first-day steps need text or a short compressed clip. Time and size are part of the guide's quality.",
  },
  {
    id: "4-2-a01",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "حلّل رحلة تسجيل الحضور التي تمر بست قوائم قبل ظهور زر حاضر: أين تنكسر تجربة المستخدم؟",
    promptEn: "Analyse an attendance journey that passes six menus before a Present button appears: where does UX break?",
    guideAr: "ارسم الخطوات وعدّ النقرات. فرّق بين رحلة UX وعناصر UI. اقترح مسارًا لمهمة واحدة في أقل خطوات.",
    guideEn: "Sketch the steps and count the clicks. Separate the UX journey from UI controls. Propose a path for one task in the fewest steps.",
  },
  {
    id: "4-2-a02",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "قارن تجربة المستخدم بواجهة المستخدم في صفحة رسوم رحلة يضيع فيها ولي الأمر بين نادي الشطرنج وأخبار الحفل.",
    promptEn: "Compare UX and UI on a trip-fees page where a parent is lost between the chess club and concert news.",
    guideAr: "UX: هل وصل إلى النموذج؟ UI: أين الزر وما لونه وتسميته؟ بيّن أن جمال التحكم لا ينقذ رحلة مكسورة.",
    guideEn: "UX: did they reach the form? UI: where is the button, its colour, its label? Show that a pretty control does not save a broken journey.",
  },
  {
    id: "4-2-a03",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "انتقد قائمة تقفز من اليمين إلى الأعلى إلى أيقونة مخفية بعد تسجيل الدخول.",
    promptEn: "Critique a menu that jumps from the right, to the top, to a hidden icon after login.",
    guideAr: "اشرح كلفة إعادة التعلّم. دافع عن الاتساق في المكان والشكل مقابل مفاجأة التخطيط.",
    guideEn: "Explain the cost of relearning. Defend consistency of place and shape against a layout surprise.",
  },
  {
    id: "4-2-a04",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "اشرح لماذا يتفوق ثبات مكان القائمة ولون الزر الرئيسي على إدهاش شكل جديد في كل صفحة.",
    promptEn: "Explain why a stable menu place and primary-button colour beat a surprising new look on every page.",
    guideAr: "اربط الاتساق بسرعة المهمة وتقليل الضياع. اذكر أن المفاجأة تصلح لمعرض لا لحضور يومي.",
    guideEn: "Tie consistency to task speed and fewer lost users. Note that surprise fits a gallery, not daily attendance.",
  },
  {
    id: "4-2-a05",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "حلّل اختبار زميل صامت يشاهد شاشة الرسوم ولا يجد زر السداد حتى يغلق الصفحة.",
    promptEn: "Analyse a silent-classmate test on the fees screen where the pay button is never found before the page closes.",
    guideAr: "صف ماذا يُسجَّل: موضع النظر، التوقف، الإغلاق. بيّن كيف يتحول الضياع إلى تعديل في التسلسل البصري.",
    guideEn: "Describe what is logged: gaze, pauses, closing. Show how getting lost becomes a change in visual hierarchy.",
  },
  {
    id: "4-2-a06",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "قارن تسلسلًا بصريًا يجعل إعلان الكافتيريا أكبر من زر سجّل حضورك بتسلسل يجعل المهمة أول ما تراه العين.",
    promptEn: "Compare a visual hierarchy that makes the cafeteria advert larger than Mark your attendance with one that puts the task first in the eye.",
    guideAr: "استخدم الحجم والموضع والتسمية. انتقد الاعتماد على اللون وحده للتفريق بين حاضر ومتأخر.",
    guideEn: "Use size, place, and label. Critique relying on colour alone to split Present and Late.",
  },
  {
    id: "4-2-a07",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "انتقد تحميل جدول الحصص عبر تسع نقرات في نشرات قديمة وتعليمات مخفية داخل تلميح يتأخر عشر ثوان.",
    promptEn: "Critique a nine-click timetable download through old newsletters and instructions hidden in a ten-second tooltip.",
    guideAr: "احسب النقرات والثواني الضائعة. اقترح مسارًا يظهر الخطوات في الصفحة ويصل إلى الملف بسرعة.",
    guideEn: "Count the wasted clicks and seconds. Propose a path that shows the steps on the page and reaches the file quickly.",
  },
  {
    id: "4-2-a08",
    lessonId: "4-2",
    chapterId: "4",
    promptAr: "اشرح لماذا يجب أن يصل الطالب إلى الحضور بلوحة المفاتيح في أقل خطوات لا بالفأرة وحدها.",
    promptEn: "Explain why a student must reach attendance by keyboard in the fewest steps, not by mouse alone.",
    guideAr: "اربط عدد الخطوات بإتاحة الوصول. بيّن أن رحلة قصيرة لا تُحسب للفأرة فقط.",
    guideEn: "Tie step count to accessibility. Show that a short journey is not counted for the mouse only.",
  },
  {
    id: "4-3-a01",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "حلّل تقييم صفحة رئيسية بالتصويت على الشكل من غير أن يجرّب أحد تسجيل حضور.",
    promptEn: "Analyse scoring a homepage by a look vote without anyone trying to mark attendance.",
    guideAr: "عرّف قابلية الاستخدام: إتمام، زمن، أخطاء. بيّن أن الذوق وحده ليس تقييمًا.",
    guideEn: "Define usability: completion, time, errors. Show that taste alone is not evaluation.",
  },
  {
    id: "4-3-a02",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "قارن نسختين لزر الحضور سجّل الآن و أنا هنا عبر اختبار أ/ب يقيس الإتمام لا جمال الكلمة.",
    promptEn: "Compare two attendance labels, Mark now and I am here, through an A/B test that measures completion, not word beauty.",
    guideAr: "اشرح توزيع الزوار والمقياس وحجم العينة. انتقد إعلان فائز بعد صديقين في الفسحة.",
    guideEn: "Explain visitor split, the measure, and sample size. Critique naming a winner after two friends at break.",
  },
  {
    id: "4-3-a03",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "انتقد قائمة درجات تمنح عشر نقاط للأناقة وتؤجّل قارئ الشاشة ولوحة المفاتيح إلى حاشية.",
    promptEn: "Critique a score sheet that gives ten points for elegance and parks the screen reader and keyboard in a footnote.",
    guideAr: "اجعل الإتاحة بندًا في الدرجة. اربط فشل حجز المختبر بلا فأرة بنقص قابلية الاستخدام.",
    guideEn: "Put accessibility on the score line. Tie a failed lab booking without a mouse to missing usability.",
  },
  {
    id: "4-3-a04",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "اشرح لماذا يُحسب زمن المهمة قبل تقريب زر الحضور وبعده دليل نجاح أو فشل لا حجم الشعار.",
    promptEn: "Explain why task time before and after moving the attendance button is evidence of success or failure, not logo size.",
    guideAr: "استخدم مثال أربع دقائق مقابل أربعين ثانية. اذكر أن الزمن يشمل التصحيح لا أول نقرة فقط.",
    guideEn: "Use four minutes versus forty seconds. Note that time includes repair, not only the first click.",
  },
  {
    id: "4-3-a05",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "حلّل تعارض خمس نجوم في استطلاع الرضا مع مغادرة نصف الطلاب قبل إرسال استمارة النادي.",
    promptEn: "Analyse a clash between five satisfaction stars and half the students leaving before sending the club form.",
    guideAr: "اقرأ الرضا مع معدل الإتمام. بيّن أن النجوم بلا مهمة مكتملة رضا ناقص.",
    guideEn: "Read satisfaction with completion rate. Show that stars without a finished task are incomplete satisfaction.",
  },
  {
    id: "4-3-a06",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "قارن عدد أخطاء نموذج دفع الرحلة وزمن إصلاح التاريخ قبل تعديل المنتقي وبعده.",
    promptEn: "Compare trip-fee form errors and date-repair time before and after changing the picker.",
    guideAr: "اجعل الأخطاء وكلفة الإصلاح معيارًا. ارفض إخفاء رسالة الخطأ لأنها محرجة.",
    guideEn: "Treat errors and repair cost as a standard. Refuse hiding the error message because it is embarrassing.",
  },
  {
    id: "4-3-a07",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "انتقد إعلان فوز البنفسجي في بوابة أولياء الأمور بعد تجربة صديقين من غير مقياس إتمام.",
    promptEn: "Critique declaring purple the winner on the parent portal after a two-friend trial with no completion measure.",
    guideAr: "بيّن أن العينة الصغيرة ذوق متنكّر. اطلب مقياسًا وعددًا قبل إعلان النسخة.",
    guideEn: "Show that a tiny sample is taste in disguise. Demand a measure and a count before naming the version.",
  },
  {
    id: "4-3-a08",
    lessonId: "4-3",
    chapterId: "4",
    promptAr: "اشرح لماذا تبقى إتاحة الوصول جزءًا من درجة التقييم حتى لو مدح المدير الخط في ليلة أولياء الأمور.",
    promptEn: "Explain why accessibility stays part of the evaluation score even if the principal praised the font at parents' evening.",
    guideAr: "اربط الرضا والوضوح بمن يُستبعد من القراءة. ارفض رفع الدرجة بالتصفيق على اللون.",
    guideEn: "Tie satisfaction and clarity to anyone excluded from reading. Refuse raising the score on colour applause.",
  },
  {
    id: "4-4-a01",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "حلّل قرار هدم موقع المدرسة في عطلة الأسبوع بعد فشل تسجيل يوم الرياضة بدل حلقة صمّم-اختبر-تعلّم-حسّن.",
    promptEn: "Analyse the decision to tear down the school site over the weekend after sports-day registration failed, instead of a design-test-learn-improve loop.",
    guideAr: "صف الحلقة المغلقة. بيّن أن العثرة الأولى فرضية لا حكم بهدم كامل.",
    guideEn: "Describe the closed loop. Show that the first stumble is a hypothesis, not a verdict to demolish everything.",
  },
  {
    id: "4-4-a02",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "قارن دورة تغيّر لون الزر وموضعه ونصّه وخط الصفحة معًا بدورتين: تسمية أولًا ثم موضع بعد ثبوت التسمية.",
    promptEn: "Compare one cycle that changes button colour, place, wording, and font together with two cycles: label first, then place after the label is proven.",
    guideAr: "اشرح لماذا يضيع السبب إن تحركت أربعة عناصر. دافع عن تغيير واحد لكل دورة.",
    guideEn: "Explain why the cause is lost if four elements move. Defend one change per cycle.",
  },
  {
    id: "4-4-a03",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "انتقد لوحة أمنيات من ثلاثين فكرة تُنفَّذ في أسبوع الامتحانات رغم دليل واحد يقول إن تسمية الحضور غامضة.",
    promptEn: "Critique a thirty-idea wish board shipped in exam week even though one piece of evidence says the attendance label is unclear.",
    guideAr: "قدّم إصلاح الدليل على القائمة. بيّن أن الأمنيات دورات لاحقة لا دفعة واحدة.",
    guideEn: "Put the evidence fix ahead of the list. Show that wishes belong in later cycles, not in one batch.",
  },
  {
    id: "4-4-a04",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "اشرح لماذا يُختبر تدفق الاستئذان على السبورة أو الورق المقوى قبل شراء رخصة تصميم أو ربط قاعدة بيانات.",
    promptEn: "Explain why the permission flow is tested on a blackboard or cardboard before buying a design licence or wiring a database.",
    guideAr: "عرّف النموذج الأولي: رخيص وسريع لكشف الضياع. قارن كلفة نقل زر على الورق بكلفة إصلاحه بعد وصوله للأجهزة.",
    guideEn: "Define a prototype: cheap and fast to reveal getting lost. Compare moving a button on paper with repairing it after it reaches devices.",
  },
  {
    id: "4-4-a05",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "حلّل مغادرة معظم الزوار صفحة الرسوم عند خانة كلمة المرور قبل ادفع، بينما يُضاف فوق الخانة رسوم متحركة.",
    promptEn: "Analyse most visitors leaving the fees page at the password field before Pay, while animation is added over the field.",
    guideAr: "اجعل نقطة الخروج فرضية الدورة. انتقد تغطية السبب بالزينة بدل تبسيط الخطوة.",
    guideEn: "Treat the leave point as the cycle's hypothesis. Critique covering the cause with decoration instead of simplifying the step.",
  },
  {
    id: "4-4-a06",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "قارن محضر قرار يكتب أعجبنا المكان الجديد بسجل يذكر أن سبعة من عشرة تجاوزوا الزر لذلك تغيّر شكله.",
    promptEn: "Compare minutes that say we liked the new place with a record that seven of ten skipped the button, so its look changed.",
    guideAr: "حدد عناصر دليل القرار: السبب، الدليل، التغيير. بيّن أن أعجبنا تعيد الذوق في الدورة التالية.",
    guideEn: "Name the parts of a decision record: reason, evidence, change. Show that we liked it returns taste in the next cycle.",
  },
  {
    id: "4-4-a07",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "انتقد نشر الموقع يوم الأحد ثم إغلاق تقارير المغادرة حتى امتحانات آخر الترم.",
    promptEn: "Critique launching on Sunday and then ignoring leave reports until end-of-term exams.",
    guideAr: "اربط المراقبة بالحلقة. الموقع لا يُنشر ويُنسى؛ الأثر يبرد إن تأخر القياس.",
    guideEn: "Tie watching to the loop. A site is not launched and forgotten; the trail goes cold if measurement waits.",
  },
  {
    id: "4-4-a08",
    lessonId: "4-4",
    chapterId: "4",
    promptAr: "اشرح لماذا يجب كتابة لماذا قرّبنا رابط جدول الامتحان وأي انخفاض في الزمن سُجّل قبل بدء دورة جديدة.",
    promptEn: "Explain why you must write why the exam-timetable link was moved closer and which time drop was logged before starting a new cycle.",
    guideAr: "اربط السجل بمنع إعادة الخلط. من غير رقم يعود الفريق إلى الشعور بهدم أو إلى قائمة أمنيات.",
    guideEn: "Tie the record to stopping mixed causes. Without a number the team returns to a feeling of teardown or to a wish list.",
  },
];
