import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_7_FACTS: BankFact[] = [
  {
    id: "7-1-f01",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "أمين مكتبة المدرسة يريد نموذجًا يتوقع إن كان الكتاب سيُعاد متأخرًا أم في موعده.",
    sceneEn: "The school librarian wants a model that predicts whether a book will come back late or on time.",
    claimAr: "اجمع إعارات سابقة معلّمة: متأخر أو في الموعد، فهذا تعلم بإشراف.",
    claimEn: "Gather past loans labeled late or on time; that is supervised learning.",
    whyAr: "التعلم بإشراف يحتاج أمثلة فيها المدخل والنتيجة المعروفة معًا.",
    whyEn: "Supervised learning needs examples that pair an input with a known outcome.",
    termAr: "تعلم بإشراف",
    termEn: "Supervised",
    wrongAr: [
      "اترك الكتب بلا أي تسمية واطلب من النموذج اختراع الفئات وحده.",
      "اختبر النموذج على نفس الإعارات التي حفظها ثم أعلن دقة كاملة.",
      "اطلب رقم صفحات الكتاب بدل فئة التأخير.",
    ],
    wrongEn: [
      "Leave the loans unlabeled and ask the model to invent the classes alone.",
      "Test the model on the same loans it memorized and announce a perfect score.",
      "Ask for the page count instead of a late-or-on-time class.",
    ],
  },
  {
    id: "7-1-f02",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مزارع يريد أن يعرف من صورة الورقة إن كانت الطماطم سليمة أو مصابة باللفحة.",
    sceneEn: "A farmer wants a photo of a tomato leaf to say healthy or blighted.",
    claimAr: "درّب النموذج على صور معلّمة سليم/مصاب ثم قِس على صور جديدة.",
    claimEn: "Train on photos labeled healthy or blighted, then measure on new photos.",
    whyAr: "المهمة لها مخرج معروف فالتعلم بإشراف هو الإطار المناسب.",
    whyEn: "The task has a known output, so supervised learning is the right frame.",
    termAr: "تعلم بإشراف",
    termEn: "Supervised",
    wrongAr: [
      "ارمِ التسميات واطلب تجمعات ألوان بلا معنى زراعي.",
      "صوّر ورقة واحدة عشر مرات وعدّها ألف مثال مستقل.",
      "استبدل الحكم بقصيدة عن الطماطم.",
    ],
    wrongEn: [
      "Throw away the labels and ask for colour clusters with no farm meaning.",
      "Photograph one leaf ten times and count that as a thousand independent examples.",
      "Replace the judgement with a poem about tomatoes.",
    ],
  },
  {
    id: "7-1-f03",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مختبر المستشفى يريد توقع إن كانت عينة الدم «ضمن المدى» أو «تحتاج مراجعة طبيب».",
    sceneEn: "A hospital lab wants to predict whether a blood sample is in range or needs a doctor review.",
    claimAr: "ابنِ مجموعة أمثلة معلّمة من نتائج سابقة راجعها المختص.",
    claimEn: "Build a labeled set from past results a specialist already reviewed.",
    whyAr: "بلا مخرج معلّم لا يتعلم النموذج معنى «يحتاج مراجعة».",
    whyEn: "Without a labeled output the model cannot learn what “needs review” means.",
    termAr: "تعلم بإشراف",
    termEn: "Supervised",
    wrongAr: [
      "أدخل الأرقام الخام واطلب منه تجميع المرضى حسب لون الأنبوب.",
      "اختبره على العينات التي درّبته عليها فقط.",
      "اجعله يتنبأ بعنوان بيت المريض.",
    ],
    wrongEn: [
      "Feed raw numbers and ask it to cluster patients by tube colour.",
      "Test it only on the samples it trained on.",
      "Have it predict the patient's home address.",
    ],
  },
  {
    id: "7-1-f04",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "خط تعبئة المياه يريد نموذجًا يفرّق الزجاجة المشروخة من السليمة قبل الإغلاق.",
    sceneEn: "A water-bottling line wants a model that separates cracked bottles from sound ones before capping.",
    claimAr: "علّم صورًا قديمة: مشروخة أو سليمة، فهذا تصنيف بإشراف.",
    claimEn: "Label old photos cracked or sound; that is supervised classification.",
    whyAr: "كل مثال يحمل مدخلًا وصنفًا معروفًا فيتعلم النموذج الحد الفاصل.",
    whyEn: "Each example carries an input and a known class, so the model can learn the boundary.",
    termAr: "تعلم بإشراف",
    termEn: "Supervised",
    wrongAr: [
      "شغّل الكاميرا بلا تسميات وانتظر أن يخترع معنى الشروخ.",
      "درّبه على زجاجات لون واحد ثم عمّمه على كل الألوان بلا فحص.",
      "اطلب منه عدد اللترات في الخزان بدل حالة الزجاجة.",
    ],
    wrongEn: [
      "Run the camera with no labels and wait for it to invent what a crack means.",
      "Train on one bottle colour then apply it to every colour with no check.",
      "Ask for the tank litre count instead of the bottle's condition.",
    ],
  },
  {
    id: "7-1-f05",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مشرف الحافلة المدرسية يريد توقع غياب الغد: يحضر الطالب أو لا يحضر.",
    sceneEn: "The school-bus supervisor wants to predict tomorrow's absence: the student rides or not.",
    claimAr: "استخدم سجلات حضور معلّمة حضر/غاب مع الطقس واليوم.",
    claimEn: "Use attendance records labeled present or absent together with weather and weekday.",
    whyAr: "النتيجة التاريخية معروفة فالإشراف يعطي النموذج هدفًا واضحًا.",
    whyEn: "The historical outcome is known, so supervision gives the model a clear target.",
    termAr: "تعلم بإشراف",
    termEn: "Supervised",
    wrongAr: [
      "احذف عمود الحضور واطلب تجمعات أسماء فقط.",
      "اختبر النموذج على نفس الأسبوع الذي حفظه.",
      "اجعله يكتب قصة عن الحافلة بدل فئة الحضور.",
    ],
    wrongEn: [
      "Delete the attendance column and ask only for name clusters.",
      "Test the model on the same week it memorized.",
      "Have it write a bus story instead of an attendance class.",
    ],
  },
  {
    id: "7-1-f06",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "معلم يريد اكتشاف مجموعات أساليب مذاكرة من غير أن يسمّي الطلاب «مجتهد» أو «هامل».",
    sceneEn: "A teacher wants to find study-habit groups without labeling students hardworking or lazy.",
    claimAr: "استخدم تعلمًا بلا إشراف للبحث عن تجمعات في أوقات المذاكرة والغياب.",
    claimEn: "Use unsupervised learning to find clusters in study times and absences.",
    whyAr: "بلا تسمية جاهزة نبحث عن أنماط لا عن فئة مفروضة مسبقًا.",
    whyEn: "With no ready label we look for patterns, not a class imposed in advance.",
    termAr: "تعلم بلا إشراف",
    termEn: "Unsupervised",
    wrongAr: [
      "أجبر النموذج على توقع ناجح/راسب من غير عمود نتيجة.",
      "اختبر التجمعات على نفس الصفوف ثم ادّعِ دقة تصنيف.",
      "سمِّ كل طالب قبل أن تنظر إلى البيانات.",
    ],
    wrongEn: [
      "Force the model to predict pass or fail with no outcome column.",
      "Test the clusters on the same rows and claim a classification score.",
      "Name every student before you look at the data.",
    ],
  },
  {
    id: "7-1-f07",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مهندس ري يجمع قراءات رطوبة وملوحة من حقول بلا اسم محصول مكتوب عليها.",
    sceneEn: "An irrigation engineer has moisture and salinity readings from fields with no crop name attached.",
    claimAr: "اطلب تجمعات تربة متشابهة بلا إجبار تسمية القمح أو البرسيم.",
    claimEn: "Ask for similar-soil clusters without forcing wheat or clover labels.",
    whyAr: "التعلم بلا إشراف يناسب البحث عن مجموعات حين لا توجد فئة جاهزة.",
    whyEn: "Unsupervised learning fits a search for groups when no class is ready.",
    termAr: "تعلم بلا إشراف",
    termEn: "Unsupervised",
    wrongAr: [
      "اخترع عمود «قمح/برسيم» عشوائيًا ثم ادّعِ إشرافًا علميًا.",
      "اختبر نموذج تصنيف على نفس القراءات التي عنقَدها.",
      "ارمِ الأرقام واستمع إلى حدس الجار فقط.",
    ],
    wrongEn: [
      "Invent a random wheat-or-clover column and call it scientific supervision.",
      "Test a classifier on the same readings you just clustered.",
      "Throw away the numbers and listen only to a neighbour's hunch.",
    ],
  },
  {
    id: "7-1-f08",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "ممرضة تريد رؤية مجموعات غير معتادة في نبض وحرارة مرضى العيادة من غير تشخيص مسبق.",
    sceneEn: "A nurse wants unusual groups in clinic pulse and temperature with no prior diagnosis.",
    claimAr: "شغّل تجميعًا بلا إشراف ثم اعرض المجموعات الشاذة على الطبيب.",
    claimEn: "Run unsupervised clustering, then show odd groups to a doctor.",
    whyAr: "النموذج يبرز نمطًا؛ الإنسان يفسّر إن كان مرضًا أو خطأ قياس.",
    whyEn: "The model highlights a pattern; a human decides if it is illness or a bad reading.",
    termAr: "تعلم بلا إشراف",
    termEn: "Unsupervised",
    wrongAr: [
      "أعلن تشخيصًا نهائيًا من التجمع وحده.",
      "اختبر «دقة الشفاء» على نفس القياسات.",
      "احذف القراءات الشاذة قبل التجميع لأنها تزعج الرسم.",
    ],
    wrongEn: [
      "Announce a final diagnosis from the cluster alone.",
      "Test a “cure accuracy” on the same measurements.",
      "Delete odd readings before clustering because they spoil the chart.",
    ],
  },
  {
    id: "7-1-f09",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "فني صيانة يسجّل اهتزاز محركات المصنع من غير أن يعرف اسم العطل بعد.",
    sceneEn: "A maintenance tech logs factory-motor vibration before anyone names the fault.",
    claimAr: "جمّع أنماط الاهتزاز أولًا بلا تسمية عطل جاهزة.",
    claimEn: "Cluster vibration patterns first, with no ready fault label.",
    whyAr: "البحث عن تجمعات يكشف مجموعات تستحق تسمية لاحقًا.",
    whyEn: "A cluster search reveals groups that may deserve a name later.",
    termAr: "تعلم بلا إشراف",
    termEn: "Unsupervised",
    wrongAr: [
      "أجبِر كل محرك على تصنيف «سليم/تالف» من غير فحص.",
      "اختبر النموذج على نفس الوردية التي درّبته عليها.",
      "استبدل القياسات بصورة شعار المصنع.",
    ],
    wrongEn: [
      "Force every motor into sound or broken with no inspection.",
      "Test the model on the same shift it trained on.",
      "Replace the measurements with the factory logo.",
    ],
  },
  {
    id: "7-1-f10",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مقصف المدرسة يملك أرقام مبيعات أصناف بلا عمود يقول «ناجح تسويقيًا».",
    sceneEn: "The school canteen has item sales with no column that says “a marketing success”.",
    claimAr: "ابحث عن تجمعات أصناف تُشترى معًا بلا اختراع تسمية نجاح.",
    claimEn: "Find clusters of items bought together without inventing a success label.",
    whyAr: "غياب عمود المخرج يعني أن الإشراف غير متاح الآن.",
    whyEn: "With no output column, supervision is not available yet.",
    termAr: "تعلم بلا إشراف",
    termEn: "Unsupervised",
    wrongAr: [
      "سمِّ نصف الأصناف نجاحًا عشوائيًا كي يبدو العمل بإشراف.",
      "أعلن دقة 100٪ لأن التجمع أغلق على نفسه.",
      "تنبّأ بدرجة الطالب من سعر الساندويتش.",
    ],
    wrongEn: [
      "Randomly stamp half the items as successes so the work looks supervised.",
      "Announce 100% accuracy because the cluster closed on itself.",
      "Predict a student's mark from the sandwich price.",
    ],
  },
  {
    id: "7-1-f11",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "طالب بنى نموذج توقع درجات على كل أوراق الصف ثم اختبره على الأوراق نفسها.",
    sceneEn: "A student built a mark predictor on every paper in the class and tested it on those same papers.",
    claimAr: "افصل أوراق اختبار لم يرها النموذج؛ درجة التدريب وحدها متفائلة كاذبة.",
    claimEn: "Hold out papers the model has not seen; a training-only score is falsely optimistic.",
    whyAr: "اختبار النموذج على ما حفظه يقيس التذكر لا القدرة على الجديد.",
    whyEn: "Testing on what the model memorized measures recall, not skill on new cases.",
    termAr: "تدريب / اختبار",
    termEn: "Train / test",
    wrongAr: [
      "أعلن أن الدقة الكاملة على التدريب تثبت الجاهزية للامتحان الوزاري.",
      "أضف الأوراق نفسها مرتين كي تزيد العينة.",
      "احذف أي ورقة أخطأ فيها النموذج قبل إعادة القياس.",
    ],
    wrongEn: [
      "Announce that a perfect training score proves readiness for the ministry exam.",
      "Add the same papers twice to grow the sample.",
      "Drop every paper the model missed before measuring again.",
    ],
  },
  {
    id: "7-1-f12",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مزرعة ألبان درّبت نموذج توقع إنتاج الحليب على أسابيع الربيع وتريد تقييمه.",
    sceneEn: "A dairy farm trained a milk-yield model on spring weeks and now wants an evaluation.",
    claimAr: "اختبر على أسابيع لاحقة لم تدخل التدريب، لا على أيام الربيع نفسها.",
    claimEn: "Test on later weeks that never entered training, not on those same spring days.",
    whyAr: "القياس الصادق يحتاج جزءًا لم يره النموذج بعد.",
    whyEn: "An honest measure needs a split the model has not seen.",
    termAr: "تدريب / اختبار",
    termEn: "Train / test",
    wrongAr: [
      "أعد الاختبار على نفس أبقار الربيع لأن الأرقام مألوفة.",
      "اخلط كل الأيام ثم اختر أجمل درجة.",
      "استبدل الاختبار بصورة القطيع.",
    ],
    wrongEn: [
      "Retest on the same spring cows because the numbers feel familiar.",
      "Mix every day then pick the prettiest score.",
      "Replace the test with a herd photograph.",
    ],
  },
  {
    id: "7-1-f13",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "قسم الأشعة درّب كاشف كسور على صور يناير ويريد رقم جودة قبل تعميمه في مارس.",
    sceneEn: "Radiology trained a fracture detector on January scans and wants a quality number before a March rollout.",
    claimAr: "قِس على صور مرضى جدد لم يدخلوا ملف التدريب.",
    claimEn: "Measure on new patients whose scans never entered the training file.",
    whyAr: "صور التدريب تعطي درجة متفائلة إن أُعيد استخدامها كاختبار.",
    whyEn: "Training scans give an optimistic score if they are reused as the test.",
    termAr: "تدريب / اختبار",
    termEn: "Train / test",
    wrongAr: [
      "اختبر على صور يناير بعد قص الحواف فقط.",
      "أظهر للنموذج إجابة مارس أثناء التدريب.",
      "أعلن النجاح لأن البرنامج فتح من غير خطأ.",
    ],
    wrongEn: [
      "Test on January scans after only cropping the edges.",
      "Show the model the March answers during training.",
      "Declare success because the program opened without an error.",
    ],
  },
  {
    id: "7-1-f14",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مصنع سيراميك درّب كاشف خدوش على وردية الصباح ويريد رقمًا قبل اعتماد وردية الليل.",
    sceneEn: "A ceramics plant trained a scratch detector on the morning shift and wants a number before trusting the night shift.",
    claimAr: "اجعل بلاط الليل مجموعة اختبار مستقلة.",
    claimEn: "Make night-shift tiles an independent test set.",
    whyAr: "إضاءة الليل وعمال مختلفون يغيّرون الصورة؛ التدريب لا يكفي.",
    whyEn: "Night lighting and different workers change the image; training alone is not enough.",
    termAr: "تدريب / اختبار",
    termEn: "Train / test",
    wrongAr: [
      "كرر صور الصباح وعدّها اختبار ليل.",
      "ارفع الدرجة بحذف البلاط الصعب.",
      "استبدل القياس بعدّ المصابيح في القاعة.",
    ],
    wrongEn: [
      "Replay morning photos and count them as a night test.",
      "Raise the score by dropping hard tiles.",
      "Replace the measure with a count of hall lights.",
    ],
  },
  {
    id: "7-1-f15",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "نادي المدرسة يفاخر بأن نموذج توقع إصابة اللاعب سجّل 99٪ على التمارين التي تعلّم منها.",
    sceneEn: "The school club boasts that an injury predictor scored 99% on the drills it learned from.",
    claimAr: "ارفض الرقم حتى يُقاس على مباريات لم تدخل التدريب.",
    claimEn: "Reject the number until it is measured on matches that never entered training.",
    whyAr: "الدرجة على مجموعة التدريب كثيرًا ما تخدع لأنها تقيس الحفظ.",
    whyEn: "A training-set score often misleads because it measures memorization.",
    termAr: "تدريب / اختبار",
    termEn: "Train / test",
    wrongAr: [
      "اطبع شهادة دقة لأن 99٪ رقم كبير.",
      "أضف تمارين التدريب إلى الاختبار لتحسين المتوسط.",
      "أوقف جمع البيانات لأن النموذج «اكتمل».",
    ],
    wrongEn: [
      "Print an accuracy certificate because 99% looks large.",
      "Add the training drills into the test to improve the average.",
      "Stop collecting data because the model is “finished”.",
    ],
  },
  {
    id: "7-1-f16",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "المرشد يريد توقع إن كان طالب الصف الأول سيُعاد قيده أو يُحوَّل مسارًا.",
    sceneEn: "A counselor wants to predict whether a first-year student will re-enrol or change track.",
    claimAr: "هذه فئة: أعد قيدًا أو حوّل؛ فالمهمة تصنيف لا رقم حر.",
    claimEn: "This is a class: re-enrol or change track; the task is classification, not a free number.",
    whyAr: "التصنيف يتنبأ بفئة محدودة لا بكمية مستمرة.",
    whyEn: "Classification predicts a limited class, not a continuous quantity.",
    termAr: "تصنيف",
    termEn: "Classification",
    wrongAr: [
      "اطلب كسرًا عشريًا لساعات المذاكرة وعدّه هو القرار.",
      "اترك المخرج بلا فئات وسمِّه انحدارًا لأن الأرقام أجمل.",
      "اختبر الفئات على نفس قائمة الأسماء التي درّبتها.",
    ],
    wrongEn: [
      "Ask for a decimal of study hours and treat that as the decision.",
      "Leave the output without classes and call it regression because numbers look nicer.",
      "Test the classes on the same name list you trained.",
    ],
  },
  {
    id: "7-1-f17",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "نحّال يريد توقع كيلوغرامات العسل هذا الشهر، لا مجرد «كثير أو قليل».",
    sceneEn: "A beekeeper wants kilograms of honey this month, not only “a lot or a little”.",
    claimAr: "الكمية رقم فالانحدار أنسب؛ التصنيف لو أردت فئتي غزير/ضعيف فقط.",
    claimEn: "A quantity is a number, so regression fits; use classification only for rich or weak classes.",
    whyAr: "التصنيف فئة، والانحدار رقم؛ السؤال يحدد الأداة.",
    whyEn: "Classification is a class and regression is a number; the question picks the tool.",
    termAr: "تصنيف",
    termEn: "Classification",
    wrongAr: [
      "أجبر المخرج على ناجح/راسب لأن ذلك أسهل في الجدول.",
      "اختبر كيلوغرامات التدريب على الخلايا نفسها.",
      "استبدل الرقم بصورة النحلة.",
    ],
    wrongEn: [
      "Force the output into pass or fail because that is easier in a table.",
      "Test the training kilograms on the same hives.",
      "Replace the number with a bee photo.",
    ],
  },
  {
    id: "7-1-f18",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "الاستقبال يريد توقع إن كان المريض يُحوَّل للطوارئ أو يبقى في العيادة، لا عدد ساعات الانتظار.",
    sceneEn: "Reception wants to predict emergency transfer or stay-in-clinic, not the waiting hours.",
    claimAr: "اختر تصنيفًا بفئتين؛ ساعات الانتظار مسألة رقم لاحقًا.",
    claimEn: "Choose two-class classification; waiting hours are a later number problem.",
    whyAr: "تحويل أو بقاء فئة، أما الساعات فانحدار منفصل.",
    whyEn: "Transfer or stay is a class; hours would be a separate regression.",
    termAr: "تصنيف",
    termEn: "Classification",
    wrongAr: [
      "اطلب رقمًا عشريًا للساعات وعدّه قرار التحويل.",
      "اخلط الفئتين في عمود درجات من 0 إلى 100 من غير معنى.",
      "اختبر القرار على نفس مرضى الصباح الذين درّبتهم.",
    ],
    wrongEn: [
      "Ask for a decimal of hours and treat it as the transfer decision.",
      "Blend the two classes into a 0–100 score with no meaning.",
      "Test the decision on the same morning patients you trained.",
    ],
  },
  {
    id: "7-1-f19",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "مراقب جودة يريد قبول الكرتون أو رفضه على الخط، بينما مهندس آخر يريد مليمترات انحراف الطباعة.",
    sceneEn: "A quality inspector wants accept or reject on the line, while another engineer wants millimetres of print drift.",
    claimAr: "القبول/الرفض تصنيف؛ المليمترات انحدار. لا تخلط السؤالين.",
    claimEn: "Accept or reject is classification; millimetres are regression. Do not mix the questions.",
    whyAr: "نوع المخرج يحدّد إن كنت تتنبأ بفئة أو برقم.",
    whyEn: "The output type decides whether you predict a class or a number.",
    termAr: "تصنيف",
    termEn: "Classification",
    wrongAr: [
      "اجمع القرار والمليمتر في خانة واحدة ثم سمِّها ذكاءً.",
      "اختبر القبول على الكرتون الذي ضبطت عليه الألوان.",
      "استبدل القياس بعدّ صناديق الشاي في الاستراحة.",
    ],
    wrongEn: [
      "Cram the decision and the millimetre into one cell and call it intelligence.",
      "Test acceptance on the cartons you used to tune the colours.",
      "Replace the measure with a count of tea boxes in the break room.",
    ],
  },
  {
    id: "7-1-f20",
    lessonId: "7-1",
    chapterId: "7",
    sceneAr: "نموذج قبول مصنع درّب فقط على ملفات حيّ راقٍ، ثم حُكِم به على متقدمين من كل الأحياء.",
    sceneEn: "A factory-hiring model trained only on files from one wealthy district, then judged applicants from every district.",
    claimAr: "ارفض التعميم؛ الغذاء المنحاز يُخرج حكمًا منحازًا.",
    claimEn: "Refuse the rollout; biased food becomes a biased judgement.",
    whyAr: "النموذج يحفظ ما أطعمته، فإن أطعمته انحيازًا أخرجه انحيازًا.",
    whyEn: "A model remembers what you fed it; biased food becomes biased output.",
    termAr: "تصنيف",
    termEn: "Classification",
    wrongAr: [
      "ثق بالنتيجة لأن الحاسوب لا يتعب ولا يحقد.",
      "اختبر النموذج على نفس ملفات الحي الراقي.",
      "احذف عمود الحي كي يختفي الانحياز سحرًا.",
    ],
    wrongEn: [
      "Trust the result because a computer does not tire or hold a grudge.",
      "Test the model on the same wealthy-district files.",
      "Delete the district column so bias vanishes by magic.",
    ],
  },
  {
    id: "7-2-f01",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "طالب يشرح لزميله أن شبكة تمييز حرف على السبورة تبدأ من نقاط صغيرة في الصورة.",
    sceneEn: "A student explains to a classmate that a board-letter network starts from tiny spots in the image.",
    claimAr: "كل عصبون اصطناعي يجمع مدخلات موزونة ثم يفعّل خرجًا.",
    claimEn: "Each artificial neuron combines weighted inputs then activates an output.",
    whyAr: "العصبون وحدة حساب بسيطة؛ الشبكة تتكون من آلاف منها.",
    whyEn: "A neuron is a simple computing unit; a network is thousands of them.",
    termAr: "عصبون اصطناعي",
    termEn: "Artificial neuron",
    wrongAr: [
      "العصبون يحفظ الدرس كإنسان ثم يقرر بالضمير.",
      "طبقة واحدة تعني أن العصبونات اختفت.",
      "الوزن لون الزر في الموقع فقط.",
    ],
    wrongEn: [
      "The neuron memorizes the lesson like a person then decides by conscience.",
      "One layer means the neurons have vanished.",
      "A weight is only the website button colour.",
    ],
  },
  {
    id: "7-2-f02",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مزرعة دواجن تمرّر حرارة ورطوبة وضوضاء إلى وحدة واحدة قبل قرار التهوية.",
    sceneEn: "A poultry house feeds temperature, humidity, and noise into one unit before a vent decision.",
    claimAr: "عامل الوحدة كعصبون: تجمع إشارات موزونة ثم تخرج تشغيلًا أو توقفًا.",
    claimEn: "Treat the unit as a neuron: it gathers weighted signals then outputs on or off.",
    whyAr: "هذا هو دور العصبون الاصطناعي قبل أن تتكوّن الطبقات.",
    whyEn: "That is the job of an artificial neuron before layers stack up.",
    termAr: "عصبون اصطناعي",
    termEn: "Artificial neuron",
    wrongAr: [
      "تجاهل الأوزان وشغّل المروحة إن أعجبك صوتها.",
      "سمِّ الوحدة صندوقًا أسود لأنها زر واحد.",
      "استبدل الإشارات بقصة عن الفرخ.",
    ],
    wrongEn: [
      "Ignore the weights and run the fan if you like its sound.",
      "Call the unit a black box because it is one switch.",
      "Replace the signals with a chick story.",
    ],
  },
  {
    id: "7-2-f03",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "جهاز مراقبة سرير يجمع نبضًا وضغطًا وأكسجينًا في خلية حساب واحدة.",
    sceneEn: "A bedside monitor folds pulse, pressure, and oxygen into one computing cell.",
    claimAr: "الخلية عصبون اصطناعي: وزن لكل إشارة ثم تفعيل إن تجاوزت الحد.",
    claimEn: "The cell is an artificial neuron: a weight per signal, then an activation past a threshold.",
    whyAr: "من غير جمع موزون لا معنى لـ«تنبيه» من ثلاث قراءات معًا.",
    whyEn: "Without a weighted sum, three readings have no joint “alert” meaning.",
    termAr: "عصبون اصطناعي",
    termEn: "Artificial neuron",
    wrongAr: [
      "اجعل كل إشارة تصرخ وحدها من غير وزن.",
      "احذف الخلية لأن الطبيب يفهم من غير أرقام.",
      "عدّل دقة الشاشة بدل الأوزان.",
    ],
    wrongEn: [
      "Let each signal shout alone with no weight.",
      "Delete the cell because a doctor understands without numbers.",
      "Change screen resolution instead of the weights.",
    ],
  },
  {
    id: "7-2-f04",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مستشعر خط اللحام يقرأ حرارة وقوسًا وسرعة سلك في لحظة واحدة.",
    sceneEn: "A weld-line sensor reads heat, arc, and wire speed in one instant.",
    claimAr: "ادمج القراءات في عصبون يُخرج «لحام مقبول» أو «أوقف الخط».",
    claimEn: "Merge the readings in a neuron that outputs acceptable weld or stop the line.",
    whyAr: "العصبون يلخّص مدخلات كثيرة إلى قرار واحد قابل للتكديس في طبقات.",
    whyEn: "A neuron collapses many inputs into one decision that can stack into layers.",
    termAr: "عصبون اصطناعي",
    termEn: "Artificial neuron",
    wrongAr: [
      "اترك كل حساس يطبع تقريرًا أدبيًا منفصلًا.",
      "سمِّ الدمج هلوسة لغوية.",
      "اختبر القرار على شرارة اللحام التي ضُبط عليها فقط.",
    ],
    wrongEn: [
      "Let each sensor print a separate literary report.",
      "Call the merge a language hallucination.",
      "Test the decision only on the spark it was tuned on.",
    ],
  },
  {
    id: "7-2-f05",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "فريق الروبوت المدرسي يلاحظ أن الشبكة صارت تميّز الكرة بعد أسابيع تدريب.",
    sceneEn: "The school robot team notices the network started spotting the ball after weeks of training.",
    claimAr: "التعلم هنا يعدّل الأوزان: صلة اللون والحافة صارت أقوى.",
    claimEn: "Learning here adjusts weights: colour and edge links grew stronger.",
    whyAr: "الوزن قوة الصلة؛ من غير تعديله تبقى الشبكة عشوائية.",
    whyEn: "A weight is connection strength; without adjusting it the net stays random.",
    termAr: "وزن",
    termEn: "Weight",
    wrongAr: [
      "غيّر لون قميص الفريق وعدّ ذلك تعلمًا.",
      "احذف الطبقات لأن الوزن يكفي وحده.",
      "أعلن أن الروبوت فهم كرة القدم كإنسان.",
    ],
    wrongEn: [
      "Change the team shirt colour and call that learning.",
      "Delete the layers because a weight is enough alone.",
      "Announce that the robot understands football as a person does.",
    ],
  },
  {
    id: "7-2-f06",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "نموذج ريّ ذكي كان يهمل قراءة الملوحة ثم بدأ يقلّل الماء حين ارتفعت.",
    sceneEn: "A smart-irrigation model once ignored salinity, then started cutting water when salinity rose.",
    claimAr: "ارتفع وزن قناة الملوحة بعد أمثلة الضرر؛ هذا هو التعلم.",
    claimEn: "The salinity channel's weight rose after damage examples; that is learning.",
    whyAr: "تعديل الأوزان يغيّر أي إشارة تُصدَّق أكثر.",
    whyEn: "Adjusting weights changes which signal is trusted more.",
    termAr: "وزن",
    termEn: "Weight",
    wrongAr: [
      "ثبّت الأوزان العشوائية الأولى لأنها «طبيعية».",
      "استبدل الوزن بعدد النحل في الحقل.",
      "اختبر النموذج على نفس أيام الجفاف التي حفظها.",
    ],
    wrongEn: [
      "Freeze the first random weights because they feel “natural”.",
      "Replace the weight with a bee count in the field.",
      "Test the model on the same drought days it memorized.",
    ],
  },
  {
    id: "7-2-f07",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "شبكة فرز صور الأشعة كانت تضخم ضوضاء الجهاز حتى قلّ وزن تلك القناة.",
    sceneEn: "A scan-sorting network used to amplify machine noise until that channel's weight shrank.",
    claimAr: "خفّض وزن الإشارة الصاخبة وارفع وزن الحافة العظمية المفيدة.",
    claimEn: "Lower the noisy channel's weight and raise the useful bone-edge weight.",
    whyAr: "التعلم يعيد توزيع الثقة بين المدخلات عبر الأوزان.",
    whyEn: "Learning redistributes trust among inputs through weights.",
    termAr: "وزن",
    termEn: "Weight",
    wrongAr: [
      "ارفع صوت المروحة في الغرفة لتتعلم الشبكة.",
      "احذف كل الأوزان وسمِّ الناتج صندوقًا شفافًا.",
      "اطبع الوزن على سوار المريض.",
    ],
    wrongEn: [
      "Turn up the room fan so the network can learn.",
      "Delete every weight and call the result a glass box.",
      "Print the weight on the patient's wristband.",
    ],
  },
  {
    id: "7-2-f08",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "خط فرز التمور ما زال يخلط بين التمرة الداكنة والظل لأن الأوزان لم تُحدَّث.",
    sceneEn: "A date-sorting line still mixes a dark fruit with a shadow because the weights were never updated.",
    claimAr: "أعد التدريب ليتحرك الوزن الذي يفصل اللون عن الظل.",
    claimEn: "Retrain so the weight that separates colour from shadow can move.",
    whyAr: "أوزان ثابتة تعني شبكة لا تتعلم من أخطائها.",
    whyEn: "Frozen weights mean the network does not learn from its mistakes.",
    termAr: "وزن",
    termEn: "Weight",
    wrongAr: [
      "أضف طبقة ألوان للموقع الإلكتروني للمصنع.",
      "أعلن أن الظل فئة طبية.",
      "اختبر الخط على نفس صندوق التمر الذي ضُبط عليه.",
    ],
    wrongEn: [
      "Add a colour layer to the factory website.",
      "Announce that shadow is a medical class.",
      "Test the line on the same crate it was tuned on.",
    ],
  },
  {
    id: "7-2-f09",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مشروع تمييز وجوه الطلاب عند بوابة المعمل يضيف صفوف وحدات بين الصورة والقرار.",
    sceneEn: "A lab-gate face project inserts rows of units between the photo and the decision.",
    claimAr: "كل صف طبقة؛ العمق يعني طبقات مخفية أكثر لا زرًا سحريًا.",
    claimEn: "Each row is a layer; depth means more hidden layers, not a magic button.",
    whyAr: "الطبقة مجموعة عصبونات تعمل معًا قبل أن يصل القرار للخرج.",
    whyEn: "A layer is a group of neurons that work together before the output decides.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "العمق يعني شاشة أوضح فقط.",
      "احذف الطبقات المخفية لأن الوجه «واضح».",
      "سمِّ كل طبقة هلوسة.",
    ],
    wrongEn: [
      "Depth only means a sharper screen.",
      "Delete hidden layers because the face is “obvious”.",
      "Call every layer a hallucination.",
    ],
  },
  {
    id: "7-2-f10",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "كاميرا حصاد آلي تتعلم أولًا حواف الورقة، ثم شكل الثمرة، ثم «تفاحة جاهزة للقطف».",
    sceneEn: "A harvest camera first learns leaf edges, then fruit shape, then “apple ready to pick”.",
    claimAr: "الطبقات تبني تمثيلات: حافة ثم شكل ثم معنى القطف.",
    claimEn: "Layers build representations: edge, then shape, then pick-ready meaning.",
    whyAr: "الشبكة لا تخزّن الصورة خامًا؛ تتعلم ملامح أعمق طبقة بعد طبقة.",
    whyEn: "The network does not store the raw photo; it learns deeper features layer by layer.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "احفظ كل بكسل كما هو من غير تمثيل.",
      "اجعل الطبقة الأولى تخرج قرار القطف مباشرة من غير حواف.",
      "استبدل الطبقات بجدول عشر صفوف.",
    ],
    wrongEn: [
      "Store every pixel as-is with no representation.",
      "Let the first layer output the pick decision with no edges.",
      "Replace the layers with a ten-row table.",
    ],
  },
  {
    id: "7-2-f11",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "شبكة قراءة تخطيط القلب تبدأ بنتوءات صغيرة ثم بإيقاع ثم بتنبيه «غير منتظم».",
    sceneEn: "An ECG network starts with tiny spikes, then a rhythm, then an irregular alert.",
    claimAr: "هذا تعلم تمثيلات عبر طبقات، لا جملة سحرية واحدة.",
    claimEn: "This is representation learning across layers, not one magic sentence.",
    whyAr: "كل طبقة تلخّص ما قبلها إلى وصف أغنى.",
    whyEn: "Each layer summarises the one before it into a richer description.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "اطلب من الطبقة الأخيرة أن تعمل من غير مدخلات.",
      "عدّ الطبقات بدرجات الطلاب.",
      "اختبر التنبيه على نفس التخطيطات المحفوظة فقط.",
    ],
    wrongEn: [
      "Ask the last layer to work with no inputs.",
      "Count the layers as student marks.",
      "Test the alert only on the stored traces it memorized.",
    ],
  },
  {
    id: "7-2-f12",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "كاميرا جودة النسيج ترى خيطًا، ثم فجوة، ثم «ثقب يرفض القطعة».",
    sceneEn: "A fabric-quality camera sees a thread, then a gap, then “a hole that rejects the piece”.",
    claimAr: "رتّب طبقات تستخرج تمثيل الخيط ثم الثقب ثم قرار الرفض.",
    claimEn: "Stack layers that extract thread, then hole, then a reject decision.",
    whyAr: "العمق مفيد إن وُجدت صور كافية لتعلم تلك التمثيلات.",
    whyEn: "Depth helps if there are enough images to learn those representations.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "ضع عشرين طبقة على عشر صور وانتظر المعجزة.",
      "احذف التمثيل الأوسط لأن القرار أهم.",
      "سمِّ الثقب وزنًا.",
    ],
    wrongEn: [
      "Put twenty layers on ten photos and wait for a miracle.",
      "Delete the middle representation because the decision matters more.",
      "Call the hole a weight.",
    ],
  },
  {
    id: "7-2-f13",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "طالب يقترح شبكة عميقة لجدول غياب من اثني عشر صفًا في دفتر الفصل.",
    sceneEn: "A student proposes a deep net for a twelve-row absence table in the class register.",
    claimAr: "ارفض العمق هنا؛ المسألة الصغيرة لا تستحق شبكة جائعة للبيانات.",
    claimEn: "Refuse depth here; a small problem does not need a data-hungry net.",
    whyAr: "التعلم العميق يحتاج عادة بيانات وحسابًا أكبر من جدول ضيق.",
    whyEn: "Deep learning usually needs more data and compute than a thin table.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "أضف طبقات مخفية حتى يصير الجدول «ذكيًا».",
      "أعلن صندوقًا أسود لغياب حصة واحدة.",
      "اختبر الشبكة على الصفوف الاثني عشر نفسها.",
    ],
    wrongEn: [
      "Add hidden layers until the table becomes “smart”.",
      "Announce a black box for one missed period.",
      "Test the net on those same twelve rows.",
    ],
  },
  {
    id: "7-2-f14",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مزارع لديه أربعون صورة لنحل ويريد شبكة تميّز المرض كما في أبحاث بملايين الصور.",
    sceneEn: "A farmer has forty bee photos and wants a disease net like papers that used millions of images.",
    claimAr: "ابدأ بنموذج أبسط أو زد الصور كثيرًا؛ العمق بلا بيانات يفشل.",
    claimEn: "Start simpler or gather far more photos; depth without data fails.",
    whyAr: "الشبكة العميقة تتعلم تمثيلات غنية فقط إن أطعمتها أمثلة كافية.",
    whyEn: "A deep net learns rich representations only if you feed it enough examples.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "ضاعف الطبقات حتى تعوّض قلة الصور.",
      "أعلن أن الأربعون صورة تكفي لأن النحل «واضح».",
      "أخفِ ضعف البيانات خلف كلمة ذكاء اصطناعي.",
    ],
    wrongEn: [
      "Double the layers to make up for few photos.",
      "Announce that forty photos are enough because bees are “obvious”.",
      "Hide the thin data behind the words artificial intelligence.",
    ],
  },
  {
    id: "7-2-f15",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "عيادة صغيرة تملك سجل ضغط لثمانين مريضًا وتقترح شبكة من عشر طبقات للتنبؤ بسكتة.",
    sceneEn: "A small clinic has blood-pressure records for eighty patients and proposes a ten-layer stroke net.",
    claimAr: "اختر نموذجًا أبسط قابلًا للشرح؛ البيانات لا تحمل عمقًا كهذا.",
    claimEn: "Choose a simpler explainable model; the data cannot carry that depth.",
    whyAr: "حين تمس حياة إنسان نحتاج تفسيرًا وبيانات كافية معًا.",
    whyEn: "When a life is at stake we need both explanation and enough data.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "شغّل الصندوق الأسود لأن الاسم يبدو طبيًا.",
      "اختبر السكتة على نفس الثمانين ملفًا.",
      "استبدل السجل بقصة مولّدة فصيحة.",
    ],
    wrongEn: [
      "Run the black box because the name sounds medical.",
      "Test stroke prediction on those same eighty files.",
      "Replace the record with a fluent generated story.",
    ],
  },
  {
    id: "7-2-f16",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مهندس يقترح شبكة عميقة لجدول حرارة فرن من عشرة صفوف يومية.",
    sceneEn: "An engineer proposes a deep net for a ten-row daily kiln-temperature table.",
    claimAr: "الجدول الصغير يحتاج خطًا أو قاعدة، لا عمقًا أول خيار.",
    claimEn: "A tiny table needs a line or a rule, not depth as first choice.",
    whyAr: "العمق قوة فقط مع بيانات كافية وحساب يبرر التكلفة.",
    whyEn: "Depth is power only with enough data and compute that justify the cost.",
    termAr: "طبقة",
    termEn: "Layer",
    wrongAr: [
      "اجعل العمق واجبًا لأن المصنع حديث.",
      "أضف طبقات حتى يصبح الفرن صندوقًا أسود.",
      "اختبر الحرارة على أيام الضبط نفسها.",
    ],
    wrongEn: [
      "Make depth mandatory because the factory is modern.",
      "Add layers until the kiln becomes a black box.",
      "Test temperature on the same tuning days.",
    ],
  },
  {
    id: "7-2-f17",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مستشفى يريد رفض عملية لمريض اعتمادًا على شبكة لا أحد يشرح خرجها.",
    sceneEn: "A hospital wants to deny a patient surgery based on a network nobody can explain.",
    claimAr: "قف؛ الصندوق الأسود مشكلة كبيرة حين يمس القرار حياة إنسان.",
    claimEn: "Stop; a black box is a serious problem when the decision touches a human life.",
    whyAr: "المساءلة تتطلب سببًا مفهومًا لا رقمًا صامتًا.",
    whyEn: "Accountability needs a reason a person can follow, not a silent score.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "نفّذ الرفض لأن الدقة على التدريب بدت عالية.",
      "أخبر الأسرة أن الشبكة «تعرف» كالجراح.",
      "احذف اسم النموذج من الملف كي يهدأ النقاش.",
    ],
    wrongEn: [
      "Carry out the denial because the training score looked high.",
      "Tell the family the network “knows” like a surgeon.",
      "Delete the model name from the file so debate cools.",
    ],
  },
  {
    id: "7-2-f18",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "إدارة المدرسة تفصل طالبًا من منحة لأن نموذجًا عميقًا أعطى درجة خطر من غير سبب مقروء.",
    sceneEn: "School leadership drops a student from a scholarship because a deep model issued a risk score with no readable reason.",
    claimAr: "اطلب تفسيرًا بشريًا قبل القرار؛ الصندوق الأسود لا يكفي للعقاب.",
    claimEn: "Demand a human explanation before the decision; a black box is not enough for punishment.",
    whyAr: "قرار يغيّر مسار طالب يحتاج سببًا يمكن مراجعته.",
    whyEn: "A decision that changes a student's path needs a reason that can be reviewed.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "نفّذ الفصل لأن الطبقة العميقة تبدو علمية.",
      "أظهر الدرجة للأهل من غير معنى.",
      "اختبر الخطر على نفس ملفات المنحة القديمة فقط.",
    ],
    wrongEn: [
      "Carry out the drop because a deep layer looks scientific.",
      "Show families the score with no meaning.",
      "Test risk only on the old scholarship files.",
    ],
  },
  {
    id: "7-2-f19",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "مصنع يقترح فصل عامل بسبب تنبؤ شبكة «ضعف إنتاج» بلا معرفة أي وردية أو آلة أثّرت.",
    sceneEn: "A factory proposes firing a worker over a net's “low output” prediction with no idea which shift or machine mattered.",
    claimAr: "ارفض الفصل الآلي؛ حياة الراتب تستحق تفسير أوزان وطبقة القرار.",
    claimEn: "Refuse automatic firing; a livelihood deserves an explanation of weights and the decision layer.",
    whyAr: "الصندوق الأسود غير مقبول حين يُفصل إنسان من عمله.",
    whyEn: "A black box is unacceptable when a person is dismissed from work.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "أرسل خطاب الفصل مع شعار الذكاء الاصطناعي.",
      "قل إن الأوزان سرّ تجاري يغني عن الشرح للعامل.",
      "درّب الشبكة على شكاوى المشرف فقط.",
    ],
    wrongEn: [
      "Send the dismissal letter with an artificial-intelligence logo.",
      "Say the weights are a trade secret that replaces an explanation to the worker.",
      "Train the net only on the supervisor's complaints.",
    ],
  },
  {
    id: "7-2-f20",
    lessonId: "7-2",
    chapterId: "7",
    sceneAr: "وحدة إسعاف تريد نموذجًا يختار من يُنقل أولًا بعد حادث طريق، والمهندس يمدح أن أحدًا لا يفهم الداخل.",
    sceneEn: "An ambulance unit wants a model that picks who is moved first after a crash, and the engineer praises that nobody understands the inside.",
    claimAr: "التفاخر بالغموض خطر؛ قرار حياة يحتاج تمثيلًا قابلًا للمراجعة.",
    claimEn: "Boasting about opacity is dangerous; a life decision needs a reviewable representation.",
    whyAr: "الصندوق الأسود مشكلة أخلاقية لا ميزة تسويق عندما يُرتَّب جرحى.",
    whyEn: "A black box is an ethical problem, not a marketing feature, when wounded people are ranked.",
    termAr: "الصندوق الأسود",
    termEn: "Black box",
    wrongAr: [
      "اعتمد الترتيب الليلي لأن الغموض يبدو متقدمًا.",
      "اختبر النموذج على نفس حوادث التدريب.",
      "استبدل المراجعة الطبية بجملة فصيحة من نموذج لغة.",
    ],
    wrongEn: [
      "Adopt the night ranking because opacity looks advanced.",
      "Test the model on the same training crashes.",
      "Replace medical review with a fluent sentence from a language model.",
    ],
  },
  {
    id: "7-3-f01",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "طالب يسأل النموذج أن «يعرف» كم درجة سيحصل في امتحان لم يُصحَّح بعد.",
    sceneEn: "A student asks the model to “know” the mark he will get on an exam that is not marked yet.",
    claimAr: "ذكّره أن النموذج يتوقع أرجح رمز تالٍ؛ لا يعلم الغيب.",
    claimEn: "Remind him the model predicts the next likely token; it does not know the future.",
    whyAr: "نموذج اللغة الكبير لا يعرف كالإنسان؛ يحسب تكملة محتملة.",
    whyEn: "An LLM does not know as a person does; it scores a likely completion.",
    termAr: "نموذج لغة كبير",
    termEn: "LLM",
    wrongAr: [
      "صدّق الرقم لأن الجملة جاءت واثقة.",
      "ألصق إجابة النموذج في ورقة الإجابة النهائية.",
      "أرسل للنموذج كشف درجات الزملاء ليصبح أدق.",
    ],
    wrongEn: [
      "Believe the number because the sentence sounded confident.",
      "Paste the model's answer onto the final script.",
      "Send it classmates' mark sheets so it becomes more accurate.",
    ],
  },
  {
    id: "7-3-f02",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "مزارع يطلب من النموذج تقريرًا عن رطوبة تربة حقله الليلة كأنه محطة أرصاد في المزرعة.",
    sceneEn: "A farmer asks the model for tonight's soil moisture on his field as if it were a station on the farm.",
    claimAr: "استخدمه لشرح فكرة الرطوبة، ثم قِس أنت؛ هو لا يرى الحقل.",
    claimEn: "Use it to explain moisture as an idea, then measure yourself; it cannot see the field.",
    whyAr: "النص الفصيح تكملة رموز لا قراءة حسّاس في الأرض.",
    whyEn: "Fluent text is token completion, not a sensor in the soil.",
    termAr: "نموذج لغة كبير",
    termEn: "LLM",
    wrongAr: [
      "اروِ الحقل حسب جرعة اخترعها النموذج.",
      "ألصق عنوان المزرعة في المحادثة ليصدق أكثر.",
      "اعتبِر التقرير معرفة يقينية.",
    ],
    wrongEn: [
      "Irrigate by a dose the model invented.",
      "Paste the farm address into the chat so it becomes truer.",
      "Treat the report as certain knowledge.",
    ],
  },
  {
    id: "7-3-f03",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "ممرضة تريد من النموذج أن يؤكد دواء مريض كأن له ملفًا في المستشفى.",
    sceneEn: "A nurse wants the model to confirm a patient's drug as if it held a hospital file.",
    claimAr: "لا تطلب معرفة سريرية من مكمل نص؛ راجع البروتوكول البشري.",
    claimEn: "Do not ask a text completer for clinical knowledge; check the human protocol.",
    whyAr: "النموذج لا يملك ملف المريض ولا «يعرف» الدواء؛ يتوقع كلمات.",
    whyEn: "The model has no patient file and does not “know” the drug; it predicts words.",
    termAr: "نموذج لغة كبير",
    termEn: "LLM",
    wrongAr: [
      "غيّر الجرعة لأن الرد بدا طبيًا.",
      "ارفع صورة بطاقة المريض إلى المحادثة.",
      "ألصق التشخيص في السجل من غير طبيب.",
    ],
    wrongEn: [
      "Change the dose because the reply sounded medical.",
      "Upload the patient's ID photo into the chat.",
      "Paste the diagnosis into the record with no doctor.",
    ],
  },
  {
    id: "7-3-f04",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "مشرف مصنع يطلب من النموذج شهادة سلامة للآلة الجديدة في سطرين واثقين.",
    sceneEn: "A factory supervisor asks the model for a two-line confident safety certificate for a new machine.",
    claimAr: "ارفض الشهادة اللغوية؛ النموذج يكمّل نصًا ولا يفحص الماكينة.",
    claimEn: "Refuse a linguistic certificate; the model completes text and does not inspect the machine.",
    whyAr: "الفصاحة ليست تفتيشًا، والتكملة ليست معرفة هندسية.",
    whyEn: "Fluency is not an inspection, and completion is not engineering knowledge.",
    termAr: "نموذج لغة كبير",
    termEn: "LLM",
    wrongAr: [
      "علّق الورقة الفصيحة على الآلة وعدّها اعتمادًا.",
      "أرسل رقم الهوية الوطنية للمشغّل لتحسين الرد.",
      "اختبر الأمان على النص الذي درّب النموذج.",
    ],
    wrongEn: [
      "Pin the fluent page on the machine and treat it as approval.",
      "Send the operator's national ID to improve the reply.",
      "Test safety on the text that trained the model.",
    ],
  },
  {
    id: "7-3-f05",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "طالب يكتب «اشرح» فقط ثم يغضب لأن رد النموذج عن الشبكات عام وبلا مثال مدرسي.",
    sceneEn: "A student types only “explain” then gets angry that the network reply is generic and has no school example.",
    claimAr: "أعد صياغة الأمر: حدّد الدرس والجمهور ومثالًا تريده.",
    claimEn: "Rewrite the prompt: name the lesson, the audience, and an example you want.",
    whyAr: "توجيه الأوامر يغيّر جودة الرد لأن النموذج يكمّل ما تلمّح إليه.",
    whyEn: "Prompting changes reply quality because the model completes the hint you give.",
    termAr: "توجيه الأوامر",
    termEn: "Prompting",
    wrongAr: [
      "اصدح بصوت أعلى في الميكروفون.",
      "ألصق واجب زميلك كاملًا ليقلّده.",
      "اعتبر الغموض في سؤالك دليل عبقرية النموذج.",
    ],
    wrongEn: [
      "Shout louder into the microphone.",
      "Paste a classmate's full homework so it can copy.",
      "Treat a vague question as proof the model is brilliant.",
    ],
  },
  {
    id: "7-3-f06",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "مزارع يسأل «ما السماد؟» بلا ذكر المحصول أو نوع التربة أو الشهر.",
    sceneEn: "A farmer asks “what fertilizer?” with no crop, soil type, or month.",
    claimAr: "قيّد الأمر: محصول، تربة، شهر، واطلب خطوات لا جرعة قاطعة.",
    claimEn: "Tighten the prompt: crop, soil, month, and ask for steps, not a final dose.",
    whyAr: "أمر ناقص يُكمل بكلام عام قد لا يناسب الحقل.",
    whyEn: "A thin prompt is completed with generic talk that may not fit the field.",
    termAr: "توجيه الأوامر",
    termEn: "Prompting",
    wrongAr: [
      "اقبل أول رقم سماد لأن الجملة سلسة.",
      "أرفق صورة بطاقة المالك «للتخصيص».",
      "اطلب قصيدة بدل شروط الحقل.",
    ],
    wrongEn: [
      "Accept the first fertilizer number because the sentence is smooth.",
      "Attach the owner's ID photo “for personalization”.",
      "Ask for a poem instead of field conditions.",
    ],
  },
  {
    id: "7-3-f07",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "طالب تمريض يكتب «شخص هذه الأعراض» ويلصق شكوى مريض من غير سياق مقرر.",
    sceneEn: "A nursing student types “diagnose these symptoms” and pastes a patient's complaint with no course context.",
    claimAr: "حوّل الأمر إلى شرح مفاهيم الدرس، لا إلى تشخيص شخص.",
    claimEn: "Turn the prompt into an explanation of lesson ideas, not a person's diagnosis.",
    whyAr: "حسن التوجيه يحدد المهمة الآمنة: تعلّم لا قرار طبي.",
    whyEn: "Good prompting sets a safe task: learning, not a medical decision.",
    termAr: "توجيه الأوامر",
    termEn: "Prompting",
    wrongAr: [
      "أضف اسم المريض وعنوانه ليصبح الرد أدق.",
      "اطلب خطة علاج نهائية للتوقيع.",
      "انسخ التشخيص إلى ملف العيادة.",
    ],
    wrongEn: [
      "Add the patient's name and address so the reply gets sharper.",
      "Ask for a final treatment plan to sign.",
      "Copy the diagnosis into the clinic file.",
    ],
  },
  {
    id: "7-3-f08",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "فني سلامة يطلب «اكتب أي شيء عن الحريق» في مصنع دهانات.",
    sceneEn: "A safety tech asks “write anything about fire” in a paint factory.",
    claimAr: "حدّد الأمر: قائمة فحص إخلاء من غير أسرار العاملين.",
    claimEn: "Specify the prompt: an evacuation checklist with no workers' secrets.",
    whyAr: "الأمر الواضح يقلّل الكلام العام ويرفع فائدة التدريب.",
    whyEn: "A clear prompt cuts generic talk and raises the value of the drill.",
    termAr: "توجيه الأوامر",
    termEn: "Prompting",
    wrongAr: [
      "اترك الأمر فضفاضًا ثم طبّق أول جملة على الخط.",
      "ارفع كشوف رواتب العمال مع السؤال.",
      "اطلب رواية رعب بدل خطوات الإخلاء.",
    ],
    wrongEn: [
      "Leave the prompt loose then apply the first sentence on the line.",
      "Upload workers' pay sheets with the question.",
      "Ask for a horror story instead of evacuation steps.",
    ],
  },
  {
    id: "7-3-f09",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "تقرير واجب يستشهد بكتاب ومؤلف وتاريخ يبدو مثاليًا، والمكتبة لا تجد أيًا منها.",
    sceneEn: "A homework report cites a book, author, and date that look perfect, and the library finds none of them.",
    claimAr: "هذا هلوسة: جملة فصيحة بلا سند. احذف الاستشهاد واكتب من مصدر حقيقي.",
    claimEn: "This is a hallucination: fluent text with no grounding. Drop the citation and write from a real source.",
    whyAr: "سلاسة اللغة لا تثبت أن المرجع وُجد.",
    whyEn: "Smooth language does not prove the reference exists.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "أبقِ المرجع لأن الأسلوب أكاديمي.",
      "زد فصاحة المقدمة لتغطي الكذب.",
      "أرسل درجات الصف للنموذج ليخترع مراجع أفضل.",
    ],
    wrongEn: [
      "Keep the reference because the style looks academic.",
      "Increase the fluency of the intro to cover the lie.",
      "Send the class marks to the model so it invents better sources.",
    ],
  },
  {
    id: "7-3-f10",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "النموذج يقترح على مزارع مبيدًا بتركيز محدد واسم شركة لا وجود لها في السوق.",
    sceneEn: "The model suggests a farmer a precise pesticide dose and a company name that does not exist in the market.",
    claimAr: "عامل النص هلوسة خطرة؛ لا ترش قبل مصدر زراعي موثوق.",
    claimEn: "Treat the text as a dangerous hallucination; do not spray before a trusted farm source.",
    whyAr: "التفاصيل الرقمية الفصيحة قد تكون اختراع تكملة.",
    whyEn: "Fluent numeric detail can be an invented completion.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "اشترِ المبيد فورًا لأن الجرعة كُتبت بثقة.",
      "أرفق صورة هويتك لتصحيح اسم الشركة.",
      "اعتبِر الاسم الغريب دليل بحث عميق.",
    ],
    wrongEn: [
      "Buy the pesticide at once because the dose was written with confidence.",
      "Attach your ID photo to correct the company name.",
      "Treat the strange name as proof of deep research.",
    ],
  },
  {
    id: "7-3-f11",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "النموذج يذكر مدىً معمليًا لإنزيم كأنه من دليل المستشفى، والقسم لا يعتمد ذلك المدى.",
    sceneEn: "The model states an enzyme range as if from the hospital handbook, and the department does not use that range.",
    claimAr: "لا تنقل المدى إلى الملف؛ الفصاحة ليست دليل صدق.",
    claimEn: "Do not copy the range into the file; fluency is not proof of truth.",
    whyAr: "الهلوسة تظهر كجملة طبية أنيقة بلا سند محلي.",
    whyEn: "A hallucination can look like an elegant medical sentence with no local grounding.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "حدّث الدليل لأن النموذج أحدث من اللجنة.",
      "ألصق رقم السرير في الأمر ليصبح المدى صحيحًا.",
      "أخفِ المصدر تحت عبارة «ذكاء اصطناعي».",
    ],
    wrongEn: [
      "Update the handbook because the model is newer than the committee.",
      "Paste the bed number into the prompt so the range becomes true.",
      "Hide the source under the words “artificial intelligence”.",
    ],
  },
  {
    id: "7-3-f12",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "تقرير مصنع يستشهد برقم مواصفة سلامة يبدو رسميًا ولا يوجد في أي قائمة.",
    sceneEn: "A factory report cites a safety-standard number that looks official and exists on no list.",
    claimAr: "اشطب الرقم؛ الهلوسة تتقن شكل الوثائق.",
    claimEn: "Strike the number; hallucination is good at the look of documents.",
    whyAr: "الشكل الرسمي تكملة رموز لا رخصة قانونية.",
    whyEn: "An official look is token completion, not a legal licence.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "علّق الرقم على الجدار لأن الخط يبدو وزاريًا.",
      "أرسل عناوين منازل العمّال مع الطلب «للتدقيق».",
      "أعد توليد النص حتى يوافق هواك من غير مصدر.",
    ],
    wrongEn: [
      "Hang the number on the wall because the font looks official.",
      "Send workers' home addresses with the request “for audit”.",
      "Regenerate the text until it matches your wish with no source.",
    ],
  },
  {
    id: "7-3-f13",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "طالب يرى الرد يظهر كلمة بعد كلمة في نافذة الدردشة ويظن أن النموذج يفكر صامتًا ثم يكشف السر.",
    sceneEn: "A student watches the reply appear word by word in the chat and thinks the model thinks in silence then reveals a secret.",
    claimAr: "ما تراه توقع رمز/توكن تالٍ لا كشف معرفة مخفية.",
    claimEn: "What you see is the next token prediction, not a hidden mind opening.",
    whyAr: "الوحدة التي يتنبأ بها النموذج رمز نصي يتبع رمزًا.",
    whyEn: "The unit the model predicts is a text token after a token.",
    termAr: "رمز / توكن",
    termEn: "Token",
    wrongAr: [
      "صدّق أنه يسترجع ذاكرتك المدرسية كلمة كلمة.",
      "أدخل رقم هويتك ليختار توكنات أصدق.",
      "أوقف ظهور الكلمات وعدّ الصمت دليل فهم.",
    ],
    wrongEn: [
      "Believe it is retrieving your school memory word by word.",
      "Enter your ID number so it picks truer tokens.",
      "Stop the words from appearing and treat silence as proof of understanding.",
    ],
  },
  {
    id: "7-3-f14",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "تطبيق إرشاد زراعي يكمّل جملة «التربة الطينية تحتاج…» في الحقل.",
    sceneEn: "A farm-advice app completes the sentence “clay soil needs…” in the field.",
    claimAr: "اعتبر التكملة سلسلة توكنات محتملة، ثم راجع دليل الزراعة.",
    claimEn: "Treat the completion as a chain of likely tokens, then check a farm guide.",
    whyAr: "النموذج لا يفهم التربة؛ يمدّ النص بالرمز الأرجح.",
    whyEn: "The model does not understand soil; it extends text with the likeliest token.",
    termAr: "رمز / توكن",
    termEn: "Token",
    wrongAr: [
      "اروِ فورًا بما كُتب لأن السلسلة اكتملت.",
      "ألصق إحداثيات البيت مع الجملة.",
      "سمِّ كل توكن حقيقة علمية.",
    ],
    wrongEn: [
      "Irrigate at once with whatever was written because the chain finished.",
      "Paste the home coordinates with the sentence.",
      "Call every token a scientific fact.",
    ],
  },
  {
    id: "7-3-f15",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "مسودة خطاب خروج مريض تُكتب توكنًا بعد توكن وتقترح موعد مراجعة لم يطلبه الطبيب.",
    sceneEn: "A draft discharge note is written token by token and suggests a follow-up date the doctor never asked for.",
    claimAr: "راجع كل رمز أُضيف؛ التكملة ليست أمر خروج.",
    claimEn: "Review every added token; completion is not a discharge order.",
    whyAr: "توقع الرمز التالي قد يُدخل موعدًا مخترعًا يبدو طبيعيًا.",
    whyEn: "Next-token prediction can insert an invented date that looks natural.",
    termAr: "رمز / توكن",
    termEn: "Token",
    wrongAr: [
      "اطبع الخطاب كما اكتمل لأن اللغة سلسة.",
      "أضف عنوان بيت المريض لتحسين الأسلوب.",
      "اعتبِر الموعد معرفة لأن التوكنات توقفت.",
    ],
    wrongEn: [
      "Print the letter as completed because the language is smooth.",
      "Add the patient's home address to improve the style.",
      "Treat the date as knowledge because the tokens stopped.",
    ],
  },
  {
    id: "7-3-f16",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "مولّد تقارير الوردية في المصنع يكمل «الحادث سببه…» بجملة لم يكتبها أي شاهد.",
    sceneEn: "A factory shift-report generator completes “the accident was caused by…” with a sentence no witness wrote.",
    claimAr: "قف عند أول توكن اختراعي؛ اكتب السبب من محضر بشري.",
    claimEn: "Stop at the first invented token; write the cause from a human record.",
    whyAr: "سلسلة الرموز تفضّل جملة مكتملة على جملة صادقة.",
    whyEn: "A token chain prefers a finished sentence over a true one.",
    termAr: "رمز / توكن",
    termEn: "Token",
    wrongAr: [
      "وقّع التقرير لأن الإكمال بدا قانونيًا.",
      "ارفع صور بطاقات الشهود إلى المولّد.",
      "أعد التوليد حتى يُلام العامل الأضعف.",
    ],
    wrongEn: [
      "Sign the report because the completion looked legal.",
      "Upload witness ID photos into the generator.",
      "Regenerate until the weakest worker is blamed.",
    ],
  },
  {
    id: "7-3-f17",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "طالب استخدم النموذج ليفهم الفرق بين التصنيف والانحدار ثم همّ بلصق الفقرة في الواجب.",
    sceneEn: "A student used the model to understand classification versus regression then almost pasted the paragraph into the homework.",
    claimAr: "أغلق النافذة واكتب من فهمك؛ الشرح مساعد لا بديل عن صوتك.",
    claimEn: "Close the window and write from your understanding; the explanation is a helper, not your voice.",
    whyAr: "الاستخدام السليم: افهم ثم اكتب أنت، لا تنقل تكملة جاهزة.",
    whyEn: "Sound use: understand, then you write; do not ship a ready completion.",
    termAr: "توجيه الأوامر",
    termEn: "Prompting",
    wrongAr: [
      "ألصق الفقرة كما خرجت لأن الفصاحة أعلى من أسلوبك.",
      "أبقِ الدردشة مفتوحة أثناء تسليم الملف.",
      "اطلب من النموذج أن يقلّد خط يدك.",
    ],
    wrongEn: [
      "Paste the paragraph as emitted because its fluency beats your style.",
      "Leave the chat open while you submit the file.",
      "Ask the model to imitate your handwriting.",
    ],
  },
  {
    id: "7-3-f18",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "زميل يلصق في الدردشة كشف درجات الصف وعناوين البيوت «كي يخصص النموذج المذاكرة».",
    sceneEn: "A classmate pastes the class mark sheet and home addresses into chat “so the model can personalise revision”.",
    claimAr: "امحُ الرسالة فورًا؛ الدرجات والعنوان والهوية أسرار لا تُطعَم للنموذج.",
    claimEn: "Delete the message at once; marks, an address, and an ID are secrets you do not feed a model.",
    whyAr: "ما يُلصق قد يُحفَظ أو يُعرض حيث لا يجب.",
    whyEn: "Whatever you paste may be stored or shown where it should not be.",
    termAr: "نموذج لغة كبير",
    termEn: "LLM",
    wrongAr: [
      "أضف صور البطاقات لتكتمل الخصوصية المعكوسة.",
      "برّر اللصق بأنه تمرين توجيه أوامر.",
      "انشر الرد مع الأسماء في مجموعة الصف.",
    ],
    wrongEn: [
      "Add ID photos to complete the inverted privacy.",
      "Excuse the paste as a prompting exercise.",
      "Post the reply with names in the class group.",
    ],
  },
  {
    id: "7-3-f19",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "متدرب في الاستقبال يصوّر بطاقة مريض ويرفعها لنموذج «ليملأ الاستمارة أسرع».",
    sceneEn: "A reception trainee photographs a patient's ID and uploads it to a model “to fill the form faster”.",
    claimAr: "أوقف الرفع؛ صورة البطاقة سرّ وليست توكن تدريب.",
    claimEn: "Stop the upload; an ID photo is a secret, not a training token.",
    whyAr: "الهوية والعنوان ليسا مادة لتكملة لغوية.",
    whyEn: "Identity and address are not material for linguistic completion.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "أكمل الرفع لأن السرعة خدمة.",
      "اكتب الرقم القومي في الأمر علنًا.",
      "صدّق الحقول التي ملأها النموذج من غير عين بشرية.",
    ],
    wrongEn: [
      "Finish the upload because speed is a service.",
      "Type the national ID into the prompt in public.",
      "Trust the fields the model filled with no human eye.",
    ],
  },
  {
    id: "7-3-f20",
    lessonId: "7-3",
    chapterId: "7",
    sceneAr: "ملصق مصنع يعلن «كلام النموذج سلس إذن تعليمات التشغيل صحيحة».",
    sceneEn: "A factory poster announces “the model's language is fluent, so the operating instructions are true”.",
    claimAr: "انزع الملصق؛ اللغة السلسة ليست دليل صدق.",
    claimEn: "Take the poster down; fluent language is not proof of truth.",
    whyAr: "الفصاحة مهارة إكمال توكنات، والصدق يحتاج مصدرًا بشريًا.",
    whyEn: "Fluency is a skill of completing tokens; truth needs a human source.",
    termAr: "هلوسة",
    termEn: "Hallucination",
    wrongAr: [
      "زِد فصاحة الملصق بدل مراجعة المهندس.",
      "أرفق عنوان المصنع السري في التذييل.",
      "ألغِ تدريب العمال لأن النص يبدو كافيًا.",
    ],
    wrongEn: [
      "Increase the poster's fluency instead of an engineer's review.",
      "Add the factory's private address in the footer.",
      "Cancel worker training because the text looks enough.",
    ],
  },
];

export const CHAPTER_7_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "7-1-a01",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "حلّل قرار مزرعة تريد التفرقة بين بيض صالح للكسر وبيض للتفريخ: أي نوع تعلم تختار، وما الذي يجب أن تحمله كل صورة أو سجل؟",
    promptEn: "Analyse a farm that wants to separate cracking eggs from hatching eggs: which learning type do you choose, and what must each photo or record carry?",
    guideAr: "اربط المهمة بمخرج معلّم (فئتان)، واذكر أن الإشراف يحتاج مثالًا ونتيجته، وحذّر من صور بلا تسمية.",
    guideEn: "Tie the task to a labeled output (two classes), note that supervision needs an example and its result, and warn against unlabeled photos.",
  },
  {
    id: "7-1-a02",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "قارن توقع «يحضر المريض أو يغيب» بتوقع «عدد دقائق الانتظار» في عيادة واحدة: أين التصنيف وأين الانحدار ولماذا لا يكفي جدول واحد بلا سؤال؟",
    promptEn: "Compare predicting “the patient attends or misses” with predicting “waiting minutes” in one clinic: where is classification, where is regression, and why is a table without a question not enough?",
    guideAr: "التصنيف فئة محدودة، والانحدار رقم. السؤال يحدد العمود المستهدف لا شكل الجدول.",
    guideEn: "Classification is a limited class; regression is a number. The question picks the target column, not the look of the table.",
  },
  {
    id: "7-1-a03",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "انتقد طالبًا اختبر نموذج توقع رسوب على كل أوراق صفه ثم أعلن جاهزية النموذج لامتحان مدرسة أخرى.",
    promptEn: "Critique a student who tested a fail-predictor on every paper in his class then declared the model ready for another school's exam.",
    guideAr: "بيّن أن الاختبار على التدريب يعطي درجة متفائلة كاذبة، وأن المدرسة الأخرى توزيع مختلف.",
    guideEn: "Show that testing on training gives a falsely optimistic score, and the other school is a different distribution.",
  },
  {
    id: "7-1-a04",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "اشرح لماذا يكرر نموذج جودة مصنع رفض علب حيّ واحد إن كانت علب التدريب كلها من ذلك الحي.",
    promptEn: "Explain why a factory quality model keeps rejecting cans from one district if every training can came from that district.",
    guideAr: "اربط الجودة بالبيانات: الغذاء المنحاز يخرج حكمًا منحازًا، والحاسوب لا يعدّل العدالة وحده.",
    guideEn: "Tie quality to data: biased food becomes biased output, and a computer does not repair fairness by itself.",
  },
  {
    id: "7-1-a05",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "حلّل استخدام تجميع بلا إشراف لمرضى عيادة لديهم قياسات بلا تشخيص مكتوب: ماذا يقدّم النموذج وماذا يبقى على الطبيب؟",
    promptEn: "Analyse unsupervised clustering of clinic patients who have measurements but no written diagnosis: what can the model offer, and what stays with the doctor?",
    guideAr: "النموذج يبرز تجمعات؛ التشخيص والتسمية قرار بشري. لا تُعلن دقة شفاء من غير عمود مخرج.",
    guideEn: "The model highlights groups; naming a diagnosis stays human. Do not announce a cure score with no output column.",
  },
  {
    id: "7-1-a06",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "قارن مشروعًا مدرسيًا يتنبأ ناجح/راسب بمشروع يبحث عن مجموعات أساليب مذاكرة من غير عمود نتيجة.",
    promptEn: "Compare a school project that predicts pass or fail with a project that looks for study-habit groups with no outcome column.",
    guideAr: "الأول بإشراف لأن المخرج معروف، والثاني بلا إشراف لأنه بحث عن نمط. لا تختبر الاثنين بأداة واحدة.",
    guideEn: "The first is supervised because the output is known; the second is unsupervised because it seeks a pattern. Do not score both with one tool.",
  },
  {
    id: "7-1-a07",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "انتقد ملصق مصنع يكتب «دقة 100٪» تحت صورة الخط نفسه الذي استُخدم في التدريب فقط.",
    promptEn: "Critique a factory poster that writes “100% accuracy” under a photo of the same line used only for training.",
    guideAr: "الرقم يقيس الحفظ لا الجودة على وردية جديدة. اطلب مجموعة اختبار لم يرها النموذج.",
    guideEn: "The number measures memorization, not quality on a new shift. Demand a test set the model has not seen.",
  },
  {
    id: "7-1-a08",
    lessonId: "7-1",
    chapterId: "7",
    promptAr: "اشرح لماذا يفصل مستشفى صور يناير للتدريب عن صور مارس للاختبار قبل اعتماد كاشف كسور.",
    promptEn: "Explain why a hospital keeps January scans for training and March scans for testing before approving a fracture detector.",
    guideAr: "القياس الصادق يحتاج جزءًا زمنيًا لم يدخل التعلم. إعادة استخدام يناير تعطي تفاؤلًا كاذبًا.",
    guideEn: "Honest measurement needs a later split that never entered learning. Reusing January yields false optimism.",
  },
  {
    id: "7-2-a01",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "حلّل كيف تبني طبقات كاميرا حصاد تمثيلات من حافة الورقة إلى شكل الثمرة إلى قرار القطف.",
    promptEn: "Analyse how a harvest camera's layers build representations from a leaf edge to fruit shape to a pick decision.",
    guideAr: "كل طبقة تلخّص ما قبلها. التمثيل يتدرج؛ القرار الأخير ليس جملة سحرية في الطبقة الأولى.",
    guideEn: "Each layer summarises the one before it. Representation deepens; the last decision is not a magic sentence in the first layer.",
  },
  {
    id: "7-2-a02",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "قارن شبكةً من عشر طبقات على جدول حرارة فرن بعشرة صفوف بخط بسيط على البيانات نفسها.",
    promptEn: "Compare a ten-layer net on a ten-row kiln-temperature table with a simple line on the same data.",
    guideAr: "العمق يحتاج بيانات كثيرة. الجدول الصغير يناسب نموذجًا أبسط وأوضح للمساءلة.",
    guideEn: "Depth needs lots of data. A tiny table fits a simpler model that is easier to hold to account.",
  },
  {
    id: "7-2-a03",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "انتقد مستشفى يرفض عملية لمريض لأن شبكةً لا يشرحها أحد أعطت درجة خطر صامتة.",
    promptEn: "Critique a hospital that denies a patient surgery because a network nobody can explain issued a silent risk score.",
    guideAr: "الصندوق الأسود مشكلة عندما يمس القرار حياة. اطلب سببًا قابلًا للمراجعة وبيانات كافية.",
    guideEn: "A black box is a problem when the decision touches a life. Demand a reviewable reason and enough data.",
  },
  {
    id: "7-2-a04",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "اشرح لماذا يتغير قرار ريّ ذكي بعد أسابيع حتى لو بقيت الحساسات كما هي.",
    promptEn: "Explain why a smart-irrigation decision can change after weeks even if the sensors stay the same.",
    guideAr: "التعلم يعدّل الأوزان: قناة كانت ضعيفة قد تُصدَّق أكثر بعد أمثلة الضرر.",
    guideEn: "Learning adjusts weights: a weak channel may be trusted more after damage examples.",
  },
  {
    id: "7-2-a05",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "حلّل فصل طالب من منحة بدرجة خطر عميقة من غير سبب مقروء للأهل.",
    promptEn: "Analyse dropping a student from a scholarship on a deep risk score with no readable reason for the family.",
    guideAr: "قرار يغيّر مسار إنسان يحتاج تفسير طبقة القرار لا رقمًا صامتًا. الصندوق الأسود لا يكفي.",
    guideEn: "A path-changing decision needs an explanation of the decision layer, not a silent number. A black box is not enough.",
  },
  {
    id: "7-2-a06",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "قارن عصبونًا واحدًا يجمع حرارة ورطوبة في مزرعة دواجن بشبكة طبقات تقرأ صورة القطيع.",
    promptEn: "Compare one neuron that combines heat and humidity in a poultry house with a layered net that reads a flock photo.",
    guideAr: "العصبون وحدة جمع موزون. الشبكة تكدّس طبقات لتمثيل أغنى، وتحتاج بيانات أكبر.",
    guideEn: "A neuron is a weighted-sum unit. A network stacks layers for a richer representation and needs more data.",
  },
  {
    id: "7-2-a07",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "انتقد اقتراح شبكة قيادة ذاتية عميقة على عشرين صورة شارع التقطها طالب بجانب المدرسة.",
    promptEn: "Critique a proposal for a deep self-driving net trained on twenty street photos a student took beside the school.",
    guideAr: "التمثيل الغني لا يُشترى بعدد طبقات إن كانت الصور قليلة. العمق بلا بيانات يفشل وقد يؤذي.",
    guideEn: "A rich representation is not bought with layer count when photos are few. Depth without data fails and can harm.",
  },
  {
    id: "7-2-a08",
    lessonId: "7-2",
    chapterId: "7",
    promptAr: "اشرح لماذا يُعد تفاخر مهندس بأن «لا أحد يفهم داخل نموذج ترتيب الجرحى» علامة خطر لا علامة تقدم.",
    promptEn: "Explain why an engineer boasting that “nobody understands the inside of the casualty-ranking model” is a warning, not progress.",
    guideAr: "ترتيب حياة بشرية يحتاج تمثيلًا قابلًا للمراجعة. الغموض هنا مشكلة أخلاقية.",
    guideEn: "Ranking human lives needs a reviewable representation. Opacity here is an ethical problem.",
  },
  {
    id: "7-3-a01",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "حلّل ادعاء طالب أن النموذج «عرف» درجته قبل التصحيح لأنه كتب رقمًا واثقًا.",
    promptEn: "Analyse a student's claim that the model “knew” his mark before grading because it wrote a confident number.",
    guideAr: "النموذج يتوقع الرمز التالي لا الغيب. الثقة الأسلوبية ليست معرفة.",
    guideEn: "The model predicts the next token, not the future. Stylistic confidence is not knowledge.",
  },
  {
    id: "7-3-a02",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "قارن أمر «اشرح» وحده بأمر يحدد درس الشبكات وجمهور الصف ومثال مزرعة.",
    promptEn: "Compare the prompt “explain” alone with a prompt that names the networks lesson, the class audience, and a farm example.",
    guideAr: "توجيه الأوامر يغيّر التكملة. الأمر الضيق يرفع جودة الرد ويقلّل الكلام العام.",
    guideEn: "Prompting changes the completion. A tighter ask raises reply quality and cuts generic talk.",
  },
  {
    id: "7-3-a03",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "انتقد لصق فقرة النموذج في واجب التصنيف والانحدار من غير إغلاق النافذة والكتابة من الفهم.",
    promptEn: "Critique pasting the model's paragraph into a classification-versus-regression homework without closing the window and writing from understanding.",
    guideAr: "الاستخدام السليم: اشرح لنفسك ثم اكتب صوتك. اللصق يلغي المسؤولية الأكاديمية.",
    guideEn: "Sound use: explain to yourself, then write in your voice. Pasting removes academic responsibility.",
  },
  {
    id: "7-3-a04",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "اشرح لماذا تُعد جملة مدى إنزيم فصيحة في خطاب خروج خطرًا إن لم يعتمدها قسم المختبر.",
    promptEn: "Explain why a fluent enzyme-range sentence in a discharge note is dangerous if the lab department does not use that range.",
    guideAr: "هذه هلوسة محتملة: شكل طبي بلا سند محلي. الفصاحة ليست دليل صدق.",
    guideEn: "This may be a hallucination: a medical look with no local grounding. Fluency is not proof of truth.",
  },
  {
    id: "7-3-a05",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "حلّل ملصق مصنع يقول إن تعليمات التشغيل صحيحة لأن لغة النموذج سلسة.",
    promptEn: "Analyse a factory poster that says operating instructions are true because the model's language is fluent.",
    guideAr: "الفصاحة إكمال توكنات. الصدق يحتاج مهندسًا ومصدرًا، لا سلاسة الجملة.",
    guideEn: "Fluency is token completion. Truth needs an engineer and a source, not a smooth sentence.",
  },
  {
    id: "7-3-a06",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "قارن استخدام النموذج لفهم فكرة الرطوبة ثم القياس في الحقل باستخدامه كمحطة أرصاد تقرر الري.",
    promptEn: "Compare using the model to understand moisture as an idea then measuring in the field with using it as a weather station that orders irrigation.",
    guideAr: "الأول تعلّم ثم عمل بشري. الثاني يخلط التكملة بالمعرفة ويخاطر بالحقل.",
    guideEn: "The first is learning then human work. The second mixes completion with knowledge and risks the field.",
  },
  {
    id: "7-3-a07",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "انتقد رفع صورة بطاقة مريض أو كشف درجات صف إلى الدردشة «لتخصيص» الرد.",
    promptEn: "Critique uploading a patient's ID photo or a class mark sheet into chat “to personalise” the reply.",
    guideAr: "الدرجات والعنوان والهوية أسرار. ما يُلصق قد يُحفظ حيث لا يجب.",
    guideEn: "Marks, an address, and an ID are secrets. Whatever you paste may be stored where it should not be.",
  },
  {
    id: "7-3-a08",
    lessonId: "7-3",
    chapterId: "7",
    promptAr: "اشرح لماذا يجب أن يراجع فني السلامة كل توكن في جملة «الحادث سببه…» قبل توقيع تقرير وردية.",
    promptEn: "Explain why a safety tech must review every token in “the accident was caused by…” before signing a shift report.",
    guideAr: "سلسلة الرموز تفضّل جملة مكتملة على جملة صادقة. السبب يُكتب من محضر بشري.",
    guideEn: "A token chain prefers a finished sentence over a true one. The cause is written from a human record.",
  },
];
