import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_2_FACTS: BankFact[] = [
  {
    id: "2-1-f01",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "ممرضة عيادة مدرسة ثانوية في المعادي تريد إرسال ملف تطعيمات على بريد المعمل.",
    sceneEn: "A school-clinic nurse in Maadi wants to email vaccination files to the lab.",
    claimAr: "شفّر الملف قبل الإرسال حتى لا يُقرأ بغير المفتاح.",
    claimEn: "Encrypt the file before sending so it cannot be read without the key.",
    whyAr: "التشفير يحوّل النص الحي إلى صورة لا تُفهم إلا بالمفتاح الصحيح.",
    whyEn: "Encryption turns clear text into a form that only the right key can open.",
    termAr: "التشفير",
    termEn: "Encryption",
    wrongAr: ["أرسل الملف نصًا واضحًا لأن العيادة داخل المدرسة", "اطبع الملف والصقه على باب العيادة", "احذف الامتداد حتى يظن النظام أنه صورة"],
    wrongEn: ["Send the file in the clear because the clinic is on campus", "Print it and tape it to the clinic door", "Delete the extension so the system thinks it is a photo"],
  },
  {
    id: "2-1-f02",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "كنترول امتحانات في الزقازيق ينقل نماذج الأسئلة من جهاز الموجه إلى طابعة الدور الأرضي.",
    sceneEn: "An exam-control room in Zagazig moves question papers from the supervisor PC to a ground-floor printer.",
    claimAr: "مرّر النماذج عبر قناة مشفّرة حتى لا تُقرأ في الطريق.",
    claimEn: "Send the papers over an encrypted channel so they stay unreadable in transit.",
    whyAr: "بدون تشفير يستطيع من يعترض الكابل أو الواي فاي أن يقرأ الأسئلة كما هي.",
    whyEn: "Without encryption anyone who taps the cable or Wi-Fi can read the questions as-is.",
    termAr: "التشفير",
    termEn: "Encryption",
    wrongAr: ["انقل الملف على فلاشة مفتوحة بلا كلمة مرور", "انشر المسودة على مجموعة أولياء الأمور لتوفير الوقت", "اترك الطابعة تقبل أي جهاز من غير تحقق"],
    wrongEn: ["Copy it to an unlocked flash drive", "Post the draft in the parents group to save time", "Let the printer accept any device with no check"],
  },
  {
    id: "2-1-f03",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "فني معمل حاسوب في الجيزة يشفّر نسخة احتياطية يومية لنفس القرص الذي سيفكّها غدًا.",
    sceneEn: "A computer-lab technician in Giza encrypts a daily backup on the same disk he will unlock tomorrow.",
    claimAr: "استخدم التشفير المتماثل: مفتاح واحد للغلق والفتح.",
    claimEn: "Use symmetric encryption: one key both locks and unlocks.",
    whyAr: "حين يملك الطرفان نفس السر يكفي مفتاح واحد للتشفير وفك التشفير.",
    whyEn: "When both sides already share a secret, one key can encrypt and decrypt.",
    termAr: "التشفير المتماثل",
    termEn: "Symmetric encryption",
    wrongAr: ["أنشئ مفتاحًا عامًا معلنًا على سبورة المعمل", "اترك النسخة بلا مفتاح لأن الجهاز في الدولاب", "استخدم بصمة الطالب بدل المفتاح"],
    wrongEn: ["Publish a public key on the lab whiteboard", "Leave the backup unkeyed because the PC is in a cupboard", "Replace the key with a student fingerprint"],
  },
  {
    id: "2-1-f04",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "إذاعة مدرسية في طنطا تسجّل حلقة داخلية وتريد حفظها على قرص مشترك بين مذيعين اثنين فقط.",
    sceneEn: "A school radio in Tanta records an internal show and wants it on a disk shared by two presenters only.",
    claimAr: "اتفقا على مفتاح سري واحد ثم شفّرا الملف وفكّاه بنفس المفتاح.",
    claimEn: "Agree on one secret key, then encrypt and decrypt with that same key.",
    whyAr: "التشفير المتماثل يناسب عددًا صغيرًا يعرف السر مسبقًا ولا يحتاج زوج مفاتيح.",
    whyEn: "Symmetric encryption fits a small group that already shares a secret and needs no key pair.",
    termAr: "التشفير المتماثل",
    termEn: "Symmetric encryption",
    wrongAr: ["انشرا المفتاح في جروب الفصل حتى لا ينساه أحد", "احفظا الملف بصيغة نص عادي في مجلد عام", "أعطيا المفتاح لكل طلاب الإذاعة الاحتياطيين"],
    wrongEn: ["Post the key in the class group so nobody forgets it", "Save the file as plain text in a public folder", "Give the key to every backup radio student"],
  },
  {
    id: "2-1-f05",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "وكيل مدرسة بنات في المنصورة يريد أن يرسل مفتاح التشفير المتماثل لمعلمة جديدة عبر ورقة في الحقيبة.",
    sceneEn: "A deputy head in Mansoura wants to send a symmetric key to a new teacher on a slip in a bag.",
    claimAr: "احمِ تسليم المفتاح نفسه؛ إن سُرق المفتاح سقطت السرية كلها.",
    claimEn: "Protect delivery of the key itself; if it is stolen, secrecy collapses.",
    whyAr: "ضعف التشفير المتماثل هو توزيع المفتاح: من يملكه يقرأ كل الرسائل.",
    whyEn: "The weakness of symmetric encryption is key distribution: whoever has the key reads everything.",
    termAr: "التشفير المتماثل",
    termEn: "Symmetric encryption",
    wrongAr: ["اكتبي المفتاح على السبورة ثم امسحيه بعد الحصة", "أرسلي المفتاح في رسالة واتساب جماعية", "كرري نفس المفتاح في كل المدارس المجاورة"],
    wrongEn: ["Write the key on the board and wipe it after class", "Send the key in a group WhatsApp", "Reuse the same key in every nearby school"],
  },
  {
    id: "2-1-f06",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "ولي أمر في الإسكندرية يريد إرسال شكوى سرية إلى بوابة المدرسة من هاتفه في البيت.",
    sceneEn: "A parent in Alexandria wants to send a private complaint to the school portal from a home phone.",
    claimAr: "شفّر الشكوى بالمفتاح العام للمدرسة ولا تشارك المفتاح الخاص.",
    claimEn: "Encrypt the complaint with the school public key and never share the private key.",
    whyAr: "في التشفير غير المتماثل المفتاح العام يغلّق والخاص وحده يفتح.",
    whyEn: "In asymmetric encryption the public key locks and only the private key opens.",
    termAr: "التشفير غير المتماثل",
    termEn: "Asymmetric encryption",
    wrongAr: ["اطلب من ولي الأمر نفس المفتاح الخاص الذي عند المدير", "انشر المفتاح الخاص في تذييل الموقع ليسهّل الدخول", "استخدم مفتاحًا واحدًا معلنًا للغلق والفتح معًا"],
    wrongEn: ["Ask the parent for the same private key the head has", "Publish the private key in the site footer to ease login", "Use one public key for both lock and unlock"],
  },
  {
    id: "2-1-f07",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "مسؤول شؤون الطلاب في حلوان يستلم ملفات تحويل مشفّرة من مدارس أخرى على الخادم.",
    sceneEn: "A student-affairs officer in Helwan receives encrypted transfer files from other schools on the server.",
    claimAr: "أبقِ المفتاح الخاص على خادم المدرسة ولا ترسله للمدرسة المرسلة.",
    claimEn: "Keep the private key on the school server and do not send it to the sending school.",
    whyAr: "المدرسة المرسلة تكفي بالمفتاح العام؛ الخاص إن خرج انكشفت كل الرسائل الواردة.",
    whyEn: "The sender only needs the public key; if the private key leaves, every inbound message is exposed.",
    termAr: "التشفير غير المتماثل",
    termEn: "Asymmetric encryption",
    wrongAr: ["انسخ المفتاح الخاص على فلاشة كل مشرف دور", "ضع زوج المفاتيح في توقيع البريد الرسمي", "اطلب من كل مدرسة مرسلة أن تحتفظ بنسخة من الخاص"],
    wrongEn: ["Copy the private key onto every floor supervisor's flash drive", "Put the key pair in the official email signature", "Ask every sending school to keep a copy of the private key"],
  },
  {
    id: "2-1-f08",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "منسق درجات في أسيوط يرسل كشف نهاية الفصل إلى إدارة تعليم بعيدة بلا لقاء مباشر لتبادل سر.",
    sceneEn: "A marks coordinator in Asyut sends end-of-term sheets to a distant education office with no meeting to swap a secret.",
    claimAr: "استخدم زوج مفاتيح عام وخاص لأن الطرفين لم يتفقا على سر مشترك مسبقًا.",
    claimEn: "Use a public–private key pair because the two sides never shared a prior secret.",
    whyAr: "التشفير غير المتماثل يحل مشكلة توزيع المفتاح حين لا يوجد لقاء آمن لتسليم سر واحد.",
    whyEn: "Asymmetric encryption solves key distribution when there is no safe meeting to hand over one secret.",
    termAr: "التشفير غير المتماثل",
    termEn: "Asymmetric encryption",
    wrongAr: ["اتفقا على كلمة مرور صفية قصيرة عبر الهاتف ثم انسياها", "أرسلا الكشف في صورة واضحة لأن المسافة كبيرة", "ضعا نفس الرقم السري على باب الإدارة"],
    wrongEn: ["Agree a short class password on a phone call then forget it", "Send the sheet in the clear because the distance is large", "Put the same PIN on the office door"],
  },
  {
    id: "2-1-f09",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "طالب في بورسعيد يفتح منصة الواجبات من مقهى ويجد درجات زملائه ظاهرة بلا سؤال عن الهوية.",
    sceneEn: "A student in Port Said opens the homework platform from a cafe and sees classmates' marks with no identity check.",
    claimAr: "أوقف العرض حتى يثبت النظام أن الداخل هو صاحب الحساب.",
    claimEn: "Stop the display until the system proves the visitor is the account holder.",
    whyAr: "المصادقة تتأكد أن الطرف هو من يدّعي أنه هو قبل كشف أي بيان.",
    whyEn: "Authentication checks that a party is who they claim to be before any data is shown.",
    termAr: "المصادقة",
    termEn: "Authentication",
    wrongAr: ["أبقِ الدرجات ظاهرة لأي زائر طالما الصفحة مشفّرة", "اخفِ الأسماء واترك الأرقام للجميع", "اسمح بالدخول باسم الصف فقط من غير كلمة مرور"],
    wrongEn: ["Keep marks visible to any visitor as long as the page is encrypted", "Hide names and leave the numbers public", "Allow login with the class name and no password"],
  },
  {
    id: "2-1-f10",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "مدير مدرسة في بني سويف يرسل قرارات مشفّرة عبر تطبيق، لكن التطبيق لا يسأل من المرسل.",
    sceneEn: "A head teacher in Beni Suef sends encrypted decisions in an app that never asks who the sender is.",
    claimAr: "أضف خطوة مصادقة قبل الثقة بالرسالة حتى لا ينتحل أحد شخصية المدير.",
    claimEn: "Add an authentication step before trusting the message so nobody impersonates the head.",
    whyAr: "السرية بلا مصادقة تترك الباب لمن يرسل باسم غير اسمه والبيانات تبقى مقروءة للطرف المخدوع.",
    whyEn: "Secrecy without authentication lets someone speak in another name while the victim still reads the payload.",
    termAr: "المصادقة",
    termEn: "Authentication",
    wrongAr: ["اكتفِ بالتشفير لأن أحدًا لن يقرأ المحتوى في الطريق", "ألغِ اسم المرسل حتى يصعب التتبع", "اجعل كلمة المرور نفسها لجميع الإداريين"],
    wrongEn: ["Rely on encryption alone because nobody will read the content in transit", "Remove the sender name to make tracing harder", "Give every administrator the same password"],
  },
  {
    id: "2-1-f11",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "مكتبة رقمية في الفيوم تحمي حساب أمين المكتبة بكلمة مرور قصيرة مكتوبة تحت الشاشة.",
    sceneEn: "A digital library in Fayoum protects the librarian account with a short password taped under the screen.",
    claimAr: "ارفض الاعتماد على كلمة المرور وحدها واستبدل الورقة بعامل ثانٍ.",
    claimEn: "Refuse to rely on the password alone and replace the paper with a second factor.",
    whyAr: "كلمة المرور تُخمَّن أو تُسرق بالنظر؛ وحدها ضعيفة أمام من يجلس مكان أمين المكتبة.",
    whyEn: "A password can be guessed or seen; alone it is weak against anyone who sits in the librarian's chair.",
    termAr: "المصادقة متعددة العوامل",
    termEn: "Multi-factor authentication",
    wrongAr: ["قصّر الكلمة إلى أربعة أرقام ليسهل تذكرها", "شارك الكلمة مع طلاب المناوبة", "عطّل القفل بعد الحصة الأولى توفيراً للوقت"],
    wrongEn: ["Shorten the word to four digits so it is easier to remember", "Share the word with duty students", "Disable the lock after first period to save time"],
  },
  {
    id: "2-1-f12",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "معلم في شبرا يدخل منصة الدرجات من البيت بكلمة المرور ثم تصل رسالة برقم على هاتفه.",
    sceneEn: "A teacher in Shubra opens the marks platform from home with a password, then a code arrives on the phone.",
    claimAr: "أدخل الرمز الثاني؛ هذا شيء تعرفه وشيء تملكه.",
    claimEn: "Enter the second code; that is something you know plus something you have.",
    whyAr: "المصادقة متعددة العوامل تجمع عاملين مختلفين حتى لا تكفي كلمة مسروقة وحدها.",
    whyEn: "MFA combines different factors so a stolen password is not enough.",
    termAr: "المصادقة متعددة العوامل",
    termEn: "Multi-factor authentication",
    wrongAr: ["تجاهل الرسالة لأن الكلمة صحيحة", "أعد إرسال الرمز إلى هاتف الطالب المراقب", "اكتب الرمز على السبورة للحصص القادمة"],
    wrongEn: ["Ignore the message because the password was correct", "Forward the code to the student on duty", "Write the code on the board for later lessons"],
  },
  {
    id: "2-1-f13",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "منسق حضور في كفر الشيخ يفعّل تطبيقًا على الهاتف يولّد أرقامًا تتغير كل نصف دقيقة.",
    sceneEn: "An attendance coordinator in Kafr El-Sheikh enables a phone app that generates codes every thirty seconds.",
    claimAr: "اربط الدخول بكلمة المرور ورقم التطبيق معًا لا بأحدهما فقط.",
    claimEn: "Tie login to both the password and the app code, not to either one alone.",
    whyAr: "التطبيق شيء تملكه يتغير بسرعة؛ مع شيء تعرفه يصعب انتحال الحساب من مقهى بعيد.",
    whyEn: "The app is something you have that changes fast; with something you know, remote impersonation is harder.",
    termAr: "المصادقة متعددة العوامل",
    termEn: "Multi-factor authentication",
    wrongAr: ["علّق صورة رمز الاستجابة على باب المكتب بدل التطبيق", "انقل أرقام التطبيق إلى ملف مشترك في درايف الصف", "أوقف التطبيق في أيام الامتحان لأنه يبطئ الدخول"],
    wrongEn: ["Tape a static QR photo on the office door instead of the app", "Copy the app numbers into a shared class Drive file", "Turn the app off on exam days because it slows login"],
  },
  {
    id: "2-1-f14",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "معمل العلوم والهندسة في أكتوبر يفتح أجهزة التصميم ببصمة الطالب بعد كلمة مرور الصف.",
    sceneEn: "A STEM lab in 6th of October unlocks design PCs with a student fingerprint after the class password.",
    claimAr: "أبقِ البصمة عاملًا ثالثًا: شيء أنت عليه فوق المعرفة والامتلاك.",
    claimEn: "Keep the fingerprint as a third factor: something you are on top of knowledge and possession.",
    whyAr: "المصادقة متعددة العوامل قد تضيف سمة حيوية حتى لا يكفي من سرق البطاقة أو الكلمة.",
    whyEn: "MFA can add a biometric so stealing a card or a password is still not enough.",
    termAr: "المصادقة متعددة العوامل",
    termEn: "Multi-factor authentication",
    wrongAr: ["سجّل بصمة طالب واحد لكل الجهاز لتسريع الاصطفاف", "ألغِ الكلمة واعتمد البصمة وحدها بلا مراجعة", "أرسل صور البصمات إلى جروب أولياء الأمور كنسخة احتياطية"],
    wrongEn: ["Register one student's fingerprint on every PC to speed the queue", "Drop the password and trust the fingerprint alone with no review", "Send fingerprint photos to the parents group as a backup"],
  },
  {
    id: "2-1-f15",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "خادم حسابات في دمياط يخزّن كلمات مرور معلمي اللغات كما كتبها المستخدمون.",
    sceneEn: "An accounts server in Damietta stores language teachers' passwords exactly as they typed them.",
    claimAr: "احفظ تجزئة الكلمة لا النص الواضح ثم قارن البصمة عند الدخول.",
    claimEn: "Store a hash of the password, not the clear text, then compare the fingerprint at login.",
    whyAr: "التجزئة اتجاه واحد: نتحقق بالمقارنة ولا نسترجع السر إن سُرق ملف الخادم.",
    whyEn: "A hash is one-way: we check by comparison and cannot recover the secret if the server file is stolen.",
    termAr: "التجزئة",
    termEn: "Hashing",
    wrongAr: ["ضع جدولاً يترجم كل تجزئة إلى الكلمة الأصلية", "أرسِل قائمة الكلمات بالبريد الأسبوعي للتذكير", "احفظ الكلمة مرتين: مرة واضحة ومرة مشفّرة بنفس المفتاح العام"],
    wrongEn: ["Keep a table that maps every hash back to the original word", "Email the password list weekly as a reminder", "Store the word twice: once clear and once encrypted with the public key"],
  },
  {
    id: "2-1-f16",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "طالب في سوهاج نسي كلمة منصة المعمل ويطلب من الفني أن يستخرجها من قاعدة البيانات.",
    sceneEn: "A student in Sohag forgot the lab-platform password and asks the technician to pull it from the database.",
    claimAr: "لا تستخرج السر؛ التجزئة لا تُعكس، فأعد تعيين كلمة جديدة بعد التحقق من الهوية.",
    claimEn: "Do not extract the secret; a hash cannot be reversed, so reset a new password after proving identity.",
    whyAr: "وظيفة التجزئة أن تمنع استرجاع الأصل؛ الاستعادة تعني أن التخزين كان ضعيفًا.",
    whyEn: "The point of a hash is that the original cannot be recovered; being able to restore it means storage was weak.",
    termAr: "التجزئة",
    termEn: "Hashing",
    wrongAr: ["شغّل برنامج فك التجزئة أمام الطالب ليأخذ الكلمة", "اقرأ الملف المشفّر بالمفتاح العام للفصل", "أعطِ الطالب كلمة معلم المعمل مؤقتًا"],
    wrongEn: ["Run a hash-cracking tool in front of the student to fetch the word", "Read the encrypted file with the class public key", "Lend the student the lab teacher's password for now"],
  },
  {
    id: "2-1-f17",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "طلاب في الأقصر يفتحون موقع المدرسة فيُحذّر المتصفح أن الشهادة غير مطابقة للاسم.",
    sceneEn: "Students in Luxor open the school site and the browser warns that the certificate does not match the name.",
    claimAr: "لا تُكمل الدخول حتى تُربط الشهادة الرقمية بالموقع الحقيقي للمدرسة.",
    claimEn: "Do not continue until a digital certificate binds to the real school site.",
    whyAr: "الشهادة الرقمية تربط المفتاح العام بهوية موثوقة حتى لا تُسلَّم البيانات لموقع منتحل.",
    whyEn: "A digital certificate binds a public key to a trusted identity so data is not handed to a fake site.",
    termAr: "الشهادة الرقمية",
    termEn: "Digital certificate",
    wrongAr: ["اضغط تجاهل التحذير لأن الحصة على وشك أن تبدأ", "انسخ المفتاح العام من رسالة مجهولة وألصقه في المتصفح", "بدّل العنوان إلى رقم آي بي عشري ودخل من غير شهادة"],
    wrongEn: ["Click past the warning because the lesson is about to start", "Paste a public key from an unknown message into the browser", "Switch to a raw IP address and skip the certificate"],
  },
  {
    id: "2-1-f18",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "عيادة أسنان تعليمية في أسوان تنشر مفتاحًا عامًا لحجز المواعيد بلا ما يثبت أنه مفتاح العيادة.",
    sceneEn: "A teaching dental clinic in Aswan publishes a public booking key with nothing proving it belongs to the clinic.",
    claimAr: "اطلب شهادة رقمية من جهة موثوقة تربط المفتاح باسم العيادة.",
    claimEn: "Demand a digital certificate from a trusted issuer that binds the key to the clinic name.",
    whyAr: "المفتاح العام وحده لا يقول من صاحبه؛ الشهادة هي الربط بين المفتاح والهوية.",
    whyEn: "A public key alone does not say who owns it; the certificate is the binding to an identity.",
    termAr: "الشهادة الرقمية",
    termEn: "Digital certificate",
    wrongAr: ["اكتفِ بأن المفتاح طويل ويبدو معقدًا", "اطبع المفتاح على ورقة الاستقبال وعدّ ذلك إثباتًا", "اسمح لأي طالب طب أسنان أن يولّد مفتاحًا بديلًا كل أسبوع"],
    wrongEn: ["Trust the key because it is long and looks complex", "Print the key at reception and call that proof", "Let any dental student generate a replacement key each week"],
  },
  {
    id: "2-1-f19",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "ولي أمر في قنا يستلم رسالة مشفّرة تدّعي أنها من رائد الفصل تطلب رقم بطاقة الطالب.",
    sceneEn: "A parent in Qena receives an encrypted message claiming to be from the class tutor and asking for the student's ID number.",
    claimAr: "لا تُرسل الرقم حتى تتحقق أن المرسل هو الرائد الحقيقي لا منتحلًا.",
    claimEn: "Do not send the number until you verify the sender is the real tutor, not an impersonator.",
    whyAr: "التشفير يحمي المحتوى في الطريق لكنه لا يثبت الهوية؛ بلا مصادقة ينجح انتحال الشخصية.",
    whyEn: "Encryption protects content in transit but does not prove identity; without authentication impersonation succeeds.",
    termAr: "انتحال الهوية",
    termEn: "Impersonation",
    wrongAr: ["أجب فورًا لأن الرسالة مشفّرة فهي رسمية", "أرفق صورة البطاقة لتسريع الرد", "حوّل المحادثة إلى مجموعة الصف كاملة"],
    wrongEn: ["Reply at once because an encrypted message must be official", "Attach a photo of the ID to speed the reply", "Move the chat into the whole class group"],
  },
  {
    id: "2-1-f20",
    lessonId: "2-1",
    chapterId: "2",
    sceneAr: "عيادة مدرسية في العريش تشفّر الملف الطبي ثم تفتحه لأي زائر يعرف اسم المريض فقط.",
    sceneEn: "A school clinic in Arish encrypts the medical file then opens it for any visitor who knows the patient's name.",
    claimAr: "اربط فك التشفير بمصادقة حقيقية؛ السرية بلا تحقق تُسلّم الملف للمنتحل.",
    claimEn: "Tie decryption to real authentication; secrecy without a check hands the file to an impersonator.",
    whyAr: "من ينتحل الاسم يحصل على السر إن لم نسأل: من أنت؟ بعد أن نحمي الطريق.",
    whyEn: "Whoever fakes the name gets the secret if we never ask who they are after we protect the path.",
    termAr: "انتحال الهوية",
    termEn: "Impersonation",
    wrongAr: ["اكتفِ بالتشفير وعدّ الاسم كلمة مرور", "علّق قائمة الأسماء على باب العيادة لتسهيل الاستلام", "أعطِ نسخة من المفتاح لكل طلاب الرحلات"],
    wrongEn: ["Rely on encryption and treat the name as the password", "Post the name list on the clinic door to ease pickup", "Give a copy of the key to every trip student"],
  },
  {
    id: "2-2-f01",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "معمل شفيق في مصر الجديدة يستقبل أجهزة طلاب تجلب ألعابًا من الإنترنت إلى شبكة الدرجات.",
    sceneEn: "A Shafik lab in Heliopolis lets student devices pull games from the Internet onto the marks network.",
    claimAr: "ضع جدار حماية يفلتر الحركة ويمنع الألعاب من الوصول لخادم الدرجات.",
    claimEn: "Place a firewall that filters traffic and blocks games from reaching the marks server.",
    whyAr: "جدار الحماية يطبّق قواعد على ما يدخل ويخرج حتى لا تختلط حركة المعمل بخادم حساس.",
    whyEn: "A firewall applies rules to what enters and leaves so lab traffic does not mix with a sensitive server.",
    termAr: "جدار الحماية",
    termEn: "Firewall",
    wrongAr: ["افتح كل المنافذ حتى لا تبطؤ الألعاب", "ألغِ الجدار في الحصة لأنه يمنع التحميل", "صل الأجهزة مباشرة في مقبس خادم الدرجات"],
    wrongEn: ["Open every port so the games stay fast", "Turn the firewall off in class because it blocks downloads", "Plug devices straight into the marks-server socket"],
  },
  {
    id: "2-2-f02",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "ساحة مدرسة في الإسماعيلية تقدّم واي فاي للطلاب بجوار مكتب شؤون العاملين.",
    sceneEn: "A school yard in Ismailia offers student Wi-Fi next to the staff-affairs office.",
    claimAr: "اضبط قواعد الجدار بحيث تُمنع أجهزة الساحة من مجلدات الموظفين.",
    claimEn: "Set firewall rules so yard devices cannot reach staff folders.",
    whyAr: "الجدار لا يغلق الإنترنت كله؛ هو يفصل المسارات حسب الدور.",
    whyEn: "A firewall does not have to kill the whole Internet; it separates paths by role.",
    termAr: "جدار الحماية",
    termEn: "Firewall",
    wrongAr: ["اجعل شبكة الساحة هي نفسها شبكة مكتب الشؤون", "عطّل الجدار بعد الطابور لأن الإشارة تضعف", "اسمح لأي ضيف بقاعدة «اسمح للكل» لتبسيط الإعداد"],
    wrongEn: ["Make the yard network the same as the staff-affairs network", "Disable the firewall after assembly because the signal drops", "Give every guest an allow-all rule to simplify setup"],
  },
  {
    id: "2-2-f03",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "خادم درجات في العباسية يجلس خلف جدار حماية واحد قديم، والأجهزة الداخلية بلا كلمة مرور.",
    sceneEn: "A marks server in Abbasiya sits behind one old firewall, and the inner PCs have no passwords.",
    claimAr: "لا تعتمد على الجدار وحده؛ أمّن الأجهزة الداخلية أيضًا.",
    claimEn: "Do not trust the firewall alone; harden the inner devices too.",
    whyAr: "إن تجاوز المهاجم طبقة المحيط وجد الشبكة عارية إن لم توجد طبقات بعدها.",
    whyEn: "If an attacker passes the perimeter layer, the network is bare unless later layers remain.",
    termAr: "الأمن متعدد الطبقات",
    termEn: "Layered security",
    wrongAr: ["حدّث ملصق الجدار واعتبر المهمة انتهت", "انقل كل كلمات المرور إلى ورقة خلف الجدار", "افتح سطح المكتب البعيد من الإنترنت لأن الجدار موجود"],
    wrongEn: ["Update the firewall sticker and call the job done", "Move every password onto a paper behind the firewall", "Open remote desktop from the Internet because a firewall exists"],
  },
  {
    id: "2-2-f04",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "معلمة في 6 أكتوبر تصحّح الواجبات من البيت عبر مقاهي الإنترنت العامة.",
    sceneEn: "A teacher in 6th of October marks homework from home through public cafe Internet.",
    claimAr: "ادخلي عبر شبكة خاصة افتراضية تشفّر النفق حتى المكتب المدرسي.",
    claimEn: "Enter through a VPN that encrypts a tunnel back to the school office.",
    whyAr: "الشبكة الخاصة الافتراضية تحمي البيانات وهي تعبر شبكة عامة لا نسيطر عليها.",
    whyEn: "A VPN protects data while it crosses a public network we do not control.",
    termAr: "شبكة خاصة افتراضية",
    termEn: "VPN",
    wrongAr: ["ادخلي لمنصة الدرجات مباشرة من واي فاي المقهى", "أرسلي ملفات الطلاب في رسالة مفتوحة للمعلمة المناوبة", "اطلبي من صاحب المقهى كلمة سر الراوتر المدرسي"],
    wrongEn: ["Open the marks platform directly on cafe Wi-Fi", "Send student files in an open message to the duty teacher", "Ask the cafe owner for the school router password"],
  },
  {
    id: "2-2-f05",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "فريق رحلة إلى مكتبة الإسكندرية يحتاج الوصول لأرشيف المدرسة من فندق على الكورنيش.",
    sceneEn: "A trip team at the Bibliotheca Alexandrina needs the school archive from a Corniche hotel.",
    claimAr: "أنشئ نفقًا مشفّرًا عبر الشبكة العامة بدل فتح الأرشيف على الإنترنت الخام.",
    claimEn: "Build an encrypted tunnel across the public network instead of exposing the archive on the raw Internet.",
    whyAr: "النفق الافتراضي يجعل الحركة كأنها داخل المدرسة رغم أن الكابل عام.",
    whyEn: "The virtual tunnel makes the traffic behave as if it were inside the school even though the cable is public.",
    termAr: "شبكة خاصة افتراضية",
    termEn: "VPN",
    wrongAr: ["انشر مجلد الأرشيف على رابط قصير بلا كلمة مرور", "استخدم شبكة الفندق المفتوحة باسم الضيف", "أعطِ الاستقبال كلمة مرور خادم المدرسة ليثبّت الإشارة"],
    wrongEn: ["Publish the archive folder on a short link with no password", "Use the hotel's open guest network by name", "Give reception the school server password to boost the signal"],
  },
  {
    id: "2-2-f06",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "معمل في المنيا أصيب بجهاز طالب، والعدوى بدأت تزحف نحو خادم نتائج الإعدادية.",
    sceneEn: "A lab in Minya was infected from a student PC, and the infection is crawling toward the prep-results server.",
    claimAr: "اقسم الشبكة الآن حتى يبقى المعمل معزولًا عن خادم النتائج.",
    claimEn: "Segment the network now so the lab stays isolated from the results server.",
    whyAr: "تقسيم الشبكة يحصر الاختراق في جزء فلا يصل إلى الدرجات.",
    whyEn: "Segmentation confines a breach to one part so it does not reach the marks.",
    termAr: "تقسيم الشبكة",
    termEn: "Segmentation",
    wrongAr: ["وصّل المعمل والخادم في سوكتش واحد لتسهيل النسخ", "أوقف التقسيم لأن الصيانة تشتكي من الكابلات", "انقل خادم النتائج إلى نفس شبكة الألعاب"],
    wrongEn: ["Put the lab and the server on one switch to ease copying", "Drop segmentation because maintenance complains about cables", "Move the results server onto the games network"],
  },
  {
    id: "2-2-f07",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "عيادة مدرسية في الزاوية الحمراء تسجّل ضغط الدم على جهاز يشارك واي فاي فصل الحاسب.",
    sceneEn: "A school clinic in Zawya El-Hamra logs blood pressure on a device that shares the computer-class Wi-Fi.",
    claimAr: "افصل شبكة العيادة عن شبكة الفصل حتى لا تُسرَّب القياسات إن أصيب معمل.",
    claimEn: "Split the clinic network from the class network so readings do not leak if a lab is hit.",
    whyAr: "العزل بين العيادة والمعمل يمنع حادثًا تعليميًا من أن يصبح تسريبًا طبيًا.",
    whyEn: "Isolating clinic from lab stops a teaching incident from becoming a medical leak.",
    termAr: "تقسيم الشبكة",
    termEn: "Segmentation",
    wrongAr: ["اجمع العيادة والمعمل في شبكة زوار واحدة", "ضع جهاز الضغط على نفس طابعة الدرجات", "اسمح لطلاب الحاسب بالدخول عن بعد لشاشة العيادة"],
    wrongEn: ["Put clinic and lab on one guest network", "Share the blood-pressure device with the marks printer", "Let computer students remote into the clinic screen"],
  },
  {
    id: "2-2-f08",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "أمين مكتبة في دمنهور يطلب صلاحية تعديل درجات الفيزياء «للاحتياط».",
    sceneEn: "A librarian in Damanhur asks for rights to edit physics marks «just in case».",
    claimAr: "ارفض؛ أعطه أقل ما يكفي لفهرسة الكتب فقط.",
    claimEn: "Refuse; give only what cataloguing books requires.",
    whyAr: "مبدأ أقل صلاحية يقلّل الضرر إن سُرق الحساب أو أُسيء استخدامه.",
    whyEn: "Least privilege shrinks the harm if the account is stolen or misused.",
    termAr: "مبدأ أقل صلاحية",
    termEn: "Least privilege",
    wrongAr: ["امنحه صلاحية المدير الكاملة حتى لا يعود يسأل", "انسخ حساب كنترول الفيزياء لاسمه", "أعطِ كل موظفي المكتبة مفتاح خادم الامتحانات"],
    wrongEn: ["Grant full administrator rights so the request stops", "Clone the physics-control account under the librarian's name", "Give every library worker the exam-server key"],
  },
  {
    id: "2-2-f09",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "طلاب معمل في المحلة يدخلون بأ حساب معلم المعمل لأن الحسابات الفردية لم تُنشأ.",
    sceneEn: "Lab students in El-Mahalla log in with the lab teacher's account because personal accounts were never created.",
    claimAr: "أنشئ حسابًا لكل طالب بصلاحية تشغيل التمرين فقط.",
    claimEn: "Create one account per student with rights only to run the exercise.",
    whyAr: "الحساب المشترك يخالف أقل صلاحية ويجعل أثر أي خطأ غير قابل للتتبع.",
    whyEn: "A shared account breaks least privilege and makes any mistake untraceable.",
    termAr: "مبدأ أقل صلاحية",
    termEn: "Least privilege",
    wrongAr: ["اترك حساب المعلم على ورقة عند السبورة", "فعّل صلاحية تثبيت البرامج لكل من يدخل المعمل", "وحّد كلمة المرور لكل صفوف المدرسة"],
    wrongEn: ["Leave the teacher account on a paper by the board", "Enable software install rights for everyone who enters the lab", "Unify one password for every class in the school"],
  },
  {
    id: "2-2-f10",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "مدرسة في مدينة نصر تضع كل ثقتها في الراوتر عند البوابة وتهمل ما خلفه.",
    sceneEn: "A school in Nasr City trusts only the router at the gate and ignores everything behind it.",
    claimAr: "صمّم طبقة المحيط كأول حاجز لا كالحاجز الوحيد.",
    claimEn: "Design the perimeter as the first barrier, not the only one.",
    whyAr: "الأمن طبقات: المحيط يصد الغريب، لكن الداخل يحتاج حماية إن سقطت البوابة.",
    whyEn: "Security is layered: the perimeter blocks strangers, but the inside still needs protection if the gate falls.",
    termAr: "الأمن متعدد الطبقات",
    termEn: "Layered security",
    wrongAr: ["أزل كلمات مرور الأجهزة لأن الراوتر يكفي", "افتح منفذ الإدارة من الشارع لتسهيل الدعم", "عطّل سجل الدخول بعد البوابة لتوفير المساحة"],
    wrongEn: ["Remove device passwords because the router is enough", "Open the admin port from the street to ease support", "Turn off login logs past the gate to save space"],
  },
  {
    id: "2-2-f11",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "شبكة داخلية في المعادي الجديدة تصل غرفة المعلمين بخادم الأنشطة بلا أي فلترة بعد الجدار الخارجي.",
    sceneEn: "An internal network in New Maadi links the staff room to the activities server with no filtering after the outer wall.",
    claimAr: "أضف ضوابط داخلية بين الغرف حتى لا يتحرك المهاجم بحرية بعد الدخول.",
    claimEn: "Add internal controls between rooms so an attacker cannot move freely after getting in.",
    whyAr: "الطبقة الداخلية تفترض أن المحيط قد يُخترق فتفصل المسارات بين الخدمات.",
    whyEn: "The internal layer assumes the perimeter may fall and then splits paths between services.",
    termAr: "الأمن متعدد الطبقات",
    termEn: "Layered security",
    wrongAr: ["اجعل كل الغرف في شبكة محلية واحدة (Ethernet) بلا فلاتر", "انقل جدار الحماية إلى درج المكتب واعتبر الداخل آمنًا تلقائيًا", "اسمح لأي جهاز داخلي أن يمسح الشبكة كلها"],
    wrongEn: ["Put every room on one Ethernet with no filters", "Move the firewall into a desk drawer and treat the inside as automatically safe", "Let any inner device scan the whole network"],
  },
  {
    id: "2-2-f12",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "أجهزة لوحية في فصل بالأقصر عليها نظام قديم ومكتبة تطبيقات مفتوحة للطلاب.",
    sceneEn: "Tablets in a Luxor classroom run an old system and an app store left open to students.",
    claimAr: "أمّن طبقة الأجهزة: حدّث النظام وأغلق تثبيت التطبيقات العشوائي.",
    claimEn: "Harden the device layer: patch the system and lock random app installs.",
    whyAr: "الجهاز نفسه طبقة؛ إن بقي ضعيفًا تجاوز المهاجم المحيط من جيب الطالب.",
    whyEn: "The device itself is a layer; if it stays weak, an attacker bypasses the perimeter from a student's pocket.",
    termAr: "الأمن متعدد الطبقات",
    termEn: "Layered security",
    wrongAr: ["اترك التحديثات لأن الشبكة بطيئة في الصعيد", "فعّل وضع المطور لكل جهاز لتسريع التجربة", "شارك رمز إلغاء القفل في جروب الصف"],
    wrongEn: ["Skip updates because the network is slow in Upper Egypt", "Turn on developer mode on every tablet to speed trials", "Share the unlock PIN in the class group"],
  },
  {
    id: "2-2-f13",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "ملفات امتحان لغة عربية على قرص في طنطا تُنسخ إلى مجلد مشترك بلا تشفير بعد أن أُغلقت البوابة.",
    sceneEn: "Arabic-exam files on a disk in Tanta are copied into an unencrypted shared folder after the gate is locked.",
    claimAr: "احمِ طبقة البيانات نفسها بالتشفير والصلاحيات حتى بعد إغلاق المحيط.",
    claimEn: "Protect the data layer itself with encryption and rights even after the perimeter is closed.",
    whyAr: "آخر طبقة هي البيانات؛ إن وصلت نسخة واضحة إلى مجلد عام سقطت الحماية السابقة.",
    whyEn: "The last layer is the data; a clear copy in a public folder wastes every earlier control.",
    termAr: "الأمن متعدد الطبقات",
    termEn: "Layered security",
    wrongAr: ["اكتفِ بقفل باب المعمل وعدّ الملفات آمنة", "سمِّ المجلد «خاص» من غير صلاحيات", "أرسِل نسخة إلى جروب المصححين المفتوح"],
    wrongEn: ["Rely on the lab door lock and call the files safe", "Name the folder Private with no real permissions", "Send a copy to an open markers group"],
  },
  {
    id: "2-2-f14",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "فني في السويس يفتخر أن جدار الحماية يكفي مدى الحياة ولا ينظر لبقية الطبقات.",
    sceneEn: "A technician in Suez boasts that one firewall is enough for life and never looks at the other layers.",
    claimAr: "انتقد الاعتماد على جدار واحد وابنِ محيطًا وشبكة وأجهزة وبيانات معًا.",
    claimEn: "Reject trust in a single firewall and build perimeter, network, devices, and data together.",
    whyAr: "طبقة واحدة نقطة فشل واحدة؛ التصميم الآمن يفترض سقوط أي حاجز منفرد.",
    whyEn: "One layer is one point of failure; secure design assumes any single barrier can fall.",
    termAr: "جدار الحماية",
    termEn: "Firewall",
    wrongAr: ["اشترِ جدارًا أغلى ثم أوقف التحديثات", "انقل كل طابعات المدرسة أمام الجدار على الإنترنت", "احذف كلمات مرور الخوادم لأن الجدار «ذكي»"],
    wrongEn: ["Buy a costlier firewall then freeze updates", "Move every school printer in front of the firewall onto the Internet", "Delete server passwords because the firewall is «smart»"],
  },
  {
    id: "2-2-f15",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "أجهزة معمل في أسيوط تعرض تنبيه تحديث أمني منذ شهر والمعلم يؤجله حتى بعد الامتحانات.",
    sceneEn: "Lab PCs in Asyut have shown a security-update banner for a month and the teacher delays it until after exams.",
    claimAr: "ثبّت التحديث الآن في نافذة صيانة قصيرة؛ التأجيل يترك ثغرة معروفة.",
    claimEn: "Install the patch now in a short maintenance window; delay leaves a known hole.",
    whyAr: "التحديث الأمني يغلق ثغرات يعلنها المهاجمون قبل أن يغلقها المعلّم.",
    whyEn: "A security patch closes holes attackers already know about before the teacher does.",
    termAr: "التحديث الأمني",
    termEn: "Security patching",
    wrongAr: ["أوقف خدمة التحديث نهائيًا حتى لا تقطع الحصة", "حمّل التحديث من فلاشة طالب بلا فحص", "أبقِ النظام عند نسخة عام سابق لأنها «مستقرة»"],
    wrongEn: ["Kill the update service forever so the lesson is not interrupted", "Load the update from a student's flash drive with no check", "Keep last year's build because it feels «stable»"],
  },
  {
    id: "2-2-f16",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "خادم أنشطة في السويس ما زال يفتح منفذ سطح مكتب بعيد لم يعد أحد يستخدمه.",
    sceneEn: "An activities server in Suez still opens a remote-desktop port that nobody uses anymore.",
    claimAr: "أغلق المنفذ غير المستخدم ولا تترك بابًا بلا حاجة.",
    claimEn: "Close the unused port and do not leave a door you no longer need.",
    whyAr: "المنفذ المفتوح بلا خدمة حقيقية هو مدخل جاهز للمسح الآلي.",
    whyEn: "An open port with no real service is a ready door for automated scans.",
    termAr: "إغلاق المنافذ",
    termEn: "Closing unused ports",
    wrongAr: ["اترك المنفذ «للاحتياط» إن احتجناه في الرحلة", "غيّر رقم المنفذ فقط من غير إغلاقه", "أعلن رقم المنفذ في دليل المدرسة الإلكتروني"],
    wrongEn: ["Leave the port «just in case» we need it on a trip", "Only change the port number without closing it", "Publish the port number in the school e-guide"],
  },
  {
    id: "2-2-f17",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "مدرسة في الشيخ زايد تبني بوابة تسجيل جديدة وتؤجّل كلمات المرور والصلاحيات «بعد الإطلاق».",
    sceneEn: "A school in Sheikh Zayed is building a new registration portal and postpones passwords and rights «until after launch».",
    claimAr: "صمم الأمن مع الشاشات من اليوم الأول لا بعد أن يدخل أولياء الأمور.",
    claimEn: "Design security with the screens from day one, not after parents start using it.",
    whyAr: "الأمن بالتصميم أرخص وأمتن من ترقيع سريع حين تكون البيانات قد خرجت.",
    whyEn: "Security by design is cheaper and stronger than a rushed patch after data has already leaked.",
    termAr: "الأمن بالتصميم",
    termEn: "Security by design",
    wrongAr: ["أطلق البوابة مفتوحة ثم أضف قفلًا إن اشتكى أحد", "ضع ملصق «آمن» على الصفحة الرئيسية من غير ضوابط", "انسخ بيانات التجريب إلى الإنترنت العام لاختبار السرعة"],
    wrongEn: ["Launch the portal open then add a lock if someone complains", "Put a Secure sticker on the home page with no controls", "Copy trial data onto the public Internet to test speed"],
  },
  {
    id: "2-2-f18",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "منصة أنشطة في التجمع الخامس اكتملت ثم طُلب من المبرمج «إضافة أمن» في آخر أسبوع.",
    sceneEn: "An activities platform in Fifth Settlement was finished, then the coder was told to «add security» in the last week.",
    claimAr: "ارفض الترقيع المتأخر وأعد مسارات الدخول والصلاحيات كجزء من البناء.",
    claimEn: "Reject the late bolt-on and rebuild login and rights as part of the structure.",
    whyAr: "الأمن المضاف في النهاية يبقى طبقة هشة فوق قرارات لم تُراجع.",
    whyEn: "Security bolted on at the end stays a thin layer over decisions that were never reviewed.",
    termAr: "الأمن بالتصميم",
    termEn: "Security by design",
    wrongAr: ["أضف خانة كلمة مرور من غير التحقق من الطرف الآخر", "اشترِ شهادة شكلية واترك الحسابات مشتركة", "أخّر السجلات حتى «المرحلة الثانية» بلا موعد"],
    wrongEn: ["Add a password box without checking the other party", "Buy a decorative certificate and keep shared accounts", "Delay logs until «phase two» with no date"],
  },
  {
    id: "2-2-f19",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "فناء في بنها يفتح شبكة ضيوف لأولياء الأمور بجانب شبكة الكنترول يوم توزيع النتائج.",
    sceneEn: "A yard in Banha opens a parent guest network beside the exam-control network on results day.",
    claimAr: "افصل شبكة الضيوف تمامًا وطبّق أقل صلاحية على من يدخل النتائج.",
    claimEn: "Fully separate the guest network and apply least privilege to anyone who opens results.",
    whyAr: "الطبقات تعمل مع التقسيم وأقل صلاحية حتى لا يصل ضيف الساحة إلى كشف الدرجات.",
    whyEn: "Layers work with segmentation and least privilege so a yard guest never reaches the mark sheets.",
    termAr: "تقسيم الشبكة",
    termEn: "Segmentation",
    wrongAr: ["اجعل الضيوف على نفس كلمة سر الكنترول لسهولة اليوم", "عطّل الجدار ساعتين أثناء الزحام", "اطبع كلمات مرور الخوادم ووزّعها مع النتيجة"],
    wrongEn: ["Put guests on the same exam-control password for an easier day", "Disable the firewall for two hours during the crowd", "Print server passwords and hand them out with the results"],
  },
  {
    id: "2-2-f20",
    lessonId: "2-2",
    chapterId: "2",
    sceneAr: "مدرسة تجريبية في الهرم تشارك حساب مدير النظام بين وكيل ومعمل ومكتب الأنشطة.",
    sceneEn: "An experimental school in Al-Haram shares one system-admin account among the deputy, the lab, and activities.",
    claimAr: "قسّم الحسابات وأعطِ كل دور أقل صلاحية مع طبقات حول البيانات.",
    claimEn: "Split the accounts and give each role least privilege with layers around the data.",
    whyAr: "حساب أدمن واحد يسقط كل الطبقات دفعة إن تسربت الكلمة.",
    whyEn: "One admin account knocks down every layer at once if the password leaks.",
    termAr: "مبدأ أقل صلاحية",
    termEn: "Least privilege",
    wrongAr: ["ألصق كلمة الأدمن في درج السكرتارية", "فعّل الدخول عن بعد للحساب من أي مقهى", "اجعل الطلاب المتفوقين مشرفين مؤقتين على الخادم"],
    wrongEn: ["Tape the admin password inside the secretary's drawer", "Enable remote login for that account from any cafe", "Make top students temporary supervisors on the server"],
  },
  {
    id: "2-3-f01",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "معمل في الهرم تظهر على شاشاته رسالة تطالب بفدية وتغلق ملفات المشاريع.",
    sceneEn: "A lab in Al-Haram shows a ransom note on the screens and locks project files.",
    claimAr: "تعامل مع الأمر كحادث يهدد الإتاحة والسلامة لا كعطل طابعة عادي.",
    claimEn: "Treat it as an incident that threatens availability and integrity, not as a normal printer fault.",
    whyAr: "الحادث حدث يمس سرية أو سلامة أو إتاحة المعلومات ويستحق خطة لا ارتجالًا.",
    whyEn: "An incident touches confidentiality, integrity, or availability and needs a plan, not improvisation.",
    termAr: "الحادث",
    termEn: "Incident",
    wrongAr: ["أعد تشغيل الأجهزة وتجاهل الرسالة لأنها مزحة", "ادفع الفدية من صندوق الرحلات بسرعة", "اطلب من الطلاب نسخ الملفات المصابة إلى الفلاش"],
    wrongEn: ["Reboot and ignore the message as a joke", "Pay the ransom quickly from the trip fund", "Ask students to copy the infected files onto flash drives"],
  },
  {
    id: "2-3-f02",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "عيادة في جامعة عين شمس تكتشف أن كشف حضور المرضى ظهر في مجموعة طلابية.",
    sceneEn: "A clinic at Ain Shams University finds the patient attendance sheet posted in a student group.",
    claimAr: "سجّل الحادث فورًا لأنه يهدد السرية حتى لو توقفت المشاركة لاحقًا.",
    claimEn: "Log the incident at once because confidentiality is threatened even if the post is later taken down.",
    whyAr: "تسريب الحضور حادث معلوماتي؛ الزمن الضائع قبل التسجيل يوسّع من رأى البيان.",
    whyEn: "A leaked attendance list is an information incident; time lost before logging widens who saw it.",
    termAr: "الحادث",
    termEn: "Incident",
    wrongAr: ["احذف المنشور واصمت حتى لا تتوتر الإدارة", "عدّ الأمر مشكلة علاقات عامة لا أمنية", "اطلب من الطلاب إعادة نشر الكشف «للتصحيح»"],
    wrongEn: ["Delete the post and stay silent so leadership stays calm", "Call it a public-relations issue, not a security one", "Ask students to repost the sheet «to correct it»"],
  },
  {
    id: "2-3-f03",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "أرشيف ورقي في الإسكندرية يعتمد طابعة قديمة معزولة بلا إنترنت ولا بيانات طلاب.",
    sceneEn: "A paper archive in Alexandria uses an old printer that is isolated, offline, and holds no student data.",
    claimAr: "يمكن قبول الخطر بعد عزله لأنه محدود ولا يلمس بيانات حية.",
    claimEn: "The risk can be accepted after isolation because it is limited and touches no live data.",
    whyAr: "قبول الخطر قرار واعٍ بعد التقدير لا إهمال؛ يناسب خطرًا صغيرًا محكومًا.",
    whyEn: "Accepting risk is a conscious choice after an estimate, not neglect; it fits a small, contained risk.",
    termAr: "قبول الخطر",
    termEn: "Accepting risk",
    wrongAr: ["اربط الطابعة بالإنترنت العام لأنها قديمة «لن يهتم أحد»", "انقل ملفات الكنترول إلى الطابعة لتجربة السرعة", "أخفِ وجود الطابعة عن سجل المخاطر"],
    wrongEn: ["Put the printer on the public Internet because it is old and «nobody will care»", "Move exam-control files onto the printer to test speed", "Hide the printer from the risk register"],
  },
  {
    id: "2-3-f04",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "معلمون في المنصورة يعيدون استخدام كلمة مرور واحدة لكل المنصات بعد حادث تخمين.",
    sceneEn: "Teachers in Mansoura reuse one password on every platform after a guessing incident.",
    claimAr: "خفّف الخطر بتدريب قصير وكلمات مختلفة وعامل ثانٍ.",
    claimEn: "Reduce the risk with a short drill, different passwords, and a second factor.",
    whyAr: "تخفيف الخطر يغيّر الاحتمال أو الأثر بدل تجاهل الحادث المتكرر.",
    whyEn: "Reducing risk changes likelihood or impact instead of ignoring a repeating incident.",
    termAr: "تخفيف الخطر",
    termEn: "Reducing risk",
    wrongAr: ["اقبل الخطر من غير تقدير لأنه «حدث مرة»", "انقل الخطر بشراء ملصق تحذيري فقط", "أبقِ الكلمة الواحدة لتسهيل الذاكرة"],
    wrongEn: ["Accept the risk with no estimate because it «happened once»", "Transfer the risk by buying a warning sticker only", "Keep the single password to make memory easier"],
  },
  {
    id: "2-3-f05",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "مدرسة في القاهرة تؤمّن أجهزة الرحلات عبر شركة نقل وصيانة خارجية بعقد واضح.",
    sceneEn: "A Cairo school covers trip devices through an external transport-and-repair firm with a clear contract.",
    claimAr: "انقل جزءًا من الخطر إلى الجهة المتعاقدة بعد تحديد المسؤوليات كتابة.",
    claimEn: "Transfer part of the risk to the contracted party after writing down the duties.",
    whyAr: "نقل الخطر يحوّل أثرًا ماليًا أو تشغيليًا إلى طرف أقدر على تحمله بعقد لا بإنكار.",
    whyEn: "Risk transfer moves a financial or operational impact to a party better able to bear it, by contract, not by denial.",
    termAr: "نقل الخطر",
    termEn: "Transferring risk",
    wrongAr: ["وقّع العقد ثم انسَ متابعة الشركة", "انقل الخطر شفهيًا من غير بنود", "ألقِ اللوم على الطلاب إن ضاعت الأجهزة من غير عقد"],
    wrongEn: ["Sign the contract then forget to follow the company", "Transfer the risk verbally with no clauses", "Blame the students if devices vanish with no contract"],
  },
  {
    id: "2-3-f06",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "كنترول في الجيزة يسجّل دخولًا غريبًا من مدينة أخرى في منتصف الليل على حساب المصحح.",
    sceneEn: "Exam control in Giza logs a strange midnight login from another city on a marker's account.",
    claimAr: "اكتشف الحادث وسجّل الوقت والمصدر قبل أي مسح.",
    claimEn: "Detect the incident and record the time and source before any wipe.",
    whyAr: "الاكتشاف أول خطوة في خطة الاستجابة؛ بلا زمن ومصدر تضيع بقية السلسلة.",
    whyEn: "Detection is the first step of the response plan; without time and source the rest of the chain is lost.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["انتظر أسبوعًا حتى يعترف المصحح", "امسح السجل حتى لا يُحرج أحد", "غيّر الساعة على الخادم لإخفاء التوقيت"],
    wrongEn: ["Wait a week until the marker confesses", "Erase the log so nobody is embarrassed", "Change the server clock to hide the time"],
  },
  {
    id: "2-3-f07",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "لابتوب طالب في الزقازيق ينشر ملفات غريبة على طابعة فصل الأحياء.",
    sceneEn: "A student laptop in Zagazig is pushing strange files onto the biology-class printer.",
    claimAr: "احتوِ الجهاز: افصله عن الشبكة ولا تطفئه بالمسح العشوائي أولًا.",
    claimEn: "Contain the device: pull it off the network and do not start with a random wipe.",
    whyAr: "الاحتواء يوقف اتساع الضرر بينما تبقى الأدلة على القرص.",
    whyEn: "Containment stops the damage from spreading while evidence stays on the disk.",
    termAr: "الاحتواء",
    termEn: "Containment",
    wrongAr: ["اترك الجهاز متصلًا حتى تنتهي الحصة", "امسح القرص فورًا من غير صورة", "انقل اللابتوب إلى شبكة الدرجات «ليُفحص»"],
    wrongEn: ["Leave the device online until the lesson ends", "Wipe the disk at once with no image", "Move the laptop onto the marks network «to be checked»"],
  },
  {
    id: "2-3-f08",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "معمل في الفيوم بعد العزل ما زال يحمل أداة خبيثة في مجلد بدء التشغيل.",
    sceneEn: "A lab in Fayoum, already isolated, still holds malware in the startup folder.",
    claimAr: "أزل السبب بعد الاحتواء: احذف الأداة الخبيثة من المسارات التي تعيدها.",
    claimEn: "After containment, eradicate the cause: remove the malware from the paths that relaunch it.",
    whyAr: "الإزالة تكسر بقاء التهديد؛ الاحتواء وحده يجمّد المشهد من غير تنظيف.",
    whyEn: "Eradication breaks the threat's persistence; containment alone freezes the scene without cleaning it.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["أعد التوصيل بالشبكة ثم أزل الملف إن تيسّر", "غيّر خلفية الشاشة وعدّ الجهاز نظيفًا", "انسخ مجلد البدء إلى بقية الأجهزة كنسخة احتياطية"],
    wrongEn: ["Reconnect to the network then remove the file if convenient", "Change the wallpaper and call the machine clean", "Copy the startup folder onto the other PCs as a backup"],
  },
  {
    id: "2-3-f09",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "معمل في سوهاج نُظّف من البرمجية ويحتاج ملفات المشاريع لحصص الأسبوع.",
    sceneEn: "A lab in Sohag is cleaned of malware and needs project files for this week's lessons.",
    claimAr: "استعد من نسخة سليمة معروفة بعد التأكد أن الخبيث لن يعود معها.",
    claimEn: "Recover from a known-good backup after checking the malware will not return with it.",
    whyAr: "التعافي يعيد الخدمة من مصدر موثوق لا من القرص المصاب نفسه.",
    whyEn: "Recovery restores the service from a trusted source, not from the infected disk itself.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["استعد من آخر نسخة حتى لو كانت يوم الإصابة", "افتح المعمل للطلاب أثناء الاستعادة التجريبية", "استورد الملفات من فلاشات الطلاب مباشرة"],
    wrongEn: ["Restore the newest backup even if it is from the day of infection", "Open the lab to students during the trial restore", "Import files straight from student flash drives"],
  },
  {
    id: "2-3-f10",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "اجتماع في حلوان بعد إعادة المعمل للعمل من غير سؤال عن الثغرة التي فتحت الباب.",
    sceneEn: "A meeting in Helwan after the lab is back, with no question about the hole that opened the door.",
    claimAr: "راجع ما فشل في التصميم وأصلح السبب لا العرض.",
    claimEn: "Review what failed in the design and fix the cause, not the symptom.",
    whyAr: "المراجعة آخر خطوة في الخطة حتى لا يتكرر الحادث بنفس الثغرة.",
    whyEn: "Review is the last step of the plan so the same hole does not invite the next incident.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["أغلق المحضر واعتبر الأمر انتهى بالتشغيل", "عاقب طالبًا واحدًا من غير فحص الشبكة", "أخّر المراجعة إلى العام القادم بلا موعد"],
    wrongEn: ["Close the minutes and treat power-on as the end", "Punish one student without inspecting the network", "Delay the review until next year with no date"],
  },
  {
    id: "2-3-f11",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "مدير في بني سويف يطلب من السكرتيرة إخفاء تسريب كشوف الغياب حتى «تهدأ الأمور».",
    sceneEn: "A head in Beni Suef tells the secretary to hide an attendance-sheet leak until «things calm down».",
    claimAr: "أبلغ الحادث فورًا؛ الإخفاء يوسّع الضرر ويضيع وقت الاحتواء.",
    claimEn: "Report the incident at once; hiding it widens harm and wastes containment time.",
    whyAr: "الوقت الضائع قبل الإبلاغ يترك المنتحل أو الملف المسرب يعمل من غير مقاومة.",
    whyEn: "Time lost before reporting leaves the impersonator or the leaked file working unopposed.",
    termAr: "الحادث",
    termEn: "Incident",
    wrongAr: ["أخّر الإبلاغ لأسبوع الامتحانات", "امسح البريد الذي يذكر التسريب", "أعد طباعة الكشف وعدّ المشكلة اختفت"],
    wrongEn: ["Delay reporting until exam week", "Delete the mail that mentions the leak", "Reprint the sheet and treat the problem as gone"],
  },
  {
    id: "2-3-f12",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "عيادة أطفال تعليمية تريد مسح جهاز استقبال التحاليل بعد ظهور برنامج غريب.",
    sceneEn: "A teaching children's clinic wants to wipe a lab-results PC after a strange program appears.",
    claimAr: "احفظ صورة من الأدلة وسجّل الزمن قبل أي مسح.",
    claimEn: "Preserve an evidence image and the timestamp before any wipe.",
    whyAr: "حفظ الأدلة يتيح التعلّم والمراجعة؛ المسح الأول يمحو السبب مع العرض.",
    whyEn: "Preserving evidence lets the team learn and review; the first wipe erases the cause with the symptom.",
    termAr: "حفظ الأدلة",
    termEn: "Preserving evidence",
    wrongAr: ["امسح فورًا حتى يدخل المرضى", "أعد تثبيت النظام فوق الملفات من غير نسخة", "أعطِ الجهاز لطالب متفوق لـ«ينظّفه في البيت»"],
    wrongEn: ["Wipe at once so patients can enter", "Reinstall over the files with no copy", "Give the PC to a top student to «clean it at home»"],
  },
  {
    id: "2-3-f13",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "فني في بورسعيد يهمّ بتهيئة قرص معمل الفنون في اللحظة التي ظهرت فيها ملفات مشبوهة.",
    sceneEn: "A technician in Port Said is about to format an art-lab disk the moment suspicious files appear.",
    claimAr: "أوقف التهيئة حتى تُحفظ الأدلة ويُحتوى الجهاز.",
    claimEn: "Stop the format until evidence is kept and the device is contained.",
    whyAr: "المسح قبل التسجيل قرار سيئ لأنه يمنع معرفة كيف دخل الخبيث.",
    whyEn: "Wiping before any record is a bad first move because it hides how the malware entered.",
    termAr: "حفظ الأدلة",
    termEn: "Preserving evidence",
    wrongAr: ["أكمل التهيئة ثم اكتب تقريرًا من الذاكرة", "فرّغ الملفات المشبوهة على شبكة المدرسة أولًا", "أعد تشغيل الجهاز عشر مرات لعل الرسالة تختفي"],
    wrongEn: ["Finish the format then write a report from memory", "Dump the suspicious files onto the school network first", "Reboot ten times in case the message vanishes"],
  },
  {
    id: "2-3-f14",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "شبكة في طنطا أُعيدت للخدمة بعد فيروس، والفني اكتفى بحذف أيقونة سطح المكتب.",
    sceneEn: "A network in Tanta is back after a virus, and the technician only deleted a desktop icon.",
    claimAr: "ابحث عن سبب الدخول: منفذ مفتوح أو كلمة مشتركة أو غياب تحديث.",
    claimEn: "Hunt the entry cause: an open port, a shared password, or a missing patch.",
    whyAr: "إصلاح العرض يترك الباب نفسه مفتوحًا للحادث التالي.",
    whyEn: "Fixing the symptom leaves the same door open for the next incident.",
    termAr: "إدارة المخاطر",
    termEn: "Risk management",
    wrongAr: ["اكتفِ بشكل الأيقونة وعدّ الشبكة محصّنة", "أخفِ تقرير السبب عن الإدارة", "افتح المنافذ من جديد «كما كانت»"],
    wrongEn: ["Trust the missing icon and call the network hardened", "Hide the cause report from leadership", "Reopen the ports «as they were»"],
  },
  {
    id: "2-3-f15",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "مديرية تعليم في أسيوط تعتمد على اتصال هاتفي وقت الأزمة من غير ورقة خطوات.",
    sceneEn: "An education directorate in Asyut relies on a phone call in a crisis with no written steps.",
    claimAr: "اكتب خطة استجابة: اكتشف، احتوِ، أزل، استعد، راجع.",
    claimEn: "Write a response plan: detect, contain, eradicate, recover, review.",
    whyAr: "الخطة المكتوبة تُنفَّذ تحت الضغط؛ الذاكرة وحدها تسقط في الهلع.",
    whyEn: "A written plan can be followed under pressure; memory alone fails in a panic.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["اترك الخطوات في رأس وكيل واحد", "ألّف الخطة بعد انتهاء كل حادث فقط", "اختصر الخطة إلى «أعد التشغيل»"],
    wrongEn: ["Keep the steps in one deputy's head", "Write the plan only after each incident ends", "Shrink the plan to «reboot»"],
  },
  {
    id: "2-3-f16",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "مدرسة بنات في الزمالك لديها ملف خطة على الرف ولم يُجرَّب في تدريب واحد.",
    sceneEn: "A girls' school in Zamalek has a plan file on a shelf that has never been rehearsed.",
    claimAr: "درّب الفريق على الخطة في تمرين هادئ قبل الحادث الحقيقي.",
    claimEn: "Rehearse the team on the plan in a calm drill before a real incident.",
    whyAr: "الخطة غير المُدرَّبة تبقى ورقة؛ التدريب يكشف من ينسى الاحتواء أو الأدلة.",
    whyEn: "An unrehearsed plan stays paper; a drill shows who forgets containment or evidence.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["اكتفِ بتوقيع المدير على الغلاف", "أجّل التمرين إلى ما بعد أول اختراق", "وزّع الخطة على الطلاب في مجموعة عامة"],
    wrongEn: ["Rely on the head's signature on the cover", "Postpone the drill until after the first breach", "Share the plan in a public student group"],
  },
  {
    id: "2-3-f17",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "غرفة معلمين في كفر الدوار تدخل في هتاف وصراخ حين تظهر شاشة سوداء على جهاز التحضير.",
    sceneEn: "A staff room in Kafr El-Dawar erupts in shouting when a prep PC goes black.",
    claimAr: "اتبع الورقة المكتوبة: افصل الشبكة، سجّل، أبلغ؛ لا ترتجل تحت الهلع.",
    claimEn: "Follow the written sheet: isolate, log, report; do not improvise under panic.",
    whyAr: "الاستجابة خطة تُدرَّب لا ارتجال وقت الهلع الذي يمسح الأدلة ويوسّع الإصابة.",
    whyEn: "Response is a rehearsed plan, not panic improvisation that wipes evidence and spreads infection.",
    termAr: "خطة الاستجابة",
    termEn: "Response plan",
    wrongAr: ["ابدأ بحذف كل الملفات «للاحتياط»", "اطفئ الكهرباء عن المبنى كله من غير سجل", "انشر الخبر في جروبات أولياء الأمور قبل الاحتواء"],
    wrongEn: ["Start by deleting every file «just in case»", "Cut power to the whole building with no record", "Post the news in parent groups before containment"],
  },
  {
    id: "2-3-f18",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "حساب معلم في منصة دمياط يرسل واجبات مزيفة بعد سرقة الجلسة.",
    sceneEn: "A teacher account on a Damietta platform is sending fake homework after a stolen session.",
    claimAr: "احتوِ الحساب: جمّده واقطع الجلسات حتى لا يتسع الضرر.",
    claimEn: "Contain the account: freeze it and cut sessions so the harm does not spread.",
    whyAr: "الاحتواء يعزل الحساب المصاب كما يعزل الجهاز؛ الاستمرار يوسّع الرسائل المزيفة.",
    whyEn: "Containment isolates a compromised account the way it isolates a device; leaving it open spreads fake messages.",
    termAr: "الاحتواء",
    termEn: "Containment",
    wrongAr: ["اترك الحساب مفتوحًا لرصد المهاجم من غير عزل", "امسح المنصة كلها من غير حفظ السجلات", "أعطِ كلمة المعلم لطالب ليرد على الرسائل"],
    wrongEn: ["Leave the account open to watch the attacker with no isolation", "Wipe the whole platform with no logs kept", "Give the teacher's password to a student to answer the messages"],
  },
  {
    id: "2-3-f19",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "مشرف في أسوان يؤجّل إبلاغ تسريب جدول الاختبارات إلى صباح الغد حتى لا يُزعج المدير ليلًا.",
    sceneEn: "A supervisor in Aswan delays reporting a leaked test timetable until morning so the head is not disturbed at night.",
    claimAr: "أبلغ الآن؛ كل ساعة تأخير تزيد من نسخ الجدول خارج المدرسة.",
    claimEn: "Report now; every delayed hour multiplies copies of the timetable outside the school.",
    whyAr: "إخفاء الحادث أو تأجيله لا يوفّر وقتًا؛ يوسّع دائرة من يملك البيان.",
    whyEn: "Hiding or delaying an incident does not save time; it widens who holds the data.",
    termAr: "الحادث",
    termEn: "Incident",
    wrongAr: ["انتظر حتى يجتمع مجلس الأمناء الأسبوع القادم", "عدّل الجدول بصمت من غير إعلان الحادث", "اطلب من الطلاب إنكار التسريب في الجروبات"],
    wrongEn: ["Wait until the board meets next week", "Quietly change the timetable with no incident notice", "Ask students to deny the leak in the groups"],
  },
  {
    id: "2-3-f20",
    lessonId: "2-3",
    chapterId: "2",
    sceneAr: "بعد تعافي معمل في قنا يعود الفريق للعمل من غير أن يسأل: أي منفذ أو صلاحية فتحت الباب؟",
    sceneEn: "After a lab in Qena recovers, the team returns to work without asking which port or right opened the door.",
    claimAr: "أغلق السبب الجذري في التصميم قبل إعلان انتهاء الأزمة.",
    claimEn: "Close the root design cause before declaring the crisis over.",
    whyAr: "التعافي بلا إصلاح السبب يعيد نفس الحادث في الأسبوع التالي.",
    whyEn: "Recovery without fixing the cause invites the same incident the following week.",
    termAr: "إدارة المخاطر",
    termEn: "Risk management",
    wrongAr: ["احتفل بتشغيل الأجهزة وتجاهل الثغرة", "انقل الخطر إلى طالب غائب من غير دليل", "اقبل الخطر شفهيًا لأن المعمل «اشتغل»"],
    wrongEn: ["Celebrate the PCs powering on and ignore the hole", "Transfer the risk onto an absent student with no evidence", "Accept the risk verbally because the lab «is running»"],
  },
];

export const CHAPTER_2_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "2-1-a01",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "حلّل موقف مكتبة الفيوم حين تُترك كلمة أمين المكتبة وحدها تحت الشاشة.",
    promptEn: "Analyse the Fayoum library case when the librarian password sits alone under the screen.",
    guideAr: "المصطلح: المصادقة متعددة العوامل. السبب: الكلمة تُسرق بالنظر. مثال مدرسي: أضف رسالة هاتف كما يفعل معلم شبرا عند فتح منصة الدرجات.",
    guideEn: "Term: multi-factor authentication. Reason: a password is stolen by looking. School example: add a phone code the way a Shubra teacher opens the marks platform.",
  },
  {
    id: "2-1-a02",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "قارن بين تشفير نسخة معمل الجيزة بمفتاح واحد وبين إرسال شكوى ولي أمر الإسكندرية بمفتاح عام.",
    promptEn: "Compare encrypting the Giza lab backup with one key and sending an Alexandria parent complaint with a public key.",
    guideAr: "المصطلح: التشفير المتماثل مقابل غير المتماثل. السبب: الطرفان إن اقتسما سرًا مسبقًا يكفيه مفتاح واحد، وإلا نحتاج زوجًا. مثال مدرسي: فني الجيزة يملك القرص غدًا، أما ولي الأمر في البيت فلم يلتقِ المدير.",
    guideEn: "Term: symmetric versus asymmetric encryption. Reason: a prior shared secret needs one key; strangers need a pair. School example: the Giza technician will hold the disk tomorrow, but the parent at home never met the head.",
  },
  {
    id: "2-1-a03",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "انتقد تطبيق مدير بني سويف الذي يشفّر القرار ولا يسأل من المرسل.",
    promptEn: "Critique the Beni Suef head's app that encrypts a decision and never asks who sent it.",
    guideAr: "المصطلح: المصادقة. السبب: السرية بلا تحقق هوية تفتح انتحال الشخصية. مثال مدرسي: رسالة مشفّرة في قنا تدّعي أنها من رائد الفصل وتطلب رقم البطاقة.",
    guideEn: "Term: authentication. Reason: secrecy without an identity check invites impersonation. School example: an encrypted Qena message claims to be the class tutor and asks for an ID number.",
  },
  {
    id: "2-1-a04",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "اشرح لماذا لا يستطيع فني سوهاج استخراج كلمة الطالب من قاعدة التجزئة.",
    promptEn: "Explain why the Sohag technician cannot pull the student's password out of the hash database.",
    guideAr: "المصطلح: التجزئة. السبب: الاتجاه الواحد يمنع استرجاع الأصل بعد السرقة. مثال مدرسي: خادم دمياط يجب أن يقارن البصمة لا أن يحفظ النص الواضح.",
    guideEn: "Term: hashing. Reason: one-way storage blocks recovering the original after theft. School example: the Damietta server should compare a fingerprint, not keep clear text.",
  },
  {
    id: "2-1-a05",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "حلّل تحذير متصفح طلاب الأقصر حين لا تطابق الشهادة اسم موقع المدرسة.",
    promptEn: "Analyse the Luxor students' browser warning when the certificate does not match the school site name.",
    guideAr: "المصطلح: الشهادة الرقمية. السبب: هي التي تربط المفتاح العام بهوية موثوقة. مثال مدرسي: عيادة أسنان أسوان لا يكفي أن تنشر مفتاحًا عامًا من غير جهة تُثبت الاسم.",
    guideEn: "Term: digital certificate. Reason: it binds a public key to a trusted identity. School example: an Aswan dental clinic cannot just publish a public key with nobody vouching for the name.",
  },
  {
    id: "2-1-a06",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "قارن بين كلمة مرور معلم شبرا ورسالة هاتفه وبصمة طالب معمل أكتوبر.",
    promptEn: "Compare the Shubra teacher's password, the phone code, and the October STEM-lab fingerprint.",
    guideAr: "المصطلح: المصادقة متعددة العوامل. السبب: شيء تعرفه وشيء تملكه وشيء أنت عليه طبقات مختلفة. مثال مدرسي: سرقة ورقة المكتبة في الفيوم لا تفتح الجهاز إن بقيت البصمة أو الرمز.",
    guideEn: "Term: multi-factor authentication. Reason: something you know, have, and are are different layers. School example: stealing the Fayoum library paper still fails if the fingerprint or code remains.",
  },
  {
    id: "2-1-a07",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "انتقد عيادة العريش التي تشفّر الملف الطبي ثم تفتحه لمن يعرف اسم المريض فقط.",
    promptEn: "Critique the Arish clinic that encrypts the medical file then opens it for anyone who knows the patient's name.",
    guideAr: "المصطلح: انتحال الهوية. السبب: التشفير يحمي الطريق لا يثبت الزائر. مثال مدرسي: كنترول الزقازيق إن مرّر النماذج مشفّرة من غير مصادقة قد يسلّمها لمنتحل عند الطابعة.",
    guideEn: "Term: impersonation. Reason: encryption protects the path and does not prove the visitor. School example: Zagazig exam control can still hand papers to a faker at the printer if nobody authenticates.",
  },
  {
    id: "2-1-a08",
    lessonId: "2-1",
    chapterId: "2",
    promptAr: "اشرح لماذا يبقى المفتاح الخاص على خادم شؤون طلاب حلوان ولا يُرسل مع الملفات الواردة.",
    promptEn: "Explain why the private key stays on the Helwan student-affairs server and is not sent with inbound files.",
    guideAr: "المصطلح: التشفير غير المتماثل. السبب: من يملك الخاص يفك كل الرسائل. مثال مدرسي: بوابة الإسكندرية تشفّر بالمفتاح العام والمدرسة وحدها تفك.",
    guideEn: "Term: asymmetric encryption. Reason: whoever holds the private key can open every message. School example: the Alexandria portal encrypts with the public key and only the school decrypts.",
  },
  {
    id: "2-2-a01",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "حلّل اعتماد خادم درجات العباسية على جدار حماية واحد وأجهزة داخلية بلا كلمة مرور.",
    promptEn: "Analyse the Abbasiya marks server that trusts one firewall while inner PCs have no passwords.",
    guideAr: "المصطلح: الأمن متعدد الطبقات. السبب: سقوط المحيط يكشف الشبكة إن لم تُحمَ الأجهزة والبيانات. مثال مدرسي: راوتر مدينة نصر عند البوابة لا يغني عن قفل الأجهزة اللوحية في الأقصر.",
    guideEn: "Term: layered security. Reason: if the perimeter falls the network is bare unless devices and data stay protected. School example: the Nasr City gate router does not replace locking tablets in Luxor.",
  },
  {
    id: "2-2-a02",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "قارن دخول معلمة أكتوبر من مقهى عبر نفق مشفّر وبين فتح الأرشيف على واي فاي فندق الإسكندرية.",
    promptEn: "Compare the October teacher entering through an encrypted tunnel with opening the archive on Alexandria hotel Wi-Fi.",
    guideAr: "المصطلح: شبكة خاصة افتراضية. السبب: الشبكة العامة لا تُوثق فالنفق يعيد الحركة كأنها داخل المدرسة. مثال مدرسي: تصحيح الواجبات من البيت يحتاج النفق لا كلمة مقهى.",
    guideEn: "Term: VPN. Reason: a public network is untrusted so the tunnel makes traffic behave as if it were on campus. School example: marking homework from home needs the tunnel, not a cafe password.",
  },
  {
    id: "2-2-a03",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "انتقد طلب أمين مكتبة دمنهور صلاحية تعديل درجات الفيزياء «للاحتياط».",
    promptEn: "Critique the Damanhur librarian asking for physics-mark rights «just in case».",
    guideAr: "المصطلح: مبدأ أقل صلاحية. السبب: زيادة الصلاحية تضخّم أثر سرقة الحساب. مثال مدرسي: حساب معلم المحلة المشترك يجعل خطأ طالب غير قابل للتتبع.",
    guideEn: "Term: least privilege. Reason: extra rights magnify harm if the account is stolen. School example: the shared El-Mahalla teacher account makes a student mistake untraceable.",
  },
  {
    id: "2-2-a04",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "اشرح لماذا يُقسم معمل المنيا المصاب عن خادم نتائج الإعدادية فورًا.",
    promptEn: "Explain why the infected Minya lab is segmented from the prep-results server at once.",
    guideAr: "المصطلح: تقسيم الشبكة. السبب: العزل يحصر الاختراق فلا يصل للدرجات. مثال مدرسي: عيادة الزاوية الحمراء يجب ألا تشارك واي فاي فصل الحاسب.",
    guideEn: "Term: segmentation. Reason: isolation confines a breach so it never reaches marks. School example: the Zawya El-Hamra clinic must not share the computer-class Wi-Fi.",
  },
  {
    id: "2-2-a05",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "حلّل قرار مدرسة الشيخ زايد بتأجيل كلمات المرور والصلاحيات إلى ما بعد إطلاق البوابة.",
    promptEn: "Analyse the Sheikh Zayed school postponing passwords and rights until after the portal launches.",
    guideAr: "المصطلح: الأمن بالتصميم. السبب: الترقيع بعد دخول أولياء الأمور أضعف وأغلى. مثال مدرسي: منصة التجمع التي طُلب «إضافة أمن» في آخر أسبوع تبقى هشة.",
    guideEn: "Term: security by design. Reason: a bolt-on after parents arrive is weaker and costlier. School example: the Fifth Settlement platform told to «add security» in the last week stays fragile.",
  },
  {
    id: "2-2-a06",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "قارن طبقات المحيط في مدينة نصر والشبكة الداخلية في المعادي الجديدة وملفات امتحان طنطا.",
    promptEn: "Compare the Nasr City perimeter, the New Maadi internal network, and the Tanta exam files.",
    guideAr: "المصطلح: الأمن متعدد الطبقات. السبب: محيط ثم شبكة ثم أجهزة ثم بيانات؛ إن سقطت واحدة تبقى التالية. مثال مدرسي: قفل باب المعمل لا يحمي مجلدًا مشتركًا بلا تشفير.",
    guideEn: "Term: layered security. Reason: perimeter, then internal network, then devices, then data; if one falls the next should still hold. School example: locking the lab door does not protect an unencrypted shared folder.",
  },
  {
    id: "2-2-a07",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "انتقد إبقاء منفذ سطح المكتب البعيد مفتوحًا على خادم أنشطة السويس من غير استخدام.",
    promptEn: "Critique leaving the unused remote-desktop port open on the Suez activities server.",
    guideAr: "المصطلح: إغلاق المنافذ. السبب: الباب بلا خدمة جاهز للمسح الآلي. مثال مدرسي: فني السويس إن غيّر الرقم فقط من غير إغلاق يظل الهدف قائمًا.",
    guideEn: "Term: closing unused ports. Reason: a door with no real service is ready for automated scans. School example: the Suez technician who only changes the number still leaves a target.",
  },
  {
    id: "2-2-a08",
    lessonId: "2-2",
    chapterId: "2",
    promptAr: "اشرح لماذا لا يؤجَّل تحديث معمل أسيوط حتى بعد الامتحانات.",
    promptEn: "Explain why the Asyut lab patch must not wait until after exams.",
    guideAr: "المصطلح: التحديث الأمني. السبب: التأجيل يترك ثغرة معروفة للمهاجم. مثال مدرسي: جدار واحد في العباسية لا يعوّض نظامًا قديمًا بلا رقعة.",
    guideEn: "Term: security patching. Reason: delay leaves a hole attackers already know. School example: one Abbasiya firewall does not make up for an unpatched old system.",
  },
  {
    id: "2-3-a01",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "حلّل طلب مدير بني سويف إخفاء تسريب كشوف الغياب حتى تهدأ الأمور.",
    promptEn: "Analyse the Beni Suef head asking to hide an attendance leak until things calm down.",
    guideAr: "المصطلح: الحادث. السبب: الوقت الضائع يوسّع من رأى البيان. مثال مدرسي: تأخير مشرف أسوان لجدول الاختبارات إلى الصباح يزيد النسخ خارج المدرسة.",
    guideEn: "Term: incident. Reason: lost time widens who saw the data. School example: the Aswan supervisor delaying a leaked timetable until morning multiplies outside copies.",
  },
  {
    id: "2-3-a02",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "قارن قبول طابعة أرشيف الإسكندرية المعزولة وتخفيف كلمات معلمي المنصورة ونقل أجهزة رحلات القاهرة بعقد.",
    promptEn: "Compare accepting the isolated Alexandria archive printer, reducing Mansoura teacher passwords, and transferring Cairo trip-device risk by contract.",
    guideAr: "المصطلح: إدارة المخاطر. السبب: بعد التقدير نقبل أو نخفّف أو ننقل لا نتجاهل. مثال مدرسي: طابعة بلا بيانات حية تُقبل بعد العزل، أما كلمة واحدة لكل المنصات فتُخفَّف.",
    guideEn: "Term: risk management. Reason: after an estimate we accept, reduce, or transfer; we do not ignore. School example: a printer with no live data can be accepted once isolated, but one password for every platform must be reduced.",
  },
  {
    id: "2-3-a03",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "انتقد تهيئة قرص معمل الفنون في بورسعيد في لحظة ظهور الملفات المشبوهة.",
    promptEn: "Critique formatting the Port Said art-lab disk the moment suspicious files appear.",
    guideAr: "المصطلح: حفظ الأدلة. السبب: المسح الأول يمحو كيف دخل الخبيث. مثال مدرسي: عيادة الأطفال التعليمية تصوّر القرص وتسجّل الزمن قبل أي مسح.",
    guideEn: "Term: preserving evidence. Reason: the first wipe erases how the malware entered. School example: the teaching children's clinic images the disk and notes the time before any wipe.",
  },
  {
    id: "2-3-a04",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "اشرح لماذا لا تكفي ورقة الخطة على رف مدرسة الزمالك من غير تمرين.",
    promptEn: "Explain why the Zamalek school's plan on a shelf is not enough without a drill.",
    guideAr: "المصطلح: خطة الاستجابة. السبب: الورقة غير المُدرَّبة تسقط تحت الهلع. مثال مدرسي: غرفة معلمي كفر الدوار إن صرخت عند الشاشة السوداء تمسح الأدلة قبل الاحتواء.",
    guideEn: "Term: response plan. Reason: unrehearsed paper fails under panic. School example: the Kafr El-Dawar staff room shouting at a black screen wipes evidence before containment.",
  },
  {
    id: "2-3-a05",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "حلّل خطوة عزل لابتوب الزقازيق عن طابعة الأحياء قبل أي تنظيف.",
    promptEn: "Analyse isolating the Zagazig laptop from the biology printer before any cleanup.",
    guideAr: "المصطلح: الاحتواء. السبب: فصل الجهاز يوقف الاتساع ويبقي الأدلة. مثال مدرسي: حساب معلم دمياط المزوَّر يُجمَّد وتُقطع جلساته لنفس العلة.",
    guideEn: "Term: containment. Reason: pulling the device off stops spread and keeps evidence. School example: a faked Damietta teacher account is frozen and its sessions cut for the same reason.",
  },
  {
    id: "2-3-a06",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "قارن حذف أيقونة الفيروس في طنطا بإصلاح المنفذ أو الكلمة التي فتحت الباب.",
    promptEn: "Compare deleting the virus icon in Tanta with fixing the port or password that opened the door.",
    guideAr: "المصطلح: إدارة المخاطر. السبب: العرض يعود إن بقي السبب. مثال مدرسي: بعد تعافي معمل قنا يجب سؤال أي صلاحية بقيت مفتوحة.",
    guideEn: "Term: risk management. Reason: the symptom returns if the cause remains. School example: after the Qena lab recovers the team must ask which right stayed open.",
  },
  {
    id: "2-3-a07",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "انتقد اعتماد مديرية أسيوط على اتصال هاتفي وقت الأزمة من غير خطوات مكتوبة.",
    promptEn: "Critique the Asyut directorate relying on a crisis phone call with no written steps.",
    guideAr: "المصطلح: خطة الاستجابة. السبب: الذاكرة تسقط في الهلع والخطة تقول اكتشف ثم احتوِ ثم أزل ثم استعد ثم راجع. مثال مدرسي: وكيل واحد يحفظ الخطوات في رأسه يعطّل المدرسة إن غاب.",
    guideEn: "Term: response plan. Reason: memory fails in a panic and the plan says detect, contain, eradicate, recover, review. School example: one deputy holding the steps in his head stalls the school if he is away.",
  },
  {
    id: "2-3-a08",
    lessonId: "2-3",
    chapterId: "2",
    promptAr: "اشرح لماذا يعقد اجتماع حلوان مراجعة بعد إعادة تشغيل المعمل لا يكتفي بالتشغيل.",
    promptEn: "Explain why the Helwan meeting reviews the lab after it is back instead of stopping at power-on.",
    guideAr: "المصطلح: خطة الاستجابة. السبب: المراجعة تصلح ما فشل في التصميم حتى لا يتكرر الحادث. مثال مدرسي: رسالة فدية الهرم إن عادت بعد أسبوع فذلك لأن السبب لم يُغلق.",
    guideEn: "Term: response plan. Reason: review fixes what failed in the design so the incident does not repeat. School example: if the Al-Haram ransom note returns a week later the cause was never closed.",
  },
];
