import type { AnalysisPrompt, BankFact } from "@/lib/question-bank/types";

export const CHAPTER_5_FACTS: BankFact[] = [
  {
    id: "5-1-f01",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "صبا تقف بطابور الكانتين وتسجّل بساعتها زمن انتظار كل طالب لتقرير حصة الإحصاء.",
    sceneEn: "Saba stands in the canteen queue and times each wait with her watch for a stats-class report.",
    claimAr: "هذه بيانات أولية لأنها جُمعت بنفسها لغرض البحث.",
    claimEn: "This is primary data because she gathered it herself for the research purpose.",
    whyAr: "القياس الميداني لغرض محدد يجعل المصدر أنت لا جدولًا جاهزًا.",
    whyEn: "A field measurement for a stated purpose makes you the source, not a ready-made table.",
    termAr: "بيانات أولية",
    termEn: "Primary data",
    wrongAr: ["اعتبرها ثانوية لأنها أرقام ساعات", "انسخ زمنًا من إنترنت بلا قياس", "ارفض القياس لأنه ليس ملفًا حكوميًا"],
    wrongEn: ["Call it secondary because the numbers are times", "Copy a time from the internet with no measurement", "Reject the measurement because it is not a government file"],
  },
  {
    id: "5-1-f02",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "يوسف يحمّل جدول الجهاز المركزي للتعبئة والإحصاء عن عدد السكان سنة 2022 لمشروع الصف.",
    sceneEn: "Youssef downloads a 2022 CAPMAS population table for the class project.",
    claimAr: "هذه بيانات ثانوية جمعها غيرك ونشرها؛ راجع الغرض والتاريخ.",
    claimEn: "This is secondary data collected and published by others; check purpose and date.",
    whyAr: "الجهاز جمع الرقم لغرضه لا لغرض حصتك، فالسؤال عن الملاءمة واجب.",
    whyEn: "The agency collected the figure for its purpose, not yours, so fitness must be checked.",
    termAr: "بيانات ثانوية",
    termEn: "Secondary data",
    wrongAr: ["سمّها أولية لأنك ضغطت زر التحميل", "اخفِ اسم الجهاز حتى يبدو البحث أصليًا", "افترض أنها تطابق سؤالك حتمًا"],
    wrongEn: ["Call it primary because you clicked download", "Hide the agency name so the research looks original", "Assume it automatically matches your question"],
  },
  {
    id: "5-1-f03",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "فصل 3ث يريد رأي كل طلاب المدرسة عن طول الحصة، لكن الوقت يكفي لسؤال أربعين طالبًا فقط.",
    sceneEn: "A Grade 12 class wants every student’s view on lesson length, but time allows only forty interviews.",
    claimAr: "المدرسة مجتمع البحث، والأربعون عينة يجب أن تشبه هذا المجتمع.",
    claimEn: "The school is the population; the forty are a sample that must resemble that population.",
    whyAr: "لا تستطيع سؤال الكل دائمًا، فالعينة العادلة صورة مصغّرة لا بديل عن المجتمع.",
    whyEn: "You cannot always ask everyone, so a fair sample is a miniature, not a replacement slogan.",
    termAr: "مجتمع / عينة",
    termEn: "Population / sample",
    wrongAr: ["اعتبر الأربعين هم المجتمع كله", "عمّم على الجمهورية لأن الرقم أربعون يبدو كبيرًا", "أضف أسماء وهمية حتى يصل العدد للمدرسة كلها"],
    wrongEn: ["Treat the forty as the whole population", "Generalise to the country because forty looks large", "Invent names so the count matches the whole school"],
  },
  {
    id: "5-1-f04",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "استطلاع درجات المذاكرة يُنشر في جروب واتساب واحد لدفعة المتفوقين فقط.",
    sceneEn: "A study-hours poll is posted in one WhatsApp group that holds only the honour-roll cohort.",
    claimAr: "لا تعمّم على المدرسة؛ الجروب الواحد يحرّف العينة.",
    claimEn: "Do not generalise to the school; one group warps the sample.",
    whyAr: "من يصل للجروب ويردّ ليس صورة باقي الصفوف ولا من لا يستخدم واتساب.",
    whyEn: "Whoever is in that group and replies is not a picture of other classes or non-WhatsApp students.",
    termAr: "تحيز العينة",
    termEn: "Sampling bias",
    wrongAr: ["عمّم على المدرسة لأن الردود كثيرة", "ضاعف أصوات الجروب لتعويض الغائبين", "احذف من لم يرد واعتبر العينة كاملة"],
    wrongEn: ["Generalise to the school because many replies arrived", "Double the group votes to replace absentees", "Drop non-repliers and treat the sample as complete"],
  },
  {
    id: "5-1-f05",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "منة تجمع إجابات الاستطلاع ثم تحسب المتوسط فورًا قبل ترتيب الصفوف وتوحيد الوحدات.",
    sceneEn: "Mennah collects poll answers then instantly computes a mean before sorting rows or unifying units.",
    claimAr: "اتبع المسار: جمع ثم تنظيم ثم تحليل، لا تقفز للحساب.",
    claimEn: "Follow collect, then organise, then analyse; do not jump to the calculation.",
    whyAr: "إن فسد الترتيب والتوحيد فالحساب الأنيق يثبّت الخطأ لا يصلحه.",
    whyEn: "If sorting and unification are skipped, neat maths locks the error in place.",
    termAr: "مسار التحليل",
    termEn: "Analysis pipeline",
    wrongAr: ["ابدأ بالرسم ثم اجمع ما يناسب الصورة", "احسب المتوسط ثم رتّب ما تبقّى للزينة", "أدمج الجمع والتحليل في خطوة واحدة بلا جدول"],
    wrongEn: ["Start with the chart then collect whatever fits the picture", "Compute the mean then tidy leftovers for decoration", "Merge collection and analysis with no table"],
  },
  {
    id: "5-1-f06",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "أمين المعمل يسحب عشرين رقم جلوس من صندوق فيه أرقام كل طلاب 2ث بعد خلط الأوراق.",
    sceneEn: "The lab prefect draws twenty seat numbers from a box that holds every Grade 11 ID after shuffling.",
    claimAr: "هذه عينة عشوائية بسيطة لأن لكل طالب فرصة متكافئة.",
    claimEn: "This is a simple random sample because every student has an equal chance.",
    whyAr: "القرعة من قائمة كاملة تعطي فرصة متماثلة وتقلل تدخل الباحث.",
    whyEn: "A lottery from a complete list gives equal chance and reduces the researcher’s hand.",
    termAr: "عينة عشوائية بسيطة",
    termEn: "Simple random sample",
    wrongAr: ["اختر أول عشرين يدخلون المعمل لأنها أسرع", "خذ أصدقاء الأمين فقط", "استبعد من يجلس في الخلف عمدًا"],
    wrongEn: ["Pick the first twenty who enter the lab because it is faster", "Take only the prefect’s friends", "Drop back-row students on purpose"],
  },
  {
    id: "5-1-f07",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "بحث عن رأي الرحلة يقسم الطلاب بنين وبنات ثم يسحب بالقرعة من كل شريحة بنفس النسبة.",
    sceneEn: "A trip-opinion study splits students into boys and girls, then draws by lottery from each slice in the same share.",
    claimAr: "هذه عينة طبقية: قسّم المجتمع ثم اسحب من كل شريحة.",
    claimEn: "This is stratified sampling: split the population, then draw from each stratum.",
    whyAr: "التقسيم قبل السحب يحفظ وجود الشرائح فلا تبتلع شريحة كبيرة الباقي.",
    whyEn: "Splitting before drawing keeps each slice present so a large group does not swallow the rest.",
    termAr: "عينة طبقية",
    termEn: "Stratified sample",
    wrongAr: ["اسأل البنين فقط لأن عددهم أكبر", "اجمع كل الأسماء في كومة واحدة بلا شرائح", "اختر من يقف عند البوابة عصرًا"],
    wrongEn: ["Ask only the boys because they are more numerous", "Dump every name in one pile with no strata", "Pick whoever stands at the gate in the afternoon"],
  },
  {
    id: "5-1-f08",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "استطلاع ستوري إنستجرام عن وقت المذاكرة يردّ عليه من يحب الظهور فقط.",
    sceneEn: "An Instagram-story poll about study time is answered only by students who like to be seen.",
    claimAr: "هذا اختيار ذاتي؛ لا تعتبر الردود صورة الصف كله.",
    claimEn: "This is self-selection; do not treat the replies as a picture of the whole class.",
    whyAr: "من يهتم أو يحب الظهور هو من يضغط، والصامتون يختفون من النتيجة.",
    whyEn: "Only the keen or visibility-seeking tap the poll, so quiet students vanish from the result.",
    termAr: "اختيار ذاتي",
    termEn: "Self-selection",
    wrongAr: ["اعتبر من لم يرد موافقًا تلقائيًا", "عمّم على الصف لأن الستوري وصل للكل", "احذف الآراء الهادئة لأنها قليلة الإعجاب"],
    wrongEn: ["Treat non-repliers as automatic yes votes", "Generalise to the class because the story reached everyone", "Drop quiet opinions because they got few likes"],
  },
  {
    id: "5-1-f09",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "جروب واتساب أولياء الأمور يُستخدم وحده لقياس مصروف الجيب ويُعمَّم على كل الأسرة المصرية.",
    sceneEn: "A parents-only WhatsApp group is used alone to measure pocket money and then generalised to every Egyptian family.",
    claimAr: "الجروب طبقة واحدة؛ التعميم على المجتمع تحيز عينة.",
    claimEn: "The group is one stratum; generalising to the population is sampling bias.",
    whyAr: "أولياء الجروب متصلون وهواتفهم تعمل، أما الأسر بلا جروب فتُحذف صامتة.",
    whyEn: "Group parents are connected and online, while families outside the chat are silently dropped.",
    termAr: "تحيز العينة",
    termEn: "Sampling bias",
    wrongAr: ["عمّم على الجمهورية لأن الجروب نشيط", "ضاعف المبالغ لتعويض الأسر الغائبة", "استبدل العينة بصورة من الإنترنت"],
    wrongEn: ["Generalise to the country because the group is active", "Inflate the amounts to replace missing families", "Replace the sample with a random internet photo"],
  },
  {
    id: "5-1-f10",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "فريق البحث يقف عند بوابة المدرسة الساعة الواحدة والنصف ويسأل من يخرج مبكرًا عن طول اليوم الدراسي.",
    sceneEn: "The research team stands at the school gate at 1:30 and asks early leavers about the length of the school day.",
    claimAr: "هذه عينة مريحة منحازة؛ غاب من يبقى للحصة الأخيرة.",
    claimEn: "This is a biased convenience sample; last-period stayers are missing.",
    whyAr: "أسهل ناس تلاقيهم عند الباب ليسوا صورة من يكمل اليوم.",
    whyEn: "The easiest people at the door are not a picture of those who finish the day.",
    termAr: "تحيز العينة",
    termEn: "Sampling bias",
    wrongAr: ["عمّم على المدرسة لأن البوابة تجمع الكل", "سمّها عشوائية بسيطة لأنها في الشارع", "احذف إجابات المتأخرين إن ظهروا لاحقًا"],
    wrongEn: ["Generalise to the school because the gate gathers everyone", "Call it simple random because it is outdoors", "Drop latecomers’ answers if they appear later"],
  },
  {
    id: "5-1-f11",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "سارة تنسخ أرقام المطر من نشرة جريدة قديمة لمشروع حدائق السطح هذا الأسبوع.",
    sceneEn: "Sara copies rainfall figures from an old newspaper bulletin for this week’s rooftop-garden project.",
    claimAr: "البيانات ثانوية وقد لا تطابق الأسبوع الحالي؛ ابحث عن مصدر أحدث أو قِس بنفسك.",
    claimEn: "The data are secondary and may not match this week; find a fresher source or measure yourself.",
    whyAr: "الجريدة جمعت الرقم لغرضها ووقتها، لا لسقف مدرستك اليوم.",
    whyEn: "The paper collected the figure for its time and purpose, not for your roof today.",
    termAr: "بيانات ثانوية",
    termEn: "Secondary data",
    wrongAr: ["اعتمد الرقم لأنه مطبوع فيبدو رسميًا", "سمّه أوليًا لأنك نقلتيه بخطك", "امزج أرقام سنوات بلا ذكر التاريخ"],
    wrongEn: ["Trust the figure because print looks official", "Call it primary because you rewrote it by hand", "Blend years with no date noted"],
  },
  {
    id: "5-1-f12",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "أحمد يسأل فصلًا واحدًا في العباسية ثم يكتب «كل مراهقي القاهرة يفضّلون الامتحان الإلكتروني».",
    sceneEn: "Ahmed asks one class in Abbasiya and then writes that every Cairo teenager prefers e-exams.",
    claimAr: "الفصل عينة ضيقة؛ لا ترفع الجملة إلى مجتمع المدينة كله.",
    claimEn: "The class is a narrow sample; do not lift the sentence to the whole city.",
    whyAr: "المجتمع المعلن أكبر من العينة بكثير فيصبح الادعاء واثقًا وخاطئًا.",
    whyEn: "The claimed population is far larger than the sample, so the claim is confident and wrong.",
    termAr: "مجتمع / عينة",
    termEn: "Population / sample",
    wrongAr: ["أبقِ الجملة كما هي لأن القاهرة قريبة من العباسية", "ضاعف النسبة حتى تغطي الأحياء الأخرى", "احذف اسم المكان حتى يبدو التعميم أوسع"],
    wrongEn: ["Keep the sentence because Abbasiya is near the rest of Cairo", "Inflate the percentage to cover other districts", "Drop the place name so the claim looks wider"],
  },
  {
    id: "5-1-f13",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "نورا تسأل جيران الديسك الثلاثة عن جودة الواي فاي وتعتبر ذلك عينة المدرسة.",
    sceneEn: "Nora asks the three students at her desk about Wi-Fi quality and treats that as the school sample.",
    claimAr: "الجيران عينة مريحة؛ اسحب من قائمة الصف بالقرعة بدل أقرب الأصوات.",
    claimEn: "Desk neighbours are a convenience sample; draw from the class list by lottery instead of the nearest voices.",
    whyAr: "القرب المكاني يكرر نفس التجربة ولا يعطي فرصة متكافئة للبعيدين.",
    whyEn: "Physical closeness repeats the same experience and gives distant students no equal chance.",
    termAr: "عينة عشوائية بسيطة",
    termEn: "Simple random sample",
    wrongAr: ["أبقِ الجيران لأنهم صادقون معك", "سمّ السؤال عشوائيًا لأنه بلا ورقة", "أضيفي أسماء من الذاكرة حتى يكبر العدد"],
    wrongEn: ["Keep the neighbours because they are honest with you", "Call the ask random because no paper was used", "Add names from memory so the count looks larger"],
  },
  {
    id: "5-1-f14",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "بحث عن وقت المواصلات يحتاج أصوات أولى وثانية وثالثة ثانوي بنسب حضور كل صف.",
    sceneEn: "A commute-time study needs voices from Grades 10, 11, and 12 in each grade’s attendance share.",
    claimAr: "قسّم الصفوف شرائح ثم اسحب من كل صف؛ هذه عينة طبقية.",
    claimEn: "Split the grades into strata then draw from each; this is a stratified sample.",
    whyAr: "إن سحبت من كومة واحدة قد تختفي أولى ثانوي لأن عددها أقل عند الباب.",
    whyEn: "A single pile can erase Grade 10 if fewer of them stand at the door.",
    termAr: "عينة طبقية",
    termEn: "Stratified sample",
    wrongAr: ["خذ من يصل أولًا أيًا كان الصف", "اسأل 3ث فقط لأنهم أكبر سنًا", "ادمج الصفوف في متوسط واحد قبل السحب"],
    wrongEn: ["Take whoever arrives first, whatever the grade", "Ask only Grade 12 because they are older", "Merge the grades into one mean before drawing"],
  },
  {
    id: "5-1-f15",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "نموذج جوجل عن الرأي في الإذاعة المدرسية يُرسل في جروب نادي المناظرات وحده.",
    sceneEn: "A Google Form on the school radio is shared only in the debate-club WhatsApp group.",
    claimAr: "الردود اختيار ذاتي من المهتمين بالكلام؛ وسّع النشر خارج النادي.",
    claimEn: "Replies are self-selected talkative students; spread the form beyond the club.",
    whyAr: "من يدخل نادي المناظرات يحب إبداء الرأي أكثر من باقي المدرسة.",
    whyEn: "Debate-club members like voicing opinions more than the rest of the school.",
    termAr: "اختيار ذاتي",
    termEn: "Self-selection",
    wrongAr: ["عمّم على المدرسة لأن النموذج إلكتروني", "أغلق الردود بعد عشرة أصوات حماسية", "احذف الإجابات القصيرة لأنها باردة"],
    wrongEn: ["Generalise to the school because the form is digital", "Close replies after ten enthusiastic votes", "Drop short answers because they sound cold"],
  },
  {
    id: "5-1-f16",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "عرض الشرائح يظهر رسمًا أنيقًا لمتوسط ساعات المذاكرة مبنيًا على جروب واتساب منحاز.",
    sceneEn: "The slide deck shows a polished mean of study hours built from a biased WhatsApp group.",
    claimAr: "لا ينقذ الرسم الجمع الفاسد؛ أعد العينة أو قلّل التعميم.",
    claimEn: "A pretty chart cannot save a rotten collection; redo the sample or shrink the claim.",
    whyAr: "مسار التحليل يبدأ بالجمع؛ إن فسد فالحساب يثبت الميل لا يصلحه.",
    whyEn: "The pipeline starts with collection; if that fails, maths cements the tilt instead of fixing it.",
    termAr: "مسار التحليل",
    termEn: "Analysis pipeline",
    wrongAr: ["زد ألوان الرسم حتى تبدو النتيجة علمية", "اخفِ حجم العينة في الملاحظة", "أعلن أن الأناقة دليل الصحة"],
    wrongEn: ["Add more chart colours so the result looks scientific", "Hide the sample size in a footnote", "Announce that polish proves correctness"],
  },
  {
    id: "5-1-f17",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "أوراق الاستطلاع تحمل تواريخ 3/5 و05-03 ومارس بلا ترتيب قبل عدّ أيام الغياب.",
    sceneEn: "Survey sheets mix 3/5, 05-03, and “March” before anyone counts absence days.",
    claimAr: "نظّم الجدول ووحّد التاريخ قبل أي تحليل.",
    claimEn: "Organise the table and unify dates before any analysis.",
    whyAr: "التنظيم خطوة بين الجمع والتحليل؛ بلا توحيد يُعدّ اليوم مرتين أو يُفقد.",
    whyEn: "Organisation sits between collection and analysis; without unification a day is double-counted or lost.",
    termAr: "مسار التحليل",
    termEn: "Analysis pipeline",
    wrongAr: ["اجمع الأيام فورًا كما كُتبت", "احذف الأوراق ذات الخط العربي", "حوّل كل تاريخ إلى صفر لتسهيل الجمع"],
    wrongEn: ["Add the days immediately as written", "Throw away sheets with Arabic handwriting", "Turn every date into zero to make addition easy"],
  },
  {
    id: "5-1-f18",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "مشروع 2026 عن زحام شارع الهرم يعتمد جدول مرور نُشر سنة 2018 بلا تعليق.",
    sceneEn: "A 2026 project on Haram Street congestion relies on a 2018 traffic table with no comment.",
    claimAr: "البيانات الثانوية قديمة لغرض آخر؛ اذكر القيد أو ابحث عن مصدر أحدث.",
    claimEn: "The secondary data are old and built for another purpose; state the limit or find a fresher source.",
    whyAr: "الشارع تغيّر، فالرقم الصحيح لسنة أخرى يضلل إن قُدّم كحاضر.",
    whyEn: "The street has changed, so a correct figure from another year misleads if sold as now.",
    termAr: "بيانات ثانوية",
    termEn: "Secondary data",
    wrongAr: ["اعتمد الجدول لأنه «رسمي قديم يعني موثوق»", "امحُ سنة 2018 من العنوان", "سمّه بيانات أولية لأنك طبعته"],
    wrongEn: ["Trust the table because old official files feel reliable", "Erase 2018 from the title", "Call it primary because you printed it"],
  },
  {
    id: "5-1-f19",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "في جروب الصف ثمانون عضوًا، يردّ اثنا عشر فقط على استطلاع الحضور الصباحي.",
    sceneEn: "A class WhatsApp group has eighty members; only twelve reply to a morning-attendance poll.",
    claimAr: "الصامتون جزء من المجتمع؛ لا تعامل الاثني عشر كأنهم الكل.",
    claimEn: "Silent members are still in the population; do not treat the twelve as everyone.",
    whyAr: "عدم الرد اختيار أيضًا، وغالبًا يميل لمن لديه وقت أو رأي حاد.",
    whyEn: "Non-response is also a choice, and it often tilts toward people with time or a sharp opinion.",
    termAr: "تحيز العينة",
    termEn: "Sampling bias",
    wrongAr: ["اعتبر الصامتين موافقين", "احذف أسماء من لم يرد من قائمة الصف", "ضاعف إجابات الاثني عشر حتى تصل لثمانين"],
    wrongEn: ["Treat the silent as agreeing", "Remove non-repliers from the class list", "Multiply the twelve answers until they reach eighty"],
  },
  {
    id: "5-1-f20",
    lessonId: "5-1",
    chapterId: "5",
    sceneAr: "مريم تعدّ بنفسها السيارات أمام بوابة المدرسة في عشر دقائق لتقرير التلوث.",
    sceneEn: "Mariam counts cars in front of the school gate for ten minutes herself for a pollution report.",
    claimAr: "العدّ الميداني بيانات أولية؛ اذكر الوقت والمكان حتى تُفهم العينة.",
    claimEn: "The field count is primary data; state time and place so the sample can be understood.",
    whyAr: "ما تجمعه أنت لغرض محدد أولي، لكن الشريحة الزمنية الضيقة تحدّ التعميم.",
    whyEn: "What you gather for a stated purpose is primary, yet a narrow time window limits generalisation.",
    termAr: "بيانات أولية",
    termEn: "Primary data",
    wrongAr: ["انسي المكان حتى تبدو الأرقام عامة", "استبدلي العدّ بخبر تليفزيوني بلا ذكر", "سمّي العشر دقائق مجتمع القاهرة المروري"],
    wrongEn: ["Drop the place so the numbers look universal", "Replace the count with a TV report and no citation", "Call the ten minutes Cairo’s traffic population"],
  },
  {
    id: "5-2-f01",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "جدول درجات الرياضيات فيه خلية فارغة لطالب غاب عن الاختبار القصير.",
    sceneEn: "The maths marks table has a blank cell for a student who missed the quiz.",
    claimAr: "قرّر حسب المعنى: علّم الغياب أو أمهل الإعادة، ولا تضع صفرًا أعمى.",
    claimEn: "Decide by meaning: flag the absence or wait for a retake; do not blindly write zero.",
    whyAr: "الخلية الفارغة قد تعني غيابًا لا درجة صفر، والخلط يظلم المتوسط.",
    whyEn: "A blank may mean absence, not a score of zero, and mixing the two warps the mean.",
    termAr: "قيمة مفقودة",
    termEn: "Missing value",
    wrongAr: ["ضع صفرًا دائمًا لتسهيل الجمع", "احذف الصف فورًا من غير سؤال", "اترك العمود مختلطًا بلا قرار"],
    wrongEn: ["Always write zero to make addition easy", "Delete the row at once with no question", "Leave the column mixed with no decision"],
  },
  {
    id: "5-2-f02",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "في كشف الحضور يظهر طالب بنسبة 250٪ بينما الباقي بين 80 و100.",
    sceneEn: "An attendance sheet shows one student at 250% while the rest sit between 80 and 100.",
    claimAr: "هذه قيمة شاذة؛ راجع الإدخال قبل أن تعتمدها حقيقة.",
    claimEn: "This is an outlier; check the input before treating it as truth.",
    whyAr: "الرقم البعيد قد يكون خطأ ضرب أو حقيقة نادرة، والقرار بعد السبب لا قبله.",
    whyEn: "A far value may be a multiply error or a rare truth; decide after the cause, not before.",
    termAr: "قيمة شاذة",
    termEn: "Outlier",
    wrongAr: ["أبقِ 250 لأنها «واقع الجدول»", "حوّل العمود كله إلى صفر", "ضاعف باقي النسب حتى تتساوى"],
    wrongEn: ["Keep 250 because it is «on the sheet»", "Set the whole column to zero", "Double the other rates until they match"],
  },
  {
    id: "5-2-f03",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "مقارنة نشاط بين زمن الطابور بالثواني وعدد الوجبات بلا توحيد مقياس.",
    sceneEn: "A canteen study compares queue time in seconds with meal counts on raw scales.",
    claimAr: "طبّع أو قيّس العمودين حتى لا يبتلع الأكبر الأصغر.",
    claimEn: "Normalise or standardise the two columns so the larger unit does not swallow the smaller.",
    whyAr: "الثواني بالمئات والوجبات بالعشرات؛ بلا تدريج تُظلم المقارنة.",
    whyEn: "Seconds run to hundreds and meals to tens; without scaling the comparison is unfair.",
    termAr: "تطبيع / تقييس",
    termEn: "Normalise / standardise",
    wrongAr: ["اجمع الثواني مع الوجبات كما هما", "احذف عمود الثواني لأنه كبير", "حوّل القيم إلى نصوص حتى تختفي المقارنة"],
    wrongEn: ["Add seconds to meals as they are", "Drop the seconds column because it is large", "Turn the values into text so comparison disappears"],
  },
  {
    id: "5-2-f04",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "بعد لصق جدول الكانتين مرتين يظهر صفّان متطابقان لنفس الإيصال والوقت.",
    sceneEn: "After pasting the canteen table twice, two identical rows show the same receipt and time.",
    claimAr: "هذا تكرار نسخ؛ احذف الصف الزائد بعد التأكد.",
    claimEn: "This is a copy-paste duplicate; delete the extra row after you confirm.",
    whyAr: "صفّان متطابقان تمامًا في كل الحقول علامة لصق لا عمليتين.",
    whyEn: "Two rows identical in every field mark a paste error, not two events.",
    termAr: "تكرار",
    termEn: "Duplicate",
    wrongAr: ["اجمع الإيصالين كبيعتين", "احذف الجدول كله", "غيّر الوقت في أحد الصفوف لإخفاء التشابه"],
    wrongEn: ["Add both receipts as two sales", "Delete the whole table", "Change the time on one row to hide the match"],
  },
  {
    id: "5-2-f05",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "إيصالان لنفس الطالب: عصير الساعة 10 وخبز الساعة 2 في يوم الرحلة.",
    sceneEn: "Two receipts for the same student: juice at 10:00 and bread at 14:00 on trip day.",
    claimAr: "لا تدمج الشراءين؛ هما عمليتان حقيقيتان لا تكرارًا.",
    claimEn: "Do not merge the two purchases; they are two real events, not a duplicate.",
    whyAr: "التشابه في الاسم لا يلغي اختلاف السلعة والوقت.",
    whyEn: "A shared name does not erase different items and times.",
    termAr: "تكرار",
    termEn: "Duplicate",
    wrongAr: ["ادمج الصفوف لأن الاسم واحد", "احذف الثاني تلقائيًا بأداة إزالة التكرار", "اجعل المبلغ متوسط الاثنين"],
    wrongEn: ["Merge the rows because the name matches", "Auto-delete the second with a dedupe tool", "Replace both amounts with their average"],
  },
  {
    id: "5-2-f06",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "عمود التاريخ في كشف المكتبة يخلط 5/3/2026 و2026-03-05 و٥ مارس.",
    sceneEn: "The library log mixes 5/3/2026, 2026-03-05, and “5 March” in one date column.",
    claimAr: "وحّد كتابة التاريخ قبل أي مجموع أو ترتيب.",
    claimEn: "Unify the date spelling before any total or sort.",
    whyAr: "البرامج تعدّ الصيغ المختلفة أيامًا منفصلة فيفسد العدّ.",
    whyEn: "Software treats mixed formats as different days, so the count breaks.",
    termAr: "توحيد الصيغة",
    termEn: "Format unification",
    wrongAr: ["اجمع الأيام كما تظهر", "أجّل التوحيد إلى بعد الرسم", "احذف التواريخ العربية فقط"],
    wrongEn: ["Add the days as they appear", "Postpone unification until after the chart", "Delete only the Arabic dates"],
  },
  {
    id: "5-2-f07",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "عمود النوع فيه ذكر وم وmale وأنثى وبنت في استطلاع النادي.",
    sceneEn: "A club survey gender column mixes ذكر, م, male, أنثى, and بنت.",
    claimAr: "وحّد رموز النوع قبل عدّ النسب.",
    claimEn: "Unify gender spellings before counting shares.",
    whyAr: "البرنامج يرى خمس فئات لا فئتين، فتنكسر النسبة.",
    whyEn: "The program sees five categories instead of two, so the share splits wrongly.",
    termAr: "توحيد الصيغة",
    termEn: "Format unification",
    wrongAr: ["اترك الكتابة كما جاءت لأنها «صادقة»", "احذف الصفوف غير الإنجليزية", "حوّل الكل إلى «غير محدد» لتسريع العرض"],
    wrongEn: ["Leave the spellings as submitted because they are «honest»", "Delete non-English rows", "Turn everyone into “unspecified” to speed the slide"],
  },
  {
    id: "5-2-f08",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "متوسط درجات الفصل يبدو مرتفعًا بعد حساب أنيق على جدول فيه أصفار مكان الغياب وأخطاء لصق.",
    sceneEn: "The class mean looks high after neat maths on a sheet that put zeros for absences and paste errors.",
    claimAr: "مدخلات سيئة تعطي مخرجات سيئة؛ نظّف قبل أن تثق بالمتوسط.",
    claimEn: "Garbage in, garbage out; clean before you trust the mean.",
    whyAr: "أناقة القانون لا تغسل خلية فارغة عوملت كصفر أو صفًا مكررًا.",
    whyEn: "A tidy formula cannot wash a blank treated as zero or a repeated row.",
    termAr: "مدخلات سيئة",
    termEn: "Garbage in",
    wrongAr: ["أعلن المتوسط لأنه خرج من معادلة", "زد الخانات العشرية لإخفاء الشك", "احذف عمود الأسماء حتى لا يراجع أحد"],
    wrongEn: ["Publish the mean because a formula produced it", "Add more decimal places to hide doubt", "Drop the name column so nobody can audit"],
  },
  {
    id: "5-2-f09",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "كشف أحياء الطلاب يترك خانة العنوان فارغة لثلاثة أسماء، وباقي الصفوف مكتملة.",
    sceneEn: "A student-district sheet leaves the address blank for three names while other rows are complete.",
    claimAr: "لا تحذف الصفوف الثلاثة آليًا؛ علّم الناقص إن بقيت حقول مفيدة.",
    claimEn: "Do not auto-delete the three rows; flag the gap if the other fields still help.",
    whyAr: "الحذف الأعمى يرمي درجات أو حضورًا صالحًا مع خلية عنوان ناقصة.",
    whyEn: "Blind deletion throws away valid marks or attendance with one missing address.",
    termAr: "قيمة مفقودة",
    termEn: "Missing value",
    wrongAr: ["احذف كل صف فيه فراغ فورًا", "املأ العناوين من خيالك", "ضع نفس عنوان المدير للثلاثة"],
    wrongEn: ["Delete every row with a blank at once", "Invent the addresses from imagination", "Copy the headteacher’s address onto the three"],
  },
  {
    id: "5-2-f10",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "في قائمة أطوال فريق السلة يظهر طالب بطول 198 سم والباقون قرب 165.",
    sceneEn: "The basketball-team height list shows one student at 198 cm while the others sit near 165.",
    claimAr: "قد تكون قيمة شاذة حقيقية؛ راجع القياس قبل الحذف.",
    claimEn: "It may be a true outlier; recheck the measurement before deleting.",
    whyAr: "اللاعب الطويل حقيقة نادرة لا خطأً حتمًا، والحذف يغيّر صورة الفريق.",
    whyEn: "A tall player can be a rare truth, not an automatic error, and deletion changes the team picture.",
    termAr: "قيمة شاذة",
    termEn: "Outlier",
    wrongAr: ["احذف 198 لأنها بعيدة", "استبدلها بالمتوسط فورًا", "قلّل كل الأطوال بنسبة واحدة"],
    wrongEn: ["Delete 198 because it is far", "Replace it with the mean at once", "Shrink every height by the same percent"],
  },
  {
    id: "5-2-f11",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "معلم يملأ كل خانة غياب في جدول الفيزياء بصفر قبل حساب أعمال السنة.",
    sceneEn: "A teacher fills every absence cell in the physics sheet with zero before computing coursework.",
    claimAr: "لا تملأ المفقود بصفر إن كان المعنى غيابًا لا درجة.",
    claimEn: "Do not impute missing as zero if the meaning is absence, not a score.",
    whyAr: "الصفر قرار تحليلي يغيّر الترتيب، لا مجرد «ملء فراغ».",
    whyEn: "Zero is an analytic decision that changes ranks, not just a way to fill a hole.",
    termAr: "قيمة مفقودة",
    termEn: "Missing value",
    wrongAr: ["الصفر دائمًا أأمن اختيار", "املأ بالغائب أعلى درجة في الصف", "اترك الصيغ تتخطى الصف ثم انسَه"],
    wrongEn: ["Zero is always the safest fill", "Fill the absence with the class top mark", "Let formulas skip the row and then forget it"],
  },
  {
    id: "5-2-f12",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "في كشف الرحلة صفّان باسم يوسف حسن بنفس اليوم: أحدهما دفع العربون والآخر دفع الباقي.",
    sceneEn: "The trip sheet has two rows named Youssef Hassan on the same day: one paid the deposit, the other the balance.",
    claimAr: "تحقق من العملية قبل الدمج؛ قد يكونان دفعتين حقيقيتين.",
    claimEn: "Check the event before merging; they may be two real payments.",
    whyAr: "تشابه الاسم واليوم لا يعني صفًا منسوخًا إن اختلف المبلغ والبيان.",
    whyEn: "A shared name and day do not mean a copied row if amount and note differ.",
    termAr: "تكرار",
    termEn: "Duplicate",
    wrongAr: ["ادمج المبلغين في صف واحد بلا سؤال", "احذف الدفعة الثانية لأنها نفس الاسم", "غيّر أحد الاسمين حتى يختفي التشابه"],
    wrongEn: ["Merge the two amounts into one row with no question", "Delete the second payment because the name matches", "Change one name so the likeness disappears"],
  },
  {
    id: "5-2-f13",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "مقارنة درجة الامتحان من 80 مع درجة المشروع من 20 في رسم واحد بلا تحويل.",
    sceneEn: "Exam marks out of 80 and project marks out of 20 are plotted together with no scaling.",
    claimAr: "قيّس أو طبّع الدرجتين قبل المقارنة حتى لا يطغى الامتحان.",
    claimEn: "Standardise or normalise both scores before comparing so the exam does not dominate.",
    whyAr: "المدى المختلف يخدع العين؛ التحويل يجعل المسافة عادلة.",
    whyEn: "Different ranges fool the eye; transforming makes distance fair.",
    termAr: "تطبيع / تقييس",
    termEn: "Normalise / standardise",
    wrongAr: ["ارسم العمودين كما هما لأنهما «درجات»", "احذف المشروع لأنه مدى صغير", "اجمع 80 مع 20 من غير نسبة"],
    wrongEn: ["Plot both as they are because both are «marks»", "Drop the project because its range is small", "Add 80 to 20 with no share"],
  },
  {
    id: "5-2-f14",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "تقرير الطقس المدرسي يخلط March ومارس و٣ في عمود الشهر قبل حساب متوسط الحرارة.",
    sceneEn: "The school weather log mixes March, مارس, and 3 in the month column before averaging temperature.",
    claimAr: "وحّد أسماء الشهر إلى صيغة واحدة قبل المتوسط.",
    claimEn: "Unify month names into one form before averaging.",
    whyAr: "ثلاث كتابات لنفس الشهر تُحسب ثلاثة أشهر فينهار المتوسط.",
    whyEn: "Three spellings of one month become three months, so the mean collapses.",
    termAr: "توحيد الصيغة",
    termEn: "Format unification",
    wrongAr: ["احسب المتوسط على النص كما هو", "احذف الصفوف العربية فقط", "استبدل الشهور برموز عشوائية"],
    wrongEn: ["Average the text as written", "Delete only the Arabic rows", "Replace months with random codes"],
  },
  {
    id: "5-2-f15",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "درجة طالب 95 كُتبت 955 في عمود اللغة العربية بعد إدخال سريع.",
    sceneEn: "A 95 in Arabic was typed as 955 after a rushed entry.",
    claimAr: "هذه شاذة بسبب خطأ إدخال؛ صحّحها بعد الرجوع للورقة.",
    claimEn: "This outlier is an input error; correct it after checking the paper.",
    whyAr: "955 من 100 مستحيلة في السياق، والتصحيح أدق من إبقاء الخطأ «للواقع».",
    whyEn: "955 out of 100 is impossible here; fixing beats keeping the error as «reality».",
    termAr: "قيمة شاذة",
    termEn: "Outlier",
    wrongAr: ["أبقِ 955 لأنها طُبعت", "احذف الطالب من الكشف", "اقسم كل درجات الصف على 10"],
    wrongEn: ["Keep 955 because it was typed", "Remove the student from the sheet", "Divide every class mark by 10"],
  },
  {
    id: "5-2-f16",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "نفس الطالب يشتري ماء الساعة 10 وماء آخر الساعة 2 في يوم الحرارة المرتفعة.",
    sceneEn: "The same student buys water at 10:00 and another water at 14:00 on a hot day.",
    claimAr: "لا تدمج الصفّين؛ الشراء المكرر في وقتين عمليتان.",
    claimEn: "Do not merge the rows; repeated purchases at two times are two events.",
    whyAr: "السلعة المتشابهة لا تلغي فجوة الساعات؛ الدمج يخفي مبيعات حقيقية.",
    whyEn: "A similar item does not erase the hours between; merging hides real sales.",
    termAr: "تكرار",
    termEn: "Duplicate",
    wrongAr: ["شغّل إزالة التكرار على الاسم والسلعة فقط", "احتفظ بالمتوسط واحذف الوقت", "اعتبر اليوم صفًا واحدًا لأي ماء"],
    wrongEn: ["Run dedupe on name and item only", "Keep the average and drop the times", "Treat the whole day as one row for any water"],
  },
  {
    id: "5-2-f17",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "رقم ولي الأمر فارغ في صف، ودرجة الاختبار فارغة في صف آخر على نفس الكشف.",
    sceneEn: "A parent phone is blank on one row and a test mark is blank on another row of the same sheet.",
    claimAr: "قرار المفقود يختلف: الهاتف يُعلَّم، والدرجة تُراجع مع المعلم.",
    claimEn: "Missing-value decisions differ: flag the phone, and review the mark with the teacher.",
    whyAr: "المعنى يحدد الحذف أو الملء أو التعليم، لا زر واحد لكل الفراغات.",
    whyEn: "Meaning chooses delete, impute, or flag; there is no single button for every blank.",
    termAr: "قيمة مفقودة",
    termEn: "Missing value",
    wrongAr: ["طبّق نفس القرار على كل الفراغات", "املأ الهاتف والدرجة بصفر", "احذف العمودين بالكامل"],
    wrongEn: ["Apply the same decision to every blank", "Fill both phone and mark with zero", "Delete both columns entirely"],
  },
  {
    id: "5-2-f18",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "كشف الحضور يخلط نعم وyes و1 وحاضر قبل حساب نسبة الغياب للإذاعة.",
    sceneEn: "Attendance mixes نعم, yes, 1, and حاضر before the radio show announces the absence rate.",
    claimAr: "وحّد الرموز ثم احسب؛ وإلا فالمدخلات السيئة تفسد النسبة.",
    claimEn: "Unify the codes then calculate; otherwise garbage in ruins the rate.",
    whyAr: "أربع كتابات للحضور تُعدّ فئات مختلفة فيظهر الغياب كذبًا.",
    whyEn: "Four spellings of present become different categories, so absence looks false.",
    termAr: "مدخلات سيئة",
    termEn: "Garbage in",
    wrongAr: ["اقرأ النسبة من أول صيغة تظهر", "احذف «نعم» لأنها عربية", "أعلن الرقم لأن الإذاعة تنتظر"],
    wrongEn: ["Read the rate from the first format you see", "Delete نعم because it is Arabic", "Announce the number because the radio is waiting"],
  },
  {
    id: "5-2-f19",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "صف في جدول المسابقات ينقصه البريد فقط، بينما الدرجة واسم الفريق مكتملان.",
    sceneEn: "A contest table row is missing only the email, while the score and team name are complete.",
    claimAr: "أبقِ الصف وعلّم البريد؛ لا ترمِ نتيجة صحيحة لفراغ جانبي.",
    claimEn: "Keep the row and flag the email; do not throw away a valid result for a side blank.",
    whyAr: "التنظيف حكم هندسي: الفراغ غير الحرج لا يبرر مسح الذهب.",
    whyEn: "Cleaning is an engineering judgement: a non-critical blank does not justify wiping gold.",
    termAr: "قيمة مفقودة",
    termEn: "Missing value",
    wrongAr: ["احذف الصف لأن أداة التنظيف تقترح ذلك", "املأ البريد بعنوان المدرسة العام", "انسخ بريد الطالب المجاور"],
    wrongEn: ["Delete the row because the cleaning tool suggests it", "Fill the email with the generic school address", "Copy the neighbouring student’s email"],
  },
  {
    id: "5-2-f20",
    lessonId: "5-2",
    chapterId: "5",
    sceneAr: "قبل رسم نسب المشاركة تظهر F وأنثى وبنت في عمود واحد لتقرير مجلس الأمناء.",
    sceneEn: "Before charting participation shares, one column mixes F, أنثى, and بنت for a governors’ report.",
    claimAr: "وحّد رموز النوع ثم اجمع؛ التوحيد قبل المجموع لا بعده.",
    claimEn: "Unify gender codes then total; unification comes before the sum, not after.",
    whyAr: "العدّ على كتابات متعددة يقسم فئة واحدة إلى ثلاث بلا وجه حق.",
    whyEn: "Counting mixed spellings splits one group into three and invents a false share.",
    termAr: "توحيد الصيغة",
    termEn: "Format unification",
    wrongAr: ["ارسم الأعمدة الثلاث وكأنها فئات مختلفة", "أجّل التوحيد إلى بعد طباعة التقرير", "احذف «بنت» لأنها غير رسمية"],
    wrongEn: ["Draw three bars as if they were different groups", "Postpone unification until after printing the report", "Delete بنت because it sounds informal"],
  },
  {
    id: "5-3-f01",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "هدى تحمّل ملف سكان من بوابة بيانات الجهاز المركزي لتقرير الجغرافيا.",
    sceneEn: "Hoda downloads a population file from the CAPMAS open-data portal for a geography report.",
    claimAr: "هذه بيانات مفتوحة مفيدة؛ راجع الترخيص وتاريخ التحديث والتحيز قبل الاستخدام.",
    claimEn: "This is useful open data; check licence, update date, and bias before use.",
    whyAr: "الإتاحة العامة تختصر الوقت لكنها لا تلغي شروط إعادة الاستخدام ولا قِدَم الرقم.",
    whyEn: "Public access saves time but does not cancel reuse rules or the age of the figure.",
    termAr: "بيانات مفتوحة",
    termEn: "Open data",
    wrongAr: ["انسخي الرقم من غير ذكر المصدر", "افترضي أن المفتوح بلا تحيز", "اخفي رابط البوابة حتى يبدو العمل أصليًا"],
    wrongEn: ["Copy the figure with no source", "Assume open means unbiased", "Hide the portal link so the work looks original"],
  },
  {
    id: "5-3-f02",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "فريق حديقة السطح يطلب درجة الحرارة الحالية عبر واجهة برمجة للطقس لا عبر ملف السنة الماضية.",
    sceneEn: "The rooftop-garden team requests the current temperature through a weather API, not last year’s file.",
    claimAr: "الواجهة تجلب شريحة حية وفق عقد واضح؛ فضّلها على الملف الراكد لهذا الغرض.",
    claimEn: "The API fetches a live slice under a clear contract; prefer it to a stale file for this purpose.",
    whyAr: "طلب منظّم يعطيك رقم اليوم، بينما الملف المحمّل قد تجمّد عند أمس أو العام الماضي.",
    whyEn: "A structured request gives today’s number, while a downloaded file may be frozen on yesterday or last year.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: ["استخدم ملف 2024 لأنه «أريح في المعمل»", "التقط لقطة شاشة من تطبيق بلا تاريخ", "اعتبر الواجهة تغني عن ذكر المصدر"],
    wrongEn: ["Use the 2024 file because it is «easier in the lab»", "Take an undated screenshot from an app", "Treat the API as a reason not to cite"],
  },
  {
    id: "5-3-f03",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ملف أسعار الخضر من بوابة محافظة يحمل عبارة «كل الحقوق محفوظة» ويطلبه تقرير الكانتين.",
    sceneEn: "A governorate vegetable-price file says “all rights reserved” and the canteen report wants to reuse it.",
    claimAr: "اقرأ الترخيص قبل النسخ؛ الممنوع لا يُعاد نشره ولو كان الملف مجاني التحميل.",
    claimEn: "Read the licence before copying; a forbidden reuse stays forbidden even if the download is free.",
    whyAr: "المجانية ليست إذن نشر؛ الشروط تقول ماذا يجوز في تقرير مدرسي.",
    whyEn: "Free to download is not permission to republish; the terms say what a school report may do.",
    termAr: "الترخيص",
    termEn: "Licence",
    wrongAr: ["انشر الجدول كاملًا لأن التحميل فُتح", "امحُ سطر الحقوق", "بدّل اسم المحافظة باسم المدرسة"],
    wrongEn: ["Republish the whole table because the download opened", "Erase the rights line", "Replace the governorate name with the school name"],
  },
  {
    id: "5-3-f04",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "تقرير مصروف الأسرة يعتمد رقم متوسط الدخل من ملف محدّث آخر مرة سنة 2019.",
    sceneEn: "A family-budget report uses an average-income figure last updated in 2019.",
    claimAr: "اذكر تاريخ التحديث أو ابحث عن رقم أحدث؛ الرقم القديم يضلل كحاضر.",
    claimEn: "State the update date or find a fresher figure; an old number misleads as if it were current.",
    whyAr: "تاريخ الجمع يحدّ صلاحية الجملة؛ إخفاؤه يوحي بحداثة كاذبة.",
    whyEn: "The collection date limits the sentence; hiding it fakes freshness.",
    termAr: "تاريخ التحديث",
    termEn: "Update date",
    wrongAr: ["اكتب «حاليًا» بجانب 2019", "احذف السنة من أسفل الجدول", "افترض أن الدخل لا يتغيّر"],
    wrongEn: ["Write “currently” next to 2019", "Delete the year from the table footer", "Assume income never changes"],
  },
  {
    id: "5-3-f05",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "قبل لصق عمود البطالة من بوابة مفتوحة في بحث الصف، يمرّ الطلاب على الصفحة مرورًا سريعًا.",
    sceneEn: "Before pasting an unemployment column from an open portal into the class paper, students skim the page.",
    claimAr: "راجع الترخيص والتاريخ واحتمال التحيز، لا الرقم وحده.",
    claimEn: "Check licence, date, and possible bias, not the number alone.",
    whyAr: "المفتوح يختصر الجمع لكنه يظل مصدرًا يحتاج سؤالًا كاستطلاعك.",
    whyEn: "Open data shortens collection but remains a source that needs questions, like your own survey.",
    termAr: "بيانات مفتوحة",
    termEn: "Open data",
    wrongAr: ["الثقة الكاملة لأن الشعار حكومي", "نسخ الرقم وإغلاق الصفحة", "تجاهل من جمع العينة الرسمية"],
    wrongEn: ["Full trust because the logo is official", "Copy the number and close the page", "Ignore who sampled the official survey"],
  },
  {
    id: "5-3-f06",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "مقارنة مواعيد الأتوبيس: ملف Excel حُفظ الفصل الماضي مقابل طلب حي من واجهة هيئة النقل.",
    sceneEn: "Bus-time comparison: an Excel file saved last term versus a live request to the transport API.",
    claimAr: "للقرار اليومي فضّل الواجهة الحية؛ الملف قد يكون راكدًا.",
    claimEn: "For a same-day decision prefer the live API; the file may be stale.",
    whyAr: "الخط يتغيّر، واللقطة القديمة تُظهر زمنًا مات.",
    whyEn: "Routes change, and last term’s snapshot shows a time that has died.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: ["اعتمد الملف لأنه منسّق أجمل", "اخلط الزمنين من غير ذكر أيهما أحدث", "التقط صورة الشاشة من العام الماضي"],
    wrongEn: ["Trust the file because it looks tidier", "Blend both times with no note on which is newer", "Use last year’s screenshot"],
  },
  {
    id: "5-3-f07",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "خاتمة تقرير العلوم تضع أرقام جودة الهواء بلا اسم الجهة ولا رابط.",
    sceneEn: "The science-report ending lists air-quality numbers with no agency name and no link.",
    claimAr: "وثّق المصدر في التقرير المدرسي: الجهة والتاريخ والرابط.",
    claimEn: "Cite the source in the school report: agency, date, and link.",
    whyAr: "بغير التوثيق لا يُراجع الرقم ولا يُحترم حق الجهة.",
    whyEn: "Without a citation the figure cannot be checked and the agency’s credit is skipped.",
    termAr: "توثيق المصدر",
    termEn: "Source citation",
    wrongAr: ["اخفِ الجهة حتى يبدو القياس لكم", "اكتب «من الإنترنت» فقط", "ضع الأرقام في الحاشية من غير رابط"],
    wrongEn: ["Hide the agency so the measurement looks yours", "Write only “from the internet”", "Put the numbers in a footnote with no link"],
  },
  {
    id: "5-3-f08",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ملف سياحي مفتوح يعرض عدد الزوار كأنه حقيقة وحيدة بلا ذكر موسم العينة.",
    sceneEn: "An open tourism file presents visitor counts as the only truth with no mention of the sample season.",
    claimAr: "اسأل عن تحيز المصدر كما تسأل استطلاعك؛ المفتوح ليس بريئًا تلقائيًا.",
    claimEn: "Question source bias as you would your own survey; open is not automatically innocent.",
    whyAr: "جهة السياحة قد تميل لإبراز موسم الذروة، فتحتاج جملة قيد.",
    whyEn: "A tourism body may highlight peak season, so the claim needs a limit.",
    termAr: "تحيز المصدر",
    termEn: "Source bias",
    wrongAr: ["انقل الرقم كحقيقة نهائية", "احذف موسم الجمع إن وُجد", "ضاعف العدد لأن الملف مفتوح"],
    wrongEn: ["Copy the figure as final truth", "Erase the collection season if it exists", "Double the count because the file is open"],
  },
  {
    id: "5-3-f09",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "معمل الحاسوب يجرّب طلبًا منظّمًا لواجهة جودة الهواء: مدينة، تاريخ، مفتاح استخدام مدرسي.",
    sceneEn: "The computer lab tries a structured air-quality API request: city, date, and a school-use key.",
    claimAr: "التزم عقد الواجهة: الحقول المطلوبة وحدود الاستخدام.",
    claimEn: "Honour the API contract: required fields and use limits.",
    whyAr: "الطلب العشوائي يفشل أو يجلب شريحة غلط، والعقد يوضح ماذا يحق لك.",
    whyEn: "A sloppy request fails or fetches the wrong slice, and the contract states what you may do.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: ["أرسل طلبًا فارغًا ثم خمن الناتج", "شارك مفتاح الصف على جروب عام", "احفظ الرد كأنه بلا مصدر"],
    wrongEn: ["Send an empty request and guess the output", "Share the class key on a public group", "Save the reply as if it had no source"],
  },
  {
    id: "5-3-f10",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ملف مترو حُمّل العام الماضي يُقارن بواجهة حية لمواعيد اليوم قبل خروج الرحلة.",
    sceneEn: "A metro file downloaded last year is compared with a live timetable API before the class trip leaves.",
    claimAr: "للخروج اليوم اعتمد الواجهة؛ الملف الراكد للمقارنة التاريخية فقط.",
    claimEn: "For leaving today trust the API; keep the stale file only for historical contrast.",
    whyAr: "الجدول القديم قد يلغي محطة أو يغيّر الخط بعد التحميل.",
    whyEn: "The old timetable may drop a station or change a line after the download.",
    termAr: "تاريخ التحديث",
    termEn: "Update date",
    wrongAr: ["اطبع ملف العام الماضي لأنه أوضح", "امزج الزمنين في عمود واحد", "اخفِ تاريخ التحميل"],
    wrongEn: ["Print last year’s file because it looks clearer", "Blend both times in one column", "Hide the download date"],
  },
  {
    id: "5-3-f11",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "بوابة بيانات تتيح إعادة الاستخدام بترخيص يذكر الاسم، وأخرى تكتب «ممنوع إعادة النشر».",
    sceneEn: "One data portal allows reuse if you name the source; another says “no republication”.",
    claimAr: "اختر ما يسمح به الترخيص أو لخّص مع الإسناد؛ لا تنسخ الممنوع.",
    claimEn: "Use what the licence allows or summarise with credit; do not copy the forbidden set.",
    whyAr: "شروط إعادة الاستخدام تختلف، والتحميل لا يساوي حق اللصق في المجلة المدرسية.",
    whyEn: "Reuse rules differ, and a download is not a right to paste into the school magazine.",
    termAr: "الترخيص",
    termEn: "Licence",
    wrongAr: ["انسخ الاثنين لأن كليهما على الويب", "امزج الملفين واحذف سطور الشروط", "اذكر المدرسة كجامع أصلي"],
    wrongEn: ["Copy both because both are on the web", "Merge the files and delete the terms lines", "Name the school as the original collector"],
  },
  {
    id: "5-3-f12",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "قائمة مراجع بحث البيئة تذكر «مواقع عامة» من غير اسم الجهاز المركزي ولا سنة الجدول.",
    sceneEn: "The environment paper’s reference list says “public websites” with no CAPMAS name and no table year.",
    claimAr: "اكتب اسم الجهة وسنة البيان ورابط الوصول في المراجع.",
    claimEn: "Write the agency name, the table year, and the access link in the references.",
    whyAr: "التوثيق يسمح بإعادة الفحص ويمنع ادعاء الملكية.",
    whyEn: "Citation lets others recheck and blocks a claim of ownership.",
    termAr: "توثيق المصدر",
    termEn: "Source citation",
    wrongAr: ["أبقِ «مواقع عامة» لأنها قصيرة", "ضع الرابط في المحادثة الخاصة فقط", "انسب الجدول إلى الطالب الأول في المجموعة"],
    wrongEn: ["Keep “public websites” because it is short", "Put the link only in a private chat", "Credit the table to the first student in the group"],
  },
  {
    id: "5-3-f13",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "رقم زيارات الأهرام من هيئة سياحية أعلى بكثير من تقدير مستقل في نفس السنة.",
    sceneEn: "A tourism-board pyramid-visit figure is far higher than an independent estimate for the same year.",
    claimAr: "قارن المصدرين واذكر احتمال التحيز، لا تختر الرقم الأكبر للصورة.",
    claimEn: "Compare both sources and note possible bias; do not pick the larger number for the slide.",
    whyAr: "الجهة قد تنتقي التعريف الأوسع للزائر، فالمقارنة تكشف الميل.",
    whyEn: "The agency may use a wider visitor definition, so comparison reveals the tilt.",
    termAr: "تحيز المصدر",
    termEn: "Source bias",
    wrongAr: ["خذ الأعلى لأنه يخدم العنوان", "احذف التقدير المستقل", "أعلن أن الاختلاف يعني خطأ الآلة الحاسبة"],
    wrongEn: ["Take the higher figure because it serves the title", "Drop the independent estimate", "Announce that the gap means a calculator error"],
  },
  {
    id: "5-3-f14",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "تقرير جودة الهواء يحدّث الرقم كل ساعة عبر واجهة، بينما ملف PDF في المعمل بتاريخ الفصل السابق.",
    sceneEn: "An air-quality readout refreshes hourly through an API, while the lab PDF is dated last term.",
    claimAr: "للرقم الحي استخدم الواجهة؛ اذكر أن ملف المعمل تاريخه أقدم.",
    claimEn: "For a live figure use the API; state that the lab file is older.",
    whyAr: "التحديث المستمر يغيّر الجملة، واللقطة الراكدة تصلح للمقارنة لا للآن.",
    whyEn: "Continuous updates change the sentence, and a frozen snapshot is for contrast, not for now.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: ["اعتمد PDF لأنه مطبوع", "اخلط الساعة الحالية برقم الفصل السابق من غير فاصل", "امسح تاريخ PDF"],
    wrongEn: ["Trust the PDF because it is printed", "Blend this hour with last term with no break", "Wipe the PDF date"],
  },
  {
    id: "5-3-f15",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "طالب يمسح اسم الوزارة من أسفل الجدول حتى يبدو البحث «من عمل المجموعة».",
    sceneEn: "A student erases the ministry name under the table so the research “looks like the group’s work”.",
    claimAr: "أبقِ اسم المصدر؛ إخفاؤه خطأ علمي وأخلاقي.",
    claimEn: "Keep the source name; hiding it is a scientific and ethical error.",
    whyAr: "الأصالة في التحليل والسؤال، لا في سرقة الجدول.",
    whyEn: "Originality lives in the analysis and the question, not in stealing the table.",
    termAr: "توثيق المصدر",
    termEn: "Source citation",
    wrongAr: ["امسح الشعار لتحسين التصميم", "انسب الرقم إلى «مجهود شخصي»", "انقل الجدول إلى خط المدرسة من غير إشارة"],
    wrongEn: ["Erase the logo to improve the layout", "Credit the figure to “personal effort”", "Restyle the table in the school font with no credit"],
  },
  {
    id: "5-3-f16",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ملف مفتوح عن الأمية لا يوضح إن شملت العينة الريف أم المدن فقط.",
    sceneEn: "An open literacy file does not say whether the sample covered villages or cities only.",
    claimAr: "اسأل من جُمع وكيف؛ نقص المنهج تحيز محتمل.",
    claimEn: "Ask who was collected and how; a missing method is possible bias.",
    whyAr: "البيانات المفتوحة بلا منهج تُخفي من غاب عن العدّ.",
    whyEn: "Open data with no method hides who was left out of the count.",
    termAr: "تحيز المصدر",
    termEn: "Source bias",
    wrongAr: ["عمّم على الجمهورية لأن الملف كبير", "افترض شمول الريف من غير دليل", "اخفِ سؤال العينة في العرض"],
    wrongEn: ["Generalise to the country because the file is large", "Assume villages are included with no evidence", "Hide the sample question in the presentation"],
  },
  {
    id: "5-3-f17",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ذيل تقرير الصف عن استهلاك الكهرباء يذكر الرابط وتاريخ الدخول واسم الجهاز.",
    sceneEn: "The class electricity report footer lists the URL, the access date, and the agency name.",
    claimAr: "هذا توثيق صحيح؛ أبقِ التاريخ لأن البوابة قد تتغيّر غدًا.",
    claimEn: "This is proper citation; keep the access date because the portal may change tomorrow.",
    whyAr: "تاريخ الدخول يثبت أي نسخة رأيت، لا أي نسخة ستظهر لاحقًا.",
    whyEn: "The access date pins which version you saw, not which version will appear later.",
    termAr: "توثيق المصدر",
    termEn: "Source citation",
    wrongAr: ["احذف تاريخ الدخول لأنه يطيل الذيل", "اكتفِ باسم الموقع التجاري للبحث", "بدّل الرابط بعنوان المدرسة"],
    wrongEn: ["Drop the access date because the footer looks long", "Cite only the commercial search-engine name", "Replace the link with the school homepage"],
  },
  {
    id: "5-3-f18",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "بحث صحي مدرسي يلصق أرقام تعداد قديم كأنّها مسح هذا الأسبوع.",
    sceneEn: "A school health paper pastes an old census count as if it were this week’s survey.",
    claimAr: "اكتب سنة التعداد صراحة أو ابحث عن تحديث؛ لا تُظهر القديم كحيّ.",
    claimEn: "State the census year clearly or find an update; do not present the old count as live.",
    whyAr: "تاريخ التحديث يحمي القارئ من رقم مات سكانيًا.",
    whyEn: "The update date protects the reader from a figure that is demographically dead.",
    termAr: "تاريخ التحديث",
    termEn: "Update date",
    wrongAr: ["اكتب «حديثًا» فوق سنة التعداد", "قصّ عمود السنة من الجدول", "ادّعِ أن التعداد لا يشيخ"],
    wrongEn: ["Write “recently” above the census year", "Crop the year column from the table", "Claim a census cannot age"],
  },
  {
    id: "5-3-f19",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "مشرف الرحلة يعتمد لقطة مواعيد من الترم الماضي بينما الواجهة تعرض تأخير اليوم.",
    sceneEn: "The trip supervisor relies on last term’s timetable screenshot while the API shows today’s delay.",
    claimAr: "للتحرك الآن خذ الشريحة الحية واذكر المصدر والوقت.",
    claimEn: "For moving now take the live slice and cite source and time.",
    whyAr: "اللقطة الراكدة تجمّد زمنًا مضى، والواجهة تعكس العقد الحالي.",
    whyEn: "The stale snapshot freezes a past moment; the API reflects the current contract.",
    termAr: "واجهة برمجة",
    termEn: "API",
    wrongAr: ["اطبع اللقطة لأنها أوضح للطلاب", "تجاهل التأخير لأن الملف «رسمي قديم»", "امزج الزمنين في إعلان واحد"],
    wrongEn: ["Print the screenshot because students can read it", "Ignore the delay because the file is «old official»", "Blend both times in one announcement"],
  },
  {
    id: "5-3-f20",
    lessonId: "5-3",
    chapterId: "5",
    sceneAr: "ترخيص ملف الطاقة يسمح بالاستخدام التعليمي مع ذكر الاسم ويمنع البيع.",
    sceneEn: "An energy-file licence allows educational use with attribution and forbids sale.",
    claimAr: "استخدمه في تقرير الصف مع ذكر الجهة، ولا تعرضه للبيع في المعرض.",
    claimEn: "Use it in the class report with credit, and do not sell it at the fair.",
    whyAr: "الترخيص يفصل ما يجوز في المدرسة عما يُمنع تجاريًا.",
    whyEn: "The licence splits what school use may do from what commerce may not.",
    termAr: "الترخيص",
    termEn: "Licence",
    wrongAr: ["بع النسخ في يوم المعرض لأن التحميل مجاني", "احذف اسم الجهة بعد الطباعة", "انسخ الملف إلى متجر إلكتروني للصف"],
    wrongEn: ["Sell copies at the fair because the download was free", "Remove the agency name after printing", "Upload the file to a class web shop"],
  },
];

export const CHAPTER_5_ANALYSIS: AnalysisPrompt[] = [
  {
    id: "5-1-a01",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "حلّل استطلاعًا نُشر في جروب واتساب واحد لدفعة المتفوقين ثم عُمّم على المدرسة: من غاب عن العينة وكيف يميل المتوسط؟",
    promptEn: "Analyse a poll posted in one honour-roll WhatsApp group then generalised to the school: who is missing, and how does the mean tilt?",
    guideAr: "اذكر الصامتين وباقي الصفوف ومن بلا واتساب، واربط الميل بتحيز العينة لا بحجم الردود.",
    guideEn: "Name silent members, other grades, and students without WhatsApp, and tie the tilt to sampling bias, not reply count.",
  },
  {
    id: "5-1-a02",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "قارن بين عدّ السيارات أمام البوابة بنفسك وبين تحميل جدول مرور من الجهاز المركزي: متى تكون كل طريقة أصلح؟",
    promptEn: "Compare counting cars at the gate yourself with downloading a CAPMAS traffic table: when is each method fitter?",
    guideAr: "الأولية تطابق غرضك ووقتك، والثانوية أسرع لكن تحتاج تاريخًا وغرض الجهة.",
    guideEn: "Primary matches your purpose and moment; secondary is faster but needs the agency’s date and purpose.",
  },
  {
    id: "5-1-a03",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "انتقد استطلاع ستوري إنستجرام عن وقت المذاكرة يُقدَّم كرأي الصف كله.",
    promptEn: "Critique an Instagram-story poll on study time presented as the whole class view.",
    guideAr: "بيّن الاختيار الذاتي: من يحب الظهور يرد، والصامتون يختفون، فالتعميم لا يجوز.",
    guideEn: "Show self-selection: visibility-seekers reply, quiet students vanish, so generalisation fails.",
  },
  {
    id: "5-1-a04",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "اشرح لماذا لا ينفع حساب متوسط أنيق إذا قفز الباحث من أوراق الاستطلاع إلى الرسم من غير تنظيم.",
    promptEn: "Explain why a neat mean fails if the researcher jumps from raw survey sheets to a chart with no organisation.",
    guideAr: "المسار جمع ثم تنظيم ثم تحليل؛ التواريخ المختلطة والوحدات المختلفة تفسد الناتج قبل القانون.",
    guideEn: "The path is collect, organise, analyse; mixed dates and units break the output before the formula.",
  },
  {
    id: "5-1-a05",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "قارن العينة العشوائية البسيطة بالقرعة على أرقام الجلوس بالعينة الطبقية حسب الصفوف الثلاثة.",
    promptEn: "Compare a simple random lottery on seat numbers with a stratified draw across the three grades.",
    guideAr: "البسيطة تعطي فرصة متكافئة من قائمة واحدة، والطبقية تحفظ وجود كل شريحة فلا تختفي أولى ثانوي.",
    guideEn: "Simple random gives equal chance from one list; stratified keeps each grade present so Grade 10 is not erased.",
  },
  {
    id: "5-1-a06",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "انتقد فريقًا يسأل الخارجين من البوابة الساعة 1:30 عن طول اليوم الدراسي ثم يعمّم على المدرسة.",
    promptEn: "Critique a team that asks 1:30 gate leavers about the school-day length and then speaks for the school.",
    guideAr: "هذه عينة مريحة: غاب من يبقى للحصة الأخيرة، فالمتوسط يميل لقصر اليوم.",
    guideEn: "This is convenience sampling: last-period stayers are missing, so the mean tilts toward a shorter day.",
  },
  {
    id: "5-1-a07",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "حلّل جملة «كل مراهقي القاهرة يفضّلون الامتحان الإلكتروني» بعد سؤال فصل واحد في العباسية.",
    promptEn: "Analyse the sentence “every Cairo teenager prefers e-exams” after asking one Abbasiya class.",
    guideAr: "حدّد المجتمع الحقيقي والعينة، واشرح لماذا الادعاء واثق وخاطئ.",
    guideEn: "Name the real population and the sample, and explain why the claim is confident and wrong.",
  },
  {
    id: "5-1-a08",
    lessonId: "5-1",
    chapterId: "5",
    promptAr: "اشرح لماذا يبقى الأعضاء الصامتون في جروب الصف جزءًا من مجتمع البحث حتى لو لم يضغطوا على الاستطلاع.",
    promptEn: "Explain why silent members of the class WhatsApp group stay in the research population even if they never tap the poll.",
    guideAr: "عدم الرد اختيار يميل لمن لديه وقت أو رأي حاد؛ حذف الصامتين يصغّر المجتمع زورًا.",
    guideEn: "Non-response is a choice that tilts toward time or sharp views; dropping the silent falsely shrinks the population.",
  },
  {
    id: "5-2-a01",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "حلّل خلية درجات فارغة لطالب غاب عن الاختبار القصير: ماذا يعني الفراغ وما القرار الأسلم؟",
    promptEn: "Analyse a blank mark cell for a student who missed the quiz: what does the gap mean, and what is the safest decision?",
    guideAr: "الفرغ قد يكون غيابًا لا صفرًا؛ قارن التعليم أو الإعادة بالحذف الأعمى أو الصفر التلقائي.",
    guideEn: "The blank may be absence, not zero; compare flagging or a retake with blind delete or auto-zero.",
  },
  {
    id: "5-2-a02",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "قارن حذف الصف وملء القيمة وتعليمها عندما ينقص العنوان فقط وتبقى الدرجة مكتملة.",
    promptEn: "Compare deleting the row, imputing, and flagging when only the address is missing and the mark is complete.",
    guideAr: "الحذف يرمي ذهبًا، والملء من الخيال يكذب، والتعليم يحفظ الصف ويكشف النقص.",
    guideEn: "Deletion throws away gold, invented fill lies, and a flag keeps the row while exposing the gap.",
  },
  {
    id: "5-2-a03",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "انتقد دمج إيصالي كانتين لنفس الاسم: عصير الساعة 10 وخبز الساعة 2.",
    promptEn: "Critique merging two canteen receipts with the same name: juice at 10:00 and bread at 14:00.",
    guideAr: "اختلاف السلعة والوقت يعني عمليتين؛ الدمج يخفي مبيعات حقيقية باسم إزالة التكرار.",
    guideEn: "Different items and times are two events; merging hides real sales under a dedupe label.",
  },
  {
    id: "5-2-a04",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "اشرح لماذا يبقى المتوسط «أنظف» شكليًا وأكذب موضوعًا إذا حُسبت الأناقة على أصفار الغياب وصفوف اللصق.",
    promptEn: "Explain why a mean can look tidier and be more false if polish is computed on absence zeros and pasted rows.",
    guideAr: "مدخلات سيئة = مخرجات سيئة؛ القانون لا يغسل الخطأ، بل يثبّته.",
    guideEn: "Garbage in, garbage out; the formula does not wash the error, it cements it.",
  },
  {
    id: "5-2-a05",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "قارن طول 198 سم في فريق السلة بدرجة 955 من 100 في كشف اللغة: أي الشاذين يُصحَّح وأيّهما قد يبقى؟",
    promptEn: "Compare a 198 cm basketball height with a 955/100 Arabic mark: which outlier is corrected, and which may stay?",
    guideAr: "955 مستحيلة فتصحَّح بعد الورقة؛ 198 قد تكون حقيقة نادرة فتُراجع بالقياس لا تُحذف تلقائيًا.",
    guideEn: "955 is impossible so it is corrected after the paper; 198 may be a rare truth and is remeasured, not auto-deleted.",
  },
  {
    id: "5-2-a06",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "انتقد كشفًا يخلط ذكر وم وmale قبل عدّ نسب النوع لتقرير مجلس الأمناء.",
    promptEn: "Critique a sheet that mixes ذكر, م, and male before counting gender shares for a governors’ report.",
    guideAr: "البرنامج يرى فئات متعددة فيقسم مجموعة واحدة؛ التوحيد قبل المجموع واجب.",
    guideEn: "The program sees extra categories and splits one group; unification must precede the total.",
  },
  {
    id: "5-2-a07",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "حلّل رسمًا يضع زمن الطابور بالثواني بجانب عدد الوجبات من غير تطبيع أو تقييس.",
    promptEn: "Analyse a chart that plots queue seconds beside meal counts with no normalisation or standardisation.",
    guideAr: "المدى الأكبر يبتلع الأصغر؛ اشرح كيف يعيد التحويل عدالة المقارنة.",
    guideEn: "The larger range swallows the smaller; explain how scaling restores a fair comparison.",
  },
  {
    id: "5-2-a08",
    lessonId: "5-2",
    chapterId: "5",
    promptAr: "اشرح لماذا يجب توحيد 5/3/2026 و2026-03-05 و٥ مارس قبل أي مجموع لأيام المكتبة.",
    promptEn: "Explain why 5/3/2026, 2026-03-05, and “5 March” must be unified before any library-day total.",
    guideAr: "الصيغ المختلفة تُعدّ أيامًا منفصلة؛ التوحيد حكم هندسي قبل الحساب لا بعده.",
    guideEn: "Mixed formats count as different days; unification is an engineering step before maths, not after.",
  },
  {
    id: "5-3-a01",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "حلّل اعتماد تقرير 2026 لمتوسط الدخل على ملف جهاز إحصاء آخر تحديثه 2019 من غير جملة قيد.",
    promptEn: "Analyse a 2026 income report that leans on a 2019 CAPMAS file with no limiting sentence.",
    guideAr: "اربط تاريخ التحديث بخداع «الحاضر»، واقترح ذكر السنة أو البحث عن رقم أحدث.",
    guideEn: "Tie the update date to the fiction of “now”, and propose stating the year or finding a fresher figure.",
  },
  {
    id: "5-3-a02",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "قارن ملف مواعيد أتوبيس حُفظ الفصل الماضي بطلب حي لواجهة هيئة النقل قبل خروج الرحلة.",
    promptEn: "Compare a bus-timetable file saved last term with a live transport-API request before the trip leaves.",
    guideAr: "الحي يعكس العقد الحالي، والراكد يصلح لمقارنة تاريخية؛ اذكر المصدر والوقت في الحالتين.",
    guideEn: "Live reflects today’s contract; stale suits historical contrast; cite source and time in both cases.",
  },
  {
    id: "5-3-a03",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "انتقد طالبًا يمسح اسم الوزارة من أسفل جدول جودة الهواء حتى يبدو القياس من عمل المجموعة.",
    promptEn: "Critique a student who erases the ministry name under an air-quality table so the measurement looks like the group’s work.",
    guideAr: "إخفاء المصدر يسرق الجدول ويكسر المراجعة؛ الأصالة في السؤال لا في الشعار الممسوح.",
    guideEn: "Hiding the source steals the table and blocks checking; originality sits in the question, not in a wiped logo.",
  },
  {
    id: "5-3-a04",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "اشرح لماذا لا يكفي أن يكون ملف أسعار الخضر مجاني التحميل حتى يُعاد نشره في مجلة المدرسة.",
    promptEn: "Explain why a free vegetable-price download is not enough to republish it in the school magazine.",
    guideAr: "الترخيص يفصل التحميل عن إعادة النشر؛ اقرأ «كل الحقوق محفوظة» قبل اللصق.",
    guideEn: "The licence splits download from republication; read “all rights reserved” before you paste.",
  },
  {
    id: "5-3-a05",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "قارن بيانات الجهاز المركزي المفتوحة باستطلاع الصف عن نفس السؤال: ماذا يوفّر كل مصدر وما الذي يبقى واجب الفحص؟",
    promptEn: "Compare CAPMAS open data with the class survey on the same question: what does each source give, and what still needs checking?",
    guideAr: "المفتوح يختصر الوقت ويغطي نطاقًا أوسع، واستطلاعك يطابق غرض الحصة؛ الاثنان يحتاجان ترخيصًا أو منهجًا وتاريخًا وتحيزًا.",
    guideEn: "Open data saves time and covers a wider range; your survey matches the class purpose; both still need licence or method, date, and bias checks.",
  },
  {
    id: "5-3-a06",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "انتقد جملة «الملف حكومي مفتوح إذن بلا تحيز» في عرض عن زيارات الأهرام.",
    promptEn: "Critique the sentence “the file is official and open, so it has no bias” in a pyramid-visits slide.",
    guideAr: "الشعار لا يلغي تعريف الزائر ولا موسم العينة؛ اطلب مقارنة بمصدر مستقل.",
    guideEn: "A logo does not cancel visitor definitions or sample season; ask for a comparison with an independent source.",
  },
  {
    id: "5-3-a07",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "حلّل لصق أرقام تعداد قديم في بحث صحي مدرسي كأنّها مسح هذا الأسبوع.",
    promptEn: "Analyse pasting an old census count into a school health paper as if it were this week’s survey.",
    guideAr: "سنة التعداد قيد واجب؛ إخفاؤها يحوّل رقمًا ميتًا إلى حاضر كاذب.",
    guideEn: "The census year is a required limit; hiding it turns a dead figure into a false present.",
  },
  {
    id: "5-3-a08",
    lessonId: "5-3",
    chapterId: "5",
    promptAr: "اشرح لماذا يُذكر تاريخ الدخول واسم الجهة في ذيل تقرير الكهرباء حتى لو كان الرابط واضحًا.",
    promptEn: "Explain why the electricity-report footer should keep the access date and agency name even when the URL is visible.",
    guideAr: "البوابة تتغيّر غدًا؛ التاريخ يثبت النسخة التي رأيتها، والاسم يمنع ادعاء الملكية.",
    guideEn: "The portal may change tomorrow; the date pins the version you saw, and the name blocks a claim of ownership.",
  },
];
