import { analysisGuide as g } from "@/lib/question-bank/guide";

export const CLEAR_GUIDES: Record<string, { guideAr: string; guideEn: string }> = {
  "1-1-a01": g(
    "قانون مور",
    "القانون يقول إن عدد الترانزستورات على الشريحة يتضاعف تقريباً كل سنتين. لكنه يقترب من حد فيزيائي، فلا نضمن إن الشريحة هتفضل تصغر إلى ما لا نهاية.",
    "معمل المدرسة يشتري أجهزة فيها أكثر من معالج يشتغلوا مع بعض، بدل ما يستنى شريحة أصغر كل سنة.",
    "Moore's Law",
    "It says the number of transistors on a chip roughly doubles every two years. It is near a physical limit, so chips will not keep shrinking forever.",
    "The school lab buys machines with several cores working together, instead of waiting for a thinner chip every year.",
  ),
  "1-1-a02": g(
    "الحوسبة الطرفية والحوسبة السحابية",
    "السحابة تحتاج نت. الطرفية تعالج على الجهاز نفسه. لو وقع الخط، السحابة تقف والطرفية تكمل.",
    "في لجنة امتحان إلكتروني: لو الراوتر وقع، الجهاز اللي بيصحح محلياً يكمل، واللي مستني السحابة يقف.",
    "Edge computing and cloud computing",
    "The cloud needs the Internet. Edge processing happens on the device. If the line drops, the cloud stops and the edge can continue.",
    "In an e-exam hall: if the router falls, a machine marking locally can finish; one waiting on the cloud cannot.",
  ),
  "1-1-a03": g(
    "الحوسبة الطرفية",
    "قرار الفرملة لازم يحصل في جزء من الثانية. رفع كل صورة لخادم بعيد يضيف تأخيراً قد يصنع حادثاً.",
    "أتوبيس المدرسة لازم يفرمل من الحساس على العربية نفسها، مش بعد ما الصورة تروح السحابة وترجع.",
    "Edge computing",
    "A brake decision must happen in a fraction of a second. Uploading every frame to a distant server adds delay that can cause a crash.",
    "The school bus must brake from a sensor on the vehicle, not after a picture goes to the cloud and back.",
  ),
  "1-1-a04": g(
    "الحوسبة السحابية",
    "الدفع والطلب بقوا خدمة عبر الشبكة، فالشغل ما عادش مربوط بورقة نقد أو دفتر في المكان فقط.",
    "كافيتريا المدرسة والمخبز جنب البيت يستقبلوا الطلب والدفع من الموبايل، والطالب يشتري من غير فلوس ورق في الطابور.",
    "Cloud computing",
    "Payment and orders became a service over the network, so work is no longer tied only to cash or a paper book on site.",
    "The school canteen and the bakery next door take orders and payment from a phone, so a student can buy without paper cash in the queue.",
  ),
  "1-1-a05": g(
    "مراحل تقنية المعلومات",
    "القدرة انتقلت من حاسوب يملأ غرفة، إلى حاسوب شخصي، إلى إنترنت، إلى هاتف، ثم إلى خدمة تُفتح من المتصفح.",
    "في حصة التاريخ الطالب يفتح المصدر من اللابتوب أو من خدمة سحابية، مش من جهاز الوزارة الكبير.",
    "Stages of IT",
    "Power moved from a room-sized computer, to a PC, to the Internet, to a phone, then to a service opened in a browser.",
    "In a history lesson the student opens a source on a laptop or a cloud service, not on a huge ministry machine.",
  ),
  "1-1-a06": g(
    "الواقع المعزز والواقع الافتراضي",
    "المعزز يضيف طبقة رقمية فوق العالم الحقيقي. الافتراضي يستبدل المكان بعالم محاكى.",
    "في المتحف المصري طبقة فوق التمثال تشرح التاريخ. في البيت خوذة تحذف البلكونة وتحط معملاً محاكى.",
    "AR and VR",
    "AR adds a digital layer on the real world. VR replaces the place with a simulated world.",
    "At the Egyptian Museum a layer on the statue explains history. At home a headset erases the balcony and plants a simulated lab.",
  ),
  "1-1-a07": g(
    "قانون مور",
    "ده اتجاه صناعي تقريبي كل سنتين تقريباً، مش أمر وزاري ومش بيحصل كل شهر.",
    "لو زميل قال إن كل جهاز مدرسي بيتضاعف سرعته كل شهر، حصة التقنية تصحح: الزمن تقريباً سنتين، والمصدر الصناعة مش اللائحة.",
    "Moore's Law",
    "It is an approximate industrial trend of about two years, not a ministry order and not a monthly rule.",
    "If a classmate says every school machine doubles every month, the IT lesson corrects: the time is about two years, and the source is industry, not a bylaw.",
  ),
  "1-1-a08": g(
    "الحوسبة السحابية",
    "الملف موجود على الخدمة عبر الإنترنت، مش مربوط بسبورة الغرفة فقط. لذلك الشغل والتعلم يكمّلوا من البيت.",
    "بعد غرق الشارع ولي الأمر يفتح حصة الابن من البيت لأن الملف على السحابة.",
    "Cloud computing",
    "The file lives on a service over the Internet, not only on the classroom board. So work and learning can continue from home.",
    "After the street floods, a parent opens the child's lesson from home because the file is in the cloud.",
  ),
  "1-2-a01": g(
    "الذكاء الاصطناعي والتعلم الآلي والتعلم العميق والذكاء التوليدي",
    "الذكاء الاصطناعي هو المظلة. التعلم الآلي جزء منه. التعلم العميق أسلوب أقوى داخل التعلم الآلي. التوليدي ينتج شيئاً جديداً في المركز.",
    "على السبورة الذكية: فلتر البريد تعلم آلي، وتوليد صورة من جملة ذكاء توليدي، والاتنين تحت مظلة الذكاء الاصطناعي.",
    "AI, machine learning, deep learning, and generative AI",
    "AI is the umbrella. Machine learning sits inside it. Deep learning is a stronger style inside machine learning. Generative AI makes something new at the centre.",
    "On the smart board: a mail filter is machine learning, an image from a sentence is generative AI, and both sit under AI.",
  ),
  "1-2-a02": g(
    "التعلم الآلي والذكاء التوليدي",
    "التعلم الآلي يحكم على شيء موجود. التوليدي يصنع شيئاً جديداً لم يكن موجوداً.",
    "فلتر بريد المعلم يصنف رسالة وصلت. ملصق الرحلة من جملة واحدة صورة جديدة.",
    "Machine learning and generative AI",
    "Machine learning judges something that already exists. Generative AI makes something new.",
    "The teacher's spam filter classes a message that arrived. A trip poster from one sentence is a new image.",
  ),
  "1-2-a03": g(
    "الهلوسة",
    "النموذج التوليدي قد يكتب كلاماً فصيحاً وهو غلط. الفصاحة مش دليل صدق.",
    "طالب يلصق فقرة عن يوم رياضي لم يحدث. هيئة التحرير تطابق الوقائع من الإدارة قبل النشر.",
    "Hallucination",
    "A generative model can write fluent text that is still false. Fluency is not proof.",
    "A student pastes a paragraph about a sports day that never happened. The magazine team checks the facts with the office before publishing.",
  ),
  "1-2-a04": g(
    "التعلم العميق",
    "النموذج يتقن شكل النمط، وقد يخطئ في الرقم أو الثابت. الشكل الصحيح مش كفاية.",
    "في حصة الفيزياء نراجع الثابت من الكتاب قبل نقله للدفتر، حتى لو المعادلة شكلها مظبوط.",
    "Deep learning",
    "The model can master the look of a pattern and still get a number or a constant wrong. A correct shape is not enough.",
    "In physics we check the constant in the textbook before copying it, even if the equation looks right.",
  ),
  "1-2-a05": g(
    "الهلوسة",
    "لو الصف كله لصق إجابة واحدة، الخطأ الفصيح ينتشر على الكل.",
    "جروب واتساب يوزع إجابة واحدة. كل طالب يحل بعد الفهم، ومش بعد اللصق.",
    "Hallucination",
    "If the whole class pastes one answer, a fluent error spreads to everyone.",
    "A WhatsApp group shares one answer. Each student solves after understanding, not after pasting.",
  ),
  "1-2-a06": g(
    "التعلم الآلي والذكاء التوليدي",
    "التصنيف يضع نصاً موجوداً في فئة. التوليد يصنع عينة جديدة، ولازم نحترم حقوق التسجيل.",
    "بطاقات المكتبة: شكوى أو شكر. نادي المسرح: صوت عاصفة جديد من غير سرقة تسجيل الزميل.",
    "Machine learning and generative AI",
    "Classification puts existing text into a class. Generation makes a new sample, and a classmate's recording must be respected.",
    "Library cards: complaint or thanks. Drama club: a new storm sound without stealing a classmate's recording.",
  ),
  "1-2-a07": g(
    "الذكاء الاصطناعي",
    "الذكاء الاصطناعي أوسع من الشات. فيه تعلم آلي يفرز البريد وصوراً في المصنع.",
    "ولي أمر يحصر الكل في شات بوت الموبايل. نوضح إن فرز الإيميل وكاميرا المصنع ذكاء اصطناعي برضه.",
    "Artificial intelligence",
    "AI is wider than chat. It includes machine learning that sorts mail and factory images.",
    "A parent who reduces all of AI to a phone chatbot needs the mail filter and the factory camera as extra examples.",
  ),
  "1-2-a08": g(
    "التعلم العميق",
    "التعلم العميق يحتاج طبقات وبيانات كثيرة. ثواني قليلة مش كفاية لتمييز موثوق.",
    "نادي البرمجة لو سمع اسم الصف ثلاث ثوان في الطابور، النموذج مش هيثبت. محتاج تسجيلات كتير.",
    "Deep learning",
    "Deep learning needs layers and a lot of data. A few seconds cannot build reliable recognition.",
    "If the coding club hears the class name for three seconds at assembly, the model will not hold. It needs many recordings.",
  ),
  "1-3-a01": g(
    "الذكاء الضيق",
    "النظام يتقن مهمة واحدة، ويضعف لو السياق اتغيّر أو بقى فيه حكم أخلاقي.",
    "برنامج شطرنج يهزم الصف، وبعد الخسارة يعجز يكتب اعتذار لزميل.",
    "Narrow AI",
    "The system masters one task and weakens when the context changes or a moral judgement is needed.",
    "A chess program can beat the class, then fail to write an apology after a loss.",
  ),
  "1-3-a02": g(
    "التحيز",
    "لو أمثلة التدريب حادة أو ناقصة، الترجمة تنقل الظلم للسياق الجديد.",
    "إعلان الإذاعة قد ينجح، وعتاب ولي الأمر ينقلب اتهام. معلم اللغة يراجع الجملة قبل ما تتبعت للأسرة.",
    "Bias",
    "If the training examples are harsh or incomplete, translation carries that harm into a new context.",
    "A radio notice may work, while a parent's rebuke becomes an accusation. The language teacher reviews the sentence before it reaches the family.",
  ),
  "1-3-a03": g(
    "التحيز",
    "النموذج يعيد ظلم العينة الناقصة. بيانات القاهرة وحدها تظلم أسماء من الصعيد.",
    "قبل ما ترتيب القبول يمس درجة طالب، المدرسة تجمع بيانات أوسع من كل المحافظات.",
    "Bias",
    "The model repeats the harm of an incomplete sample. Cairo-only data lowers Upper Egypt names unfairly.",
    "Before an admissions ranker touches a mark, the school rebuilds the data from more governorates.",
  ),
  "1-3-a04": g(
    "الصيانة التنبؤية",
    "الحساس يقرأ النمط قبل العطل، فنوقف الآلة قبل الانقطاع.",
    "مضخة محطة المياه تتوقف قبل أسبوعين من التآكل المتوقع حتى ما يقف طابور المدرسة عطشان.",
    "Predictive maintenance",
    "A sensor reads the pattern before the fault, so the machine is stopped before the outage.",
    "A water-plant pump is stopped two weeks before forecast wear so the school queue is not left thirsty.",
  ),
  "1-3-a05": g(
    "نظام التوصية",
    "النظام يعيد أول اختيار، فيحبس المستخدم في نفس النوع حتى لو احتياجه اتغيّر.",
    "بوفيه الرحلة يفضل يعرض ساندوتش سبتمبر. المشرف يطلب اختيار يدوي لما الجوع أو الجدول يتغير.",
    "Recommender system",
    "The system replays the first choice, so it traps the user in the same type even when need changes.",
    "The trip buffet keeps offering a September sandwich. The supervisor asks for a hand choice when hunger or the timetable changes.",
  ),
  "1-3-a06": g(
    "الذكاء الضيق",
    "المساعد يسرّع الجمع، لكن المعنى والأمانة من الكتاب والمصدر.",
    "بحث الحملة الفرنسية: استخدم المساعد للوصول، ثم ثبّت الجملة من الكتاب. تسليم الملخص بلا مصدر يسقط الأمانة.",
    "Narrow AI",
    "The assistant speeds gathering, but meaning and honesty come from the book and the source.",
    "French-campaign project: use the assistant to reach sources, then confirm the line in the book. A summary with no source fails honesty.",
  ),
  "1-3-a07": g(
    "الذكاء الضيق",
    "النموذج يلتقط نمطاً إحصائياً ولا يحمل مسؤولية طبية.",
    "عيادة المدرسة: توقع الغياب مش إذن لصرف دواء من غير ممرضة.",
    "Narrow AI",
    "The model catches a statistical pattern and carries no medical duty.",
    "School clinic: an absence forecast is not permission to issue medicine with no nurse.",
  ),
  "1-3-a08": g(
    "الصيانة التنبؤية",
    "تبديل السير بعد ارتفاع الاهتزاز يمنع توقف الحصة، لأن النمط ظهر قبل الكسر.",
    "ورشة الخراطة تبدّل السير لما الاهتزاز يزيد، مش بعد ما يقطع قدام الصف.",
    "Predictive maintenance",
    "Replacing the belt after vibration rises stops the lesson collapsing, because the pattern appeared before the snap.",
    "The lathe workshop changes the belt when vibration rises, not after it snaps in front of the class.",
  ),
  "1-4-a01": g(
    "الخصوصية",
    "بيانات الزميل ملكه. لصقها في نموذج عام يسلّمها لمزود إحنا مش بنسيطر عليه.",
    "جروب الرحلة يتعمل من تليفون محلي، من غير ما نلزق أرقام الصف في موقع عام.",
    "Privacy",
    "A classmate's data belongs to them. Pasting it into a public model hands it to a provider we do not control.",
    "The trip group is created from a local phone, without pasting class numbers into a public site.",
  ),
  "1-4-a02": g(
    "الشفافية",
    "الشفافية تعطي سبباً مفهوماً فيقدر الطالب يعترض. الصمت يخلي القرار صندوقاً أسود.",
    "كاميرا الغياب لو شرحت سبب الخصم، الطالب يعترض بعد الطابور. لو النظام سكت، باب الاعتراض يتقفل.",
    "Transparency",
    "Transparency gives a reason the student can understand and appeal. Silence turns the ruling into a black box.",
    "If the attendance camera explains a deduction, the student can object after assembly. If the system stays silent, the appeal door shuts.",
  ),
  "1-4-a03": g(
    "التزييف العميق",
    "المقطع ممكن يكون مقنع وهو مفبرك. المشاهدة مش دليل رسمي.",
    "فيديو يلغي الامتحان بصوت الناظر. نسأل الإدارة أولاً، ومش نبني جدول المذاكرة على مقطع مجهول.",
    "Deepfake",
    "A clip can look convincing and still be fabricated. Views are not an official statement.",
    "A video cancels the exam in the principal's voice. Ask the office first, and do not build a revision plan on an unknown clip.",
  ),
  "1-4-a04": g(
    "المساءلة",
    "أثر القرار على إنسان. العطل التقني ما يشيلش المسؤولية من المعلم أو الكنترول.",
    "درجة صفر طلعت من عطل نموذج. المعلم يصحح السجل قبل ما الأسرة تتظلم.",
    "Accountability",
    "The effect of the decision falls on a person. A technical fault does not remove the teacher's or the control room's duty.",
    "A zero produced by a model fault is corrected by the teacher before the family is harmed.",
  ),
  "1-4-a05": g(
    "المساءلة",
    "الورقة لازم تبقى فهم الطالب. اللصق الأعمى يحول الأداة لغش.",
    "قاعدة الصف: افهم بالذكاء الاصطناعي ثم اكتب بنفسك. ليلة الامتحان الاعتماد الأعمى ممنوع.",
    "Accountability",
    "The script must be the student's understanding. A blind paste turns the tool into cheating.",
    "Class rule: understand with AI, then write it yourself. Blind trust on exam night is not allowed.",
  ),
  "1-4-a06": g(
    "الخصوصية",
    "الخصوصية تسري على الصحة وعلى أرقام التجربة، مش على الملف الطبي بس.",
    "ملف الحساسية يقعد في العيادة. قياسات معمل الكيمياء بأسماء الزملاء تترسم على جهاز المدرسة المغلق، مش على موقع عام.",
    "Privacy",
    "Privacy covers health and experiment numbers, not only a medical file.",
    "The allergy file stays in the clinic. Chemistry readings with classmates' names are charted on a closed school device, not a public site.",
  ),
  "1-4-a07": g(
    "المساءلة",
    "ارتفاع الإنتاج قدرة تقنية. فصل العمال من غير تدريب إذن أخلاقي ناقص.",
    "زيارة الصف للمصنع تسأل عن خطة رزق للعمال، مش عن سرعة الروبوت وحدها.",
    "Accountability",
    "A rise in output is technical power. Firing workers with no retraining is a missing moral permission.",
    "A class factory visit asks about a livelihood plan, not only robot speed.",
  ),
  "1-4-a08": g(
    "التزييف العميق",
    "الصوت والوجه هوية. المشاهدات مش إذن بنشر وجه أو صوت المعلمة المصنّع.",
    "مقطع يوتيوب بأغنية بصوت معلمة لم تسجّل يُحذف حتى لو المشاهدات عالية.",
    "Deepfake",
    "Voice and face are identity. A view count is not permission to publish a fabricated teacher voice.",
    "A YouTube clip singing in a teacher's unrecorded voice is deleted even if views rise.",
  ),
};
