import type { ChapterId } from "@/lib/curriculum";

export type BookDrill = {
  id: string;
  lessonId: string;
  chapterId: ChapterId;
  kind: "mcq" | "tf";
  promptAr: string;
  promptEn: string;
  optionsAr: string[];
  optionsEn: string[];
  correctIndex: number;
};

function mcq(
  id: string,
  lessonId: string,
  chapterId: ChapterId,
  promptAr: string,
  promptEn: string,
  optionsAr: string[],
  optionsEn: string[],
  correctIndex: number,
): BookDrill {
  return { id, lessonId, chapterId, kind: "mcq", promptAr, promptEn, optionsAr, optionsEn, correctIndex };
}

function tf(
  id: string,
  lessonId: string,
  chapterId: ChapterId,
  promptAr: string,
  promptEn: string,
  truth: boolean,
): BookDrill {
  return {
    id,
    lessonId,
    chapterId,
    kind: "tf",
    promptAr,
    promptEn,
    optionsAr: ["صح", "غلط"],
    optionsEn: ["True", "False"],
    correctIndex: truth ? 0 : 1,
  };
}

/** Official worked-example questions from the ministry book. Keep option order as printed. */
export const BOOK_DRILLS: BookDrill[] = [
  mcq(
    "1-1-book-1",
    "1-1",
    "1",
    "من الاختيارات التالية، أي ترتيب لمراحل تطور تكنولوجيا المعلومات صحيح زمنيًا؟",
    "From the following options (A–D), choose the one that lists the stages of information technology (IT) development in the correct chronological order.",
    [
      "مولد الحاسوب → ظهور الهواتف الذكية → إتاحة الإنترنت تجاريًا → انتشار الحوسبة السحابية",
      "مولد الحاسوب → إتاحة الإنترنت تجاريًا → ظهور الهواتف الذكية → انتشار الحوسبة السحابية",
      "إتاحة الإنترنت تجاريًا → مولد الحاسوب → انتشار الحوسبة السحابية → ظهور الهواتف الذكية",
      "ظهور الهواتف الذكية → إتاحة الإنترنت تجاريًا → مولد الحاسوب → انتشار الحوسبة السحابية",
    ],
    [
      "Birth of the computer → Rise of smartphones → Commercialization of the Internet → Spread of cloud computing",
      "Birth of the computer → Commercialization of the Internet → Rise of smartphones → Spread of cloud computing",
      "Commercialization of the Internet → Birth of the computer → Spread of cloud computing → Rise of smartphones",
      "Rise of smartphones → Commercialization of the Internet → Birth of the computer → Spread of cloud computing",
    ],
    1,
  ),
  tf(
    "1-1-book-2a",
    "1-1",
    "1",
    "قانون مور ملاحظة تجريبية: عدد الترانزستورات على الشريحة يتضاعف تقريبًا كل سنتين.",
    "Moore's Law is the empirical observation that the number of transistors on an integrated circuit doubles approximately every two years.",
    true,
  ),
  tf(
    "1-1-book-2b",
    "1-1",
    "1",
    "قانون مور اقترب في السنوات الأخيرة من حد فيزيائي.",
    "Moore's Law has been said to be approaching a physical limit in recent years.",
    true,
  ),
  tf(
    "1-1-book-2c",
    "1-1",
    "1",
    "شبكات التواصل الاجتماعي فعّالة جدًا في نشر المعلومات بسرعة.",
    "SNS is highly effective at spreading information rapidly.",
    true,
  ),
  tf(
    "1-1-book-2d",
    "1-1",
    "1",
    "التجارة الإلكترونية تعني شراء السلع من محل فعلي نقدًا.",
    "E-commerce (EC) refers to purchasing goods at physical stores using cash.",
    false,
  ),
  mcq(
    "1-1-book-3a",
    "1-1",
    "1",
    "تقنية تضيف معلومات رقمية فوق صور العالم الحقيقي هي:",
    "A technology that overlays digital information on real-world images is:",
    ["القيادة الذاتية", "الواقع المعزز", "الواقع الافتراضي"],
    ["Autonomous driving", "AR", "VR"],
    1,
  ),
  mcq(
    "1-1-book-3b",
    "1-1",
    "1",
    "تقنية تستخدم الذكاء الاصطناعي لقيادة مركبة من غير تدخل بشري هي:",
    "A technology that uses AI to drive a vehicle without human operation is:",
    ["القيادة الذاتية", "الواقع المعزز", "الواقع الافتراضي"],
    ["Autonomous driving", "AR", "VR"],
    0,
  ),
  mcq(
    "1-1-book-3c",
    "1-1",
    "1",
    "تقنية تتيح للمستخدم الغوص في فضاء افتراضي يولّده الحاسوب هي:",
    "A technology that allows users to immerse themselves in a virtual space generated by a computer is:",
    ["القيادة الذاتية", "الواقع المعزز", "الواقع الافتراضي"],
    ["Autonomous driving", "AR", "VR"],
    2,
  ),
];

export function isBookDrill(id: string): boolean {
  return id.includes("-book-");
}

export function bookDrillsForLesson(lessonId: string): BookDrill[] {
  return BOOK_DRILLS.filter((row) => row.lessonId === lessonId);
}
